plugins {
    // We need to use api-java here because we have public api classes (specifically AntTarget) in this project
    // That class is here because it depends on core for ConventionTask.  If ConventionTask is pulled up out of core,
    // presumably AntTarget could then move up to ant-api and this project could apply implementation-java instead.
    id("gradlebuild.distribution.api-java")
}

description = "Implementation of Gradle's Ant integration"

strictCompile {
    ignoreRawTypes() // raw types in Groovy-based APIs
}

dependencies {
    api(projects.ant)                      // AntBuilderFactory, AntBuilderDelegate
    api(projects.antApi)                   // AntBuilder
    api(projects.core)                     // ClassPathRegistry, ModuleRegistry, ClassLoaderFactory, etc.
    api(projects.coreApi)                  // Project, Task, Transformer
    api(projects.baseServices)             // UncheckedException, Stoppable
    api(projects.serviceProvider)
    api(libs.ant)
    api(libs.groovy)
    api(libs.jspecify)

    implementation(projects.concurrent)
    implementation(projects.modelCore)
    implementation(projects.stdlibJavaExtensions)
    implementation(libs.guava)

    compileOnly(libs.jetbrainsAnnotations)
    compileOnly(projects.internalInstrumentationApi)

    testImplementation(testFixtures(projects.core))   // AbstractProjectBuilderSpec, TestUtil
    testImplementation(projects.internalTesting)       // TestNameTestDirectoryProvider
    testImplementation(testFixtures(projects.logging)) // ConfigureLogging, TestOutputEventListener

    testRuntimeOnly(projects.distributionsCore) {
        because("Required by ProjectBuilder to find gradle-plugins.properties")
    }

    integTestDistributionRuntimeOnly(projects.distributionsJvm) {
        because("AntBuilder relies on groovy-loader which ships with the JVM distribution")
    }
}

gradleModule {
    requiredRuntimes {
        daemon = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
    }
}
