plugins {
    // We need to use api-java here because we have public api classes (specifically AntTarget) in this project
    // That class is here because it depends on core for ConventionTask.  If ConventionTask is pulled up out of core,
    // presumably AntTarget could then move up to ant-api and this project could apply implementation-java instead.
    id("gradlebuild.distribution.api-java")
}

description = "Implementation of Gradle's Ant integration"

strictCompile {
    ignoreRawTypes() // raw types in DefaultIsolatedAntBuilder (Vector) and Groovy-based APIs
}

dependencies {
    api(projects.ant)                      // IsolatedAntBuilder, AntBuilderFactory, AntBuilderDelegate
    api(projects.antApi)                   // AntBuilder
    api(projects.core)                     // ClassPathRegistry, ModuleRegistry, ClassLoaderFactory, etc.
    api(projects.coreApi)                  // Project, Task, Transformer
    api(projects.baseServices)             // UncheckedException, Stoppable
    api(projects.buildProcessServices)
    api(projects.classloaders)             // CachingClassLoader, FilteringClassLoader, etc.
    api(projects.concurrent)
    api(projects.serviceProvider)
    api(libs.ant)
    api(libs.groovy)
    api(libs.inject)
    api(libs.jspecify)

    implementation(projects.loggingApi)
    implementation(projects.modelCore)
    implementation(projects.stdlibJavaExtensions)
    implementation(projects.groovyLoader)  // GroovySystemLoader, GroovySystemLoaderFactory
    implementation(libs.guava)
    implementation(libs.slf4jApi)

    compileOnly(libs.jetbrainsAnnotations)
    compileOnly(projects.internalInstrumentationApi)

    testImplementation(testFixtures(projects.core))   // AbstractProjectBuilderSpec, TestUtil
    testImplementation(projects.internalTesting)       // TestNameTestDirectoryProvider
    testImplementation(testFixtures(projects.logging)) // ConfigureLogging, TestOutputEventListener

    testRuntimeOnly(projects.distributionsCore) {
        because("Required by ProjectBuilder to find gradle-plugins.properties")
    }

    integTestImplementation(libs.log4jToSlf4j)   // TestAntTask: org.apache.log4j
    integTestImplementation(libs.jclToSlf4j)      // TestAntTask: org.apache.commons.logging

    integTestDistributionRuntimeOnly(projects.distributionsJvm) {
        because("AntBuilder relies on groovy-loader which ships with the JVM distribution")
    }
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
        worker = true
    }
}
