{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-metadata-1.0.jar",
          "url": "kotlin-multiplatform-android-library-1.0.jar",
          "size": 1096,
          "sha512": "8521c2f0acd9a0026c3225f35e735874f4a9e9e521ca17fb51ff05f2a9a1cc7d74a560c62a3215504c59ba70bd49fc69ea7332fb0bab19b20b172c2017603d5d",
          "sha256": "d0afaa260187935b851f4510ccf7ddb98a88c7a594e5b5af78966011aa2b859e",
          "sha1": "2438124313565116a4ccbd7adae94f2619c889c6",
          "md5": "b7d07612b92573c052f946c6c61dabe6"
        }
      ]
    },
    {
      "name": "demoDebugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "demoDebug",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-demo-debug/1.0/kotlin-multiplatform-android-library-android-demo-debug-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-demo-debug",
        "version": "1.0"
      }
    },
    {
      "name": "demoDebugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "demoDebug",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-demo-debug/1.0/kotlin-multiplatform-android-library-android-demo-debug-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-demo-debug",
        "version": "1.0"
      }
    },
    {
      "name": "fullDebugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "fullDebug",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-full-debug/1.0/kotlin-multiplatform-android-library-android-full-debug-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-full-debug",
        "version": "1.0"
      }
    },
    {
      "name": "fullDebugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "fullDebug",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-full-debug/1.0/kotlin-multiplatform-android-library-android-full-debug-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-full-debug",
        "version": "1.0"
      }
    },
    {
      "name": "demoReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "demoRelease",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-demo/1.0/kotlin-multiplatform-android-library-android-demo-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-demo",
        "version": "1.0"
      }
    },
    {
      "name": "demoReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "demoRelease",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-demo/1.0/kotlin-multiplatform-android-library-android-demo-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-demo",
        "version": "1.0"
      }
    },
    {
      "name": "fullReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "fullRelease",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-full/1.0/kotlin-multiplatform-android-library-android-full-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-full",
        "version": "1.0"
      }
    },
    {
      "name": "fullReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "fullRelease",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-full/1.0/kotlin-multiplatform-android-library-android-full-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-full",
        "version": "1.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-js/1.0/kotlin-multiplatform-android-library-js-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-js",
        "version": "1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-js/1.0/kotlin-multiplatform-android-library-js-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-js",
        "version": "1.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-linuxx64/1.0/kotlin-multiplatform-android-library-linuxx64-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-linuxx64",
        "version": "1.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-macosx64/1.0/kotlin-multiplatform-android-library-macosx64-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-macosx64",
        "version": "1.0"
      }
    }
  ]
}
