{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "demoDebugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "demoDebug",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-debug-1.0.aar",
          "size": 2361,
          "sha512": "50d999f4f0e8b5ce4cd40c423f4e993abf51d7944a699d1afdef466a0389511889a219a3cd78cd617742e44d5121833a8cd53def7366952b18af10245b6558dd",
          "sha256": "1fcc5eefa4ffb8353827c854814ea2e2de18b0142b1b196cc7a65ae9d57b1c7a",
          "sha1": "f2eaf3e2b184d8bb648733bafd70ee03dc3c38c2",
          "md5": "8ca861047da176c00157b937ec382bd6"
        }
      ]
    },
    {
      "name": "demoDebugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "demoDebug",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-debug-1.0.aar",
          "size": 2361,
          "sha512": "50d999f4f0e8b5ce4cd40c423f4e993abf51d7944a699d1afdef466a0389511889a219a3cd78cd617742e44d5121833a8cd53def7366952b18af10245b6558dd",
          "sha256": "1fcc5eefa4ffb8353827c854814ea2e2de18b0142b1b196cc7a65ae9d57b1c7a",
          "sha1": "f2eaf3e2b184d8bb648733bafd70ee03dc3c38c2",
          "md5": "8ca861047da176c00157b937ec382bd6"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
