{
    "formatVersion": "1.0",
    "component": {
        "group": "org.gradle.test",
        "module": "publishTest",
        "version": "1.9",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "4.5-20171204230000+0000",
            "buildId": "mmkppe3smvbgbhp5yeotxkaweq"
        }
    },
    "variants": [
        {
            "name": "runtime",
            "attributes": {
                "org.gradle.usage": "java-runtime"
            },
            "dependencies": [
                {
                    "group": "commons-collections",
                    "module": "commons-collections",
                    "version": {
                        "prefers": "3.2.2"
                    }
                },
                {
                    "group": "org.springframework",
                    "module": "spring-core",
                    "version": {
                        "prefers": "2.5.6"
                    },
                    "excludes": [
                        {
                            "group": "commons-logging",
                            "module": "commons-logging"
                        }
                    ]
                },
                {
                    "group": "commons-beanutils",
                    "module": "commons-beanutils",
                    "version": {
                        "prefers": "1.8.3"
                    },
                    "excludes": [
                        {
                            "group": "commons-logging",
                            "module": "*"
                        }
                    ]
                },
                {
                    "group": "commons-dbcp",
                    "module": "commons-dbcp",
                    "version": {
                        "prefers": "1.4"
                    },
                    "excludes": [
                        {
                            "group": "*",
                            "module": "*"
                        }
                    ]
                },
                {
                    "group": "org.apache.camel",
                    "module": "camel-jackson",
                    "version": {
                        "prefers": "2.15.3"
                    },
                    "excludes": [
                        {
                            "group": "*",
                            "module": "camel-core"
                        }
                    ]
                },
                {
                    "group": "commons-io",
                    "module": "commons-io",
                    "version": {
                        "prefers": "1.4"
                    }
                }
            ],
            "files": [
                {
                    "name": "publishTest-1.9.jar",
                    "url": "publishTest-1.9.jar",
                    "size": 261,
                    "sha1": "7577e284a8b6daf5cb2fe0d826343f22fadb8ad0",
                    "md5": "7233c4d2f6a17fd35a2def674868828b"
                }
            ]
        },
        {
            "name": "api",
            "attributes": {
                "org.gradle.usage": "java-api"
            },
            "dependencies": [
                {
                    "group": "commons-io",
                    "module": "commons-io",
                    "version": {
                        "prefers": "1.4"
                    }
                },
                {
                    "group": "commons-collections",
                    "module": "commons-collections",
                    "version": {
                        "prefers": "3.2.2"
                    }
                },
                {
                    "group": "org.springframework",
                    "module": "spring-core",
                    "version": {
                        "prefers": "2.5.6"
                    },
                    "excludes": [
                        {
                            "group": "commons-logging",
                            "module": "commons-logging"
                        }
                    ]
                },
                {
                    "group": "commons-beanutils",
                    "module": "commons-beanutils",
                    "version": {
                        "prefers": "1.8.3"
                    },
                    "excludes": [
                        {
                            "group": "commons-logging",
                            "module": "*"
                        }
                    ]
                },
                {
                    "group": "commons-dbcp",
                    "module": "commons-dbcp",
                    "version": {
                        "prefers": "1.4"
                    },
                    "excludes": [
                        {
                            "group": "*",
                            "module": "*"
                        }
                    ]
                },
                {
                    "group": "org.apache.camel",
                    "module": "camel-jackson",
                    "version": {
                        "prefers": "2.15.3"
                    },
                    "excludes": [
                        {
                            "group": "*",
                            "module": "camel-core"
                        }
                    ]
                }
            ],
            "files": [
                {
                    "name": "publishTest-1.9.jar",
                    "url": "publishTest-1.9.jar",
                    "size": 261,
                    "sha1": "7577e284a8b6daf5cb2fe0d826343f22fadb8ad0",
                    "md5": "7233c4d2f6a17fd35a2def674868828b"
                }
            ]
        }
    ]
}
