{
    "formatVersion": "1.0",
    "variants": [
        {
            "name": "api",
            "dependencies": [
                { "group": "g0", "module": "m0" },
                { "group": "g1", "module": "m1", "version": { "requires": "v1" } },
                { "version": { "requires": "v1", "prefers": "v2" }, "group": "g2", "module": "m2" },
                {
                    "group": "g3",
                    "module": "m3",
                    "version": { "requires": "v3" },
                    "excludes": [
                        {"group": "gx", "module": "mx" },
                        {"group": "*", "module": "*" }
                    ]
                }
            ],
            "attributes": { "usage": "compile" }
        },
        {
            "attributes": { "usage": "runtime", "packaging": "zip" },
            "dependencies": [
                { "module": "m3", "group": "g3", "version": { "prefers": "v3" }},
                { "module": "m4", "version": { "requires": "v4", "prefers": "v3", "rejects": ["v5"] }, "group": "g4"},
                { "module": "m5", "version": { "prefers": "v5", "rejects": ["v6", "v7"] }, "group": "g5"},
                { "module": "m6", "version": { "rejects": ["v8"] }, "group": "g6"},
                { "module": "m7", "version": { "rejects": ["v7"] }, "group": "g7", "reason": "v7 is buggy"},
                { "module": "m8", "version": { "strictly": "v8" }, "group": "g8"},
                { "module": "m9", "version": { "requires": "v9" }, "group": "g9",
                    "thirdPartyCompatibility": { "artifactSelector": { "name": "foo", "type": "bar", "extension": "baz", "classifier": "claz" } }
                }
            ],
            "name": "runtime"
        }
    ]
}
