// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[version_catalog]]
= Version Catalog

A version catalog keeps all dependency declarations and version numbers in a single place.

The catalog makes sharing dependencies and version configurations between subprojects easy.
It also allows teams to enforce versions of libraries and plugins in large projects.

== Create the TOML file
A version catalog is a TOML file called `libs.versions.toml`.

The file is located in the `gradle` directory so that it can be used by Gradle and IDEs automatically.
The version catalog should be checked into subversion: `gradle/libs.versions.toml`.

This file contains four sections:

1. [versions] to declare the version numbers that plugins and libraries will reference.
2. [libraries] to define the libraries used in the build files.
3. [bundles] to define a set of dependencies.
4. [plugins] to define plugins.

A sample version catalog:

[source, libs.versions.toml]
----
[versions]
androidMaterial = "1.8.0"
androidPlugin = "7.4.1"

[libraries]
android-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core-ktx = "androidx.core:core-ktx:1.7.0"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.5.1"
androidx-test-junit = "androidx.test.ext:junit:1.1.5"
junit = "junit:junit:4.13.2"

[bundles]
androidx-tests = ["androidx-test-junit", "androidx-test-espresso"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidPlugin" }
android-library = { id = "com.android.library", version.ref = "androidPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android" , version = "1.8.0" }
----

Then, the catalog can be used in the build scripts as such:

====
[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.android.material)
    implementation(libs.androidx.constraintlayout)

    testImplementation(libs.junit)

    androidTestImplementation(libs.bundles.androidx.tests)
}
----
=====

[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.android.material
    implementation libs.androidx.constraintlayout

    testImplementation libs.junit

    androidTestImplementation libs.bundles.androidx.tests
}
----
=====
====
