package Gradle_Check.patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'Gradle_Check_deferred_tests' (id = 'Gradle_Check_deferred_tests')
accordingly, and delete the patch script.
*/
changeProject(uuid("Gradle_Check_deferred_tests")) {
    features {
        add {
            feature {
                type = "project-graphs"
                id = "PROJECT_EXT_35"
                param("series", """
                    [
                      {
                        "type": "valueType",
                        "title": "Build Duration (excluding Checkout Time)",
                        "sourceBuildTypeId": "Gradle_Check_Instant_20_platformPlay",
                        "key": "BuildDurationNetTime"
                      }
                    ]
                """.trimIndent())
                param("format", "text")
                param("title", "New chart title")
                param("seriesTitle", "Serie")
            }
        }
    }
}
