package Gradle_Check.patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'Gradle_Check' (id = 'Gradle_Check')
accordingly, and delete the patch script.
*/
changeProject(uuid("Gradle_Check")) {
    params {
        add {
            param("macos.java11.openjdk.64bit", "/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home")
        }
    }
}
