package Gradle_Check.patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'Gradle_Check_Parallel_Java8_Ibm_Linux' (id = 'Gradle_Check_Parallel_Java8_Ibm_Linux')
accordingly, and delete the patch script.
*/
changeProject(uuid("Gradle_Check_Parallel_Java8_Ibm_Linux")) {
    params {
        add {
            param("linux.java8.ibm.64bit", "/opt/jdk/ibm-jdk-8")
        }
    }
}
