package Gradle_Check.patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'Gradle_Check_Quick_1' (id = 'Gradle_Check_Quick_1')
accordingly, and delete the patch script.
*/
changeProject(uuid("Gradle_Check_Quick_1")) {
    features {
        add {
            feature {
                type = "project-graphs"
                id = "PROJECT_EXT_20"
                param("series", """
                    [
                      {
                        "type": "valueType",
                        "title": "Build Duration (excluding Checkout Time)",
                        "sourceBuildTypeId": "Gradle_Check_Quick_1_AllUnitTest",
                        "key": "BuildDurationNetTime"
                      }
                    ]
                """.trimIndent())
                param("format", "duration")
                param("title", "New chart title")
                param("seriesTitle", "Build Duration")
            }
        }
    }
}
