// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= Introduction

We would like to introduce Gradle to you, a build system that we think is a quantum leap for build technology in the Java (JVM) world. Gradle provides:

* A very flexible general purpose build tool like Ant.
* Switchable, build-by-convention frameworks a la Maven. But we never lock you in!
* Very powerful support for multi-project builds.
* Very powerful dependency management (based on Apache Ivy).
* Full support for your existing Maven or Ivy repository infrastructure.
* Support for transitive dependency management without the need for remote repositories or `pom.xml` and `ivy.xml` files.
* Ant tasks and builds as first class citizens.
*  _Groovy_ build scripts.
* A rich domain model for describing your build.

In <<overview#, the overview>> you will find a detailed summary of Gradle. Otherwise, the link:{guides}[guides] are waiting, have fun :)


[[sec:about_this_user_guide]]
== About this user guide

We need your help to improve this user guide. You can find out more about contributing to the documentation in the link:https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md[the contributing guide].

Throughout the user guide, you will find some diagrams that represent dependency relationships between Gradle tasks. These use something analogous to the UML dependency notation, which renders an arrow from one task to another task that the first task depends on.
