/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id("gradlebuild.distribution.repackaged.api-java")
}

description = "The XDCL Gradle API (org.gradle.api.xdcl): the reaction SPI, the facade base types the generated ecosystem facades extend, and the ConfigurationNode accessor — the org.xdcl build's xdcl-gradle-api classes, repackaged as a Gradle module"

// Gradle public API like any other org.gradle.api package: shipped in lib/, carried by every
// derivative API artifact (the public API jar and its ABI stubs, gradleApi(), the Kotlin DSL
// extensions, the docs), gated by the binary compatibility and architecture checks, and referenced by
// NO published metadata — the ecosystem libraries that extend it depend on it compileOnly, the way
// they reference the rest of Gradle. The classes are the org.xdcl build's, compiled once there and
// repackaged here (see gradlebuild.distribution.repackaged.api-java); that build's own copy of the
// jar is excluded where its owning modules enter the distribution (:launcher's provider edge,
// :distributions-full's codegen-plugin edge), so the distribution carries these classes exactly once.

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

dependencies {
    repackaged(libs.xdclGradleApi)

    // The references the API classes carry: `@Incubating` on the public types and, on the internal
    // seam, `@ServiceScope` — both runtime-retained, both from this module, both on the public
    // surface (hence `api`). `@Nullable`/`@NullMarked` are jspecify's; the annotation classes are never
    // needed at runtime (reflection ignores an absent annotation class), so compile-only, as
    // everywhere else in the build.
    api(projects.stdlibJavaExtensions)
    compileOnly(libs.jspecify)
}
