# Find all references here https://developer.android.com/studio/archive
android.studio=2025.3.2.6
# https://youtrack.jetbrains.com/articles/IDEA-A-21/IDEA-Latest-Builds-And-Release-Notes
intellij.ultimate=2025.3.2
