pull_request_rules:
  - name: Integration with @gradle-bot
    conditions:
      - check-success=Bot Says OK
      - check-success=Quick Feedback - Linux Only (Trigger) (Check)
    actions:
      merge:
        method: merge
        strict_method: rebase
        strict: true
  - name: Trigger mergify on TestAndMerge command
    conditions:
      - check-success=Bot Triggers Mergify
    actions:
      merge:
        method: merge
        strict_method: rebase
        strict: true
