[[modeling-features]]
= Modeling features and their dependencies

[[declaring-component-capabilities]]
== Declaring component capabilities

[NOTE]
====
Capabilities are a core feature of the experimental Gradle metadata file format.
This means that components published with the experimental Gradle metadata file format can declare capabilities, but also that this feature is only natively understood by Gradle.
However, it's possible to declare capabilities on components which were _not_ built by Gradle, as explained in this section.
====

If your build file contains the following dependencies:

.A build file with an implicit conflict of logging frameworks
====
include::sample[dir="userguide/dependencyManagement/managingTransitiveDependencies/declaringCapabilities/groovy",files="build.gradle[tags=dependencies]"]
include::sample[dir="userguide/dependencyManagement/managingTransitiveDependencies/declaringCapabilities/kotlin",files="build.gradle.kts[tags=dependencies]"]
====

As is, it's pretty hard to figure out that you will end up with two logging frameworks on the classpath.
In fact, `zookeeper` will bring in `log4j`, where what we want to use is `log4j-over-slf4j`.
We can preemptively detect the conflict by adding a rule which will declare that both logging frameworks provide the same capability:

.A build file with an implicit conflict of logging frameworks
====
include::sample[dir="userguide/dependencyManagement/managingTransitiveDependencies/declaringCapabilities/groovy",files="build.gradle[tags=declare_capability]"]
include::sample[dir="userguide/dependencyManagement/managingTransitiveDependencies/declaringCapabilities/kotlin",files="build.gradle.kts[tags=declare_capability]"]
====

By adding this rule, we will make sure that Gradle _will_ detect conflicts and properly fail:

```
Cannot choose between log4j:log4j:1.2.16 and org.slf4j:log4j-over-slf4j:1.7.10 because they provide the same capability: org.slf4j:slf4j-capability:1.0
```

It does not, however, choose what component to use for you: detecting a conflict is the first step, then you have to fix it.

include::feature-variants.adoc[]

[[understanding-variant-selection]]
== Understanding variant selection

[[variant-attributes]]
=== Variant attributes

[[variant-aware-matching]]
=== Variant aware matching

[[mapping-maven-ivy-to-variants]]
=== Mapping from Maven/Ivy to variants

[[adding-more-variants]]
== Adding more variants to a component

[[modeling-test-fixtures]]
=== Modeling test fixtures

[[targeting-different-platforms]]
=== Targeting different platforms

[[producing-different-artifacts]]
=== Producing different artifacts




