plugins {
    id("gradlebuild.distribution.api-java")
}

description = "The Gradle build option parser."

dependencies {
    api(projects.cli)
    api(projects.stdlibJavaExtensions)

    api(libs.jspecify)

    compileOnly(libs.errorProneAnnotations)

    implementation(projects.baseServices)
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}
