[[introduction_to_gradle_builds]]
= Introduction to Gradle Builds

You may know Gradle as the tool that helps you build Java or Android projects.
Perhaps you use Gradle through your IDE. Maybe you've dabbled in the CLI.
You've probably made small edits to your Gradle build files: squashing bugs, or even integrating frameworks and libraries.
This introduction will help you understand the fundamentals of Gradle.
With this knowledge, you can take on bigger tasks, like speeding up your Gradle builds,
running style checks, and optimizing your test suites.

== Concepts

To understand Gradle, you should familiarize yourself with the most fundamental concepts:

* *project*: A thing that needs to be built.
* *task*: An atomic piece of work within a build.
* *plugin*: Infrastructure for projects and tasks.
* *build*: The act of running a task or tasks.

== Projects

Projects are the things that Gradle builds.
Projects contain a build script, named `build.gradle` or `build.gradle.kts`.
Builds scripts define tasks, dependencies, plugins, and other configuration for your build.
A single project can contain many subprojects, which can each contain their own subprojects.

== Tasks

Tasks contain the logic that implements builds.
In most use cases, you'll use or extend existing tasks, like the built-in Java `test` task.
Gradle provides task implementations for many common build sytem goals, like running tests and creating archives.
Plugins provide even more task implementations.

== Plugins

Plugins provide a means of reusing logic and configuration across multiple projects.
With plugins, you can write a task once and use it in multiple builds. Or you can store common configuration,
like logging, dependencies, and Java version management, in one place. This reduces duplication in similar
build scripts.

Gradle projects prefer _convention over configuration_: sensible defaults reduce the amount of
code in build scripts. Since the base Gradle defaults can't cover every use case, plugins provide
a means of setting sensible defaults in Gradle for any kind of project.

== Optimizations

Over the years, Gradle has engineered a number of ways to make your builds faster.
Gradle enables some of these, like the Daemon, by default. You must explicitly enable some other optimizations,
either through configuration or build logic. This section highlights some of the most important
optimizations to know about when you start using Gradle.

=== Configuration Cache

The configuration phase is a large up-front cost for all Gradle builds. Every time you build your project, Gradle
configures the project based on available inputs like build scripts, settings, and system properties. The
configuration cache allows Gradle to cache the result of this configuration. This can save significant time
in every build. However, the configuration cache sometimes requires particular syntax.

=== Build Cache

Every time you run a build, Gradle runs a set of tasks.
The build cache stores the inputs provided to and outputs generated by those tasks.
When you run Gradle with the build cache enabled, Gradle checks the inputs for each
task. If the build cache contains output for a repeated set of task inputs, Gradle reuses that output.
Gradle can speed up builds significantly by pulling data from the cache instead of running the same task repeatedly.
However, the build cache requires annotated inputs and outputs on tasks.
