[[validation-problem]]
= Dealing with validation problems

This page summarizes the different task (or in general work) validation problems that Gradle reports and provides guidance for fixing them.

[[invalid_use_of_cacheable_transform_annotation]]
== Invalid use of @CacheableTransform

This error indicates that you have annotated a type with `@CacheableTransform` but this annotation only makes sense on artifact transforms types. Therefore, it's a no-op.

The solution is to remove the annotation. For tasks, the annotation to use is `@CacheableTask`.

[[missing_normalization_annotation]]
== Missing normalization annotation

This error occurs whenever a task or artifact transform is cacheable and that a file or file collection input property isn't declaring how it should be normalized.
Normalization tells Gradle if, for example, the absolute path of input files matter or if only the contents is relevant.
If you don't declare the normalization strategy, outputs of the task cannot be reused between machines or between different locations on the same machine.
In short, without normalization, caching is highly ineffective.

To fix this problem, you need to declare a normalization strategy, by applying one of the following annotations:

- link:{javadocPath}/org/gradle/api/tasks/PathSensitive.html[`PathSensitive`]
- link:{javadocPath}/org/gradle/api/tasks/Classpath.html[`Classpath`]
- link:{javadocPath}/org/gradle/api/tasks/CompileClasspath.html[`CompileClasspath`]

[[value_not_set]]
== Required value isn't set

This error indicates that a property expected a value but none was provided.
By default, Gradle properties are _required_, that is to say that if an input or output property isn't configured, either via a conventional value or explicitly by a build script, then Gradle will fail because it doesn't know what value to use when the task is executed.

To fix the problem, you must either:

- provide a value for this property explicitly (for example by configuring the task in your build script)
- or make the property optional by annotating it with link:{javadocPath}/org/gradle/api/tasks/Optional[`@Optional`]

[[cacheable_transform_cant_use_absolute_sensitivity]]
== Invalid use of absolute path sensitivity for an artifact transform

This error indicates that you have annotated an input of a cacheable artifact transform as sensitive to the absolute path.
However, artifact transforms are executed in isolation using their own workspace which, for example, is resilient to `clean` builds.
Even if the artifact transform result can't be shared via the build cache, using an absolute path sensitivity doesn't make sense.

To fix this problem, you must change the normalization strategy using one of those:

- link:{javadocPath}/org/gradle/api/tasks/PathSensitive.html[`PathSensitive`] (but not absolute)
- link:{javadocPath}/org/gradle/api/tasks/Classpath.html[`Classpath`]
- link:{javadocPath}/org/gradle/api/tasks/CompileClasspath.html[`CompileClasspath`]

[[artifact_transform_should_not_declare_output]]
== Invalid use of an output property on an artifact transforms

This error indicates that you have annotated a property of an artifact transform with an output annotation, which is not the correct way to register outputs for artifact transforms.

To fix this problem, you must remove the property and use the `TransformOutputs` parameter instead.

See link:{javadocPath}/org/gradle/api/artifacts/transform/TransformAction.html#transform-org.gradle.api.artifacts.transform.TransformOutputs-[TransformAction#transform(TransformOutputs)] for details.

[[ignored_annotations_on_field]]
== Invalid use of annotations on fields

This error indicates that you have a field annotated, but that there's no getter for this field.
Gradle will recognize annotations on fields _only_ if there's a corresponding getter.
If this getter is absent, the annotations have no effect whatsoever.

To fix this, you need to create a getter for this field.
We also recommend to annotate the getter instead of the field.

If you are using Groovy, it's likely that you unintentionally added the `private` modifier to a property declaration:

```groovy
@InputFile
RegularFileProperty inputFile // this is a public property

@InputFile
private RegularFileProperty inputFile // this is a field, remove the `private` modifier
```

[[ignored_annotations_on_method]]
== Invalid annotation on method

This error indicates that a annotation has been placed on an unexpected method.
In general, annotations like `@InputFiles` or `@OutputDirectory` need to be placed on a "property" method.
A property is defined by having a getter.

This causes Gradle to ignore the annotations, so they are typically not used in up-to-date checking or caching.

To fix this problem, you must remove the annotation, create a getter for the property you want to use and annotate the getter instead.

[[mutable_type_with_setter]]
== Mutable type with setter

This error indicates that a property of "mutable" type is also providing a setter.
Mutable types in Gradle include link:{javadocPath}/org/gradle/api/provider/Property.html[Property] or link:{javadocPath}/org/gradle/api/file/ConfigurableFileCollection.html[ConfigurableFileCollection].

For example, you wrote:

```groovy
class MyTask extends DefaultTask {
    private Property<Integer> x

    @Input
    Property<Integer> getX() { this.x }

    void setX(Property<Integer> x) { this.x = x }
}
```

However, mutable types like `Property` are designed to track dependencies and origin of values they are supplied with.
As a consequence, it is an error to make them overwritable, because Gradle will then be unable to tell where a property value comes from.

To fix this problem, you should either make your property final and remove the setter:

```groovy
class MyTask extends DefaultTask {
    @Input
    final Property<Integer> getX() = ...
```

You can also rely on Gradle's built-in capacity to inject final properties:

```groovy
abstract class MyTask {
    abstract Property<Integer> getX()
}
```

Then the value of the properties need to be configured via the mutation methods:

```groovy
myTask {
    x.set(123)
}
```

[[redundant_getters]]
== Redundant getters

This error indicates that a `boolean` property has both a `get` and an `is` getter method.
This is a problem because both getters can be annotated differently and Gradle cannot know which ones to use.

The solution to this problem is to get rid of one of the getters or to mark one of the getters with link:{javadocPath}/org/gradle/api/tasks/Internal.html[@Internal]

[[private_getter_must_not_be_annotated]]
== Annotations on private getters

This error indicates that you have annotated a _private_ getter with an input or output annotation.
Gradle doesn't consider private getters as inputs for up-to-date checking, which means that your annotations effectively are ignored.
It is important to fix because you might think that you have declared an input when it's not the case.

To fix this, either make the getter public, or annotate an existing getter instead, or create a new annotated getter.

[[ignored_property_must_not_be_annotated]]
== Annotations on ignored properties

This error indicates that you have a property which is annotated with an annotation which tells Gradle to ignore it (for example link:{javadocPath}/org/gradle/api/model/ReplacedBy.html[`@ReplacedBy`]) but is also annotated with an input annotation (for example link:{javadocPath}/org/gradle/api/tasks/InputFile.html[`@InputFile`]).

This is an error because Gradle cannot determine if the property should actually be used for up-to-date checking, that is to say if it's actually an input or not.

To fix this, you must either:

- remove the input annotations from the property, or
- remove the ignoring annotation from the property.

[[conflicting_annotations]]
== Conflicting annotations

This error indicates that a property is annotated with conflicting annotations, that is to say annotations which have different, irreconciliable semantics.

For example, a property cannot be annotated both with `@InputFile` and `@OutputFile` at the same time.

To fix this problem, you need to understand the semantics of the different annotations and choose only one.

[[annotation_invalid_in_context]]
== Annotation is invalid in a particular context

This error indicates that a property was annotated with an annotation which is invalid in a particular context.
For example, it's in general possible to annotate a `DirectoryProperty` with `@OutputDirectory`, but this is invalid in the context of an artifact transform, because artifact transforms provide their own workspace.

To fix this problem, you must remove the property.

[[missing_annotation]]
== Properties without annotations

This error indicates that a property isn't annotated with an input or output annotation.
Therefore, Gradle doesn't know if this property represents an input, an output, or simply should be ignored.
As a consequence, up-to-date checking and caching won't work.

To fix this problem, you need to annotate the property with the appropriate annotation, for example `@InputDirectory` for a property representing an input directory, or `@OutputDirectory` for a property representing an output directory.

Alternatively, if the property is internal, that is to say that it shouldn't participate in up-to-date checking (it's not an input or an output), then you need to annotate it with link:{javadocPath}/org/gradle/api/tasks/Internal.html[@Internal].

[[incompatible_annotations]]
== Annotation is incompatible with the property type

This error indicates that for a specific kind of property, a modifier annotation doesn't make sense.
This is the case, for example, if the `@SkipWhenEmpty` is used on an output property.
Because there are no semantics associated with this combination, Gradle cannot deduce your intent.

To fix this, you most likely need to remove the conflicting modifier annotation or check that the actual property type is what you intended.

[[incorrect_use_of_input_annotation]]
== Incorrect use of the `@Input` annotation

This error indicates that a property is annotated with `@Input`, but that it should be annotated with `@InputFile` or `@InputDirectory` instead.

If you use the `@Input` annotation on a file-based property, Gradle wouldn't consider the file contents, or the directory contents, as inputs, as you might expect.

To fix this problem, you need to tell Gradle if the file property represents an input file, in which case you should annotate it with `@InputFile`, or a directory, in which case it should be annotated with `@InputDirectory`.
If what you really wanted to say is that the actual file path is an input, then you should return a `String` instead which corresponds to the absolute path of the file.



