[[version-catalog-problems]]
= Troubleshooting version catalog problems

This page summarizes the different problems that Gradle reports when using version catalogs and provides guidance for fixing them.

[[accessor_name_clash]]
== Accessor name clash

This error indicates that your version catalog contains (at least) two aliases which are mapped to the same accessor.
Given an alias like `some.alias`, Gradle implements a mapping strategy to a _getter_ for type-checked accessors.
In this case, it means that two aliases are in conflict because they result in the same getter being created.

To fix this problem, you must choose different aliases.

[[too_many_entries]]
== Too many entries in a single catalog

This error indicates that a version catalog contains too many entries.
Because of JVM file format restrictions, when Gradle generates dependency accessors, it has to put an upper limit to the number of aliases that a catalog may contain.
This limit is currently of 32000 entries.

To fix this problem, if you need more entries, it's probably best to split the catalog into multiple, distinct catalogs.

[[reserved_alias_name]]
== Use of a reserved alias name

This error indicates that you chose an alias which is a reserved name.
Typically this happens if you choose an alias which ends with `version` or `bundle`, as it may clash with generated accessors.

To fix this problem, you must choose a different alias.

[[undefined_version_reference]]
== Undefined version reference

This error indicates that your catalog declares a library which references a non-existing version.
When you use version references in a catalog, the version reference must point to an existing version alias.

To fix this, you must either:

- fix the version reference to use one of the versions declared in the catalog
- or declare a new version corresponding to the reference you want to use in the catalog

It's worth noting that catalogs are isolated, so you cannot use a version reference from one catalog in another catalog.
