/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id("gradlebuild.distribution.api-java")
}

description = "Implementation of the Problems API reporting services, shared by the daemon and worker processes"

dependencies {
    api(projects.baseServices)
    api(projects.buildOperations)
    api(projects.problemsApi)
    api(projects.serialization)
    api(projects.snapshots)

    compileOnly(libs.jspecify)

    implementation(libs.slf4jApi)
    implementation(projects.problemsRendering)

    testImplementation(projects.logging)
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}
