executable: gradle
args: "run -Dorg.gradle.continue=true"
expect-failure: true
expected-output-file: useTheGradlePropertiesFile-avoidGroovy.out
allow-additional-output: true
allow-disordered-output: true
