// Copyright 2023 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[build_file_basics]]
= Build File Basics

Every Gradle build is made up of one or more _projects_; a root project and subprojects.

For every project or subproject, there is a build script.

The default name of the build script file is either build.gradle( for Groovy) or build.gradle.kts( for Kotlin). There is a one-to-one relationship between a project instance and a build file.

The single project builds — Build file contains dependencies and repository information for both build script and project.

Multi-project build — Each sub-project may have its build file, and each sub-project will be evaluated by executing its build file, if present. The build file of a root project is generally used for sharing common things that will be needed in all sub-projects. For example, build script dependencies, and repository links to locate those dependencies. And common tasks like clean, which will delete the previously created resources by root project and each sub-project.

== Build script dependency Vs. Project dependency

Build script dependency means the libraries or plugins on which our Gradle build is dependent. For example, we want to build an Android project using Gradle then we need to add build script dependency on the com.android.tools.build:gradle, then only Gradle will know how to build an android application.

project.buildscript {
// repository links to locate build script dependencies.
repositories {
google()
jcenter()
}
// build script dependencies
dependencies {
val kotlin_version = "1.3.61"
classpath("com.android.tools.build:gradle:4.0.0-alpha09")
classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlin_version}")
}
}

On the other hand, project dependency is related to code which is going to be built. For example, let’s say our project need JUnit library to execute tests; hence we will need to declare JUnit dependency in the project scope and not in the build script scope.

project.repositories {
// repository links to locate project dependencies.
google()
jcenter()
}

project.dependencies {
// project dependencies
implementation("org.jetbrains.kotlin:kotlin-stdlib:${kotlin_version}")
testImplementation("junit:junit:4.12")
}
