package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'Check'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("Check")) {
    params {
        expect {
            param("env.GRADLE_ENTERPRISE_ACCESS_KEY", "%ge.gradle.org.access.key%")
        }
        update {
            param("env.GRADLE_ENTERPRISE_ACCESS_KEY", "credentialsJSON:e3d5c1dc-678f-4b7d-a13d-6f9dd5a3cfb5")
        }
    }
}
