apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'

repositories {
<% if (repository) { %>
    maven {
        url = rootProject.file("${repository.rootDir.name}")
    }
<% } %>
    mavenCentral()
}

<% if (binding.hasVariable("projectDependencies")) { %>
    configurations {
        compile.extendsFrom projectsConfiguration
    }
<% } %>

<% if (binding.hasVariable("springDmPluginVersion")) {%>
apply plugin: "io.spring.dependency-management"
dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:4.1.0'
        mavenBom 'io.spring.platform:platform-bom:2.0.8.RELEASE'
    }
}
<% } %>

dependencies {
    implementation 'org.apache.commons:commons-lang3:3.20.0'
    implementation "org.apache.httpcomponents.client5:httpclient5:5.6.2"
    implementation "commons-codec:commons-codec:1.22.0"
    implementation "org.slf4j:jcl-over-slf4j:2.0.18"
    implementation "org.apache.groovy:groovy:4.0.32"
    testImplementation 'junit:junit:4.13.2'
    runtimeOnly 'com.esotericsoftware:reflectasm:1.11.9'

    <% if (dependencies) { dependencies.each { %>
        implementation "${it.shortNotation()}" <% } %>
    <% } %>
    <% if (binding.hasVariable("projectDependencies")) { %>
        <% if (subprojectNumber != null && subprojectNumber - 3 > 0) { %>
            projectsConfiguration project(":project${subprojectNumber - 3 }")
            <% } %>
    <% } %>
}

test {
    if (!JavaVersion.current().java8Compatible) {
        jvmArgs('-XX:MaxPermSize=512m')
    }
    jvmArgs('-XX:+HeapDumpOnOutOfMemoryError')
    <% if (binding.hasVariable("fullTestLogging")) { %>
        testLogging {
            events "started", "skipped", "failed", "passed", "standard_out", "standard_error"
        }
    <% } %>
}

String compilerMemory = getProperty('compilerMemory')
String testRunnerMemory = getProperty('testRunnerMemory')
int testForkEvery = getProperty('testForkEvery') as Integer

tasks.withType(JavaCompile) {
    options.fork = true
    options.forkOptions.memoryInitialSize=compilerMemory
    options.forkOptions.memoryMaximumSize=compilerMemory
}
tasks.withType(Test) {
    minHeapSize = testRunnerMemory
    maxHeapSize = testRunnerMemory
    maxParallelForks = 4
    forkEvery = testForkEvery
}

<% if (groovyProject) { %>
apply plugin: 'groovy'
dependencies {
    implementation 'org.apache.groovy:groovy-all:4.0.32'
}
<% } %>

<% if (scalaProject) { %>
apply plugin: 'scala'
dependencies {
    implementation 'org.scala-lang:scala-library:2.13.18'
}
tasks.withType(ScalaCompile) {
    scalaCompileOptions.with {
        useAnt = false
        fork = true
        if (!JavaVersion.current().java8Compatible) {
            forkOptions.jvmArgs = ["-XX:MaxPermSize=512m"]
        }
    }
}
<% } %>

<% if (binding.hasVariable("resolveDependenciesTask")) { %>
task resolveDependencies {
    dependsOn configurations.testRuntimeClasspath
    // Need this to ensure that configuration is actually resolved
    doLast {
        configurations.testRuntimeClasspath.files.size()
    }
}
<% } %>

task dependencyReport(type: DependencyReportTask) {
    outputs.upToDateWhen { false }
    outputFile = new File(buildDir, "dependencies.txt")
}
