/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.api.plugins.quality.v2;

import groovy.lang.Closure;
import groovy.lang.DelegatesTo;
import org.gradle.api.Action;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.file.RegularFile;
import org.gradle.api.plugins.quality.AbstractCodeQualityTask;
import org.gradle.api.plugins.quality.CheckstyleReports;
import org.gradle.api.plugins.quality.internal.CheckstyleAction;
import org.gradle.api.plugins.quality.internal.CheckstyleActionParameters;
import org.gradle.api.plugins.quality.internal.CheckstyleReportsImpl;
import org.gradle.api.provider.MapProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.Provider;
import org.gradle.api.reporting.Reporting;
import org.gradle.api.resources.TextResource;
import org.gradle.api.tasks.CacheableTask;
import org.gradle.api.tasks.Classpath;
import org.gradle.api.tasks.Console;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.InputFiles;
import org.gradle.api.tasks.Internal;
import org.gradle.api.tasks.Nested;
import org.gradle.api.tasks.Optional;
import org.gradle.api.tasks.PathSensitive;
import org.gradle.api.tasks.PathSensitivity;
import org.gradle.api.tasks.TaskAction;
import org.gradle.internal.Describables;
import org.gradle.util.internal.ClosureBackedAction;
import org.gradle.workers.WorkQueue;
import org.gradle.api.Incubating;

/**
 * New Checkstyle task implementation that uses Gradle lazy properties.
 * All execution logic resides here. Legacy {@link org.gradle.api.plugins.quality.Checkstyle} delegates to this implementation.
 */
@CacheableTask
public abstract class Checkstyle extends AbstractCodeQualityTask implements Reporting<CheckstyleReports> {

    private final CheckstyleReports reports;

    public Checkstyle() {
        super();
        this.reports = getObjectFactory().newInstance(CheckstyleReportsImpl.class, Describables.quoted("Task", getIdentityPath()));
        getEnableExternalDtdLoadProperty().convention(false);
        getShowViolationsProperty().convention(true);
        getMaxWarningsProperty().convention(Integer.MAX_VALUE);
        getMaxErrorsProperty().convention(0);
    }

    /**
     * The class path containing the Checkstyle library to be used.
     */
    @Classpath
    public abstract ConfigurableFileCollection getCheckstyleClasspath();

    /**
     * The class path containing the compiled classes for the source files to be analyzed.
     */
    @Classpath
    public abstract ConfigurableFileCollection getClasspath();

    /**
     * The Checkstyle configuration to use.
     */
    @Nested
    public abstract Property<TextResource> getConfigProperty();

    /**
     * Resolved configuration file derived from {@link #getConfigProperty()}.
     */
    @Internal
    public Provider<RegularFile> getConfigFile() {
        return getProject().getLayout().file(getConfigProperty().map(TextResource::asFile));
    }

    /**
     * The properties available for use in the configuration file. These are substituted into the configuration file.
     */
    @Optional
    @Input
    public abstract MapProperty<String, Object> getConfigPropertiesProperty();

    /**
     * Path to other Checkstyle configuration files. Exposed as variable {@code config_loc} in Checkstyle configs.
     */
    @PathSensitive(PathSensitivity.RELATIVE)
    @InputFiles
    public abstract DirectoryProperty getConfigDirectory();

    /**
     * The reports to be generated by this task.
     */
    @Override
    @Nested
    public final CheckstyleReports getReports() {
        return reports;
    }

    /**
     * The maximum number of errors tolerated before failing the task.
     */
    @Input
    public abstract Property<Integer> getMaxErrorsProperty();

    /**
     * The maximum number of warnings tolerated before failing the task.
     */
    @Input
    public abstract Property<Integer> getMaxWarningsProperty();

    /**
     * Whether to show violations on the console.
     */
    @Console
    public abstract Property<Boolean> getShowViolationsProperty();

    /**
     * Whether to enable external DTD loading for Checkstyle.
     */
    @Incubating
    @Input
    public abstract Property<Boolean> getEnableExternalDtdLoadProperty();

    // Reports configuration bridge
    @Override
    @SuppressWarnings({"rawtypes", "unused"})
    public CheckstyleReports reports(@DelegatesTo(value = CheckstyleReports.class, strategy = Closure.DELEGATE_FIRST) Closure closure) {
        return reports(new ClosureBackedAction<>(closure));
    }

    @Override
    public CheckstyleReports reports(Action<? super CheckstyleReports> configureAction) {
        configureAction.execute(reports);
        return reports;
    }

    // Execution
    @TaskAction
    public void run() {
        WorkQueue workQueue = getWorkerExecutor().processIsolation(spec -> {
            configureForkOptions(spec.getForkOptions());
            spec.getForkOptions().getSystemProperties().put("checkstyle.enableExternalDtdLoad", getEnableExternalDtdLoadProperty().get().toString());
        });
        workQueue.submit(CheckstyleAction.class, this::setupParameters);
    }

    private void setupParameters(CheckstyleActionParameters parameters) {
        parameters.getAntLibraryClasspath().setFrom(getCheckstyleClasspath());
        Provider<RegularFile> configFile = getConfigFile();
        parameters.getConfig().set(configFile);
        parameters.getMaxErrors().set(getMaxErrorsProperty());
        parameters.getMaxWarnings().set(getMaxWarningsProperty());
        parameters.getIgnoreFailures().set(getIgnoreFailuresProperty());
        parameters.getConfigDirectory().set(getConfigDirectory());
        parameters.getShowViolations().set(getShowViolationsProperty());
        parameters.getSource().setFrom(getSource());
        parameters.getIsHtmlRequired().set(getReports().getHtml().getRequired());
        parameters.getIsXmlRequired().set(getReports().getXml().getRequired());
        parameters.getIsSarifRequired().set(getReports().getSarif().getRequired());
        parameters.getXmlOutputLocation().set(getReports().getXml().getOutputLocation());
        parameters.getHtmlOutputLocation().set(getReports().getHtml().getOutputLocation());
        parameters.getSarifOutputLocation().set(getReports().getSarif().getOutputLocation());
        parameters.getTemporaryDir().set(getTemporaryDir());
        parameters.getConfigProperties().set(getConfigPropertiesProperty());
        if (getReports().getHtml().getStylesheet() != null) {
            parameters.getStylesheetString().set(getReports().getHtml().getStylesheet().asString());
        }
    }
}
