[[declaring-repositories]]
= Declare Repositories

Gradle allows you to define **repositories**: sources for dependency downloads.
During a build, Gradle searches repositories to resolve dependencies.
You can specify repositories as locations in a file system or URLs.
Gradle can resolve dependencies from one or many repositories.

[TIP]
====
Can't find the information you're looking for?
Check out the <<repositories_cheat_sheet.adoc#repositories-cheat-sheet, Repositories Cheat Sheet>> for advanced content about repositories.
====

[[sec:repository-types]]
== Supported Repository Types

Gradle supports the following repository formats:

* <<#sec:maven_repo,Maven compatible artifact repositories>>
* <<#sec:ivy_repositories,Ivy compatible artifact repositories>>
* <<#sub:flat_dir_resolver,local (flat) directories>>

Gradle supports the following connection methods to access repositories:

* <<repositories_cheat_sheet.adoc#sec:authentication_schemes,authenticated repositories>>
* <<repositories_cheat_sheet.adoc#sec:supported_transport_protocols,remote protocols>> including HTTPS, SFTP, AWS S3 and Google Cloud Storage

[[sec:declaring_multiple_repositories]]
== Declare Multiple Repositories

You an declare more than one repository within a single build.
This can come in handy when certain dependencies are only available in one repository.

Gradle uses the following rules to decide which repository to use to download each dependency:

- Gradle searches repositories in the order that they are declared.
- When Gradle finds a dependency, it attempts to download all artifacts for that dependency from that same repository.

The following build script example declares multiple repositories:

====
include::sample[dir="snippets/dependencyManagement/declaringRepositories-multipleRepositories/groovy",files="build.gradle[tags=multiple-repositories]"]
include::sample[dir="snippets/dependencyManagement/declaringRepositories-multipleRepositories/kotlin",files="build.gradle.kts[tags=multiple-repositories]"]
====

[NOTE]
====
For more information about dependency resolution with multiple repositories, see <<dependency_resolution.adoc#sec:how-gradle-downloads-deps, dependency downloads>>.
====

[[sec:declaring_public_repository]]
== Declare a Repository with Shorthand Notation

Gradle provides built-in shorthand notations for certain widely-used repositories.
Popular repositories include <<#sub:maven_central,Maven Central>> and <<#sub:maven_google,Google's Maven repository for Android>>.
For a full list of built-in shorthand notations, see link:{groovyDslPath}/org.gradle.api.artifacts.dsl.RepositoryHandler.html[RepositoryHandler].
To declare a repository that doesn't have a built-in shorthand notation, declare the repository by URL.

[[sub:maven_central]]
=== Declare the Maven Central Repository

The Maven Central repository hosts open source libraries for Java projects.
To add the link:https://repo.maven.apache.org/maven2/[Maven Central repository] to your build, add the following to your build script:

====
include::sample[dir="snippets/artifacts/defineRepository/groovy",files="build.gradle[tags=maven-central]"]
include::sample[dir="snippets/artifacts/defineRepository/kotlin",files="build.gradle.kts[tags=maven-central]"]
====

[[sub:maven_google]]
=== Declare the Google Maven Repository

The Google Maven repository hosts Android-specific artifacts, including the Android SDK.
To add the link:https://maven.google.com/[Google Maven repository] to your build, add the following to your build script:

====
include::sample[dir="snippets/artifacts/defineRepository/groovy",files="build.gradle[tags=maven-google]"]
include::sample[dir="snippets/artifacts/defineRepository/kotlin",files="build.gradle.kts[tags=maven-google]"]
====

[[sub:flat_dir_resolver]]
== Declare a Flat Directory Repository

Some projects store dependencies on a shared drive or as part of the project source code instead of a binary repository product.
Gradle calls this a directory repository.
The following example adds a directory repository to a project:

====
include::sample[dir="snippets/artifacts/defineRepository/groovy",files="build.gradle[tags=flat-dir-multi]"]
include::sample[dir="snippets/artifacts/defineRepository/kotlin",files="build.gradle.kts[tags=flat-dir-multi]"]
====

Directory repositories do not support metadata file formats like Ivy XML or Maven POM files.
Instead, Gradle dynamically generates a module descriptor (without any dependency information) based on the presence of artifacts.
Gradle prefers modules with dependency information.
As a result, dependencies sourced from a directory repository are only used when no other repository contains that dependency.
To override remote artifacts with local artifacts, consider using a local Ivy or Maven repository instead.

Because directory repositories don't provide metadata, Gradle disables the <<dependency_resolution.adoc#sec:dependency_cache,dependency cache>> for directory repositories.

[[sec:maven_repo]]
== Declare a Maven Repository

You can declare Maven repositories by URL.
To add a Maven repository to your build, add the following to your build script:

====
include::sample[dir="snippets/artifacts/defineRepository/groovy",files="build.gradle[tags=maven-like-repo]"]
include::sample[dir="snippets/artifacts/defineRepository/kotlin",files="build.gradle.kts[tags=maven-like-repo]"]
====

Maven POM metadata can reference external repositories.
Gradle ignores these additional repositories to ensure the reproducibility and security of Gradle builds.

[[sub:custom-maven-repo]]
=== Declare a Composite Maven Repository

Sometimes repositories publish metadata and artifacts in separate locations.
Gradle calls these *composite repositories*.
To add a composite Maven repository to your build, add the following to your build script:

====
include::sample[dir="snippets/artifacts/defineRepository/groovy",files="build.gradle[tags=maven-like-repo-with-jar-repo]"]
include::sample[dir="snippets/artifacts/defineRepository/kotlin",files="build.gradle.kts[tags=maven-like-repo-with-jar-repo]"]
====

Gradle automatically queries the base `url` location for metadata and artifacts.
If artifacts can't be found at the base URL, Gradle checks for artifacts at the extra `artifactUrls`.

[[sub:accessing_secured_maven_repositories]]
=== Access an Authenticated Maven Repository

You can specify credentials for Maven repositories secured by authentication.

Specify credentials for Maven repositories secured by basic authentication with link:{javadocPath}/org/gradle/api/credentials/PasswordCredentials.html[PasswordCredentials]:

====
include::sample[dir="snippets/artifacts/defineRepository/groovy",files="build.gradle[tags=authenticated-maven-repo]"]
include::sample[dir="snippets/artifacts/defineRepository/kotlin",files="build.gradle.kts[tags=authenticated-maven-repo]"]
====

For more information about authentication options, see <<repositories_cheat_sheet.adoc#sec:authentication_schemes>>.

[[sub:declare-a-release-or-snapshot-maven-repository]]
=== Declare a Release or Snapshot Maven Repository

Maven repositories sometimes contain either release artifacts or snapshot artifacts, but not both.
You can filter Maven repositories based on the artifact type with the `mavenContent` block:

====
include::sample[dir="snippets/dependencyManagement/declaringRepositories-filtering/groovy",files="build.gradle[tags=repository-snapshots]"]
include::sample[dir="snippets/dependencyManagement/declaringRepositories-filtering/kotlin",files="build.gradle.kts[tags=repository-snapshots]"]
====

[[sec:ivy_repositories]]
== Declare an Ivy Repository

You can declare Ivy repositories by URL.
To add an Ivy repository to your build, add the following to your build script:

====
include::sample[dir="snippets/artifacts/defineRepository/groovy",files="build.gradle[tags=ivy-repo]"]
include::sample[dir="snippets/artifacts/defineRepository/kotlin",files="build.gradle.kts[tags=ivy-repo]"]
====

[[sub:defining_a_named_layout_for_an_ivy_repository]]
=== Specify a Named Layout for an Ivy Repository

You can specify that your repository conforms to the Ivy or Maven default layout with a named layout.
To add an Ivy repository with a named layout to a build, add the following to your build script:

====
include::sample[dir="snippets/artifacts/defineRepository/groovy",files="build.gradle[tags=ivy-repo-with-maven-layout]"]
include::sample[dir="snippets/artifacts/defineRepository/kotlin",files="build.gradle.kts[tags=ivy-repo-with-maven-layout]"]
====

Gradle accepts the following layout values for Ivy repositories:

* `gradle`
* `maven`
* `ivy`

By default, Gradle uses the `gradle` layout.
For more information about these layouts, see link:{groovyDslPath}/org.gradle.api.artifacts.repositories.IvyArtifactRepository.html#org.gradle.api.artifacts.repositories.IvyArtifactRepository:layout(java.lang.String)[IvyArtifactRepository.layout(java.lang.String)].

[[sub:defining_custom_pattern_layout_for_an_ivy_repository]]
=== Specify a Custom Pattern Layout for an Ivy Repository

To declare an Ivy repository with a non-standard layout, add a *pattern layout* to the repository declaration:

====
include::sample[dir="snippets/artifacts/defineRepository/groovy",files="build.gradle[tags=ivy-repo-with-pattern-layout]"]
include::sample[dir="snippets/artifacts/defineRepository/kotlin",files="build.gradle.kts[tags=ivy-repo-with-pattern-layout]"]
====

Some repositories store Ivy metadata and artifacts in different locations. 
You can define separate patterns to fetch Ivy metadata and artifacts from these locations.
Use `artifact` to specify artifact location patterns, and `ivy` to specify Ivy metadata location patterns.
You can add multiple locations for both artifacts and metadata.
Gradle uses these patterns in the order that they are defined.
The following example shows a build script that declares multiple patterns:

====
include::sample[dir="snippets/artifacts/defineRepository/groovy",files="build.gradle[tags=ivy-repo-with-custom-pattern]"]
include::sample[dir="snippets/artifacts/defineRepository/kotlin",files="build.gradle.kts[tags=ivy-repo-with-custom-pattern]"]
====

==== Specify a Maven Style Custom Pattern Layout

Some Ivy repositories use Maven style for organisation layouts, where forward slashes replace dots as separators.
For example, Maven style represents the organisation `my.company` as `my/company`.

To use Maven style organization layouts in a repository, assign `m2compatible` a value of "true" in the `patternLayout` block:

====
include::sample[dir="snippets/artifacts/defineRepository/groovy",files="build.gradle[tags=ivy-repo-with-m2compatible-layout]"]
include::sample[dir="snippets/artifacts/defineRepository/kotlin",files="build.gradle.kts[tags=ivy-repo-with-m2compatible-layout]"]
====

[[sub:accessing_secured_ivy_repositories]]
=== Access an Authenticated Ivy Repository

You can specify credentials for Ivy repositories secured by basic authentication:

====
include::sample[dir="snippets/artifacts/defineRepository/groovy",files="build.gradle[tags=authenticated-ivy-repo]"]
include::sample[dir="snippets/artifacts/defineRepository/kotlin",files="build.gradle.kts[tags=authenticated-ivy-repo]"]
====

For additional authentication options, see <<repositories_cheat_sheet.adoc#sec:supported_transport_protocols,supported transport protocols>>.

[[sec:repository-content-filtering]]
== Filter Repository Contents

Gradle exposes an API to control which dependencies your project can fetch from a repository.
Common use cases include:

* performance (e.g. you know a dependency will never be found in a specific repository)
* security  (e.g. avoiding leaking dependencies used in a private project)
* reliability (e.g. some repositories contain corrupted metadata or artifacts)

To add a filter to a repository, add an include or exclude clause to the `content` block within the repository configuration.
The following example:

* uses an inclusion clause to fetch only dependencies produced by a specific organization from a maven repository defined with a custom URL
* uses an exclusion clause to exclude dependencies produced by that same organization from the Maven Central repository defined with built-in shorthand notation

====
include::sample[dir="snippets/dependencyManagement/declaringRepositories-filtering/groovy",files="build.gradle[tags=repository-filter]"]
include::sample[dir="snippets//dependencyManagement/declaringRepositories-filtering/kotlin",files="build.gradle.kts[tags=repository-filter]"]
====

By default, repositories include everything and exclude nothing.
Adding an include or exclude clause has the following side effects:

* If you declare only includes, Gradle includes *only dependencies that match the includes*.
* If you declare only excludes, Gradle includes *everything except dependencies that match the excludes*.
* If you declare both includes and excludes, Gradle includes *only dependencies that match the includes that also do not match the excludes*.

You can filter by _group_, _module_ or _version_, either with strict string matching or regular expressions.
You can filter versions by version range, using <<single_versions.adoc#single-version-declarations,the Gradle version format>>.
You can also filter by configuration name or attributes.
See link:{javadocPath}/org/gradle/api/artifacts/repositories/RepositoryContentDescriptor.html[RepositoryContentDescriptor] for details.


=== Declare Content Exclusively Found in One Repository

Including a dependency in one repository doesn't prevent other repositories from also including that dependency.
For situations where you must source a dependency from a specific repository -- and no other repository -- you can declare *exclusive content*.
To declare exclusive content, you must declare a repository and a dependency filter.
When a dependency matches the filter, Gradle only searches the exclusive content repository for the dependency.
If Gradle doesn't find the dependency in the exclusive content repository, it doesn't look for the dependency in any other repositories.

The following snippet declares an `exclusiveContent` block that uses a custom URL maven repository to source dependencies only from a specific organization:

====
include::sample[dir="snippets/dependencyManagement/declaringRepositories-filtering/groovy",files="build.gradle[tags=exclusive-repository-filter]"]
include::sample[dir="snippets/dependencyManagement/declaringRepositories-filtering/kotlin",files="build.gradle.kts[tags=exclusive-repository-filter]"]
====

Exclusive content uses the same filters as repository filters.

[WARN]
====
Exclusive content filtering in the Gradle settings file <<plugins.adoc#sec:custom_plugin_repositories,pluginManagement>> block is not compatible with build script repository declaration.
If you must use exclusive content filters in the `pluginManagement` block, you must declare all of your repositories in the settings file.
====

=== Filter a Maven Repository by Artifact Type (Releases or Snapshots)

Some Maven repositories only contain releases or snapshots, not both.
To filter Maven repository contents by artifact type, see <<sub:declare-a-release-or-snapshot-maven-repository,Declare a Release or Snapshot Maven Repository>>.

[[sub:centralized-repository-declaration]]
== Centralize Repositories Declarations

NOTE: Central declaration of repositories is an incubating feature.

In large projects that contain multiple subprojects, it can be tedious to declare independent repository settings within each subproject.
Instead, you can declare repositories centrally in the Gradle settings file:

====
include::sample[dir="snippets/artifacts/defineRepositoryInSettings/groovy",files="settings.gradle[tags=declare_repositories_settings]"]
include::sample[dir="snippets/artifacts/defineRepositoryInSettings/kotlin",files="settings.gradle.kts[tags=declare_repositories_settings]"]
====

The `repositories` block within `dependencyResolutionManagement` uses the same syntax as the corresponding build script blocks.

=== Override Build Script Repositories with Central Declarations

By default, repositories declared within build scripts *override* centrally declared repositories.
You can change this behavior to always use centrally declared repositories when available:

====
include::sample[dir="snippets/artifacts/defineRepositoryInSettings/groovy",files="settings.gradle[tags=prefer_settings]"]
include::sample[dir="snippets/artifacts/defineRepositoryInSettings/kotlin",files="settings.gradle.kts[tags=prefer_settings]"]
====

[[sub:fail_build_on_project_repositories]]

Gradle emits a warning when a build ignores build script repositories.
You can change this behavior to instead _fail the build_ when a build script declares repositories:

====
include::sample[dir="snippets/artifacts/defineRepositoryInSettings/groovy",files="settings.gradle[tags=enforce_settings]"]
include::sample[dir="snippets/artifacts/defineRepositoryInSettings/kotlin",files="settings.gradle.kts[tags=enforce_settings]"]
====

[[sub:plugin-repos]]
== Declare a Plugin Repository

When resolving dependencies, Gradle uses *build repositories* to fetch dependencies.
When <<build_lifecycle.adoc#sec:build_phases,configuring your build>>, Gradle uses *plugin repositories* to fetch applied plugins.

By default, Gradle uses the http://plugins.gradle.org[Gradle plugin portal] to look for plugins.
But you can also source plugins from other repositories.

Plugin repository declaration syntax depends on the way you apply the plugin.
For more information, see <<plugins.adoc#sec:custom_plugin_repositories, Custom Plugin Repositories>>.

[TIP]
====
Can't find the information you're looking for?
Check out the <<repositories_cheat_sheet.adoc#repositories-cheat-sheet, Repositories Cheat Sheet>> for advanced content about repositories.
====