[[config_cache]]
= Configuration cache

- What is it?
- How to enable it?
- How does it work?
- Limitations?
- Diagnosing problems?


[NOTE]
====
The configuration cache is an incubating feature: details are subject to change.
====


== Usage

[[enable]]
=== Enabling the configuration cache

The configuration cache can be enabled from the command line:

[source,bash]
----
gradle --configuration-cache=on
----

It can also be enabled persistently in a `gradle.properties` file:

[source,properties]
----
org.gradle.unsafe.configuration-cache=on
----

If it is enabled in a `gradle.properties` file, it can be disabled on the command line for one build invocation:

[source,bash]
----
gradle --configuration-cache=off
----

[[ignore_problems]]
=== Ignoring problems

Configuration cache problems can be turned into warnings on the command line:

[source,bash]
----
gradle --configuration-cache=warn
----

or in a `gradle.properties` file:

[source,properties]
----
org.gradle.unsafe.configuration-cache=warn
----

[[max_problems]]
=== Allowing a maximum number of problems

When configuration cache problems are turned into warnings, Gradle will fail the build if `512` problems are found by default.

This can be adjusted by specifying an allowed maximum number of problems on the command line:

[source,bash]
----
gradle -Dorg.gradle.unsafe.configuration-cache.max-problems=1024
----

or in a `gradle.properties` file:

[source,properties]
----
org.gradle.unsafe.configuration-cache.max-problems=1024
----


== Constraints

Constraints and how to change your build

[[disallowed_types]]
== Types that must not be referenced by tasks

There are a number of types that task instances must not reference from their fields. Usually these types are used to carry some task input that should be explicitly
declared instead.

[[use_project_during_execution]]
== Using the Project object

A task must not use any `Project` objects at execution time. This includes calling `Task.getProject()` while the task is running.

[[build_listeners]]
== Using build listeners

Plugins and build scripts must not register any build listeners.

[[undeclared_sys_prop_reads]]
=== Reading system properties

Plugins and build scripts should not read system properties directly using the Java APIs. Instead, these system properties must be declared as a potential build input by
using the value supplier APIs.

Before:

```
def enabled = System.getProperty("some-property")
```

After:

```
def enabled = providers.systemProperty("some-property").forUseAtConfigurationTime().present
```

[[not_yet_implemented]]
== Not yet implemented

Support for using configuration caching with certain Gradle features is not yet implemented.

- Composite builds


[[testkit]]
== Testing Build Logic with TestKit

The Gradle TestKit (a.k.a. just TestKit) is a library that aids in testing Gradle plugins and build logic generally.
For general guidance on how to use TestKit see the <<test_kit.adoc#test_kit,dedicated chapter>>.

To enable configuration caching in your tests, you can pass the `--configuration-cache=on` argument to link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html[GradleRunner] or use one of the other methods described in <<configuration_cache.adoc#enable,Enabling the configuration cache>>.

You need to run your tasks twice.
Once to store the configuration cache.
Once to reuse the configuration cache.

.Testing the configuration cache
====
include::sample[dir="snippets/configurationCache/testKit/groovy",files="src/test/groovy/org/example/BuildLogicFunctionalTest.groovy[tags=functional-test-configuration-cache]"]
include::sample[dir="snippets/configurationCache/testKit/kotlin",files="src/test/kotlin/org/example/BuildLogicFunctionalTest.kt[tags=functional-test-configuration-cache]"]
====
<1> First run stores the configuration cache.
<2> Second run reuses the configuration cache.
<3> Assert that the configuration cache gets reused.

If problems with the configuration cache are found then Gradle will fail the build reporting the problems, and the test will fail.

When gradually improving your plugin or build logic to support the configuration cache it can be useful to temporarily <<configuration_cache.adoc#ignore_problems,ignore problems>> or <<configuration_cache.adoc#max_problems,allow a given number of problems>>.
