[[config_cache]]
= Configuration cache

// Run tests for snippets included in this chapter with:
// ./gradlew :docs:docsTest --tests="ExemplarExternalSamplesFunctionalTest.snippet-configuration-cache-*"

[NOTE]
====
The configuration cache is an <<feature_lifecycle.adoc#feature_lifecycle,incubating>> feature, and the details described here may change.
====

// TODO prefix anchors sec:, problem:,

== Introduction

The configuration cache is a feature that significantly improves build performance by caching the result of the <<build_lifecycle#build_lifecycle,configuration phase>> and reusing this for subsequent builds.
Using the configuration cache, Gradle can skip the configuration phase entirely when nothing that affects the build configuration, such as build scripts, has changed.
Gradle also applies some performance improvements to task execution as well.

The configuration cache is conceptually similar to the <<build_cache#build_cache,build cache>>, but caches different information.
The build cache takes care of caching the outputs and intermediate files of the build, such as task outputs or artifact transform outputs.
The configuration cache takes care of caching the build configuration for a particular set of tasks.
In other words, the configuration cache caches the output of the configuration phase, and the build cache caches the outputs of the execution phase.

[IMPORTANT]
====
This feature is currently *experimental* and not enabled by default.

Not all <<configuration_cache#core_plugins, core Gradle plugins>> are supported.
Your build and the plugins you depend on might require changes to fulfil the <<configuration_cache#requirements, requirements>>.
Some Gradle features are <<configuration_cache#not_yet_implemented, not yet implemented>>.
====

=== How does it work?

When the configuration cache is enabled and you run Gradle for a particular set of tasks, for example by running `gradlew check`, Gradle checks whether a configuration cache entry is available for the requested set of tasks.
If available, Gradle uses this entry instead of running the configuration phase.
The cache entry contains information about the set of tasks to run, along with their configuration and dependency information.

The first time you run a particular set of tasks, there will be no entry in the configuration cache for these tasks and so Gradle will run the configuration phase as normal:

1. Run init scripts.
2. Run the settings script for the build, applying any requested settings plugins.
3. Configure and build the `buildSrc` project, if present.
4. Run the builds scripts for the build, applying any requested project plugins.
5. Calculate the task graph for the requested tasks, running any deferred configuration actions.

Following the configuration phase, Gradle writes the state of the task graph to the configuration cache, taking a snapshot for later Gradle invocations.
The execution phase then runs as normal.
This means you will not see any build performance improvement the first time you run a particular set of tasks.

When you subsequently run Gradle with this same set of tasks, for example by running `gradlew check` again, Gradle will load the tasks and their configuration directly from the configuration cache and skip the configuration phase entirely.
Before using a configuration cache entry, Gradle checks that none of the "build inputs", such as build scripts, for the entry have changed.
If a build input has changed, Gradle will not use the entry and will run the configuration phase again as above, saving the result for later reuse.

Build inputs include:

- Init scripts, settings scripts, build scripts.
- System properties, Gradle properties and configuration files used during the configuration phase, accessed using value suppliers (TODO - add docs for this).
- build inputs and source files for `buildSrc` projects.

=== Performance improvements

Apart from skipping the configuration phase, the configuration cache provides some additional performance improvements:

- All tasks run in parallel by default.
- Dependency resolution is cached.

== Using the configuration cache

It is recommended to get started with the simplest task invocation possible.
Running `help` with the configuration cache enabled is a good first step:

[source,text]
----
❯ gradle --configuration-cache help
include::{snippetsPath}/configurationCache/noProblem/tests/store.out[]
Configuration cache entry stored.
----

Running this for the first time, the configuration phase is executed, calculating the task graph.

Then, run the same command again.
This will reuse the cached configuration:

[source,text]
----
❯ gradle --configuration-cache help
include::{snippetsPath}/configurationCache/noProblem/tests/load.out[]
Configuration cache entry reused.
----

If it succeeds on your build, congratulations, you can now try with more useful tasks.
You should target your development loop.
A good example is running tests after making incremental changes.

If any problem is found caching or reusing the configuration, an HTML report is generated to help you diagnose and fix the issues.
See the <<configuration_cache#troubleshooting>> section below for more information.

Keep reading to learn how to tweak the configuration cache, manually invalidate the state if something goes wrong and use the configuration cache from an IDE.

[[enable]]
=== Enabling the configuration cache

By default, the configuration cache is not enabled.
It can be enabled from the command line:

[source,bash]
----
❯ gradle --configuration-cache
----

It can also be enabled persistently in a `gradle.properties` file:

[source,properties]
----
org.gradle.unsafe.configuration-cache=true
----

If it is enabled in a `gradle.properties` file, it can be disabled on the command line for one build invocation:

[source,bash]
----
❯ gradle --no-configuration-cache
----

[[ignore_problems]]
=== Ignoring problems

By default, Gradle will fail the build if any configuration cache problems are encountered.
Configuration cache problems can be turned into warnings on the command line:

[source,bash]
----
❯ gradle --configuration-cache-problems=warn
----

or in a `gradle.properties` file:

[source,properties]
----
org.gradle.unsafe.configuration-cache-problems=warn
----

[[max_problems]]
=== Allowing a maximum number of problems

When configuration cache problems are turned into warnings, Gradle will fail the build if `512` problems are found by default.

This can be adjusted by specifying an allowed maximum number of problems on the command line:

[source,bash]
----
❯ gradle -Dorg.gradle.unsafe.configuration-cache.max-problems=5
----

or in a `gradle.properties` file:

[source,properties]
----
org.gradle.unsafe.configuration-cache.max-problems=5
----

[[invalidating_the_cache]]
=== Invalidating the cache

The configuration cache is automatically invalidated when inputs to the configuration phase change.
But, you may have to manually invalidate the configuration cache when untracked inputs to the configuration phase change.
This can happen if you <<configuration_cache#ignore_problems,ignored problems>>, or when your build uses <<dynamic_versions#sec:dynamic_versions_and_changing_modules, dynamic dependency versions>> and remote dependencies changed for example.
See the <<configuration_cache#requirements>> and <<configuration_cache#not_yet_implemented>> sections below for more information.

The configuration cache state is stored on disk in a directory named `.gradle/configuration-cache` in the root directory of the Gradle build in use.
If you need to invalidate the cache, simply delete that directory:

[source,bash]
----
❯ rm -rf .gradle/configuration-cache
----

Configuration cache entries are checked periodically (at most every 24 hours) for whether they are still in use.
They are deleted if they haven't been used for 7 days.

== IDE support

If you enable and configure the configuration cache from your `gradle.properties` file, then the configuration cache will be enabled when your IDE delegates to Gradle.
There's nothing more to do.

`gradle.properties` is usually checked in source control.
If you don't want to enable the configuration cache for your whole team yet you can also enable the configuration cache from your IDE only.

Note that syncing a build from an IDE doesn't benefit from the configuration cache, only running tasks does.
Future Gradle versions will make IDE sync faster.

=== IntelliJ based IDEs

In IntelliJ IDEA or Android Studio this can be done in two ways, either globally or per run configuration.

To enable it globally, go to `Help > Edit Custom VM Options...`.
This will open the IntelliJ IDEA or Android Studio custom VM options file.
You can use the properties described above as system properties.
For example to enable the configuration cache, turning problems into warnings, add the following to this file:

[source]
----
-Dorg.gradle.unsafe.configuration-cache=true
-Dorg.gradle.unsafe.configuration-cache-problems=warn
----

To enable it for a given run configuration, simply add the same system properties to the `VM options` field.

Combining these two ways you can enable globally and disable for certain run configurations, or the opposite.

=== Eclipse IDEs

In Eclipse IDEs you can enable and configure the configuration cache through Buildship in two ways, either globally or per run configuration.

To enable it globally, go to `Preferences > Gradle`.
You can use the properties described above as system properties.
For example to enable the configuration cache, turning problems into warnings, add the following JVM arguments:

* `-Dorg.gradle.unsafe.configuration-cache=true`
* `-Dorg.gradle.unsafe.configuration-cache-problems=warn`

To enable it for a given run configuration, go to `Run configurations...`, find the one you want to change, go to `Project Settings`, tick the `Override project settings` checkbox and add the same system properties as a `JVM argument`.

Combining these two ways you can enable globally and disable for certain run configurations, or the opposite.

[[plugin_support]]
== Supported plugins

The configuration cache is brand new and has strong requirements.
As a result, both core Gradle plugins, and third party plugins need to be adjusted.
This section provides information about the current support in <<configuration_cache#core_plugins, core Gradle plugins>> and <<configuration_cache#third_party_plugins, third party plugins>>.

[[core_plugins]]
=== Core Gradle plugins

Not all <<plugin_reference#plugin_reference, core Gradle plugins>> support configuration caching yet.

[cols=3*]
|===
h| JVM languages and frameworks
h| Native languages
h| Packaging and distribution

a|
[horizontal]
[.yellow]#⚠#:: <<java_plugin.adoc#java_plugin,Java>>
[.yellow]#⚠#:: <<java_library_plugin.adoc#java_library_plugin,Java Library>>
[.yellow]#⚠#:: <<java_platform_plugin.adoc#java_platform_plugin,Java Platform>>
[.yellow]#⚠#:: <<groovy_plugin.adoc#groovy_plugin,Groovy>>
[.red]#✖#:: <<scala_plugin.adoc#scala_plugin,Scala>>
[.yellow]#⚠#:: <<antlr_plugin.adoc#antlr_plugin,ANTLR>>

a|
[horizontal]
[.red]#✖#:: <<cpp_application_plugin.adoc#cpp_application_plugin,C++ Application>>
[.red]#✖#:: <<cpp_library_plugin.adoc#cpp_library_plugin,C++ Library>>
[.red]#✖#:: <<cpp_unit_test_plugin.adoc#cpp_unit_test_plugin,C++ Unit Test>>
[.red]#✖#:: <<swift_application_plugin.adoc#swift_application_plugin,Swift Application>>
[.red]#✖#:: <<swift_library_plugin.adoc#swift_library_plugin,Swift Library>>
[.red]#✖#:: <<xctest_plugin.adoc#xctest_plugin,XCTest>>

a|
[horizontal]
[.green]#✓#:: <<application_plugin.adoc#application_plugin,Application>>
[.yellow]#⚠#:: <<war_plugin.adoc#war_plugin,WAR>>
[.green]#✓#:: <<ear_plugin.adoc#ear_plugin,EAR>>
[.yellow]#⚠#:: <<publishing_maven.adoc#publishing_maven,Maven Publish>>
[.red]#✖#:: <<publishing_ivy.adoc#publishing_ivy,Ivy Publish>>
[.gray]#✖#:: <<maven_plugin.adoc#maven_plugin,Legacy Maven Plugin>>
[.green]#✓#:: <<distribution_plugin.adoc#distribution_plugin,Distribution>>
[.yellow]#⚠#:: <<java_library_distribution_plugin.adoc#java_library_distribution_plugin,Java Library Distribution>>

h| Code analysis
h| IDE integration
h| Utility

a|
[horizontal]
[.red]#✖#:: <<checkstyle_plugin.adoc#checkstyle_plugin,Checkstyle>>
[.red]#✖#:: <<pmd_plugin.adoc#pmd_plugin,PMD>>
[.red]#✖#:: <<jacoco_plugin.adoc#jacoco_plugin,JaCoCo>>
[.red]#✖#:: <<codenarc_plugin.adoc#codenarc_plugin,CodeNarc>>

a|
[horizontal]
[.red]#✖#:: <<eclipse_plugin.adoc#eclipse_plugin,Eclipse>>
[.red]#✖#:: <<idea_plugin.adoc#idea_plugin,IntelliJ IDEA>>
[.red]#✖#:: <<visual_studio_plugin.adoc#visual_studio_plugin,Visual Studio>>
[.red]#✖#:: <<xcode_plugin.adoc#xcode_plugin,Xcode>>

a|
[horizontal]
[.green]#✓#:: <<base_plugin.adoc#base_plugin,Base>>
[.green]#✓#:: <<build_init_plugin.adoc#build_init_plugin,Build Init>>
[.red]#✖#:: <<signing_plugin.adoc#signing_plugin,Signing>>
[.yellow]#⚠#:: <<java_gradle_plugin.adoc#java_gradle_plugin,Plugin Development>>
[.red]#✖#:: <<kotlin_dsl.adoc#sec:kotlin-dsl_plugin,Kotlin DSL Plugin Development>>
[.red]#✖#:: <<project_report_plugin.adoc#project_report_plugin,Project Report Plugin>>

|===

[horizontal]
[.green]#✓#:: Supported plugin
[.yellow]#⚠#:: Partially supported plugin
[.red]#✖#:: Unsupported plugin
[.gray]#✖#:: Won't fix

Later Gradle releases will add support for more core plugins.

[[third_party_plugins]]
=== Third party plugins

Please refer to issue link:https://github.com/gradle/gradle/issues/13490[gradle/gradle#13490] to learn about the status of third party plugins.

[[troubleshooting]]
== Troubleshooting

The following sections will go through some general guidelines on dealing with problems with the configuration cache.
This applies to both your build logic and to your Gradle plugins.

Upon failure to serialize the state required to run the tasks, an HTML report of detected problems is generated.
The Gradle failure output includes a clickable link to the report.
This report is useful and allows to drill down into problems, understand what is causing them.

Let's look at a simple example build script that contains a couple problems:

====
include::sample[dir="snippets/configurationCache/problemsGroovy/groovy",files="build.gradle[]"]
include::sample[dir="snippets/configurationCache/problemsKotlin/kotlin",files="build.gradle.kts[]"]
====
<1> <<configuration_cache#undeclared_sys_prop_read, Undeclared system property read at configuration time>>
<2> <<configuration_cache#use_project_during_execution, Using the `Project` object at execution time>>

Running that task fails and print the following in the console:

[source,text]
----
❯ gradle --configuration-cache someTask -DsomeMessage=hello
...
include::{snippetsPath}/configurationCache/problemsKotlin/tests/store.out[]
Configuration cache entry stored.
----

Details can be found in the linked HTML report.
The report displays the set of problems twice.
First grouped by problem message, then grouped by task.
The former allows to quickly see what classes of problems your build is facing.
The latter allows to quickly see which tasks are problematic.
In both cases you can expand the tree in order to discover where in the object graph is the culprit.

[TIP]
====
Problems displayed in the report have links to the corresponding <<configuration_cache#requirements,requirement>> where you can find guidance on how to fix the problem or to the corresponding <<configuration_cache#not_yet_implemented,not yet implemented>> feature.

When changing your build or plugin to fix the problems you should consider <<configuration_cache#testkit, testing your build logic with TestKit>>.
====

At this stage, you can decide to either <<configuration_cache#ignore_problems, turn the problems into warnings>> and continue exploring how your build reacts to the configuration cache, or fix the problems at hand.

Let's ignore the problems reported when storing the configuration cache, and run the same build again to see what happens when reusing the problematic cached configuration:

[source,text]
----
❯ gradle --configuration-cache someTask -DsomeMessage=hello
...
include::{snippetsPath}/configurationCache/problemsKotlin/tests/load.out[]
Configuration cache entry reused.
----

The build fails again, reporting the observed problems.
The first problem that happened at configuration time when storing is not reported given the configuration phase was skipped.
The second problem about using `Project` at execution time is reported.

With the help of the links present in the console problem summary and in the HTML report we can fix our problems.
Here's a fixed version of the build script:

====
include::sample[dir="snippets/configurationCache/problemsFixed/groovy",files="build.gradle[]"]
include::sample[dir="snippets/configurationCache/problemsFixed/kotlin",files="build.gradle.kts[]"]
====
<1> we turned our ad-hoc task into a proper task class
<2> this allows the injection of the `ExecOperations` service, a supported replacement for `project.exec {}`
<3> finally, we declare the system property as a build logic input, used at configuration time and wire it to our task input

Running the task twice now succeeds without reporting any problem and reusing the configuration cache on the second run:

[source,text]
----
❯ gradle --configuration-cache someTask -DsomeMessage=hello
include::{snippetsPath}/configurationCache/problemsFixed/tests/store.out[]
Configuration cache entry stored.
❯ gradle --configuration-cache someTask -DsomeMessage=hello
include::{snippetsPath}/configurationCache/problemsFixed/tests/load.out[]
Configuration cache entry reused.
----

But, what if we change the value of the system property?

[source,text]
----
❯ gradle --configuration-cache someTask -DsomeMessage=bye
include::{snippetsPath}/configurationCache/problemsFixed/tests/store-bye.out[]
Configuration cache entry stored.
----

The previous configuration cache entry could not be reused and the task graph had to be calculated again.
This is because we read the system property at configuration time, hence requiring to run the configuration phase again when the value of that property changes.
Fixing that is as simple as using a `Property<String>` as the task input and wiring the system property directly, without reading it at configuration time.

====
include::sample[dir="snippets/configurationCache/problemsFixedReuse/groovy",files="build.gradle[]"]
include::sample[dir="snippets/configurationCache/problemsFixedReuse/kotlin",files="build.gradle.kts[]"]
====
<1> we turned our task property into a proper `Property<String>`
<2> this allows to wire the declared system property directly, without reading it at configuration time

With those changes in place we can run the task twice, changing the system property value:

[source,text]
----
❯ gradle --configuration-cache someTask -DsomeMessage=hello
include::{snippetsPath}/configurationCache/problemsFixedReuse/tests/store.out[]
Configuration cache entry stored.
❯ gradle --configuration-cache someTask -DsomeMessage=bye
include::{snippetsPath}/configurationCache/problemsFixedReuse/tests/load-bye.out[]
Configuration cache entry reused.
----

We're now done with fixing the problems with this simple task.

Keep reading to learn how to adopt the configuration cache for your build or your plugins.

[[adoption]]
== Adoption steps

An important prerequisite is to keep your Gradle and plugins versions up to date.
The following explores the recommended steps for a successful adoption.
It applies both to builds and plugins.
While going through these steps, keep in mind the HTML report and the solutions explained in the <<configuration_cache#requirements, requirements>> chapter below.

Start with `:help`::
Always start by trying your build or plugin with the simplest task `:help`.
This will exercise the minimal configuration phase of your build or plugin.

Progressively target useful tasks::
Don't go with running `build` right away.
You can also use `--dry-run` to discover more configuration time problems first.
+
When working on a build, progressively target your development feedback loop.
For example, running tests after making some changes to the source code.
+
When working on a plugin, progressively target the contributed or configured tasks.

Explore by turning problems into warnings::
Don't stop at the first build failure and <<configuration_cache#ignore_problems, turn problems into warnings>> to discover how your build or plugin behave.
Use the HTML report to reason about the reported problems, read about them in the <<configuration_cache#requirements, requirements>> and <<configuration_cache#not_yet_implemented, not yet implemented>> sections below.
Continue running more tasks.
+
This will give you a good overview of what problems your build or plugin is facing.
Remember that when turning problems into warnings you might need to <<configuration_cache#invalidating_the_cache, manually invalidating the cache>> in case of troubles.

Step back and fix problems iteratively::
When you feel you know enough about what needs to be fixed, take a step back and start iteratively fixing the most important problems.
Use the HTML report and this documentation to help you in this journey.
+
Start with problems reported when _storing_ the configuration cache.
Once fixed, you can rely on a valid cached configuration phase and move on to fixing problems reported when _loading_ the configuration cache if any.

Test, test, test::
Consider adding tests for your build logic.
See the below section on <<configuration_cache#testkit, testing your build logic>> for the configuration cache.
This will help you while iterating on the required changes and prevent future regressions.

[[testkit]]
== Testing your build logic

The Gradle TestKit (a.k.a. just TestKit) is a library that aids in testing Gradle plugins and build logic generally.
For general guidance on how to use TestKit see the <<test_kit.adoc#test_kit,dedicated chapter>>.

To enable configuration caching in your tests, you can pass the `--configuration-cache` argument to link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html[GradleRunner] or use one of the other methods described in <<configuration_cache.adoc#enable,Enabling the configuration cache>>.

You need to run your tasks twice.
Once to prime the configuration cache.
Once to reuse the configuration cache.

.Testing the configuration cache
====
include::sample[dir="snippets/configurationCache/testKit/groovy",files="src/test/groovy/org/example/BuildLogicFunctionalTest.groovy[tags=functional-test-configuration-cache]"]
include::sample[dir="snippets/configurationCache/testKit/kotlin",files="src/test/kotlin/org/example/BuildLogicFunctionalTest.kt[tags=functional-test-configuration-cache]"]
====
<1> First run primes the configuration cache.
<2> Second run reuses the configuration cache.
<3> Assert that the configuration cache gets reused.

If problems with the configuration cache are found then Gradle will fail the build reporting the problems, and the test will fail.

When gradually improving your plugin or build logic to support the configuration cache it can be useful to temporarily <<configuration_cache.adoc#ignore_problems,ignore problems>> or <<configuration_cache.adoc#max_problems,allow a given number of problems>>.

[[requirements]]
== Requirements

In order to capture the state of the task graph to the configuration cache and reload it again in a later build, Gradle applies certain requirements to tasks and other build logic.
Each of these requirements is treated as a configuration cache "problem" and fail the build if violations are present.

The following sections describe each of the requirements and how to change your build to fix the problems.

[[disallowed_types]]
=== Certain types must not be referenced by tasks

There are a number of types that task instances must not reference from their fields.
Usually these types are used to carry some task input that should be explicitly declared instead.

To fix, you can often replace such a field with a `Property` or `Provider` typed field that exposes the exact information that the task will need at execution time.

// TODO - examples, more details
// - Live JVM state
// - Gradle, Settings, Project -> data
// - SourceSet or SourceSetContainer -> FileCollection(s) for the source directories|files, classpath or outputs
// - Dependency resolution types
//   - explain global rule, results NO, specs YES
//   - Configuration -> FileCollection
//   - Dependencies -> ArtifactCollection


[[use_project_during_execution]]
=== Using the `Project` object

A task must not use any `Project` objects at execution time.
This includes calling `Task.getProject()` while the task is running.

Some cases can be fixed in the same way as the previous requirement.

Often, similar things are available on both `Project` and `Task`.
For example if you need a `Logger` in your task actions you should use `Task.logger` instead of `Project.logger`.

Otherwise, you can use <<custom_gradle_types#service_injection,injected services>> instead of the methods of `Project`.

// TODO - examples
// - with 2 problems
// - p1 is using `project.version`
// - p2 is using `project.exec {}`
// - in task types
// - in tasks declared in scripts
//   https://gradle.slack.com/archives/CH43P3A10/p1591477979141600

[cols="a,a",options="header"]
|===
| Instead of:
| Use:

| `project.rootDir`
| A task field or script variable to capture the root directory.

| `project.projectDir`
| `link:{javadocPath}/org/gradle/api/file/ProjectLayout.html[ProjectLayout].projectDirectory`

| `project.buildDir`
| `link:{javadocPath}/org/gradle/api/file/ProjectLayout.html[ProjectLayout].buildDirectory`

| `project.name`
| A task field or script variable to capture the project name.

| `project.description`
| A task field or script variable to capture the project description.

| `project.group`
| A task field or script variable to capture the project group.

| `project.version`
| A task field or script variable to capture the project version.

| `project.properties`, `project.property(name)`, `project.hasProperty(name)`, `project.getProperty(name)` or `project.findProperty(name)`
| <<configuration_cache#undeclared_gradle_prop_read, Value providers for Gradle properties>>

| `project.provider {}`
| `link:{javadocPath}/org/gradle/api/provider/ProviderFactory.html[ProviderFactory].provider {}`

| `project.file(path)`
| `link:{javadocPath}/org/gradle/api/file/ProjectLayout.html[ProjectLayout].projectDirectory.file(path)` or `link:{javadocPath}/org/gradle/api/file/ProjectLayout.html[ProjectLayout].buildDirectory.file(path)`

| `project.uri(path)`
| [.red]#✖# Unsupported

| `project.relativePath(path)`
| `ProjectLayout.projectDirectory.file(path)`

| `project.files(paths)`
| `link:{javadocPath}/org/gradle/api/model/ObjectFactory.html[ObjectFactory].fileCollection().from(paths)`

| `project.fileTree(paths)`
| `link:{javadocPath}/org/gradle/api/model/ObjectFactory.html[ObjectFactory].fileTree().from(dir)`

| `project.zipTree(path)`
| `link:{javadocPath}/org/gradle/api/file/ArchiveOperations.html[ArchiveOperations].zipTree(path)`

| `project.tarTree(path)`
| `link:{javadocPath}/org/gradle/api/file/ArchiveOperations.html[ArchiveOperations].tarTree(path)`

| `project.resources`
| [.red]#✖# Unsupported

| `project.copySpec {}`
| [.red]#✖# Unsupported

| `project.copy {}`
| `link:{javadocPath}/org/gradle/api/file/FileSystemOperations.html[FileSystemOperations].copy {}`

| `project.sync {}`
| `link:{javadocPath}/org/gradle/api/file/FileSystemOperations.html[FileSystemOperations].sync {}`

| `project.delete {}`
| `link:{javadocPath}/org/gradle/api/file/FileSystemOperations.html[FileSystemOperations].delete {}`

| `project.mkdir(path)`
| The Kotlin, Groovy or Java API available to your build logic.

| `project.exec {}`
| `link:{javadocPath}/org/gradle/process/ExecOperations.html[ExecOperations].exec {}`

| `project.javaexec {}`
| `link:{javadocPath}/org/gradle/process/ExecOperations.html[ExecOperations].javaexec {}`

| `project.ant {}`
| [.red]#✖# Unsupported

| `project.createAntBuilder()`
| [.red]#✖# Unsupported

|===

[[task_access]]
=== Accessing a task instance from another instance

Tasks should not directly access the state of another instance.
Instead, tasks should be connected using inputs and outputs.

To fix, connect tasks using input and output relationships.
`Property` and `Provider` types can be useful for this.

// TODO - examples, more details
// TODO - tasks configuring another tasks are unsupported

[[build_listeners]]
=== Using build listeners

Plugins and build scripts must not register any build listeners.

To fix, use a <<build_services#build_services,build service>>.

// TODO - examples, more details

[[undeclared_gradle_prop_read]]
=== Undeclared reading of Gradle properties

Plugins and build scripts should not read Gradle properties directly at configuration time.
Instead, these Gradle properties must be declared as a potential build input by using the value supplier APIs.

This problem is caused by build logic similar to this:

====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
def enabled = project.getProperty("some-property")
----
=====

[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
val enabled = project.getProperty("some-property")
----
=====
====

To fix this problem, read Gradle properties using link:{javadocPath}/org/gradle/api/provider/ProviderFactory.html#gradleProperty-java.lang.String-[providers.gradleProperty()] instead:

====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
def enabled = providers.gradleProperty("some-property").forUseAtConfigurationTime().present
----
=====

[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
val enabled = providers.gradleProperty("some-property").forUseAtConfigurationTime().isPresent
----
=====
====

In general, you should avoid reading the value of Gradle properties at configuration time, to avoid invalidating configuration cache entries when the Gradle property value changes.
Instead, you can connect the `Provider` returned by link:{javadocPath}/org/gradle/api/provider/ProviderFactory.html#gradleProperty-java.lang.String-[providers.gradleProperty()] to task properties.

[[undeclared_sys_prop_read]]
=== Undeclared reading of system properties

Plugins and build scripts should not read system properties directly using the Java APIs at configuration time.
Instead, these system properties must be declared as a potential build input by using the value supplier APIs.

This problem is caused by build logic similar to this:

====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
def enabled = System.getProperty("some-property")
----
=====

[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
val enabled = System.getProperty("some-property")
----
=====
====

To fix this problem, read system properties using link:{javadocPath}/org/gradle/api/provider/ProviderFactory.html#systemProperty-java.lang.String-[providers.systemProperty()] instead:

====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
def enabled = providers.systemProperty("some-property").forUseAtConfigurationTime().present
----
=====

[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
val enabled = providers.systemProperty("some-property").forUseAtConfigurationTime().isPresent
----
=====
====

In general, you should avoid reading the value of system properties at configuration time, to avoid invalidating configuration cache entries when the system property value changes.
Instead, you can connect the `Provider` returned by link:{javadocPath}/org/gradle/api/provider/ProviderFactory.html#systemProperty-java.lang.String-[providers.systemProperty()] to task properties.

[[undeclared_env_var_read]]
=== Undeclared reading of environment variables

Plugins and build scripts should not read environment variables directly using the Java APIs at configuration time.
Instead, declare environment variables as potential build inputs using the value supplier APIs.

This problem is caused by build logic similar to this:

====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
def enabled = System.getenv("SOME_ENV_VAR")
----
=====

[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
val enabled = System.getenv("SOME_ENV_VAR")
----
=====
====

To fix this problem, read environment variables using link:{javadocPath}/org/gradle/api/provider/ProviderFactory.html#environmentVariable-java.lang.String-[providers.environmentVariable()] instead:

====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
def enabled = providers.environmentVariable("SOME_ENV_VAR").forUseAtConfigurationTime().present
----
=====

[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
val enabled = providers.environmentVariable("SOME_ENV_VAR").forUseAtConfigurationTime().isPresent
----
=====
====

In general, you should avoid reading the value of environment variables at configuration time, to avoid invalidating configuration cache entries when the environment variable value changes.
Instead, you can connect the `Provider` returned by link:{javadocPath}/org/gradle/api/provider/ProviderFactory.html#environmentVariable-java.lang.String-[providers.environmentVariable()] to task properties.

[[undeclared_file_read]]
=== Undeclared reading of files

Plugins and build scripts should not read files directly using the Java, Groovy or Kotlin APIs at configuration time.
Instead, declare files as potential build inputs using the value supplier APIs.

This problem is caused by build logic similar to this:

====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
def config = file("some.conf").text
----
=====

[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
val config = file("some.conf").readText()
----
=====
====

To fix this problem, read files using link:{javadocPath}/org/gradle/api/provider/ProviderFactory.html#fileContents-org.gradle.api.file.RegularFile-[providers.fileContents()] instead:

====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
def config = providers.fileContents(layout.projectDirectory.file('some.conf'))
    .asText.forUseAtConfigurationTime()
----
=====

[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
val config = providers.fileContents(layout.projectDirectory.file("some.conf"))
    .asText.forUseAtConfigurationTime()
----
=====
====

In general, you should avoid reading files at configuration time, to avoid invalidating configuration cache entries when the file content changes.
Instead, you can connect the `Provider` returned by link:{javadocPath}/org/gradle/api/provider/ProviderFactory.html#fileContents-org.gradle.api.file.RegularFile-[providers.fileContents()] to task properties.

[[not_yet_implemented]]
== Not yet implemented

Support for using configuration caching with certain Gradle features is not yet implemented.
Support for these features will be added in later Gradle releases.

=== Build scan support

When it comes to link:https://gradle.com/build-scans/[build scans], only the `--scan` command line option is supported for now.

The build scan plugin is currently ignored when applied via an init script or build script, as is any configuration done via the build scan extension (server location, accept license, tags, etc).
This means that scans will be published to the public `scans.gradle.com` instance by default.

=== Sharing the configuration cache

The configuration cache is currently stored locally only.
It can be reused by hot or cold local Gradle daemons.
But it can't be shared between developers or CI machines.

[[composite_builds]]
=== Composite builds

When using the configuration cache on a <<composite_builds#composite_builds,composite build>> a problem will be reported.
If you <<configuration_cache#ignore_problems,ignore problems>> then the included builds will be skipped when reusing the configuration cache.

=== Source dependencies

Support for link:https://blog.gradle.org/introducing-source-dependencies[source dependencies] is not yet implemented.
With the configuration cache enabled, no problem will be reported and the build will fail.

=== Dependency locking

<<dependency_locking#dependency-locking, Locking dependency versions>> isn't supported yet.
With the configuration cache enabled, no problem will be reported and dependency locks will be ignored.

=== Dynamic or changing dependencies

<<dynamic_versions#sec:dynamic_versions_and_changing_modules,Dependencies with versions which change over time>> aren't supported yet.
With the configuration cache enabled, no problem will be reported and changes to dependencies won't be detected.

You can force refresh dynamic dependencies using `--refresh-dependencies`.

=== Filesystem repositories

Repositories on local file systems are not supported yet.
With the configuration cache enabled, no problem will be reported and changes to the filesystem in the repositories won't be detected.

This includes:

* <<declaring_repositories#sec:declaring_custom_repository,Maven or Ivy repositories>> with `file://` URLs,
* <<declaring_repositories#sub:maven_local,`mavenLocal()`>>,
* and <<declaring_repositories#sub:flat_dir_resolver,flat directory repositories>>.
