[[config_cache]]
= Configuration cache

- What is it?
- How to enable it?
- How does it work?
- Limitations?
- Diagnosing problems?


== Usage

[[enable]]
=== Enabling the configuration cache

The configuration cache can be enabled from the command line:

[source,bash]
----
gradle --configuration-cache=on
----

It can also be enabled persistently in a `gradle.properties` file:

[source,properties]
----
org.gradle.unsafe.configuration-cache=on
----

If it is enabled in a `gradle.properties` file, it can be disabled on the command line for one build invocation:

[source,bash]
----
gradle --configuration-cache=off
----

[[ignore_problems]]
=== Ignoring problems

Configuration cache problems can be turned into warnings on the command line:

[source,bash]
----
gradle --configuration-cache=warn
----

or in a `gradle.properties` file:

[source,properties]
----
org.gradle.unsafe.configuration-cache=warn
----

[[max_problems]]
=== Allowing a maximum number of problems

When configuration cache problems are turned into warnings, Gradle will fail the build if `512` problems are found by default.

This can be adjusted by specifying an allowed maximum number of problems on the command line:

[source,bash]
----
gradle -Dorg.gradle.unsafe.configuration-cache.max-problems=1024
----

or in a `gradle.properties` file:

[source,properties]
----
org.gradle.unsafe.configuration-cache.max-problems=1024
----


== Constraints

Constraints and how to change your build

[[disallowed_types]]
== Types that must not be referenced by tasks

There are a number of types that task instances must not reference from their fields. Usually these types are used to carry some task input that should be explicitly
declared instead.

[[use_project_during_execution]]
== Using the Project object

A task must not use any `Project` objects at execution time. This includes calling `Task.getProject()` while the task is running.

[[build_listeners]]
== Using build listeners

Plugins and build scripts must not register any build listeners.

[[undeclared_sys_prop_reads]]
=== Reading system properties

Plugins and build scripts should not read system properties directly using the Java APIs. Instead, these system properties must be declared as a potential build input by
using the value supplier APIs.

Before:

```
def enabled = System.getProperty("some-property")
```

After:

```
def enabled = providers.systemProperty("some-property").forUseAtConfigurationTime().present
```

[[not_yet_implemented]]
== Not yet implemented

Support for using configuration caching with certain Gradle features is not yet implemented.

- Composite builds
