[[config_cache]]
= Configuration cache

[NOTE]
====
The configuration cache is an <<feature_lifecycle.adoc#feature_lifecycle,incubating>> feature, and the details described here may change.
====

== Introduction

The configuration cache is a feature that significantly improves build performance by caching the result of the configuration phase and reusing this for subsequent builds.
This allows Gradle to skip the configuration phase entirely when nothing has changed to affect the build configuration, and in addition allows Gradle to apply some
performance improvements to task execution as well. (TODO - link to build lifecycle reference)

The configuration cache is similar to the build cache, but caches different information. The build cache takes care of caching the outputs and intermediate files of the build,
such as task outputs or artifact transform outputs. The configuration cache takes care of caching the build configuration for a particular set of tasks. You can think of this
as caching the output of the configuration phase, which is an input to the execution phase.

This feature is currently experimental and not enabled by default.

=== How does it work?

When the configuration cache is enabled and you run Gradle for a particular set of tasks, for example by running `gradlew check`, Gradle checks whether a configuration cache entry is available for
the requested set of tasks and if available will use this instead of running the configuration phase.

The first time you run a set of tasks, there will be no entry in the configuration cache for these tasks and so Gradle will run the configuration phase as normal. Gradle will:

1. Run any init scripts.
2. Run the settings script for the build, applying any requested settings plugins.
3. Run the builds scripts for the build, applying any requested project plugins.
4. Calculate the task graph for the requested tasks, running any deferred configuration actions.

Following the configuration phase, Gradle writes the state of the task graph to the configuration cache, taking a snapshot for later Gradle invocations. The execution phase then runs as normal.
This means you will not see any build performance improvement the first time you run a particular set of tasks.

When you subsequently run Gradle with this set of tasks, for example by running `gradlew check` again, Gradle will load the tasks and their configuration directly from the configuration cache
and skip the configuration phase entirely.
Before using a configuration cache entry, Gradle checks that none of the "build inputs" for the entry have changed. If a build input has changed, Gradle will not use the entry and will
run the configuration phase again as above, saving the result for later reuse.

Build inputs include:

- Init scripts, settings scripts, build scripts.
- System properties, Gradle properties and configuration files used during the configuration phase, accessed using value suppliers (TODO - add docs for this).
- build inputs and source files for `buildSrc` projects.

=== Performance improvements

Apart from the clear advantage of skipping the configuration phase, the configuration cache provides some additional performance improvements:

- All tasks run in parallel by default.
- Dependency resolution is cached as well.

== Using the configuration cache

[[enable]]
=== Enabling the configuration cache

The configuration cache can be enabled from the command line:

[source,bash]
----
gradle --configuration-cache=on
----

It can also be enabled persistently in a `gradle.properties` file:

[source,properties]
----
org.gradle.unsafe.configuration-cache=on
----

If it is enabled in a `gradle.properties` file, it can be disabled on the command line for one build invocation:

[source,bash]
----
gradle --configuration-cache=off
----

[[ignore_problems]]
=== Ignoring problems

Configuration cache problems can be turned into warnings on the command line:

[source,bash]
----
gradle --configuration-cache=warn
----

or in a `gradle.properties` file:

[source,properties]
----
org.gradle.unsafe.configuration-cache=warn
----

[[max_problems]]
=== Allowing a maximum number of problems

When configuration cache problems are turned into warnings, Gradle will fail the build if `512` problems are found by default.

This can be adjusted by specifying an allowed maximum number of problems on the command line:

[source,bash]
----
gradle -Dorg.gradle.unsafe.configuration-cache.max-problems=1024
----

or in a `gradle.properties` file:

[source,properties]
----
org.gradle.unsafe.configuration-cache.max-problems=1024
----


== Constraints

Constraints and how to change your build

[[disallowed_types]]
== Types that must not be referenced by tasks

There are a number of types that task instances must not reference from their fields. Usually these types are used to carry some task input that should be explicitly
declared instead.

[[use_project_during_execution]]
== Using the Project object

A task must not use any `Project` objects at execution time. This includes calling `Task.getProject()` while the task is running.

[[build_listeners]]
== Using build listeners

Plugins and build scripts must not register any build listeners.

[[undeclared_sys_prop_reads]]
=== Reading system properties

Plugins and build scripts should not read system properties directly using the Java APIs. Instead, these system properties must be declared as a potential build input by
using the value supplier APIs.

Before:

```
def enabled = System.getProperty("some-property")
```

After:

```
def enabled = providers.systemProperty("some-property").forUseAtConfigurationTime().present
```

[[not_yet_implemented]]
== Not yet implemented

Support for using configuration caching with certain Gradle features is not yet implemented.

- Composite builds

[[testkit]]
== Testing Build Logic with TestKit

The Gradle TestKit (a.k.a. just TestKit) is a library that aids in testing Gradle plugins and build logic generally.
For general guidance on how to use TestKit see the <<test_kit.adoc#test_kit,dedicated chapter>>.

To enable configuration caching in your tests, you can pass the `--configuration-cache=on` argument to link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html[GradleRunner] or use one of the other methods described in <<configuration_cache.adoc#enable,Enabling the configuration cache>>.

You need to run your tasks twice.
Once to prime the configuration cache.
Once to reuse the configuration cache.

.Testing the configuration cache
====
include::sample[dir="snippets/configurationCache/testKit/groovy",files="src/test/groovy/org/example/BuildLogicFunctionalTest.groovy[tags=functional-test-configuration-cache]"]
include::sample[dir="snippets/configurationCache/testKit/kotlin",files="src/test/kotlin/org/example/BuildLogicFunctionalTest.kt[tags=functional-test-configuration-cache]"]
====
<1> First run primes the configuration cache.
<2> Second run reuses the configuration cache.
<3> Assert that the configuration cache gets reused.

If problems with the configuration cache are found then Gradle will fail the build reporting the problems, and the test will fail.

When gradually improving your plugin or build logic to support the configuration cache it can be useful to temporarily <<configuration_cache.adoc#ignore_problems,ignore problems>> or <<configuration_cache.adoc#max_problems,allow a given number of problems>>.

== Troubleshooting

TODO
