// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[intro_multi_project_builds]]
= Executing Multi-Project Builds

TIP: The Gradle Build Cache can help reduce build time of multi project builds by up to 90%. https://gradle.com/training/build-cache-deep-dive/?bid=docs-multi-project-builds[Register here] for our live Build Cache training session to learn how.

Only the smallest of projects has a single build file and source tree, unless it happens to be a massive, monolithic application. It’s often much easier to digest and understand a project that has been split into smaller, inter-dependent modules. The word “inter-dependent” is important, though, and is why you typically want to link the modules together through a single build.

Gradle supports this scenario through _multi-project_ builds.

For details about authoring _multi-project_ builds, consult the <<multi_project_builds#,Authoring Multi-Project Builds section of the user manual>>.


[[sec:executing_a_multiproject_build]]
== Executing a multi-project build

To identify the project structure, you can use `gradle projects` command.
As an example, let's use a multi-project build with the following structure:
----
> gradle -q projects
include::{snippetsPath}/java/multiproject/tests/listProjects.out[]
----

From a user's perspective, multi-project builds are still collections of tasks you can run.
The difference is that you may want to control _which_ project's tasks get executed. You have two options here:

* Change to the directory corresponding to the subproject you’re interested in and just execute `gradle &lt;task&gt;` as normal.
* Use a qualified task name from any directory, although this is usually done from the root.
For example: `gradle :services:webservice:build` will build the _webservice_ subproject and any subprojects it depends on.

The first approach is similar to the single-project use case, but Gradle works slightly differently in the case of a multi-project build.
The command `gradle test` will execute the `test` task in any subprojects, relative to the current working directory, that have that task.
So if you run the command from the root project directory, you’ll run `test` in _api_, _shared_, _services:shared_ and _services:webservice_.
If you run the command from the services project directory, you’ll only execute the task in _services:shared_ and _services:webservice_.

For more control over what gets executed, use qualified project names (the second approach mentioned).
These are paths just like directory paths, but use ‘:’ instead of ‘/’ or ‘\’.
If the path begins with a ‘:’, then the path is resolved relative to the root project.
In other words, the leading ‘:’ represents the root project itself.
All other colons are path separators.

This approach works for any task, so if you want to know what tasks are in a particular subproject, just use the `tasks` task, e.g. `gradle :services:webservice:tasks` .

Regardless of which technique you use to execute tasks, Gradle will take care of building any subprojects that the target depends on.
You don’t have to worry about the inter-project dependencies yourself.
If you’re interested in how this is configured, you can read about writing multi-project builds <<multi_project_builds.adoc#multi_project_builds,later in the user manual>>.

There’s one last thing to note.
When you’re using the Gradle wrapper, the first approach doesn’t work well because you have to specify the path to the wrapper script if you’re not in the project root.
For example, if you’re in the _webservice_ subproject directory, you would have to run `../../gradlew build`.

That’s all you really need to know about multi-project builds as a build user.
You can now identify whether a build is a multi-project one and you can discover its structure.
And finally, you can execute tasks within specific subprojects.
