// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[part6_gradle_caching]]
= Part 6: Enable the Gradle Cache

Learn the basics of Gradle's caching system.

****
**In this section you will:**

- Update Gradle Properties
- Turn on Local cache
- Understand caching
- Explore remote caching
****

[[part6_begin]]
== Step 0. Before you Begin

1. Complete <<part5_gradle_inc_builds#part5_begin,part 5>>.

== Step 1. Understanding Caching
Another optimization is called caching. Let's turn on caching for your app.

== Step 2. Enabling the Local Cache
Run the clean task and then the build task using the `./gradlew :app:clean :app:build` command:
[source]
----
$ ./gradlew :app:clean :app:build
> Task :app:clean
> Task :app:compileJava
> Task :app:processResources NO-SOURCE
> Task :app:classes
> Task :app:jar
> Task :app:startScripts
> Task :app:distTar
> Task :app:distZip
> Task :app:assemble
> Task :app:compileTestJava
> Task :app:processTestResources NO-SOURCE
> Task :app:testClasses
> Task :app:test
> Task :app:check
> Task :app:build

BUILD SUCCESSFUL in 1s
8 actionable tasks: 8 executed
----

Add `org.gradle.caching=true` to the `gradle.properties` file:
[source]
----
org.gradle.console=verbose
org.gradle.caching=true
----

== Step 3. Using the Local Cache
Run the build task to populate the local cache:
[source]
----
$ ./gradlew :app:build

> Task :app:compileJava UP-TO-DATE
> Task :app:processResources NO-SOURCE
> Task :app:classes UP-TO-DATE
> Task :app:jar UP-TO-DATE
> Task :app:startScripts UP-TO-DATE
> Task :app:distTar UP-TO-DATE
> Task :app:distZip UP-TO-DATE
> Task :app:assemble UP-TO-DATE
> Task :app:compileTestJava UP-TO-DATE
> Task :app:processTestResources NO-SOURCE
> Task :app:testClasses UP-TO-DATE
> Task :app:test UP-TO-DATE
> Task :app:check UP-TO-DATE
> Task :app:build UP-TO-DATE

BUILD SUCCESSFUL in 409ms
7 actionable tasks: 7 up-to-date
----

No surprise here, thanks to incremental builds, Gradle noticed nothing changed. However, in the background, the local cache has been populated.

Let's run the clean and build again:
[source]
----
$ ./gradlew :app:clean :app:build

> Task :app:clean
> Task :app:compileJava FROM-CACHE
> Task :app:processResources NO-SOURCE
> Task :app:classes UP-TO-DATE
> Task :app:jar
> Task :app:startScripts
> Task :app:distTar
> Task :app:distZip
> Task :app:assemble
> Task :app:compileTestJava FROM-CACHE
> Task :app:processTestResources NO-SOURCE
> Task :app:testClasses UP-TO-DATE
> Task :app:test FROM-CACHE
> Task :app:check UP-TO-DATE
> Task :app:build

BUILD SUCCESSFUL in 525ms
8 actionable tasks: 5 executed, 3 from cache
----

Gradle is efficient, especially with the local cache turn on.
Gradle will look at the cache directory on your machine to check for output files that may already exist. If they do, instead of running that task, it will copy its (output) results into your project `build` directory.

The _outcome label_ `FROM-CACHE` lets the user know that Gradle has fetched the task results from the local cache.

The Gradle cache is located at:

- **On Windows**: %USERPROFILE%\.gradle\caches
- **On OS X / UNIX**: ~/.gradle/caches/

Gradle will periodically clean-up the local cache directory by removing entries that have not been used recently to conserve disk space.

== Step 5. Understanding Remote Caching
The remote cache (called a Build Cache Node) is a shared build cache available via HTTP.

The idea of a remote cache is to share commonly built task outputs across remote builds to improve build times.

When both remote and local caches are enabled, then the build output is first checked in the local cache.
If the output isn't present in the local cache, it'll be downloaded from the remote cache and also stored in the local cache.

A remote build cache is available for free from Gradle. Individuals and organizations can also deploy their own cache node which is distributed as a Docker image and an executable JAR.

[.text-right]
**Next Step:** <<part7_gradle_refs.adoc#part7_begin,Using Reference Materials>> >>
