// Copyright 2023 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


[[writing_build_scripts]]
= Build Scripts Basics

In the Gradle Build lifecycle, the initialization phase finds the root project and subprojects included in your <<directory_layout#dir:project_root,project root directory>> using the settings file.

Then, for each project included in the settings file, Gradle creates a `Project()` instance.
Gradle then looks for a corresponding build script file which is used in the configuration phase.

[[tutorial_using_tasks]]
== Build scripts

Every Gradle build is made up of one or more _projects_; a root project and subprojects.

A project typically corresponds to a software component that needs to be built, like a library or an application.
It might represent a library JAR, a web application, or a distribution ZIP assembled from the JARs produced by other projects.
A project does not always represent something to be built.
It might represent a thing to be done, such as deploying your application to staging or production environments.

Gradle scripts are written in either Groovy DSL or Kotlin DSL (domain-specific language).

The build script is either a `\*.gradle` file for Groovy or a `*.gradle.kts` file for Kotlin.

A build script configures a _project_ and is associated with an object of type link:{javadocPath}org/gradle/api/Project.html[`Project`].

As the build script executes, it configures this `Project`.

[IMPORTANT]
====
_Build scripts_ define `Project` objects.
====

== Project object

The `Project` object is part of the link:{javadocPath}org/gradle/api/Project.html[Gradle API].

- In Groovy, the `Project` reference in the DSL is available: link:{groovyDslPath}/org.gradle.api.Project.html[here].
- In Kotlin, the `Project` reference in the DSL is available: link:{kotlinDslPath}/org.gradle.api.initialization/-settings/index.html[here].

Many top-level properties and blocks in a build script are part of the link:{javadocPath}org/gradle/api/Project.html[`Project`] API.

The following build script uses the link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:name[Project.name] property to print the name of the project:

====
include::sample[dir="snippets/tutorial/projectApi/kotlin",files="build.gradle.kts[tags=project-name]"]
include::sample[dir="snippets/tutorial/projectApi/groovy",files="build.gradle[tags=project-name]"]
----
$ gradle -q check
include::{snippetsPath}/tutorial/projectApi/tests/projectApi.out[]
----
====

Both `println` statements print out the same property.

The first uses the top-level reference to the `name` property of the `Project` object.
The second statement uses the `project` property available to any build script, which returns the associated `Project` object.

[[sec:standard_project_properties]]
=== Standard project properties

The `Project` object exposes a standard set of properties in your build script.

The following table lists a few commonly used properties:

[%header%autowidth,compact]
|===
| Name | Type | Default Value

| `allprojects`
| `[Project]`
| The set containing all projects - the root project and its subprojects.

| `project`
| link:{groovyDslPath}/org.gradle.api.Project.html[Project]
| The `Project` instance.

| `name`
| `String`
| The name of the project directory.

| `path`
| `String`
| The absolute path of the project.

| `description`
| `String`
| A description for the project.

| `dependencies`
| `DependencyHandler`
| Returns the dependency handler of the project.

| `repositories`
| `RepositoryHandler`
| Returns the repository handler of the project.

| `layout`
| `ProjectLayout`
| Provides access to several important locations for a project.

| `projectDir`
| `File`
| The directory containing the build script.

| `group`
| `Object`
| `unspecified`

| `version`
| `Object`
| `unspecified`
|===

[[sec:the_script_api]]
== The Script API

When Gradle executes a Groovy build script (`.gradle`), it compiles the script into a class that
implements link:{groovyDslPath}/org.gradle.api.Script.html[Script].

As a result, builds scripts have access to all properties and methods declared by the `Script` interface.

When Gradle executes a Kotlin build script (`.gradle.kts`), it compiles the script into a subclass of link:{kotlinDslPath}/gradle/org.gradle.kotlin.dsl/-kotlin-project-script-template/index.html[KotlinProjectScriptTemplate].

As a result, builds scripts have access to all visible properties and functions declared by the `KotlinProjectScriptTemplate` type.

== Build script structure

A build script is made up of zero or more statements and script blocks.

----
println(project.layout.projectDirectory);
----

Statements can include method calls, property assignments, and local variable definitions.

----
version = '1.0.0.GA'
----

A script block is a method call which takes a closure as a parameter.

----
configurations {
}
----

The closure is treated as a configuration closure which configures some delegate object as it executes.

----
allprojects {
    repositories {
        mavenLocal()
    }
}
----

Let's take a look at an example and break it down:

The top level script blocks included in the example:

[%header%autowidth,compact]
|===
| Block | Description

| `allprojects { }`
| Configures this project and each of its subprojects.

| `repositories { }`
| Configures the repositories for this project.
|===

A build script is also a Groovy or a Kotlin script, and so can contain those elements allowed in a Groovy or Kotlin script, such as method definitions and class definitions.
