// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[partr5_build_scripts]]
= Part 5: Writing a Build Script

Learn the basics of authoring Gradle by developing the Build Script.

****
**In this section you will:**

- Understand the Project object
- Update the Build script
- How to use Build scripts
****

[[part5_begin]]
== Step 0. Before you Begin

1. You initialized your Java app in <<partr1_gradle_init.adoc#part1_begin,part 1>>.
2. You understand the Gradle Build Lifecycle from <<partr2_build_lifecycle.adoc#part2_begin,part 2>>.
3. You added a subproject and a separate Build in <<partr3_multi_project_builds#part3_begin, part3>>.
4. You authored a Settings file in <<partr4_settings_file.adoc#part4_begin,part 4>>.

== Step 1. The `Project` object

Build scripts invoke Gradle APIs to configure the build.

During the configuration phase, Gradle finds the build script(s) in the root and subproject directories.

When a build script, `build.gradle(.kts)`, is found, Gradle configures a link:{javadocPath}org/gradle/api/Project.html[Project] object.

The purpose of the link:{javadocPath}org/gradle/api/Project.html[Project] object is to create a collection of link:{javadocPath}/org/gradle/api/Task.html[Task] objects, apply plugins, and retrieve dependencies.

You can use any of the methods and properties on the link:{javadocPath}org/gradle/api/Project.html[Project] interface directly in your script.

For example:

[source]
----
 defaultTasks('some-task')      // Delegates to Project.defaultTasks()
 reportsDir = file('reports')   // Delegates to Project.file() and the Java Plugin
----

== Step 2. Update the Build script

.license-plugin/build.gradle.kts
[source]
----
gradlePlugin {
    // Define the plugin
    val license by plugins.creating {
        id = "com.gradle.license"
        implementationClass = "com.gradle.LicensePlugin"
    }
}
----

.app/build.gradle.kts
[source]
----
plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.gradle.license")
}
----

[.text-right]
**Next Step:** <<partr6_writing_tasks#partr6_writing_tasks,Writing Tasks>> >>
