// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[partr3_settings_file]]
= Part 3: Writing the Settings File

Learn the basics of authoring Gradle by developing the Settings File.

****
**In this section you will:**

- Initialize a Java project
- Run a Java application
- Produce a Build Scan
- Bundle the application in an archive
- Review the directory layout
****

[[part1_begin]]
== Step 0. Before you Begin

1. You understand the Gradle Build Lifecycle from <<partr2_gradle_init.adoc#part1_begin,part 2>>.

== Step 1.

[source,settings.gradle.kts]
----
pluginManagement {                                          // <1>
    repositories {
        gradlePluginPortal()
        google()
    }
    includeBuild("../build-logic")
}

plugins {                                                   // <2>
    id("org.gradle.toolchains.fake") version "0.6.0"
}

rootProject.name = "root-project"                           // <3>

dependencyResolutionManagement {                            // <4>
    repositories {
        mavenCentral()
    }
    includeBuild("../other-project")
}

include("sub-project-a")                                    // <5>
include("sub-project-b")
include("sub-project-c")
----

[.text-right]
**Next Step:** <<partr4_build_script#partr4_build_script,Writing a Build Script>> >>
