// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[partr4_settings_file]]
= Part 4: Writing the Settings File

Learn the basics of authoring Gradle by developing the Settings File.

****
**In this section you will:**

- Understand the Settings object
- Understand the Settings file
- Run tasks in subprojects
****

[[part4_begin]]
== Step 0. Before you Begin

1. You initialized your Java app in <<partr1_gradle_init.adoc#part1_begin,part 1>>.
2. You understand the Gradle Build Lifecycle from <<partr2_build_lifecycle.adoc#part2_begin,part 2>>.
3. You added a subproject and a separate Build in <<partr3_multi_project_builds#part3_begin, part3>>.

== Step 1. The `Settings` object

The settings file is the entry point of every Gradle project.

During the initialization phase, Gradle finds the settings file in your project root directory.

When the settings file, `settings.gradle(.kts)`, is found, Gradle instantiates a link:{groovyDslPath}/org.gradle.api.initialization.Settings.html[Settings] object.

One of the purposes of the link:{groovyDslPath}/org.gradle.api.initialization.Settings.html[Settings] object is to allow you to declare all the projects to be included in the build.

You can use any of the methods and properties on the link:{groovyDslPath}/org.gradle.api.initialization.Settings.html[Settings] interface directly in your settings file.

For example:

[source]
----
 includeBuild('some-build')                         // Delegates to Settings.includeBuild()
 reportsDir = findProject("/myInternalProject")     // Delegates to Settings.findProject()
----

== Step 2. The Settings file

.settings.gradle.kts
[source,kotlin]
----
println("SETTINGS FILE: This is executed during the initialization phase")

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"  // <1>
}

rootProject.name = "authoring-tutorial"                                     // <2>

include("app")                                                              // <3>
include("subproject")

includeBuild("license-plugin")                                              // <4>
----
<1> PluginDependenciesSpec

public open fun getRootProject(): ProjectDescriptor
From interface:
org.gradle.api.initialization.Settings
Returns the root project of the build.
Specified by:
getRootProject in interface Settings

 org.gradle.api.initialization.Settings
public void include(     String... projectPaths )

public open fun includeBuild(
rootProject: Any
): Unit
From interface:
org.gradle.api.initialization.Settings Includes a build at the specified path to the composite build.
Specified by:
includeBuild in interface Settings

== Step 3. Build structure and Tasks

[source]
----
$ ./gradlew tasks --all

------------------------------------------------------------
Tasks runnable from root project 'authoring-tutorial'
------------------------------------------------------------

Other tasks
-----------
app:lifecycle
subproject:sublifecycle

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----

[source]
----
$ ./gradlew app:lifecycle

SETTINGS FILE: This is executed during the initialization phase

> Configure project :app
BUILD SCRIPT: This is executed during the configuration phase
REGISTER TASK: This is executed during the configuration phase
NAMED TASK: This is executed during the configuration phase

> Task :app:lifecycle
NAMED TASK - doFirst: This is executed during the execution phase
NAMED TASK - doLast: This is executed during the execution phase

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----

[source]
----
$ ./gradlew subproject:sublifecycle

SETTINGS FILE: This is executed during the initialization phase

> Configure project :app
BUILD SCRIPT: This is executed during the configuration phase
REGISTER TASK IN SUB: This is executed during the configuration phase
NAMED TASK IN SUB: This is executed during the configuration phase

> Task :subproject:sublifecycle
NAMED TASK IN SUB - doFirst: This is executed during the execution phase
NAMED TASK IN SUB - doLast: This is executed during the execution phase

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----

[.text-right]
**Next Step:** <<partr5_build_scripts#partr5_build_scripts,Writing a Build Script>> >>
