// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[partr3_multi_project_builds]]
= Part 3: Multi-Project Builds

Learn the basics of structuring large Gradle projects using subprojects and composite builds.

****
**In this section you will:**

- Understand Multi-Project builds
- Understand Composite Builds
- Add a subproject to your Build
- Add a build to your Build
****

[[part3_begin]]
== Step 0. Before you Begin

1. You initialized your Java app in <<partr1_gradle_init.adoc#part1_begin,part 1>>.
2. You understand the Gradle Build Lifecycle from <<partr2_build_lifecycle.adoc#part2_begin,part 2>>.

== Step 1. About Multi-Project Builds
A multi-project build consists of:

- `settings.gradle(.kts)` file representing your Gradle build including required subprojects e.g. include("app", "model", "service")
- `build.gradle(.kts)` and source code for each subproject in corresponding subdirectories

----
.
├── app
│   ...
│   └── build.gradle.kts
└── settings.gradle.kts
----

== Step 2. Add a Subproject to the Build
// FIX me - how do you want to organize a growing / more complex project
// CHeck the calc old example
[source]
----
mkdir lib
----

[source]
----
cd lib
----

Create a file called `build.gradle.kts` and add the following lines to it:

.subproject/build.gradle.kts
[source,kotlin]
----
tasks.register("sublifecycle"){
    println("REGISTER TASK IN SUB: This is executed during the configuration phase")
}

tasks.named("sublifecycle"){
    println("NAMED TASK IN SUB: This is executed during the configuration phase")
    doFirst {
        println("NAMED TASK IN SUB - doFirst: This is executed during the execution phase")
    }
    doLast {
        println("NAMED TASK IN SUB - doLast: This is executed during the execution phase")
    }
}
----

Your project should look like this:

----
.
├── app
│   ...
│   └── build.gradle.kts
├── lib
│   └── build.gradle.kts
└── settings.gradle.kts
----

The subproject will not belong to the build, and you won't be able to the `sublifecycle` task until it is added to the `settings.gradle.kts` file.

To add `lib` to the build, update the `settings.gradle.kts` file accordingly:

.settings.gradle.kts
[source,kotlin]
----
println("SETTINGS FILE: This is executed during the initialization phase")

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
}

rootProject.name = "authoring-tutorial"

include("app")

include("lib") // Add new subproject to the root project // FIX ME!!!
----

== Step 3. Understand Composite Builds
A composite build is simply a build that includes other builds.

Composite builds allow you to:

– Combine builds that are usually developed independently (such as a plugin and an application)
– Decompose a large build into smaller, more isolated chunks

== Step 4. Add build to the Build

[source]
----
mkdir license-plugin
----

[source]
----
cd license-plugin
----

[source]
----
$ gradle init

SETTINGS FILE: This is executed during the initialization phase
> Task :wrapper

Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4] 4

Select implementation language:
  1: Groovy
  2: Java
  3: Kotlin
Enter selection (default: Java) [1..3] 3

Select build script DSL:
  1: Kotlin
  2: Groovy
Enter selection (default: Kotlin) [1..2] 1

Project name (default: license-plugin): license
Source package (default: license): com.gradle
Generate build using new APIs and behavior (some features may change in the next minor release)? (default: no) [yes, no]

> Task :init
For more information, please refer to https://docs.gradle.org/8.3/userguide/custom_plugins.html in the Gradle documentation.

BUILD SUCCESSFUL in 20s
2 actionable tasks: 2 executed
----

Your project should look like this:

----
.
├── app
│   ...
│   └── build.gradle.kts
├── subproject
│   └── build.gradle.kts
├── gradle/license-plugin // FIX ME!!!
│    ├── build.gradle.kts
│    └── src
│        ├── main
│        │   └── kotlin
│        │       └── com.gradle
│        │           └── LicensePlugin.kt
│        └── test
│            └── kotlin
│                └── com.gradle
│                    └── LicencePluginTest.kt
└── settings.gradle.kts
----

To add our `license-plugin` project to the build, update the `settings.gradle.kts` file accordingly:

.settings.gradle.kts
[source,kotlin]
----
println("SETTINGS FILE: This is executed during the initialization phase")

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
}

rootProject.name = "authoring-tutorial"

include("app")
include("subproject")

includeBuild("license-plugin") // Add the new build
----

[source]
----
$ ./gradlew projects

------------------------------------------------------------
Root project 'authoring-tutorial'
------------------------------------------------------------

Root project 'authoring-tutorial'
+--- Project ':app'
\--- Project ':subproject'

Included builds
\--- Included build ':license-plugin'

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----

[.text-right]
**Next Step:** <<partr4_settings_file#partr4_settings_file,Settings File>> >>
