// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[partr6_writing_tasks]]
= Part 6: Writing Tasks

Learn the basics of authoring Gradle tasks by creating a simple one in your Build script.

****
**In this section you will:**

- Understand Tasks
- Update the Plugin with a new task
- Analyze Task code
- Run new Plugin task
****

[[part6_begin]]
== Step 0. Before you Begin

1. You initialized your Java app in <<partr1_gradle_init.adoc#part1_begin,part 1>>.
2. You understand the Gradle Build Lifecycle from <<partr2_build_lifecycle.adoc#part2_begin,part 2>>.
3. You added a subproject and a separate Build in <<partr3_multi_project_builds#part3_begin, part3>>.
4. You viewed a Settings file in <<partr4_settings_file.adoc#part4_begin,part 4>>.
5. You authored a Build script in <<partr5_build_scripts.adoc#part5_begin,part 5>>.

== Step 1. Understand Tasks
A Task is an executable piece of code that contains sequences of actions.

Actions are added to a Task via the `doFirst{}` and `doLast{}` closures.

A Task can depend on other tasks.

== Step 2. Register a Task

Early on in the tutorial we registed and configured `task1` in the `app` build script:

.app/build.gradle.kts
[source,kotlin]
----
tasks.register("task1"){
    println("REGISTER TASK1: This is executed during the configuration phase")
}

tasks.named("task1"){
    println("NAMED TASK1: This is executed during the configuration phase")
    doFirst {
        println("NAMED TASK1 - doFirst: This is executed during the execution phase")
    }
    doLast {
        println("NAMED TASK1 - doLast: This is executed during the execution phase")
    }
}
----

== Step 3. Create a Task


== Step 4. Update the Plugin

When you ran `gradle init` and added the `license-plugin` build to the project, Gradle added a "hello-world" example:

.license-plugin/plugin/src/main/kotlin/com/gradle/LicensePlugin.kt
[source,kotlin]
----
class OtherPluginPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            task.description = "greeting" // Add description
            task.group = "from my plugin" // Add group
            task.doLast {
                println("Hello from plugin 'com.gradle.greeting'")
            }
        }
    }
}
----


.build.gradle.kts
[source,kotlin]
----
task.register
----

== Step 3. Configure a Task

.build.gradle.kts
[source,kotlin]
----
task.named
----

[.text-right]
**Next Step:** <<partr7_writing_plugins#partr7_writing_plugins,Writing Plugins>> >>
