// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[partr3_settings_file]]
= Part 3: Writing the Settings File

Learn the basics of authoring Gradle by developing the Settings File.

****
**In this section you will:**

- Understand the Settings object
- Update the Settings file
- How to use a Settings file
****

[[part3_begin]]
== Step 0. Before you Begin

1. You initialized your Java app in <<partr1_gradle_init.adoc#part1_begin,part 1>>.
2. You understand the Gradle Build Lifecycle from <<partr2_build_lifecycle.adoc#part2_begin,part 2>>.

== Step 1. The `Settings` object

The settings file is the entry point of every Gradle project.

During the initialization phase, Gradle finds the settings file in your project root directory.

When the settings file, `settings.gradle(.kts)`, is found, Gradle instantiates a link:{groovyDslPath}/org.gradle.api.initialization.Settings.html[Settings] object.

One of the purposes of the link:{groovyDslPath}/org.gradle.api.initialization.Settings.html[Settings] object is to allow you to declare all the projects to be included in the build.

You can use any of the methods and properties on the link:{groovyDslPath}/org.gradle.api.initialization.Settings.html[Settings] interface directly in your settings file.

For example:

[source]
----
 includeBuild('some-build')                         // Delegates to Settings.includeBuild()
 reportsDir = findProject("/myInternalProject")     // Delegates to Settings.findProject()
----

== Step 2. Update the Settings file

[source,settings.gradle.kts]
----
plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
}

rootProject.name = "temp"
include("app")
----

[source,settings.gradle.kts]
----
pluginManagement {                                          // <1>
    repositories {
        gradlePluginPortal()
        google()
    }
    includeBuild("../build-logic")
}

plugins {                                                   // <2>
    id("org.gradle.toolchains.fake") version "0.6.0"
}

rootProject.name = "root-project"                           // <3>

dependencyResolutionManagement {                            // <4>
    repositories {
        mavenCentral()
    }
    includeBuild("../other-project")
}

include("sub-project-a")                                    // <5>
include("sub-project-b")
include("sub-project-c")
----

[.text-right]
**Next Step:** <<partr4_build_scripts#partr4_build_scripts,Writing a Build Script>> >>
