// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[partr6_writing_tasks]]
= Part 6: Writing Tasks

Learn the basics of authoring Gradle tasks by creating a simple one in your Build script.

****
**In this section you will:**

- Initialize a Java project
****

[[part6_begin]]
== Step 0. Before you Begin

1. You initialized your Java app in <<partr1_gradle_init.adoc#part1_begin,part 1>>.
2. You understand the Gradle Build Lifecycle from <<partr2_build_lifecycle.adoc#part2_begin,part 2>>.
3. You added a subproject and a separate Build in <<partr3_multi_project_builds#part3_begin, part3>>.
4. You authored a Settings file in <<partr4_settings_file.adoc#part4_begin,part 4>>.
5. You authored a Build script in <<partr5_build_scripts.adoc#part5_begin,part 5>>.

== Step 2. Understand Tasks

== Step 2. Register a Task

.Plugin.kts
[source,kotlin]
----
project.tasks.register("license") { task ->
    task.description = "license"
    task.group = "from my plugin"
    task.doLast {
        println("Hello from plugin 'com.gradle.license'")
    }
}
----

== Step 3. Create a Task

.build.gradle.kts
[source,kotlin]
----
task.register
----

== Step 3. Configure a Task

.build.gradle.kts
[source,kotlin]
----
task.named
----

[.text-right]
**Next Step:** <<partr7_writing_plugins#partr7_writing_plugins,Writing Plugins>> >>
