name: Feature request
description: Suggest an idea for this project
labels: [ "a:feature", "to-triage" ]
assignees: [ ]
body:
  - type: markdown
    attributes:
      value: |
        Please follow the instructions below.
        We receive dozens of issues every week, so to stay productive, we will close issues that don't provide enough information.

        Please open Android-related issues on [the Android Issue Tracker](https://source.android.com/source/report-bugs)
        Please open IntelliJ-related issues on [the JetBrains Issue Tracker](https://youtrack.jetbrains.com/newIssue?project=IDEA)
        Please open Gradle Native-related issues on [the Gradle Native repository](https://github.com/gradle/gradle-native/issues)

        Provide a brief summary of the issue in the title above
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Tell us how it should work
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior (optional)
      description: Explain the difference from current behavior
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        How has this issue affected you? What are you trying to accomplish? What other alternatives have you considered?
        Providing context helps us come up with a solution that is most useful in the real world
    validations:
      required: true
