// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[structure_large_projects]]
= Structuring Large Projects

== Folder structure

Your software may have multiple components and subprojects as highlighted in the folder structure below.
Each subproject has its own build.gradle file.

All Gradle related development such as convention plugins are stored in the `gradle` folder:

[source,text]
----
.
├── gradle  <1>
│   ├── plugins
│   ├── platform
│   └── ...
├── gradlew
├── settings.gradle.kts <3>
├── app     <2>
│   ├── build.gradle.kts
│   └── src
│       └── ...
├── core
│   ├── build.gradle.kts
│   └── src
│       └── ...
├── tools
│   ├── build.gradle.kts
│   └── src
│       └── ...
└── api
    ├── build.gradle.kts
    └── src
        └── ...
----
<1> Gradle specific
<2> Software specific
<3> Settings for the build describing subprojects, repositories, and anything else that applies to the whole build

== Gradle

everything, which is not a dependency declaration of a concrete subproject, into the gradle/ folder

[source,text]
----
.
├── gradle
│   ├── plugins     <1>
│   ├── platform    <2>
│   └── ...
├── gradlew
├── settings.gradle.kts
├── app
│   ├── build.gradle.kts
│   └── src
│       └── ...
├── core
│   ├── build.gradle.kts
│   └── src
│       └── ...
├── tools
│   ├── build.gradle.kts
│   └── src
│       └── ...
└── api
    ├── build.gradle.kts
    └── src
        └── ...
----
<1> Shared build logic and convention plugins
<2> Dependency versions and constraints (i.e., BOM or version catalog)

Talk more about dependency rules here with the version catalog and things like reject

Centralize dependency versions

== Dependency declaration

[source,text]
----
.
├── gradle
│   ├── plugins
│   ├── platform
│   └── ...
├── gradlew
├── settings.gradle.kts
├── app
│   ├── build.gradle.kts    <1>
│   └── src
│       └── ...
├── core
│   ├── build.gradle.kts    <1>
│   └── src
│       └── ...
├── tools
│   ├── build.gradle.kts    <1>
│   └── src
│       └── ...
└── api
    ├── build.gradle.kts    <1>
    └── src
        └── ...
----

Each subproject has a build file that is now much cleaner and simpler since the majority of the build logic is located in the `gradle` folder.

The local build file now applies the convention plugins which is not expected to change much.
The important part is the dependencies.

== Dos and Don'ts

With this, the following outdated practices are avoided:

No direct dependencies between tasks declared (except for extending lifecycle tasks like assemble or check)
No direct dependencies between tasks from different subprojects are declared
No cross-project configuration (subproject / allprojects) is performed
Each build script of a subproject is simpler to read as all relationships to other projects are expressed in terms of dependencies
