plugins {
    id("gradlebuild.distribution.implementation-java")
}

description = """
   Utilities and services for executing processes, but without any
   dependency on daemon-related code. This project is safe to use
   in clients and workers without pulling in unwanted dependencies.
"""

dependencies {
    api(projects.baseServices)
    api(projects.buildOperations)
    api(projects.concurrent)
    api(projects.processServicesApi)
    api(projects.stdlibJavaExtensions)

    api(libs.nativePlatform)
    api(libs.jspecify)

    implementation(projects.loggingApi)
    implementation(projects.messaging)
    implementation(projects.native)
    implementation(projects.serviceLookup)

    implementation(libs.jnrConstants)
    implementation(libs.guava)
    implementation(libs.commonsLang)
    implementation(libs.commonsIo)
    implementation(libs.slf4jApi)

    testImplementation(projects.io)
    testImplementation(testFixtures(projects.core))
    testImplementation(testFixtures(projects.logging))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

jvmCompile {
    // ExecHandleRunner uses Java 9+ Process APIs via a Multi-Release JAR while the base
    // classes remain Java 8 compatible. See org.gradle.process.internal.jvm.
    addMultiReleaseVersion(9)
}
