/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id("gradlebuild.distribution.implementation-java")
    id("gradlebuild.xdcl-ecosystem-library")
}

description = "Shared XDCL schema common to the built-in ecosystems: dependency scopes and the HasDependencies capability trait every ecosystem's project types compose. Published for plugin authors and shipped in the distribution (prototype)"

// A schema-only ecosystem foundation: common.xdsl (packed under META-INF/xdcl/ by xdcl-gradle-plugin)
// and the Java facades generated from it. The built-in ecosystems (plugin-development today; JVM,
// Native etc. later) `import` this schema and `with` its capability traits, so the shared dependency
// surface is declared once. Publishable because it carries no internal-Gradle dependency — only the
// external org.xdcl facade API.
// No dependencies block: the facade base types (org.gradle.api.xdcl.*) come as `api` from the
// gradlebuild.xdcl-ecosystem-library convention, and this foundational schema imports nothing else.

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
    }
}
