plugins {
    id("gradlebuild.distribution.api-java")
}

description = "Public API interfaces for input normalization"

dependencies {
    api(projects.baseServices)
    implementation(projects.stdlibJavaExtensions)
    compileOnly(libs.jspecify)
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}
