// Copyright (C) 2025 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[script-default-imports]]
= Default Imports

To make build scripts more concise, Gradle automatically adds a set of import statements to scripts.

Gradle implicitly adds the following imports to each script (for both Groovy and Kotlin):

[source]
----
include::default-imports.txt[]
----

Additionally, for Groovy, the following imports are added too:
[source]
----
import java.lang.*
import java.io.*
import java.net.*
import java.util.*
import java.time.*
import java.math.BigDecimal
import java.math.BigInteger
import javax.inject.Inject
----
