// Copyright (C) 2025 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[public_gradle_apis]]
= Public Gradle APIs
:keywords: public api

Gradle provides many public APIs that allow developers to interact with various build system components.

Only elements explicitly documented as part of the stable public API are supported for use.
All other classes, methods, or packages, including, but not limited to, those containing the name `Internal` or located in a package segment `.internal.`, are considered internal implementation details and must not be relied upon for stable usage.

Use of Gradle internal APIs in plugins and build scripts can break builds when either Gradle or plugins change.

The list of public API packages is as follows:

[source,text]
----
org.gradle.*  (top-level classes only — excludes subpackages)
org.gradle.api.**  (includes subpackages)
org.gradle.authentication.**
org.gradle.build.**
org.gradle.buildconfiguration.**
org.gradle.buildinit.**
org.gradle.caching.**
org.gradle.concurrent.**
org.gradle.deployment.**
org.gradle.external.javadoc.**
org.gradle.ide.**
org.gradle.ivy.**
org.gradle.jvm.**
org.gradle.language.**
org.gradle.maven.**
org.gradle.nativeplatform.**
org.gradle.normalization.**
org.gradle.platform.**
org.gradle.plugin.devel.**
org.gradle.plugin.use.*
org.gradle.plugin.management.*
org.gradle.plugins.**
org.gradle.process.**
org.gradle.testfixtures.**
org.gradle.testing.jacoco.**
org.gradle.tooling.**
org.gradle.swiftpm.**
org.gradle.model.**
org.gradle.testkit.**
org.gradle.testing.**
org.gradle.vcs.**
org.gradle.work.**
org.gradle.workers.**
org.gradle.util.**
----

NOTE: The `\*` wildcard matches only classes directly in the package (e.g., `org.gradle.Foo`), but **does not include subpackages** like `org.gradle.something.Foo`.
Conversely, the `**` wildcard matches the noted package and its subpackages.
