// Copyright (C) 2025 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[public_gradle_apis]]
= Public Gradle APIs
:keywords: public api

Gradle provides many public APIs that allow developers to interact with various build system components.

Any class or package name containing `Internal`, or located in a package segment `.internal.`, is not part of the public Gradle API and should not be relied upon for stable usage.
Use of Gradle internal APIs in plugins and build scripts can break builds when either Gradle or plugins change.

The list of public API packages is maintained in the link:https://github.com/gradle/gradle/blob/master/buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/public-api.kt[Gradle public API definition] (excluding any subpackages containing internal).
It is also available below:

[source,text]
----
org/gradle/*
org/gradle/api/**
org/gradle/authentication/**
org/gradle/build/**
org/gradle/buildconfiguration/**
org/gradle/buildinit/**
org/gradle/caching/**
org/gradle/concurrent/**
org/gradle/deployment/**
org/gradle/external/javadoc/**
org/gradle/ide/**
org/gradle/ivy/**
org/gradle/jvm/**
org/gradle/language/**
org/gradle/maven/**
org/gradle/nativeplatform/**
org/gradle/normalization/**
org/gradle/platform/**
org/gradle/plugin/devel/**
org/gradle/plugin/use/*
org/gradle/plugin/management/*
org/gradle/plugins/**
org/gradle/process/**
org/gradle/testfixtures/**
org/gradle/testing/jacoco/**
org/gradle/tooling/**
org/gradle/swiftpm/**
org/gradle/model/**
org/gradle/testkit/**
org/gradle/testing/**
org/gradle/vcs/**
org/gradle/work/**
org/gradle/workers/**
org/gradle/util/**
----

== Avoiding internal APIs

Some older Gradle internals are still used in the wild but are **not supported** and may break between Gradle releases.
Use the following public alternatives instead:

[cols="1,3",options="header"]
|===
| Internal API (do not use) | Supported alternative

| `org.gradle.internal.reflect.Instantiator`
| Use link:{javadocPath}/org/gradle/api/model/ObjectFactory.html[ObjectFactory] to create and wire new objects in tasks or plugins.

| `org.gradle.api.internal.ConventionMapping`
| Use link:{javadocPath}/org/gradle/api/provider/Property.html[Property] and link:{javadocPath}/org/gradle/api/provider/Provider.html[Provider] to model user inputs and lazy configuration.

| `org.gradle.internal.os.OperatingSystem`
| Detect the OS using standard Java `System.getProperty("os.name")` or use link:https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/SystemUtils.html[Apache Commons `SystemUtils`].

| `org.gradle.util.*` classes (e.g., `CollectionUtils`, `GFileUtils`)
| Prefer standard Java collections and I/O APIs or other well-maintained libraries.
|===
