// Copyright 2023 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[gradle_optimizations]]
= Gradle Optimizations

Gradle uses two main feature to reduce build time, incremental builds and build caching.

== Incremental builds
Incremental builds is used when your run a task with inputs and outputs that haven't changed since the last time you have run it.

When you run a task that has been already executed and hasn't changed then `UP-TO-DATE` is printed next to the task.

== Build caching
The Gradle Build Cache is designed to help you save time by reusing outputs produced by previous builds. It works by storing (locally or remotely) build outputs, and allowing builds to fetch these outputs from the cache when it determines that inputs have not changed. The build cache gives you the ability to avoid the redundant work and cost of regenerating time-consuming and expensive processes.

When the build cache has been used to repopulate the local directory the tasks are marked as `FROM-CACHE`.
Once the local directory has been repopulated, the next execution will mark tasks as `UP-TO-DATE` and not `FROM-CACHE`.

The build cache allows you to share and reuse unchanged build and test outputs across the team. This speeds up local and CI builds since cycles are not wasted re-building components that are unaffected by new code changes.

=== Turn on local build cache

=== Turn off local build  cache

=== Clear local build cache
