// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[gradle_properties]]
= Gradle Properties

Gradle can be configured using properties.

There are two types of properties, *project properties* and *system properties*.

The system properties are passed to the JVM, which runs Gradle.
System properties can be used to make sure the entire development team uses the same environment such as a specific version of java.
If a system property is null or doesn't exist, Gradle execution will not stop or fail.

The project properties are used to customise the project build using user-defined properties.
If a project property is null or doesn't exist, then a `MissingPropertyException` is raised and Gradle stops the execution, which means build will fail.

Properties are declared 3 ways:

1. A `gradle.properties` file: `org.gradle.caching=true`
2. Extra Properties: `project.ext.caching = 'on'`
3. Command line option: `gradle build --build-cache`

==  1. The `gradle.properties` file

We can declare both system and project properties in the gradle.properties file.
And we can have properties file for specific to a project as well as common file for all projects.
Project specific property file resides in the same directory as root project. Shared, Global file properties file resides in the USER_HOME/.gradle/ directory.
Use systemProp prefix to declare system properties.

[source]
----
# gradle(JVM) arguments
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048m

# system properties
systemProp.gradle.wrapperUser=myuser
systemProp.gradle.wrapperPassword=mypassword
systemProp.greetMessageSystem="hello : System property"

# project properties
greetMessageProject="Hello, Good Morning."
----

== 2. Extra properties
All enhanced objects in Gradle’s domain model can hold extra user-defined properties.
This includes, projects, tasks, and source sets.
Extra properties can be added, read and set via the owning object’s ext property.
Alternatively, an ext block can be used to add multiple properties at once.

[source, build.gradle.kts]
----
// declare properties using set(key,value) of ext.
project.ext.set("greetMessage", " Good Morning")

// declare properties inside ext closure
project.ext {
    set("greetMessage", "Good Morning")
    set("greetMessage2", "Good Afternoon")
}

// access a property using its key
println("${project.property("greetMessage")}")

// Project properties can be accessed via delegation
val greetMessage: String by project


// Print all project properties
println("gradle: In Root Project Printing all properties -------")
project.properties.forEach{
    println("Property key name: ${it.key} and value is : ${it.value}")
}
----

== 3. Properties from the Command Line
We can set both project and system properties from command line at the time of executing the build.

To set system property from command line use -D option, for example, let’s say there is system property named javaVersion and if we want to set it from command line, then we can use -DjavaVersion=1.8 with gradle command.

To set project property from command line use -P option, for example, let’s say there is project property named testable and if we want to set it from the command line, then we can use -Ptestable=true with gradle command.

----
$ ./gradlew :docs:checkDeadInternalLinks '-Dorg.gradle.ignoreBuildJavaVersionCheck=true'
----
