plugins {
    id("gradlebuild.distribution.api-java")
    id("gradlebuild.distribution.api-kotlin")
}

description = "Bundled Gradle plugin that mitigates flaky tests by retrying them when they fail"

sourceSets.main {
    // All Java sources in this subproject are copied verbatim from the upstream
    // test-retry-gradle-plugin and would trigger multiple errorprone checks.
    // Disable errorprone for the main sourceset rather than modify any imported file.
    errorprone.enabled = false
}

dependencies {
    api(projects.coreApi)
    api(projects.testingBaseInfrastructure)

    compileOnly(projects.kotlinDsl)

    api(libs.asm)
    api(libs.inject)
    api(libs.jspecify)
    api(projects.baseServices)
    api(projects.testingBase)
    api(projects.testingJvm)

    implementation(projects.core)
    implementation(projects.loggingApi)
    implementation(projects.serviceLookup)

    implementation(libs.groovyXml)
    implementation(libs.slf4jApi)

    testImplementation(libs.groovy)
    testImplementation(testLibs.spock)

    integTestDistributionRuntimeOnly(projects.distributionsJvm)
}

gradleModule {
    requiredRuntimes {
        daemon = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
    }
}
