plugins {
    id("gradlebuild.distribution.api-java")
    id("gradlebuild.distribution.api-kotlin")
}

description = "Bundled Gradle plugin that mitigates flaky tests by retrying them when they fail"

dependencies {
    api(projects.coreApi)
    api(projects.testingBaseInfrastructure)

    compileOnly(projects.kotlinDsl)

    api(libs.asm)
    api(libs.inject)
    api(libs.jspecify)
    api(projects.baseServices)
    api(projects.testingBase)
    api(projects.testingJvm)

    implementation(projects.core)
    implementation(projects.loggingApi)
    implementation(projects.serviceLookup)

    implementation(libs.groovyXml)
    implementation(libs.slf4jApi)

    testImplementation(libs.groovy)
    testImplementation(testLibs.spock)

    integTestDistributionRuntimeOnly(projects.distributionsJvm)
}

gradleModule {
    requiredRuntimes {
        daemon = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
    }
}
