{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "demoDebugAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-library-1.0-demoDebug.aar",
          "url": "android-library-1.0-demoDebug.aar",
          "size": 1528,
          "sha512": "3ca0a60b743ae6371eafdfb73c6635e3376d8357e56d076c556223d1ee1cedab56f0e91ee8f27733d800717ce7f942bee24fc9d8e6d11d335d6e0f6a3b50fbad",
          "sha256": "911efb06c5566e0eed53344d6963a7440d00dd02f976f7e5be9e69eff0c938b5",
          "sha1": "6d1e395f0bbd2fd54c39c3d14ace373c2d933bb5",
          "md5": "76e7e67fadbae5b91e19299e20f1291f"
        }
      ]
    },
    {
      "name": "demoDebugAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-library-1.0-demoDebug.aar",
          "url": "android-library-1.0-demoDebug.aar",
          "size": 1528,
          "sha512": "3ca0a60b743ae6371eafdfb73c6635e3376d8357e56d076c556223d1ee1cedab56f0e91ee8f27733d800717ce7f942bee24fc9d8e6d11d335d6e0f6a3b50fbad",
          "sha256": "911efb06c5566e0eed53344d6963a7440d00dd02f976f7e5be9e69eff0c938b5",
          "sha1": "6d1e395f0bbd2fd54c39c3d14ace373c2d933bb5",
          "md5": "76e7e67fadbae5b91e19299e20f1291f"
        }
      ]
    },
    {
      "name": "fullDebugAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-library-1.0-fullDebug.aar",
          "url": "android-library-1.0-fullDebug.aar",
          "size": 1529,
          "sha512": "3cafdcb56369c5d0a65a6d768c0907828f9c16d728c4cc3b4effe52ff1a49ef4215a4a964f945b4ca1dde2821286d95b53240ac3f5732957f13cc9900b7ab122",
          "sha256": "911944a0a11ed6b296250062571cb46267f330d6830f15e32befa26e7d8cf129",
          "sha1": "f2a9f57970a03f2d6613ea0e3042df172c476d5f",
          "md5": "bf0884f6207dff732602be6d499566c4"
        }
      ]
    },
    {
      "name": "fullDebugAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-library-1.0-fullDebug.aar",
          "url": "android-library-1.0-fullDebug.aar",
          "size": 1529,
          "sha512": "3cafdcb56369c5d0a65a6d768c0907828f9c16d728c4cc3b4effe52ff1a49ef4215a4a964f945b4ca1dde2821286d95b53240ac3f5732957f13cc9900b7ab122",
          "sha256": "911944a0a11ed6b296250062571cb46267f330d6830f15e32befa26e7d8cf129",
          "sha1": "f2a9f57970a03f2d6613ea0e3042df172c476d5f",
          "md5": "bf0884f6207dff732602be6d499566c4"
        }
      ]
    },
    {
      "name": "demoReleaseAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-library-1.0-demoRelease.aar",
          "url": "android-library-1.0-demoRelease.aar",
          "size": 1442,
          "sha512": "41a2c512c7a6d1da55abf6187d4f7e9e51c0602d26d6c1ed9cc8496b4e02e12b9a1e980d48365d1a6c6f5fcbe64142de33d6342cd129038334dfb0326f9e2540",
          "sha256": "2cf0e377326830a0a99c92240d07435098439ccf52fa0465cd9c8cef0fff4127",
          "sha1": "17a7cb2f5b8690107bf2382387cd98c78331eee0",
          "md5": "5df7ef17e85be1e7446f42b0841cf080"
        }
      ]
    },
    {
      "name": "demoReleaseAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-library-1.0-demoRelease.aar",
          "url": "android-library-1.0-demoRelease.aar",
          "size": 1442,
          "sha512": "41a2c512c7a6d1da55abf6187d4f7e9e51c0602d26d6c1ed9cc8496b4e02e12b9a1e980d48365d1a6c6f5fcbe64142de33d6342cd129038334dfb0326f9e2540",
          "sha256": "2cf0e377326830a0a99c92240d07435098439ccf52fa0465cd9c8cef0fff4127",
          "sha1": "17a7cb2f5b8690107bf2382387cd98c78331eee0",
          "md5": "5df7ef17e85be1e7446f42b0841cf080"
        }
      ]
    },
    {
      "name": "fullReleaseAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-library-1.0-fullRelease.aar",
          "url": "android-library-1.0-fullRelease.aar",
          "size": 1441,
          "sha512": "791790c04ff0986f9187bcfe92abd4587f509f9e196c94011e8f4eaaccb788659e1f8d652e3707ce6ade916047bab2f613cb0c18ca7ac837ecc0cff80b445f8d",
          "sha256": "e3799ecaaf720643900ed50a141b2fc0ef80b3e276cdd3eb6c9bd3d51275355f",
          "sha1": "b664ccf60842c6d23514dd05ed13d73afcc25b38",
          "md5": "adcc9c06e6ebe0c2f751be60182f7aa3"
        }
      ]
    },
    {
      "name": "fullReleaseAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-library-1.0-fullRelease.aar",
          "url": "android-library-1.0-fullRelease.aar",
          "size": 1441,
          "sha512": "791790c04ff0986f9187bcfe92abd4587f509f9e196c94011e8f4eaaccb788659e1f8d652e3707ce6ade916047bab2f613cb0c18ca7ac837ecc0cff80b445f8d",
          "sha256": "e3799ecaaf720643900ed50a141b2fc0ef80b3e276cdd3eb6c9bd3d51275355f",
          "sha1": "b664ccf60842c6d23514dd05ed13d73afcc25b38",
          "md5": "adcc9c06e6ebe0c2f751be60182f7aa3"
        }
      ]
    }
  ]
}
