{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "demoDebugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "demo",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-library-1.0-demoDebug.aar",
          "url": "android-library-1.0-demoDebug.aar",
          "size": 1765,
          "sha512": "12ba4004a6de03de3842c89e7fb1cfc60d5482c4646fdbc69daa9439c0c71e62429a78a7050d7435c8228145e09b62a01d134a8b1d470de903d7889730a68bf9",
          "sha256": "cbf5cc04e8a8fd9ecb737d4764fb30113c36468bb60badf08124bbfaca693417",
          "sha1": "61721d4b290350d7964af098077148d5d7004586",
          "md5": "c5c2bc6dd65dbfe6a26bc9e3529fee86"
        }
      ]
    },
    {
      "name": "demoDebugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "demo",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-library-1.0-demoDebug.aar",
          "url": "android-library-1.0-demoDebug.aar",
          "size": 1765,
          "sha512": "12ba4004a6de03de3842c89e7fb1cfc60d5482c4646fdbc69daa9439c0c71e62429a78a7050d7435c8228145e09b62a01d134a8b1d470de903d7889730a68bf9",
          "sha256": "cbf5cc04e8a8fd9ecb737d4764fb30113c36468bb60badf08124bbfaca693417",
          "sha1": "61721d4b290350d7964af098077148d5d7004586",
          "md5": "c5c2bc6dd65dbfe6a26bc9e3529fee86"
        }
      ]
    },
    {
      "name": "fullDebugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "full",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-library-1.0-fullDebug.aar",
          "url": "android-library-1.0-fullDebug.aar",
          "size": 1764,
          "sha512": "ff0ee7d990b790a9ab2504ce4bd6a827cd2adc6ebdf6df30e29812dcb2c21d42dcb89e387f73a0ec696c20a34ba41891ad3ea1b24f2c04290270c8fb97d33a3b",
          "sha256": "5bd69599ba3497c7780fee27d945d9bb5cea42f7130f0c051abbbf1547498e4d",
          "sha1": "a7ec8673191fd8664fd39a9b4b6b48f521b48dc3",
          "md5": "4b79cd70ee907157ab2d2845b17b1ca6"
        }
      ]
    },
    {
      "name": "fullDebugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "full",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-library-1.0-fullDebug.aar",
          "url": "android-library-1.0-fullDebug.aar",
          "size": 1764,
          "sha512": "ff0ee7d990b790a9ab2504ce4bd6a827cd2adc6ebdf6df30e29812dcb2c21d42dcb89e387f73a0ec696c20a34ba41891ad3ea1b24f2c04290270c8fb97d33a3b",
          "sha256": "5bd69599ba3497c7780fee27d945d9bb5cea42f7130f0c051abbbf1547498e4d",
          "sha1": "a7ec8673191fd8664fd39a9b4b6b48f521b48dc3",
          "md5": "4b79cd70ee907157ab2d2845b17b1ca6"
        }
      ]
    },
    {
      "name": "demoReleaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "demo",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-library-1.0-demoRelease.aar",
          "url": "android-library-1.0-demoRelease.aar",
          "size": 1666,
          "sha512": "8512bfd3d432278690fa959da980d386d17dd201648054451d554f1aed41a33c47c6f41288a9eeb7d284d04f934bc3e89345dbf1c0087d364f70a24c5118877e",
          "sha256": "349c897c9ca5a57d930b511a6aeecd66415426d368ebe0be373e1f3cc4143fb9",
          "sha1": "1aa20667dd9916ba78497347a13b0a0d5644653c",
          "md5": "f319bb2902dd5ebbdf406ede762aedbc"
        }
      ]
    },
    {
      "name": "demoReleaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "demo",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-library-1.0-demoRelease.aar",
          "url": "android-library-1.0-demoRelease.aar",
          "size": 1666,
          "sha512": "8512bfd3d432278690fa959da980d386d17dd201648054451d554f1aed41a33c47c6f41288a9eeb7d284d04f934bc3e89345dbf1c0087d364f70a24c5118877e",
          "sha256": "349c897c9ca5a57d930b511a6aeecd66415426d368ebe0be373e1f3cc4143fb9",
          "sha1": "1aa20667dd9916ba78497347a13b0a0d5644653c",
          "md5": "f319bb2902dd5ebbdf406ede762aedbc"
        }
      ]
    },
    {
      "name": "fullReleaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "full",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-library-1.0-fullRelease.aar",
          "url": "android-library-1.0-fullRelease.aar",
          "size": 1670,
          "sha512": "df2d60c71d64853cbb87c83e02bdddea6b4d32b4ce78bd7150f0b05e7cf98bba6192949216ecb961b82f722e2685cccce42e3caa0b084b5299b3f57d7dc3639b",
          "sha256": "f4193d10b694090957f8f9879f4fa75101954ed094bf1c3ee635b30435fd8773",
          "sha1": "926bb1f63cacf98f7b491e7a2af3b62078ef4a36",
          "md5": "f081038b8a6e55c618d518827fcd1ca3"
        }
      ]
    },
    {
      "name": "fullReleaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "full",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-library-1.0-fullRelease.aar",
          "url": "android-library-1.0-fullRelease.aar",
          "size": 1670,
          "sha512": "df2d60c71d64853cbb87c83e02bdddea6b4d32b4ce78bd7150f0b05e7cf98bba6192949216ecb961b82f722e2685cccce42e3caa0b084b5299b3f57d7dc3639b",
          "sha256": "f4193d10b694090957f8f9879f4fa75101954ed094bf1c3ee635b30435fd8773",
          "sha1": "926bb1f63cacf98f7b491e7a2af3b62078ef4a36",
          "md5": "f081038b8a6e55c618d518827fcd1ca3"
        }
      ]
    }
  ]
}
