{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "android-kotlin-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "debugAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-kotlin-library-1.0-debug.aar",
          "url": "android-kotlin-library-1.0-debug.aar",
          "size": 2266,
          "sha512": "90cfb9bbfe79be18936d64f04ffc39ad8f76a8fa805ec2f9eb0d147bb6631431fecc2d1dd134563c4b2bd6514ac3fbb0ba9ed564a0f5219d399e709fa9c4c237",
          "sha256": "eb65738fe98b87c71ec97a3209067db264c0bdf747c5a70818a4937d56df7ce5",
          "sha1": "f14d4462f414b8c0442f749f286584e87ceb6561",
          "md5": "ccd1f4d05caf016378548d8e150303c6"
        }
      ]
    },
    {
      "name": "debugAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "android-kotlin-library-1.0-debug.aar",
          "url": "android-kotlin-library-1.0-debug.aar",
          "size": 2266,
          "sha512": "90cfb9bbfe79be18936d64f04ffc39ad8f76a8fa805ec2f9eb0d147bb6631431fecc2d1dd134563c4b2bd6514ac3fbb0ba9ed564a0f5219d399e709fa9c4c237",
          "sha256": "eb65738fe98b87c71ec97a3209067db264c0bdf747c5a70818a4937d56df7ce5",
          "sha1": "f14d4462f414b8c0442f749f286584e87ceb6561",
          "md5": "ccd1f4d05caf016378548d8e150303c6"
        }
      ]
    },
    {
      "name": "releaseAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-kotlin-library-1.0-release.aar",
          "url": "android-kotlin-library-1.0-release.aar",
          "size": 2160,
          "sha512": "3d0edf831c8e7056938f8fbdf4313c73c9dcf994d6f3680eddda37c751dfc8940fb14f27537deebe0b122537c1705136f38e4bb2d6724933942b875999daf999",
          "sha256": "e1514488fd5148cc27a4cd7ca50d64d3f86c88c8864f3d1299674b613812f6c9",
          "sha1": "c7150a223cb7fb9eba4a77cf9c07702465552195",
          "md5": "fec5ff5e45f41602786bbe52de3fb25a"
        }
      ]
    },
    {
      "name": "releaseAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "android-kotlin-library-1.0-release.aar",
          "url": "android-kotlin-library-1.0-release.aar",
          "size": 2160,
          "sha512": "3d0edf831c8e7056938f8fbdf4313c73c9dcf994d6f3680eddda37c751dfc8940fb14f27537deebe0b122537c1705136f38e4bb2d6724933942b875999daf999",
          "sha256": "e1514488fd5148cc27a4cd7ca50d64d3f86c88c8864f3d1299674b613812f6c9",
          "sha1": "c7150a223cb7fb9eba4a77cf9c07702465552195",
          "md5": "fec5ff5e45f41602786bbe52de3fb25a"
        }
      ]
    }
  ]
}
