{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "android-library-single-variant",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "fullReleaseVariantFullReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-library-single-variant-1.0.aar",
          "url": "android-library-single-variant-1.0.aar",
          "size": 1717,
          "sha512": "61b7687be376f680be27a94f610f651b4113d660a539d657bc38188de153d6dbd558337ff23fe242daf8d50a2468c33956598c02b9d4d8872aaab1950b95a301",
          "sha256": "6d9f00d75a233eb5b3649b0f1a1dfdfad359a58008f3ff721c5852569cf234c8",
          "sha1": "165459bcaab095c2362cbbd4aa9ba1fd3f576b3a",
          "md5": "9cdf827ac27c638340b0bb33da3b8cd5"
        }
      ]
    },
    {
      "name": "fullReleaseVariantFullReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-library-single-variant-1.0.aar",
          "url": "android-library-single-variant-1.0.aar",
          "size": 1717,
          "sha512": "61b7687be376f680be27a94f610f651b4113d660a539d657bc38188de153d6dbd558337ff23fe242daf8d50a2468c33956598c02b9d4d8872aaab1950b95a301",
          "sha256": "6d9f00d75a233eb5b3649b0f1a1dfdfad359a58008f3ff721c5852569cf234c8",
          "sha1": "165459bcaab095c2362cbbd4aa9ba1fd3f576b3a",
          "md5": "9cdf827ac27c638340b0bb33da3b8cd5"
        }
      ]
    }
  ]
}
