{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "android-kotlin-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-kotlin-library-1.0-debug.aar",
          "url": "android-kotlin-library-1.0-debug.aar",
          "size": 2318,
          "sha512": "435e8ccb26cc9f26dbbecde34c90751d6efad972b190e3291d7b0164339ab82c6d75e4abb4f4a07ea6d34410545a70711ea88fa9338e5f75639d4a8b8f8e5119",
          "sha256": "0f39ba8938ecdaa60ca21660b68acb542139d834452cc94b8594e96994e5e5f5",
          "sha1": "6166d9d16facf38a9d9c2584eab7cc6d8c43e936",
          "md5": "f33885b0616951b5c6e71109069195c5"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-kotlin-library-1.0-debug.aar",
          "url": "android-kotlin-library-1.0-debug.aar",
          "size": 2318,
          "sha512": "435e8ccb26cc9f26dbbecde34c90751d6efad972b190e3291d7b0164339ab82c6d75e4abb4f4a07ea6d34410545a70711ea88fa9338e5f75639d4a8b8f8e5119",
          "sha256": "0f39ba8938ecdaa60ca21660b68acb542139d834452cc94b8594e96994e5e5f5",
          "sha1": "6166d9d16facf38a9d9c2584eab7cc6d8c43e936",
          "md5": "f33885b0616951b5c6e71109069195c5"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-kotlin-library-1.0-release.aar",
          "url": "android-kotlin-library-1.0-release.aar",
          "size": 2214,
          "sha512": "531c950e754ba477ec7911d4831357fab76801241501743f66719a48d7eb4f986abe790e61007513ede3f4f7673dfd1082580877e4017050503d7f89ab23a2d6",
          "sha256": "6ded7080ab1722a27897c38073f2f1903ad158367e667fc9084c0ee1bd02fda7",
          "sha1": "c2aae9bcd19518823b5a41e02c4b63696dde52cb",
          "md5": "c8db365609829806807f966e917d7dde"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-kotlin-library-1.0-release.aar",
          "url": "android-kotlin-library-1.0-release.aar",
          "size": 2214,
          "sha512": "531c950e754ba477ec7911d4831357fab76801241501743f66719a48d7eb4f986abe790e61007513ede3f4f7673dfd1082580877e4017050503d7f89ab23a2d6",
          "sha256": "6ded7080ab1722a27897c38073f2f1903ad158367e667fc9084c0ee1bd02fda7",
          "sha1": "c2aae9bcd19518823b5a41e02c4b63696dde52cb",
          "md5": "c8db365609829806807f966e917d7dde"
        }
      ]
    }
  ]
}
