{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "android-library-single-variant",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "fullReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-library-single-variant-1.0.aar",
          "url": "android-library-single-variant-1.0.aar",
          "size": 1485,
          "sha512": "3f3c9c003eb403c1371f4ff7765c321b99461f3b87aa14dcb01a53d58beb9400a4a787b705d2534c24bffc4293e94f1c02dbf9bb3215fec003efaf202b2c97bf",
          "sha256": "8992626cbaeaa3d569d1080b01e5c29870a99b9cfc3341e0e80c6b0b5e5f04f1",
          "sha1": "a2b7a62634b29ba226c7fb8f852b953fc9d03dab",
          "md5": "5d063fc54606c280fbb0c662e60da0ef"
        }
      ]
    },
    {
      "name": "fullReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-library-single-variant-1.0.aar",
          "url": "android-library-single-variant-1.0.aar",
          "size": 1485,
          "sha512": "3f3c9c003eb403c1371f4ff7765c321b99461f3b87aa14dcb01a53d58beb9400a4a787b705d2534c24bffc4293e94f1c02dbf9bb3215fec003efaf202b2c97bf",
          "sha256": "8992626cbaeaa3d569d1080b01e5c29870a99b9cfc3341e0e80c6b0b5e5f04f1",
          "sha1": "a2b7a62634b29ba226c7fb8f852b953fc9d03dab",
          "md5": "5d063fc54606c280fbb0c662e60da0ef"
        }
      ]
    }
  ]
}
