{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "android-kotlin-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "debugAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-kotlin-library-1.0-debug.aar",
          "url": "android-kotlin-library-1.0-debug.aar",
          "size": 2108,
          "sha512": "6285c2a221d819ed3d87a3a1652f5f57c9212d74b5fbf8a1f536b041d6734cd1bed47c3d96e13c15d91986db82da3e97e2e4a15926c1c722c69e257b7a207c54",
          "sha256": "9ecf17ef7d638182768be4ce71a809caa5527e8de8de27d2d525a07030c90065",
          "sha1": "fb066af3c5b457f7ed79efcf17cf7453aebb6884",
          "md5": "c8282720dff92465fb2a1fd4347d3d56"
        }
      ]
    },
    {
      "name": "debugAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "android-kotlin-library-1.0-debug.aar",
          "url": "android-kotlin-library-1.0-debug.aar",
          "size": 2108,
          "sha512": "6285c2a221d819ed3d87a3a1652f5f57c9212d74b5fbf8a1f536b041d6734cd1bed47c3d96e13c15d91986db82da3e97e2e4a15926c1c722c69e257b7a207c54",
          "sha256": "9ecf17ef7d638182768be4ce71a809caa5527e8de8de27d2d525a07030c90065",
          "sha1": "fb066af3c5b457f7ed79efcf17cf7453aebb6884",
          "md5": "c8282720dff92465fb2a1fd4347d3d56"
        }
      ]
    },
    {
      "name": "releaseAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-kotlin-library-1.0-release.aar",
          "url": "android-kotlin-library-1.0-release.aar",
          "size": 2011,
          "sha512": "00a9a38504266e38898f44300c06d350a5c4a08bebdf8d316f7212c330699adb7f0837f1187a908b4a0d7818144e846a3f937bd824361261d275d40af26ec690",
          "sha256": "aa8fd2d336459320754e1ba404782038d9a7fbd499249b897761a21ca037a77a",
          "sha1": "1c7f39d735f3ce3e4f70643b78bf736cbeb81782",
          "md5": "42cc48ea3cdf8603fe334692acfdf15b"
        }
      ]
    },
    {
      "name": "releaseAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "android-kotlin-library-1.0-release.aar",
          "url": "android-kotlin-library-1.0-release.aar",
          "size": 2011,
          "sha512": "00a9a38504266e38898f44300c06d350a5c4a08bebdf8d316f7212c330699adb7f0837f1187a908b4a0d7818144e846a3f937bd824361261d275d40af26ec690",
          "sha256": "aa8fd2d336459320754e1ba404782038d9a7fbd499249b897761a21ca037a77a",
          "sha1": "1c7f39d735f3ce3e4f70643b78bf736cbeb81782",
          "md5": "42cc48ea3cdf8603fe334692acfdf15b"
        }
      ]
    }
  ]
}
