{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "java-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "java-library-1.0.jar",
          "url": "java-library-1.0.jar",
          "size": 971,
          "sha512": "f9b7bd9b7a026cd3c7fc95694515b363da3ac87543f4f22436c0aa32ddcfeff82c3516ae0db3371474c2c4c9297df5bf60a3b5ae5095921c1ab12562f5866dc2",
          "sha256": "d4d23a096a33a398c71553fe5d673e81cecc4a795cb5b218661410527e5fef3f",
          "sha1": "8452516ae0544ad0d1fe384d8fd47e11a5e13b5e",
          "md5": "1a874f0114de786786b8b846e2b0c53a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-library-1.0.jar",
          "url": "java-library-1.0.jar",
          "size": 971,
          "sha512": "f9b7bd9b7a026cd3c7fc95694515b363da3ac87543f4f22436c0aa32ddcfeff82c3516ae0db3371474c2c4c9297df5bf60a3b5ae5095921c1ab12562f5866dc2",
          "sha256": "d4d23a096a33a398c71553fe5d673e81cecc4a795cb5b218661410527e5fef3f",
          "sha1": "8452516ae0544ad0d1fe384d8fd47e11a5e13b5e",
          "md5": "1a874f0114de786786b8b846e2b0c53a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-library-1.0-sources.jar",
          "url": "java-library-1.0-sources.jar",
          "size": 750,
          "sha512": "eb4609eefd9d3de7cbd238a0ca9b16b6bfee1727551a499ca56dec00d59ab06f5b2a14e1a9660faf1a3726ee5ade01a12136b631698d6ab791733b847452546f",
          "sha256": "18f64993f07f0211b9236274f12fc3db80e7402386ead2a8bd088efa38010f6d",
          "sha1": "89a8cb005b7ef63b505a5026e74a380e5563e7a0",
          "md5": "075e936022ff75f4dcacaacae3ab7669"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-library-1.0-javadoc.jar",
          "url": "java-library-1.0-javadoc.jar",
          "size": 393290,
          "sha512": "6bffb34245e935c0766d3e7d6185e07d582a4f672b47744b709e720a2d0e5938b98f35003bb97091a08ff1c1ec29335c89fe9232de7613149889a10536756f36",
          "sha256": "b29f90183d62a9567773b3456fe37a512beee73b0b7638d2a7f5a681d31ffdb5",
          "sha1": "39438d84778724136d405708989493cb968b4568",
          "md5": "a7ffa5addcb8b488eb6a0e39efbc0e63"
        }
      ]
    }
  ]
}
