{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "java-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "java-library-1.0.jar",
          "url": "java-library-1.0.jar",
          "size": 971,
          "sha512": "5a7d44937366f96486ed2027b0c4a673347ced949879f55b7aa365adc697d86083a33c72c31785888f5bdc8a6f067dfd02e54642f1c99fe8cc023265f7f685fd",
          "sha256": "5e854a1db22026274e4c1884d59197415b91fc277b77435ea8263a0b04b90b24",
          "sha1": "7540539b199e774030077ccde023951f316f0a61",
          "md5": "ab73e222b2856e44ca45ffdae1d82a88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-library-1.0.jar",
          "url": "java-library-1.0.jar",
          "size": 971,
          "sha512": "5a7d44937366f96486ed2027b0c4a673347ced949879f55b7aa365adc697d86083a33c72c31785888f5bdc8a6f067dfd02e54642f1c99fe8cc023265f7f685fd",
          "sha256": "5e854a1db22026274e4c1884d59197415b91fc277b77435ea8263a0b04b90b24",
          "sha1": "7540539b199e774030077ccde023951f316f0a61",
          "md5": "ab73e222b2856e44ca45ffdae1d82a88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-library-1.0-sources.jar",
          "url": "java-library-1.0-sources.jar",
          "size": 750,
          "sha512": "85648fe7d940524767a59622d739945d670b26bb79dae28df663242186ea4bf99c400079b5bf5c18ed3dc80622262f8d8e3c12008d160d4e40ed41a84b93edd2",
          "sha256": "a91f50e17ec902f6065189f9255c31daf78ab9bbdee0aa02b4637522f1362294",
          "sha1": "3f57e160412feba2c81f110a1989be599031ecf9",
          "md5": "6a571af6a3e22dd65a9f329e61acac2e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-library-1.0-javadoc.jar",
          "url": "java-library-1.0-javadoc.jar",
          "size": 393326,
          "sha512": "a80dc0bb9b30a2a3d9a2dfb89feb8d4e8902dfcf31e9ffe43010cbe90fd3faf5f3952a596cdb1ea50f7a426cd5b9cf508fd127af62cd2d45a6fb868f858fa179",
          "sha256": "96f038ebb86d37864d68460987536cd515881c33c8aa27dc3d591c7184f8e192",
          "sha1": "1a076a153b9bdbed7ee0d938ad45d9d7687d1e87",
          "md5": "1e10a127351ddd0a5ffb8a5b18504b66"
        }
      ]
    }
  ]
}
