{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "java-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "java-library-1.0.jar",
          "url": "java-library-1.0.jar",
          "size": 971,
          "sha512": "b5b0154d601ecc55f81656312fae467fe44813e8d1d8cc4af5025d8dee84497922453b7cbb523774dbbfcb20f61f731d1341b7605c181d528731d40e9f2322f2",
          "sha256": "c2adfbd62ab9c5b64d18f16dd00140ab1d2289ac5bdd87c9778ff1c20eb632ef",
          "sha1": "4682dfc6da5339486005bcfcc4e3e9f8f641a748",
          "md5": "859e71daaf29cafe9ea7aa066a036681"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-library-1.0.jar",
          "url": "java-library-1.0.jar",
          "size": 971,
          "sha512": "b5b0154d601ecc55f81656312fae467fe44813e8d1d8cc4af5025d8dee84497922453b7cbb523774dbbfcb20f61f731d1341b7605c181d528731d40e9f2322f2",
          "sha256": "c2adfbd62ab9c5b64d18f16dd00140ab1d2289ac5bdd87c9778ff1c20eb632ef",
          "sha1": "4682dfc6da5339486005bcfcc4e3e9f8f641a748",
          "md5": "859e71daaf29cafe9ea7aa066a036681"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-library-1.0-sources.jar",
          "url": "java-library-1.0-sources.jar",
          "size": 750,
          "sha512": "a81e4d1cc8929ebb2a450e431a34197c986e2fc0735bfcb32ee54021fcc71b66f396b8b46a12e9233e4553dd2d932fbead5267007f21304dbbb39a0f2262ea98",
          "sha256": "9251a52249aca92a8e40fa01e92308717b972945e5116f6cb406145f0d319212",
          "sha1": "69c7380ffe5f951de3bceb689b67e820bf93fd6d",
          "md5": "7d992e31836199ba5c6b94bd3aea8927"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-library-1.0-javadoc.jar",
          "url": "java-library-1.0-javadoc.jar",
          "size": 397477,
          "sha512": "7ab0a478f52fd9161429a60c91323e2d33dd94314e68b446ed34634fa62ff101d34ce6f0d88ec12ac47a70c120769d79ab9f5bb8b9ebd45f4c72fcf40bfcb849",
          "sha256": "d41e3fa38b3928f08c91cc6eaacc96fb8fd271acf92daf9dc7db69af9f12768f",
          "sha1": "6250b27a1df1a6145a9406498b9bdb7fe6932538",
          "md5": "781f411859ff8f7481fa0ffb629b8c2c"
        }
      ]
    }
  ]
}
