{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-library-linuxx64/1.0/kotlin-multiplatform-library-linuxx64-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-library-linuxx64",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-library-metadata-1.0.jar",
          "url": "kotlin-multiplatform-library-metadata-1.0.jar",
          "size": 1031,
          "sha512": "d14d257029c1786f03315d970e7f78425e6e12bc0ea15883e2f432dce12638aea9a27eafe7d758d3af5ec2a51b91c196ff2b344e8b723f6fd3f613242a1163f5",
          "sha256": "93d5c8a809c536f2fad956dd5c3dd2129c593c189d568a87d007d950adcb9f0b",
          "sha1": "56ef39d9ddf424002281729c3e33bcc8b65b86cd",
          "md5": "6cb4717aa4606913062e2590b3a3ee56"
        }
      ]
    }
  ]
}
