{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-library/1.0/kotlin-multiplatform-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-library.klib",
          "url": "kotlin-multiplatform-library-linuxx64-1.0.klib",
          "size": 5435,
          "sha512": "697c58ee85340107cc708e5ef1e3c3f75ad6fbd9235cd82cc1a4a5ce919ff097dbb30a2acca201a9e46cb48187091e72ef2a46c3bc089c699c2ada550d49e3e6",
          "sha256": "6c588bcac6835562e29ceca2536e20846d2ffa3c408717799c72189aeee08df6",
          "sha1": "f721c992cc7754e5d88adc5e46b898f6df54c504",
          "md5": "26a70bb158df0d9a0be6a0b78412506f"
        }
      ]
    }
  ]
}
