{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "macosX64-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library.klib",
          "url": "kotlin-multiplatform-android-library-macosx64-1.0.klib",
          "size": 5523,
          "sha512": "7529de431f5c410b65c3aaf96bf7ec9e23027d947787a39d580d3c779d9f72e81484bf5482c03f8773e5ca522193182b0ef0ce6737aed0bc5f6e2e90c8df84e6",
          "sha256": "65669a4fb8aca3e9b4a86da97086f79fd9bdf7dca26994331a840fc51dd78268",
          "sha1": "57ca2e8adbfbb3430fa6e6c2a63ca2f91b23b7cd",
          "md5": "c5905bb74cdd1a694bae761d975f5997"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
