{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library-macosx64/1.0/kotlin-multiplatform-android-library-macosx64-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library-macosx64",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-metadata-1.0.jar",
          "url": "kotlin-multiplatform-android-library-metadata-1.0.jar",
          "size": 1096,
          "sha512": "15bbe93c135851c1f6797e02620e28920b169a415568c96af325a217716175d6c2348a9c66f6ab0accc086d6d2a8850fe2b5d7ee84748c080a64f8aa7b530285",
          "sha256": "6f751b274c45743f3fe4fa5c8198943c68c19cd0426b5f6e89b0ac526ab3a1b9",
          "sha1": "3921422a7bf6f68e9165763e69445422eb993d77",
          "md5": "60fe613b928a018306a918320838fcf4"
        }
      ]
    }
  ]
}
