{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-library/1.0/kotlin-multiplatform-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-library-jvm-1.0.jar",
          "url": "kotlin-multiplatform-library-jvm-1.0.jar",
          "size": 1670,
          "sha512": "0cc934ea92442f77e2aef215567318debf848ded407e4bc572c53f711e6a692a550cf0863a79cb91cc4b256c477cb38b70f37042194f2fb4fcda2856ed602e34",
          "sha256": "4e7b409753359f56ce32bf3476e7c135233250eb380f56d88d71e551727fabc4",
          "sha1": "ffd0f6302d80a4d9713da640c5a09c73c407261d",
          "md5": "723d60bd14e0bc442dc050600ddacc92"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-library-jvm-1.0.jar",
          "url": "kotlin-multiplatform-library-jvm-1.0.jar",
          "size": 1670,
          "sha512": "0cc934ea92442f77e2aef215567318debf848ded407e4bc572c53f711e6a692a550cf0863a79cb91cc4b256c477cb38b70f37042194f2fb4fcda2856ed602e34",
          "sha256": "4e7b409753359f56ce32bf3476e7c135233250eb380f56d88d71e551727fabc4",
          "sha1": "ffd0f6302d80a4d9713da640c5a09c73c407261d",
          "md5": "723d60bd14e0bc442dc050600ddacc92"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-metadata/1.0/kotlin-multiplatform-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
