{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-library/1.0/kotlin-multiplatform-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-library-js-1.0.jar",
          "url": "kotlin-multiplatform-library-js-1.0.jar",
          "size": 3783,
          "sha512": "a06bfd22332fa26c80b190db16b622b47b68a2dabb8206ebcdc753142b610cebba88bf17b2eee6a27f0aaf749180fae80bfb8309ed93bc1637664a22641b6050",
          "sha256": "f1aac487d446e13af19693c9de2ca89c9206386a64955255e7d6b060fd212b5c",
          "sha1": "d3326d0f50737a338b46d6813bcd75d13b91f5aa",
          "md5": "77f4ccbe1924971d6c98d18fdfbd39d9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-library-js-1.0.jar",
          "url": "kotlin-multiplatform-library-js-1.0.jar",
          "size": 3783,
          "sha512": "a06bfd22332fa26c80b190db16b622b47b68a2dabb8206ebcdc753142b610cebba88bf17b2eee6a27f0aaf749180fae80bfb8309ed93bc1637664a22641b6050",
          "sha256": "f1aac487d446e13af19693c9de2ca89c9206386a64955255e7d6b060fd212b5c",
          "sha1": "d3326d0f50737a338b46d6813bcd75d13b91f5aa",
          "md5": "77f4ccbe1924971d6c98d18fdfbd39d9"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-metadata/1.0/kotlin-multiplatform-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
