{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library.klib",
          "url": "kotlin-multiplatform-android-library-linuxx64-1.0.klib",
          "size": 5541,
          "sha512": "92ed51022e5c76b2b4bf8143293b4569da10125f6d458feb2af7e97551c75a9f04bd59ad4b71ef5ef04e6a584dd9f9cf8c045ebf2d797d39c7457f3ab27be18d",
          "sha256": "fc342889fe6d61e9f69a95db52fe2f4e06f5f41200169fb9a87455cc55993d69",
          "sha1": "741fb20e281f9aa9a5d73f0552748dc978af226d",
          "md5": "9f271c5a7d91703c94c5db2f0c3cdbe3"
        }
      ]
    }
  ]
}
