{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-library/1.0/kotlin-multiplatform-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-library-jvm-1.0.jar",
          "url": "kotlin-multiplatform-library-jvm-1.0.jar",
          "size": 1614,
          "sha512": "af0ea7e99721bbf266b2ea1700c893e21ed33ab617d9fd34a4c361ebd8ba140777f8d7a4ff1ba3f77d218fb44889a2a1c6140825adb752d59335a70697fa50d6",
          "sha256": "fb06a82b1e2117660c4e8cf4248d9f04098b49a5c033491caba18a9d525e4bec",
          "sha1": "65f4fb4e927a9ffc2c9d05a82e9721ccf4bb7b4d",
          "md5": "4ee4bc056a9e3837289c37e53d4d00e7"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-library-jvm-1.0.jar",
          "url": "kotlin-multiplatform-library-jvm-1.0.jar",
          "size": 1614,
          "sha512": "af0ea7e99721bbf266b2ea1700c893e21ed33ab617d9fd34a4c361ebd8ba140777f8d7a4ff1ba3f77d218fb44889a2a1c6140825adb752d59335a70697fa50d6",
          "sha256": "fb06a82b1e2117660c4e8cf4248d9f04098b49a5c033491caba18a9d525e4bec",
          "sha1": "65f4fb4e927a9ffc2c9d05a82e9721ccf4bb7b4d",
          "md5": "4ee4bc056a9e3837289c37e53d4d00e7"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-metadata/1.0/kotlin-multiplatform-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
