{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library.klib",
          "url": "kotlin-multiplatform-android-library-linuxx64-1.0.klib",
          "size": 5231,
          "sha512": "2c4a75349de0055684e3b6414b271887d29e7b3ce8607877ecb37e814ebb845c3793e7b4f6d6a467545661448085927d7b31a067d1966b61cdb449ea4d6acf77",
          "sha256": "4a365b2bb8662f22f8445f09e9ef1a8d0114da7e7c9759594df780aec1604cf6",
          "sha1": "7c1e660f2025076b7bee2cb4f287a9e3fc6c5143",
          "md5": "11f289449f6ad238bc0afee3e257d00c"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
