{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-metadata-1.0.jar",
          "url": "kotlin-multiplatform-android-library-1.0.jar",
          "size": 3001,
          "sha512": "a0dc64ff490d027c69db524c49fcee170d6c938a28ba99b0029ade53613f7e8fa018b921f9675f6892783e111354c87a7b146de987ed7a089558f313b0ae4b39",
          "sha256": "c5c076146fab88eb1e4802a2a8f434f64260b1471fc9c1e479a8dade5f9de85a",
          "sha1": "005806287bfd07edb6d0b580d3532d60a0525927",
          "md5": "ac181beb924692bbc278fb58b4b10700"
        }
      ]
    },
    {
      "name": "demoDebugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "demo",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-demo-debug/1.0/kotlin-multiplatform-android-library-android-demo-debug-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-demo-debug",
        "version": "1.0"
      }
    },
    {
      "name": "demoDebugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "demo",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-demo-debug/1.0/kotlin-multiplatform-android-library-android-demo-debug-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-demo-debug",
        "version": "1.0"
      }
    },
    {
      "name": "fullDebugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "full",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-full-debug/1.0/kotlin-multiplatform-android-library-android-full-debug-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-full-debug",
        "version": "1.0"
      }
    },
    {
      "name": "fullDebugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "full",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-full-debug/1.0/kotlin-multiplatform-android-library-android-full-debug-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-full-debug",
        "version": "1.0"
      }
    },
    {
      "name": "demoReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "demo",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-demo/1.0/kotlin-multiplatform-android-library-android-demo-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-demo",
        "version": "1.0"
      }
    },
    {
      "name": "demoReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "demo",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-demo/1.0/kotlin-multiplatform-android-library-android-demo-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-demo",
        "version": "1.0"
      }
    },
    {
      "name": "fullReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "full",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-full/1.0/kotlin-multiplatform-android-library-android-full-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-full",
        "version": "1.0"
      }
    },
    {
      "name": "fullReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "full",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-android-full/1.0/kotlin-multiplatform-android-library-android-full-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-android-full",
        "version": "1.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-js/1.0/kotlin-multiplatform-android-library-js-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-js",
        "version": "1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-js/1.0/kotlin-multiplatform-android-library-js-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-js",
        "version": "1.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-linuxx64/1.0/kotlin-multiplatform-android-library-linuxx64-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-linuxx64",
        "version": "1.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-macosx64/1.0/kotlin-multiplatform-android-library-macosx64-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-macosx64",
        "version": "1.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-macosx64/1.0/kotlin-multiplatform-android-library-macosx64-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-macosx64",
        "version": "1.0"
      }
    }
  ]
}
