{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "fullReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "fullRelease",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-full-release.aar",
          "url": "kotlin-multiplatform-android-library-android-full-1.0.aar",
          "size": 2265,
          "sha512": "d294833d960347986008d48fb7705de2920f2486a3fae5c4acb7401b06c2d568a797ea3c61f1ae5c845dab9f60857facb415253b317cd362fa616b16c590f228",
          "sha256": "8543269660d3b5108c1cb735f3513743d383afdf176571cfd54dd6f9869188f4",
          "sha1": "704ed198d18d80adc2fcc2d2c7e1347335af344c",
          "md5": "4018d82b5bbdd40f314fff4e06a12dd3"
        }
      ]
    },
    {
      "name": "fullReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "fullRelease",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-full-release.aar",
          "url": "kotlin-multiplatform-android-library-android-full-1.0.aar",
          "size": 2265,
          "sha512": "d294833d960347986008d48fb7705de2920f2486a3fae5c4acb7401b06c2d568a797ea3c61f1ae5c845dab9f60857facb415253b317cd362fa616b16c590f228",
          "sha256": "8543269660d3b5108c1cb735f3513743d383afdf176571cfd54dd6f9869188f4",
          "sha1": "704ed198d18d80adc2fcc2d2c7e1347335af344c",
          "md5": "4018d82b5bbdd40f314fff4e06a12dd3"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
