{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "kotlin-multiplatform-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-library-metadata-1.0.jar",
          "url": "kotlin-multiplatform-library-1.0.jar",
          "size": 1031,
          "sha512": "73537b3b0f94685b252f62be37781700b0157b4ab31c75f7b453c0ac95c757f145375d4d54218b37a74b0cd1ea67c02791361d69ae92e482695c152d9511da02",
          "sha256": "153aa4903707541a3e62ee9c8c6b4ad029c4146791452963649c90436ebf0230",
          "sha1": "5fd117ee704ce51cf5b6cd0a08a38ba36cd30e74",
          "md5": "190f9f1b8f79aa2e68325fc7a500a94a"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-js/1.0/kotlin-multiplatform-library-js-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-js",
        "version": "1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-js/1.0/kotlin-multiplatform-library-js-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-js",
        "version": "1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-jvm/1.0/kotlin-multiplatform-library-jvm-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-jvm/1.0/kotlin-multiplatform-library-jvm-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-linuxx64/1.0/kotlin-multiplatform-library-linuxx64-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-linuxx64",
        "version": "1.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-macosx64/1.0/kotlin-multiplatform-library-macosx64-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-macosx64",
        "version": "1.0"
      }
    }
  ]
}
