{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "android-demoReleaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "demoRelease",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-release.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-1.0.aar",
          "size": 2100,
          "sha512": "031fb487590d4f0336bf73f1546ed5faed8790c72ed55c1de6ae3b5c4110805821a8612c3cc037927207361dc53ab3115087867d882ba174825c8aaecabfe03e",
          "sha256": "ef15d2dd149a3bdcd45545fb947c14869ec3f9af3a8b56c40ccad57e76c696b3",
          "sha1": "d6b44b28b762d12f38515433b69dca5138da2d0b",
          "md5": "006ca0248394cade0cf573d20c1b345b"
        }
      ]
    },
    {
      "name": "android-demoReleaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "demoRelease",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-release.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-1.0.aar",
          "size": 2100,
          "sha512": "031fb487590d4f0336bf73f1546ed5faed8790c72ed55c1de6ae3b5c4110805821a8612c3cc037927207361dc53ab3115087867d882ba174825c8aaecabfe03e",
          "sha256": "ef15d2dd149a3bdcd45545fb947c14869ec3f9af3a8b56c40ccad57e76c696b3",
          "sha1": "d6b44b28b762d12f38515433b69dca5138da2d0b",
          "md5": "006ca0248394cade0cf573d20c1b345b"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
