{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "demoDebugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "demoDebug",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-debug-1.0.aar",
          "size": 2179,
          "sha512": "d09adc3ee9dba4ed713728e1475be62b0e6fe082fbc6f1caeb54acf50fb630a19c41b26dfb428556fffcd1f0d49095915d0880047109fc5c3d5b6d4a02a70949",
          "sha256": "309504588598e12e4fa3152a18c13e1bac235415fc529c2e1d08b92f2abde752",
          "sha1": "7071984d40acb1f2e511b1be3aadb031a1113660",
          "md5": "82bf395e70538757136222e2dc61691f"
        }
      ]
    },
    {
      "name": "demoDebugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "demoDebug",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-debug-1.0.aar",
          "size": 2179,
          "sha512": "d09adc3ee9dba4ed713728e1475be62b0e6fe082fbc6f1caeb54acf50fb630a19c41b26dfb428556fffcd1f0d49095915d0880047109fc5c3d5b6d4a02a70949",
          "sha256": "309504588598e12e4fa3152a18c13e1bac235415fc529c2e1d08b92f2abde752",
          "sha1": "7071984d40acb1f2e511b1be3aadb031a1113660",
          "md5": "82bf395e70538757136222e2dc61691f"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
