{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "demoReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "demoRelease",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-release.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-1.0.aar",
          "size": 2084,
          "sha512": "742078165ba917b3e823b90fb027718d6a08eb600e1acd4bfa9594f3a43b745c56a9cc2a73c1f432aae97fd7a0271159f8fe1aadb75a4432c14f074b5e986c5e",
          "sha256": "692ab48e93758b3eb33246ae38e49342cb6aabdeb2bcd07c9c657027186ab9d6",
          "sha1": "a36ba67a16d8b6f522713b9a0ec46bd5a28a8cb4",
          "md5": "c446ca95c20ceebb7fb553f432ca433a"
        }
      ]
    },
    {
      "name": "demoReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "demoRelease",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-release.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-1.0.aar",
          "size": 2084,
          "sha512": "742078165ba917b3e823b90fb027718d6a08eb600e1acd4bfa9594f3a43b745c56a9cc2a73c1f432aae97fd7a0271159f8fe1aadb75a4432c14f074b5e986c5e",
          "sha256": "692ab48e93758b3eb33246ae38e49342cb6aabdeb2bcd07c9c657027186ab9d6",
          "sha1": "a36ba67a16d8b6f522713b9a0ec46bd5a28a8cb4",
          "md5": "c446ca95c20ceebb7fb553f432ca433a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
