{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-library/1.0/kotlin-multiplatform-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-library-jvm-1.0.jar",
          "url": "kotlin-multiplatform-library-jvm-1.0.jar",
          "size": 1635,
          "sha512": "ab17ba6a94825060f66c280e5e29d0f278b4ae154628c13c78c80bd4333c654fe7e11d07ebc1955e039a9afef1e0e54bbdcc7706d8d064b45de5c6d4acdacc8d",
          "sha256": "42940a7f61267f536ef0946d83f1e229e56669bb168a894ff9031faa0e1df02a",
          "sha1": "a6b75ab5168e99ea0a7b29e896dcaa473b7ff083",
          "md5": "158946b92d47276bb252389fb0bc4e72"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-library-jvm-1.0.jar",
          "url": "kotlin-multiplatform-library-jvm-1.0.jar",
          "size": 1635,
          "sha512": "ab17ba6a94825060f66c280e5e29d0f278b4ae154628c13c78c80bd4333c654fe7e11d07ebc1955e039a9afef1e0e54bbdcc7706d8d064b45de5c6d4acdacc8d",
          "sha256": "42940a7f61267f536ef0946d83f1e229e56669bb168a894ff9031faa0e1df02a",
          "sha1": "a6b75ab5168e99ea0a7b29e896dcaa473b7ff083",
          "md5": "158946b92d47276bb252389fb0bc4e72"
        }
      ]
    }
  ]
}
