{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "kotlin-multiplatform-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-library-metadata-1.0.jar",
          "url": "kotlin-multiplatform-library-1.0.jar",
          "size": 2897,
          "sha512": "41e539be1a309e789fbb9ba71ae6cad79f7d37d5d492b3ecfd966b33d8b456e10020d3c10bf18c7d695004010bc21c139042b77a7a934643fb0fec64637c9393",
          "sha256": "cdd614bb4814c17060b408f7e1a8b9375b3ae93c9bc9ed5e219bf4df97e9fdab",
          "sha1": "5a7bf11aa9245cff216f8ab7819a6a63ecab25b3",
          "md5": "9f8cb8dd2cf2227a1671fc2453e67b7c"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-js/1.0/kotlin-multiplatform-library-js-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-js",
        "version": "1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-js/1.0/kotlin-multiplatform-library-js-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-js",
        "version": "1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-jvm/1.0/kotlin-multiplatform-library-jvm-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-jvm/1.0/kotlin-multiplatform-library-jvm-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-linuxx64/1.0/kotlin-multiplatform-library-linuxx64-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-linuxx64",
        "version": "1.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-macosx64/1.0/kotlin-multiplatform-library-macosx64-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-macosx64",
        "version": "1.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-macosx64/1.0/kotlin-multiplatform-library-macosx64-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-macosx64",
        "version": "1.0"
      }
    }
  ]
}
