{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-library/1.0/kotlin-multiplatform-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-library.klib",
          "url": "kotlin-multiplatform-library-macosx64-1.0.klib",
          "size": 5128,
          "sha512": "c1a013e32e75c88ca8ca5b7315925828222c905a468c79874b9b671d88587897a3690acbb620add8320ff6623385365189b973716ba8b3b928700fa333cfe7bf",
          "sha256": "b5dc36e47d0449c9dec6efdb96f8e633a5b3866970689f6e2f9da8b4d9f2dd49",
          "sha1": "29ed7977289d0ce79090a887de443a4b343818f6",
          "md5": "faf896fc6f615ff66192d1abef14f276"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-metadata/1.0/kotlin-multiplatform-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
