{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "fullDebugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "fullDebug",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-full-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-full-debug-1.0.aar",
          "size": 2179,
          "sha512": "6e3cdfb4ded110d4e7a08570051a74f1ba50a9cdbe665aa39f122e320d077f944bbe3b4680ddf5aac1e27329dbdfb40cd59aa00ba5e6c14b77c6297fe8e6250a",
          "sha256": "cbf1ac0434c7450499f7ccc90c09bd4fe997e1d0869ddb2fe5ab8be8320daf3c",
          "sha1": "3a48502e7f928d426797126ba767fd5ae721aefc",
          "md5": "002b3404c660e2b25b370a854e003770"
        }
      ]
    },
    {
      "name": "fullDebugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "fullDebug",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-full-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-full-debug-1.0.aar",
          "size": 2179,
          "sha512": "6e3cdfb4ded110d4e7a08570051a74f1ba50a9cdbe665aa39f122e320d077f944bbe3b4680ddf5aac1e27329dbdfb40cd59aa00ba5e6c14b77c6297fe8e6250a",
          "sha256": "cbf1ac0434c7450499f7ccc90c09bd4fe997e1d0869ddb2fe5ab8be8320daf3c",
          "sha1": "3a48502e7f928d426797126ba767fd5ae721aefc",
          "md5": "002b3404c660e2b25b370a854e003770"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
