{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-library/1.0/kotlin-multiplatform-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-library.klib",
          "url": "kotlin-multiplatform-library-macosx64-1.0.klib",
          "size": 5079,
          "sha512": "dc32805b962dbaa6da1388e4a42071398dd9c093416db261ba101699e10f89b5ad0a6917c8943cb60e09149e95018a71039fc4ccd7cab20c5104c6ec28f8d93a",
          "sha256": "dfd1e2f9085c398398ab1e24fbe14b7ee85c0b1b867db0a7f6c42b10f0061655",
          "sha1": "112689f6aaae7ca45bc251d4366a6e266971dcbb",
          "md5": "0e7f673c2440c54235d8cc3d425ac943"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-metadata/1.0/kotlin-multiplatform-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
