{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "android-fullDebugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "fullDebug",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-full-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-full-debug-1.0.aar",
          "size": 2194,
          "sha512": "5350742ada8d754cc6a2c5d9919e0aaa5b87a39eefee2e76e915b04bfeeb461255d867d932c4efbc0eba75cba21e0cf1a08a2772af8946115a1a244bba3bbf0a",
          "sha256": "c98095ae96e5d5835b4b032bfc53a26f852d71b7c7475b9249e985e4a5e5eaf5",
          "sha1": "5a2386911dc426cb5bc123bbb9b2c5067fcaa390",
          "md5": "5a6bf7331536ebb785dca1249a7c500c"
        }
      ]
    },
    {
      "name": "android-fullDebugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "fullDebug",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-full-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-full-debug-1.0.aar",
          "size": 2194,
          "sha512": "5350742ada8d754cc6a2c5d9919e0aaa5b87a39eefee2e76e915b04bfeeb461255d867d932c4efbc0eba75cba21e0cf1a08a2772af8946115a1a244bba3bbf0a",
          "sha256": "c98095ae96e5d5835b4b032bfc53a26f852d71b7c7475b9249e985e4a5e5eaf5",
          "sha1": "5a2386911dc426cb5bc123bbb9b2c5067fcaa390",
          "md5": "5a6bf7331536ebb785dca1249a7c500c"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
