{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library.klib",
          "url": "kotlin-multiplatform-android-library-macosx64-1.0.klib",
          "size": 5542,
          "sha512": "bce3c84062b24e26917a4128dd2a6f7fb783268a9192dbd58979cc1c0a62b2108ad39c5061d2bbe10b5e2933b4c756ac600523e01124b12cc609faeadf1b4e18",
          "sha256": "3b111cdfc6e4d02c0f886145a546e6c46d7d217a8d38dde7536e5f9e15780d97",
          "sha1": "0f3c0143267813bfa429e461f2c090cc09293a6b",
          "md5": "fb956a7ca319aea880120891d63b07a4"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-macosx64-1.0-metadata.jar",
          "url": "kotlin-multiplatform-android-library-macosx64-1.0-metadata.jar",
          "size": 261,
          "sha512": "d0a063a84c0245114b55052c8a6662dcd9c3c6233c662e68476df99101d8fc3506bc5a73a756a041605399809082c782867e4e13442144818323777a746f3931",
          "sha256": "ec97ee984a700ae22e7717be30f9e6d8c137e20f19046a1ef1a6b5e6d1733365",
          "sha1": "03c28e5357b7b544621ba03c7c8df4d5b94eaaf5",
          "md5": "bc87180c5c8fb0049442d0f487f4ed4a"
        }
      ]
    }
  ]
}
