{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-library/1.0/kotlin-multiplatform-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-library-js-1.0.jar",
          "url": "kotlin-multiplatform-library-js-1.0.jar",
          "size": 3791,
          "sha512": "6d7eeddb0566e73796b4ebe36640900df24d7f06a9fd1fab4aa5e960ea34e3818da1c06e1f5cc547ba9572d04e0cce41974cf079dc6d538291c5fb6068247d25",
          "sha256": "0687414bfecc964c3091aab3b74f8ef7926dbaad955271c2ef100b35729be673",
          "sha1": "96987a3a4cf89e242ce00741e5c475ee1567bed3",
          "md5": "808fd48b8c2b64a2761488990c96b5ce"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-library-js-1.0.jar",
          "url": "kotlin-multiplatform-library-js-1.0.jar",
          "size": 3791,
          "sha512": "6d7eeddb0566e73796b4ebe36640900df24d7f06a9fd1fab4aa5e960ea34e3818da1c06e1f5cc547ba9572d04e0cce41974cf079dc6d538291c5fb6068247d25",
          "sha256": "0687414bfecc964c3091aab3b74f8ef7926dbaad955271c2ef100b35729be673",
          "sha1": "96987a3a4cf89e242ce00741e5c475ee1567bed3",
          "md5": "808fd48b8c2b64a2761488990c96b5ce"
        }
      ]
    }
  ]
}
