{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "fullReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "full",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-full-release.aar",
          "url": "kotlin-multiplatform-android-library-android-full-1.0.aar",
          "size": 2311,
          "sha512": "e5242c48f6d6c20a8819af8cf0c90f6dedaf03233853b5a6b44bf3d78fce1d207433eb9a48ccac39479f7d0c97ff47c4e703764aa606a5f613f6f2308ff44c83",
          "sha256": "2b9dd3ef76c4c546211a16d1537e7df0cab7f49340d0c882a905d4c420c8499f",
          "sha1": "d6dd496eb8599a14d96b117456b38f40f5356278",
          "md5": "694e2a518e9798ff85a5e216fd863d6a"
        }
      ]
    },
    {
      "name": "fullReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "full",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-full-release.aar",
          "url": "kotlin-multiplatform-android-library-android-full-1.0.aar",
          "size": 2311,
          "sha512": "e5242c48f6d6c20a8819af8cf0c90f6dedaf03233853b5a6b44bf3d78fce1d207433eb9a48ccac39479f7d0c97ff47c4e703764aa606a5f613f6f2308ff44c83",
          "sha256": "2b9dd3ef76c4c546211a16d1537e7df0cab7f49340d0c882a905d4c420c8499f",
          "sha1": "d6dd496eb8599a14d96b117456b38f40f5356278",
          "md5": "694e2a518e9798ff85a5e216fd863d6a"
        }
      ]
    }
  ]
}
