{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-js-1.0.jar",
          "url": "kotlin-multiplatform-android-library-js-1.0.jar",
          "size": 4002,
          "sha512": "1a36678787fe1f12dd1a10f25e0a54566db6f9b66d2d8a8bdb915fc76e17aaf43e666fce711179f7d8067c891934839d38949c2301761b514f15040b7cc61347",
          "sha256": "b3e8694eb309df07a87e017bfe6c4539a894b1b6e8a4f473255517348d89ee32",
          "sha1": "6abd39e09f592f518560309e215b7e1157623fc7",
          "md5": "cf8be76656f8ae56765fe5d90ce7b2ea"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-js-1.0.jar",
          "url": "kotlin-multiplatform-android-library-js-1.0.jar",
          "size": 4002,
          "sha512": "1a36678787fe1f12dd1a10f25e0a54566db6f9b66d2d8a8bdb915fc76e17aaf43e666fce711179f7d8067c891934839d38949c2301761b514f15040b7cc61347",
          "sha256": "b3e8694eb309df07a87e017bfe6c4539a894b1b6e8a4f473255517348d89ee32",
          "sha1": "6abd39e09f592f518560309e215b7e1157623fc7",
          "md5": "cf8be76656f8ae56765fe5d90ce7b2ea"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
