{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "kotlin-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-library-1.0.jar",
          "url": "kotlin-library-1.0.jar",
          "size": 1584,
          "sha512": "0a3226549086a24c0d5a51a3b1d5f797f8c49050a3e5e9dbd24fa7cff47149e54b5340a48a5b2d145e05f02fa064958e99f2abd2d2d8b26af23da742a28d2b49",
          "sha256": "da7493510ed11ce52c2aaa73bc834618fbbcc8ceea0c0c37f4396a0f9dcfd7c1",
          "sha1": "59828ea026330ef117e4627b0dfce3ad20223dc6",
          "md5": "b62ee53fe148f8f7c28db5dff28883d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-library-1.0.jar",
          "url": "kotlin-library-1.0.jar",
          "size": 1584,
          "sha512": "0a3226549086a24c0d5a51a3b1d5f797f8c49050a3e5e9dbd24fa7cff47149e54b5340a48a5b2d145e05f02fa064958e99f2abd2d2d8b26af23da742a28d2b49",
          "sha256": "da7493510ed11ce52c2aaa73bc834618fbbcc8ceea0c0c37f4396a0f9dcfd7c1",
          "sha1": "59828ea026330ef117e4627b0dfce3ad20223dc6",
          "md5": "b62ee53fe148f8f7c28db5dff28883d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-library-1.0-sources.jar",
          "url": "kotlin-library-1.0-sources.jar",
          "size": 722,
          "sha512": "75bf3bd4b89bdbfbbbfa3a007056635cb92b9c3ac1a86c9bb98eeb6affb71128b0bd44a3a549e0719b56d7c6c121e4d9a3154419dbcb883c1df419ede50a613b",
          "sha256": "7b865958f0c65fd199f3483e7e194e285d950053ad479fd36da3543c75dcd224",
          "sha1": "c94da4655009742200a60e577b3d675ca5cffbff",
          "md5": "b9add99d10c49f6d2de3008155962fcf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-library-1.0-javadoc.jar",
          "url": "kotlin-library-1.0-javadoc.jar",
          "size": 261,
          "sha512": "78214cf7a5c8d131eea070ae1e1d399e8abed99852b13e1822bd07c0e604245d211b0c8f1944cf65f96c78cf612724363ba72c8a6c3441899f03924ed7ef4e37",
          "sha256": "27b6b9f0ffff5da92ef43741067d75aa929c6427ed3403105c4bc6d9e180c1e3",
          "sha1": "75efa6402c8c2496257eeec57b7fdab8ef2c1a63",
          "md5": "bdd5855930004f4406b6c48cc59c4ae6"
        }
      ]
    }
  ]
}
