{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "android-demoDebugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "demoDebug",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-debug-1.0.aar",
          "size": 2196,
          "sha512": "28f2feaa7ad4df3c1c83d4245473cafdbc9654f784f8eba03781488d408a74a180c52f39d1fd864318fab1e4caa83f614b107bc062b2cafd371f264bb5992643",
          "sha256": "a17f98ed9bed5e6cd2cb947bf83520eea9e977708b46ba355b4e5e74b2fe3a23",
          "sha1": "6f46553340b5e4c15209b480f80ff5b9562be1ed",
          "md5": "9727c05ed9695e7fd1dd23dbe8892e4d"
        }
      ]
    },
    {
      "name": "android-demoDebugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "demoDebug",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-debug-1.0.aar",
          "size": 2196,
          "sha512": "28f2feaa7ad4df3c1c83d4245473cafdbc9654f784f8eba03781488d408a74a180c52f39d1fd864318fab1e4caa83f614b107bc062b2cafd371f264bb5992643",
          "sha256": "a17f98ed9bed5e6cd2cb947bf83520eea9e977708b46ba355b4e5e74b2fe3a23",
          "sha1": "6f46553340b5e4c15209b480f80ff5b9562be1ed",
          "md5": "9727c05ed9695e7fd1dd23dbe8892e4d"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
