{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "demoDebugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "demo",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-debug-1.0.aar",
          "size": 2408,
          "sha512": "f925980b3288314e7c2d08e27025cc5507922f52208764223dd9a1a9f105ae225efd9694b362cfbd91317ef4589b9983ce3961c30d183045173ba729604cbf66",
          "sha256": "b395bf64543d6184f9d0f77c13136a8a46c64e38546ed855226f1868cdc30bd1",
          "sha1": "400a41360cec8212cc3e8a674bbae259a8e644d1",
          "md5": "8b1a5438eb7e3f0dbec71139c45c4931"
        }
      ]
    },
    {
      "name": "demoDebugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "demo",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-debug-1.0.aar",
          "size": 2408,
          "sha512": "f925980b3288314e7c2d08e27025cc5507922f52208764223dd9a1a9f105ae225efd9694b362cfbd91317ef4589b9983ce3961c30d183045173ba729604cbf66",
          "sha256": "b395bf64543d6184f9d0f77c13136a8a46c64e38546ed855226f1868cdc30bd1",
          "sha1": "400a41360cec8212cc3e8a674bbae259a8e644d1",
          "md5": "8b1a5438eb7e3f0dbec71139c45c4931"
        }
      ]
    }
  ]
}
