{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-library/1.0/kotlin-multiplatform-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "macosX64-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-library.klib",
          "url": "kotlin-multiplatform-library-macosx64-1.0.klib",
          "size": 5437,
          "sha512": "cf6097c614c452dbf4933242a80a3339a9361e2d77febb78a4d3543f68d7cc0ec370a392f8813ad4a36d42da6cc1245888ee204fcf327070abff9e08edc5ab3f",
          "sha256": "842613d67c34a9da15ede4cf465fc8420ac0b7439173086abcf443f72c45fd3f",
          "sha1": "082370a48c327a8104ba4809470b7eec729a8edc",
          "md5": "e27f4e03644ad77d47c9b07e0d21d4d3"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-metadata/1.0/kotlin-multiplatform-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
