{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "android-fullReleaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "fullRelease",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-full-release.aar",
          "url": "kotlin-multiplatform-android-library-android-full-1.0.aar",
          "size": 2100,
          "sha512": "3a1988390706b449d41d9b1c12471ed8fa4cfd876ec72b82991f4dbc6c40859d49f1a1cb3da6ad1e053ca5096b8e430e53a737bdd8d9b65b70b1a70a08751eff",
          "sha256": "ec40bf4e51487a673886baa48bf31ad4b77df2e1a8961c334638828418e6ee19",
          "sha1": "0785402e008ed74c66dba20872f16f77d8791b88",
          "md5": "fcc77bda4c0ee6ff6833e8f468b852a1"
        }
      ]
    },
    {
      "name": "android-fullReleaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "fullRelease",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-full-release.aar",
          "url": "kotlin-multiplatform-android-library-android-full-1.0.aar",
          "size": 2100,
          "sha512": "3a1988390706b449d41d9b1c12471ed8fa4cfd876ec72b82991f4dbc6c40859d49f1a1cb3da6ad1e053ca5096b8e430e53a737bdd8d9b65b70b1a70a08751eff",
          "sha256": "ec40bf4e51487a673886baa48bf31ad4b77df2e1a8961c334638828418e6ee19",
          "sha1": "0785402e008ed74c66dba20872f16f77d8791b88",
          "md5": "fcc77bda4c0ee6ff6833e8f468b852a1"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
