{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-js-1.0.jar",
          "url": "kotlin-multiplatform-android-library-js-1.0.jar",
          "size": 4002,
          "sha512": "843d8b60faa61097d94da6e38a022fb5ca115ed06eaebf033bc8d33823bd6b709beca11b6dcb74d2026734415a82e0df8c428cc3b7c6949a159cf8b4c1e0df16",
          "sha256": "a7de480825f21386cbe83bb9e745d6de9dd9c5bf5f1cdf834943a878d2bccc4e",
          "sha1": "6befc41cddf1140bb3bd6b671192ead64147bb02",
          "md5": "0c0e59624a75245d84eb11d3c6cb2cca"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-js-1.0.jar",
          "url": "kotlin-multiplatform-android-library-js-1.0.jar",
          "size": 4002,
          "sha512": "843d8b60faa61097d94da6e38a022fb5ca115ed06eaebf033bc8d33823bd6b709beca11b6dcb74d2026734415a82e0df8c428cc3b7c6949a159cf8b4c1e0df16",
          "sha256": "a7de480825f21386cbe83bb9e745d6de9dd9c5bf5f1cdf834943a878d2bccc4e",
          "sha1": "6befc41cddf1140bb3bd6b671192ead64147bb02",
          "md5": "0c0e59624a75245d84eb11d3c6cb2cca"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
