{
  "formatVersion": "1.1",
  "component": {
    "group": "example",
    "module": "kotlin-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-library-1.0.jar",
          "url": "kotlin-library-1.0.jar",
          "size": 1555,
          "sha512": "70d6c0772496fb79190ce9d1d13de3fa8260b080e61a61084e3a726b0c13d05dd36e910e269216b1b80c55c00678d7b5e73dfa9e68dc38ad74dbe032c1e63cc6",
          "sha256": "1edc5db277f1f5561aa102c3194641b9302c9c6b2599dc2a19f3153893ce856b",
          "sha1": "0a986dbc392a8f04cf97671a15666b049d78b7eb",
          "md5": "1731d3e723f5f3dce597ac34cfb43fc9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-library-1.0.jar",
          "url": "kotlin-library-1.0.jar",
          "size": 1555,
          "sha512": "70d6c0772496fb79190ce9d1d13de3fa8260b080e61a61084e3a726b0c13d05dd36e910e269216b1b80c55c00678d7b5e73dfa9e68dc38ad74dbe032c1e63cc6",
          "sha256": "1edc5db277f1f5561aa102c3194641b9302c9c6b2599dc2a19f3153893ce856b",
          "sha1": "0a986dbc392a8f04cf97671a15666b049d78b7eb",
          "md5": "1731d3e723f5f3dce597ac34cfb43fc9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-library-1.0-sources.jar",
          "url": "kotlin-library-1.0-sources.jar",
          "size": 722,
          "sha512": "59c34c3774024fe2073e27ecaa0da01d65088b889d1cada546e86cabd7c3703d81d2508e4cc1a1ffb10a61822e36cfd15c5f9422d61b27d73b352d3ed90bbc78",
          "sha256": "e236dc3fff55fa7d096ee9dd5904c7344483a1f221854ae6336a80ba59463818",
          "sha1": "8c51519460e4d5f9d6b29d99fe86c0c8a091c419",
          "md5": "522c7dd70306dc23109ab99c456d83a9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-library-1.0-javadoc.jar",
          "url": "kotlin-library-1.0-javadoc.jar",
          "size": 261,
          "sha512": "f89797aa31e5649019d249ff5a9662e06cc1fa81e9cc026fb6c904fd338939d3d68616b90034eb82e223be7a28d9bafaf504fa49e868477570f1b577f6ea5429",
          "sha256": "12403a5eb128d0bedc150d8d839a3644fdd2531b782dfb39bebe59609df24996",
          "sha1": "2a910294c9b09bdcd787ed369d4a245f0ea7bd53",
          "md5": "29148a78fc06ee9e338fa826ac521370"
        }
      ]
    }
  ]
}
