{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-library/1.0/kotlin-multiplatform-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "pr4n4lpg5ja6re27qc3piepc4q"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-RC"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-library.klib",
          "url": "kotlin-multiplatform-library-linuxx64-1.0.klib",
          "size": 5127,
          "sha512": "756f2eaa622a4d87e08cebbfc5639cd627b3a07c3032dce7be7a3c5c60d2f333e1267f41bdd588decccbab5ae32cd899161814db8a426ce25d1da49bea80036d",
          "sha256": "9a6e9de35cfe0a896a5f974fa1b18496825248a8a253e431cf171d6ead001ea0",
          "sha1": "d474aa444d2dac761df4683edba8d6d0a064f0ea",
          "md5": "1e0ca11151400c48fd41383df633036c"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-library-metadata/1.0/kotlin-multiplatform-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
