{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "demoReleaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "demoRelease",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-release.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-1.0.aar",
          "size": 2261,
          "sha512": "7a32f1ed173a562976e914a6ac060caa23f653dd738fc44dc84fb86f722063faaf9f0d3718885501168d15503b2128b1a22a29cf5e93875c4c076d7b18fc31c4",
          "sha256": "bd941d94ea1bb503154210cc0dd000b0341f18b6921c12accf5e14ac15c6dae8",
          "sha1": "b462820a36c5158b6ea409b4d4cf0b36b14271e8",
          "md5": "c43e048c0c0da449e431d28d81023e70"
        }
      ]
    },
    {
      "name": "demoReleaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "demoRelease",
        "org.gradle.example.my-own-flavor": "demo",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-demo-release.aar",
          "url": "kotlin-multiplatform-android-library-android-demo-1.0.aar",
          "size": 2261,
          "sha512": "7a32f1ed173a562976e914a6ac060caa23f653dd738fc44dc84fb86f722063faaf9f0d3718885501168d15503b2128b1a22a29cf5e93875c4c076d7b18fc31c4",
          "sha256": "bd941d94ea1bb503154210cc0dd000b0341f18b6921c12accf5e14ac15c6dae8",
          "sha1": "b462820a36c5158b6ea409b4d4cf0b36b14271e8",
          "md5": "c43e048c0c0da449e431d28d81023e70"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotlin-multiplatform-android-library-metadata/1.0/kotlin-multiplatform-android-library-metadata-1.0.module",
        "group": "example",
        "module": "kotlin-multiplatform-android-library-metadata",
        "version": "1.0"
      }
    }
  ]
}
