{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-multiplatform-android-library/1.0/kotlin-multiplatform-android-library-1.0.module",
    "group": "example",
    "module": "kotlin-multiplatform-android-library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.7-20220815220000+0000"
    }
  },
  "variants": [
    {
      "name": "fullDebugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "full",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-full-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-full-debug-1.0.aar",
          "size": 2406,
          "sha512": "428ca6f5ac6b76a8ef1d18f2ecb17c7d098d75d8ee758e36c11252bda7b451ac418cafb7516284f24ddad75687b698f0a0697fc1c0d352d9c2dee57da1f9067f",
          "sha256": "c2a42d04a6a21c1bfb2e33f3cb7dbda989d526ef62b05bf1e3347192111ca04b",
          "sha1": "1bba31676d10c11737872690f94af07edb02b90d",
          "md5": "4ff380e8f5a0047794f67350954d4fbe"
        }
      ]
    },
    {
      "name": "fullDebugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:org.gradle.example.my-own-flavor": "full",
        "org.gradle.category": "library",
        "org.gradle.example.my-own-flavor": "full",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-multiplatform-android-library-full-debug.aar",
          "url": "kotlin-multiplatform-android-library-android-full-debug-1.0.aar",
          "size": 2406,
          "sha512": "428ca6f5ac6b76a8ef1d18f2ecb17c7d098d75d8ee758e36c11252bda7b451ac418cafb7516284f24ddad75687b698f0a0697fc1c0d352d9c2dee57da1f9067f",
          "sha256": "c2a42d04a6a21c1bfb2e33f3cb7dbda989d526ef62b05bf1e3347192111ca04b",
          "sha1": "1bba31676d10c11737872690f94af07edb02b90d",
          "md5": "4ff380e8f5a0047794f67350954d4fbe"
        }
      ]
    }
  ]
}
