// Copyright 2018 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[about_manual]]
= The User Manual

== Content

The Gradle User Manual is broken down into the following sections:

<<introduction.adoc#getting_started,Quick Start>> :: Get up and running by installing Gradle.
<<command_line_interface.adoc#command_line_interface,Running Gradle Builds>> :: Use Gradle to build your project.
<<build_lifecycle.adoc#build_lifecycle,Authoring Gradle Builds>> :: Develop tasks and plugins to customize your build.
<<building_java_projects.adoc#building_java_projects,Authoring JVM Builds>> :: Use Gradle with your Java project.
<<dependency_management_terminology.adoc#dependency_management_terminology,Working with Dependencies>> :: Add dependencies to your build.
<<performance.adoc#performance_gradle,Optimizing Build Times>> :: Use a cache to optimize your build.
<<jenkins.adoc#build_jenkins,Gradle on CI>> :: Gradle integration with popular continuous integration (CI) servers.

== Reference

. Gradle API link:{javadocPath}/index.html[Javadocs]
. Gradle's link:{groovyDslPath}/index.html[Groovy DSL]
. Gradle's link:{kotlinDslPath}/index.html[Kotlin DSL]
. Gradle <<plugin_reference#plugin_reference,Core Plugins>>
