// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[build_announcements_plugin]]
= The Build Announcements Plugin


[NOTE]
====

The build announcements plugin is currently <<feature_lifecycle.adoc#feature_lifecycle,incubating>>. Please be aware that the DSL and other configuration may change in later Gradle versions.

====

The build announcements plugin uses the <<announce_plugin.adoc#announce_plugin,announce>> plugin to send local announcements on important events in the build.


[[sec:build_announcements_usage]]
== Usage

To use the build announcements plugin, include the following in your build script:

=== Example: Using the build announcements plugin

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/announce/build.gradle[tag=use-build-announcements-plugin]
----

That's it. If you want to tweak where the announcements go, you can configure the <<announce_plugin.adoc#announce_plugin,announce>> plugin to change the local announcer.

You can also apply the plugin from an init script:

=== Example: Using the build announcements plugin from an init script

[source.multi-language-sample,groovy]
.init.gradle
----
include::{samplesPath}/announce/init.gradle[]
----
