// Copyright 2019 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[compatibility]]
= Compatibility Matrix
The sections below describe Gradle's compatibility with several integrations. Other versions not listed here may or may not work.

== Java
A Java version between 8 and 16 is required to execute Gradle. Java 17 and later versions are not yet supported.

Java 6 and 7 can still be used for <<building_java_projects.adoc#sec:java_cross_compilation,compilation and forked test execution>>.

Any supported version of Java can be used for compile or test.

For older Gradle versions, please see the table below which Java version is supported by which Gradle release.


.Java Compatibility
|===
|Java version|First Gradle version to support it
|8|2.0
|9|4.3
|10|4.7
|11|5.0
|12|5.4
|13|6.0
|14|6.3
|15|6.7
|16|7.0
|===

== Kotlin
Gradle is tested with Kotlin 1.3.72 through 1.5.21.

== Groovy
Gradle is tested with Groovy 1.5.8 through 3.0.8.

== Android
Gradle is tested with Android Gradle Plugin 4.1, 4.2, 7.0 and 7.1. Alpha and beta versions may or may not work.
