// Copyright 2019 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[compatibility]]
= Compatibility Matrix
The sections below describe Gradle's compatibility with several integrations. Other versions not listed here may or may not work.

== Java
A Java version between 8 and 14 is required to execute Gradle. Java 15 and later versions are not yet supported.

Java 6 and 7 can still be used for <<building_java_projects.adoc#sec:java_cross_compilation,compilation and forked test execution>>.

Any supported version of Java can be used for compile or test.

== Kotlin
Gradle is tested with Kotlin 1.3.21 through 1.3.71.

== Groovy
Gradle is tested with Groovy 1.5.8 through 2.5.10.

== Android
Gradle is tested with Android Gradle Plugin 3.4, 3.5 and 3.6.
