// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[custom_tasks]]
== Writing Custom Task Classes

Gradle supports two types of task. One such type is the simple task, where you define the task with an action closure. We have seen these in <<tutorial_using_tasks>>. For this type of task, the action closure determines the behaviour of the task. This type of task is good for implementing one-off tasks in your build script.

The other type of task is the enhanced task, where the behaviour is built into the task, and the task provides some properties which you can use to configure the behaviour. We have seen these in <<more_about_tasks>>. Most Gradle plugins use enhanced tasks. With enhanced tasks, you don't need to implement the task behaviour as you do with simple tasks. You simply declare the task and configure the task using its properties. In this way, enhanced tasks let you reuse a piece of behaviour in many different places, possibly across different builds.

The behaviour and properties of an enhanced task is defined by the task's class. When you declare an enhanced task, you specify the type, or class of the task.

Implementing your own custom task class in Gradle is easy. You can implement a custom task class in pretty much any language you like, provided it ends up compiled to bytecode. In our examples, we are going to use Groovy as the implementation language, but you could use, for example, Java or Scala. In general, using Groovy is the easiest option, because the Gradle API is designed to work well with Groovy.


[[sec:packaging_a_task_class]]
=== Packaging a task class

There are several places where you can put the source for the task class.

Build script::You can include the task class directly in the build script. This has the benefit that the task class is automatically compiled and included in the classpath of the build script without you having to do anything. However, the task class is not visible outside the build script, and so you cannot reuse the task class outside the build script it is defined in.`buildSrc` project::You can put the source for the task class in the `<replaceable>rootProjectDir</replaceable>/buildSrc/src/main/groovy` directory. Gradle will take care of compiling and testing the task class and making it available on the classpath of the build script. The task class is visible to every build script used by the build. However, it is not visible outside the build, and so you cannot reuse the task class outside the build it is defined in. Using the `buildSrc` project approach separates the task declaration - that is, what the task should do - from the task implementation - that is, how the task does it.

See <<organizing_build_logic>> for more details about the `buildSrc` project.Standalone project::You can create a separate project for your task class. This project produces and publishes a JAR which you can then use in multiple builds and share with others. Generally, this JAR might include some custom plugins, or bundle several related task classes into a single library. Or some combination of the two.

In our examples, we will start with the task class in the build script, to keep things simple. Then we will look at creating a standalone project.

[[sec:writing_a_simple_task_class]]
=== Writing a simple task class

To implement a custom task class, you extend api:org.gradle.api.DefaultTask[].

++++
<sample id="customTask" dir="userguide/tasks/customTask" title="Defining a custom task">
            <sourcefile file="build.gradle" snippet="define-task"/>
        </sample>
++++

This task doesn't do anything useful, so let's add some behaviour. To do so, we add a method to the task and mark it with the api:org.gradle.api.tasks.TaskAction[] annotation. Gradle will call the method when the task executes. You don't have to use a method to define the behaviour for the task. You could, for instance, call `doFirst()` or `doLast()` with a closure in the task constructor to add behaviour.

++++
<sample id="customTaskWithAction" dir="userguide/tasks/customTask" title="A hello world task">
            <sourcefile file="build.gradle" snippet="add-action"/>
            <output args="-q hello"/>
        </sample>
++++

Let's add a property to the task, so we can customize it. Tasks are simply POGOs, and when you declare a task, you can set the properties or call methods on the task object. Here we add a `greeting` property, and set the value when we declare the `greeting` task.

++++
<sample id="customTaskWithProperty" dir="userguide/tasks/customTaskWithProperty" title="A customizable hello world task">
            <sourcefile file="build.gradle" snippet="add-property"/>
            <output args="-q hello greeting"/>
        </sample>
++++


[[sec:custom_tasks_standalone_project]]
=== A standalone project

Now we will move our task to a standalone project, so we can publish it and share it with others. This project is simply a Groovy project that produces a JAR containing the task class. Here is a simple build script for the project. It applies the Groovy plugin, and adds the Gradle API as a compile-time dependency.

++++
<sample id="customTaskStandalone" dir="customPlugin/plugin" title="A build for a custom task" includeLocation="true">
            <sourcefile file="build.gradle" snippet="use-plugin"/>
        </sample>
++++

We just follow the convention for where the source for the task class should go.

++++
<sample id="customTaskStandalone" dir="customPlugin/plugin" title="A custom task">
            <sourcefile file="src/main/groovy/org/gradle/GreetingTask.groovy"/>
        </sample>
++++


[[sec:using_your_task_class_in_another_project]]
==== Using your task class in another project

To use a task class in a build script, you need to add the class to the build script's classpath. To do this, you use a `buildscript { }` block, as described in <<sec:build_script_external_dependencies>>. The following example shows how you might do this when the JAR containing the task class has been published to a local repository:

++++
<sample id="usingCustomTask" dir="customPlugin/consumer" title="Using a custom task in another project">
                <test args="-p../plugin uploadArchives"/>
                <test args="greeting"/>
                <sourcefile file="build.gradle" snippet="use-task"/>
            </sample>
++++


[[sec:writing_tests_for_your_task_class]]
==== Writing tests for your task class

You can use the api:org.gradle.testfixtures.ProjectBuilder[] class to create api:org.gradle.api.Project[] instances to use when you test your task class.

++++
<sample id="customTaskStandalone" dir="customPlugin/plugin" title="Testing a custom task">
                <sourcefile file="src/test/groovy/org/gradle/GreetingTaskTest.groovy" snippet="test-task"/>
            </sample>
++++


[[incremental_tasks]]
=== Incremental tasks

NOTE:  Incremental tasks are an <<feature_lifecycle,incubating>> feature.  Since the introduction of the implementation described above (early in the Gradle 1.6 release cycle), discussions within the Gradle community have produced superior ideas for exposing the information about changes to task implementors to what is described below. As such, the API for this feature will almost certainly change in upcoming releases. However, please do experiment with the current implementation and share your experiences with the Gradle community.  The feature incubation process, which is part of the Gradle feature lifecycle (see <<feature_lifecycle>>), exists for this purpose of ensuring high quality final implementations through incorporation of early user feedback. 

With Gradle, it's very simple to implement a task that gets skipped when all of it's inputs and outputs are up to date (see <<sec:up_to_date_checks>>). However, there are times when only a few input files have changed since the last execution, and you'd like to avoid reprocessing all of the unchanged inputs. This can be particularly useful for a transformer task, that converts input files to output files on a 1:1 basis.

If you'd like to optimise your build so that only out-of-date inputs are processed, you can do so with an _incremental task_.


[[sec:implementing_an_incremental_task]]
==== Implementing an incremental task

For a task to process inputs incrementally, that task must contain an _incremental task action_. This is a task action method that contains a single api:org.gradle.api.tasks.incremental.IncrementalTaskInputs[] parameter, which indicates to Gradle that the action will process the changed inputs only.

The incremental task action may supply an api:org.gradle.api.tasks.incremental.IncrementalTaskInputs#outOfDate[] action for processing any input file that is out-of-date, and a api:org.gradle.api.tasks.incremental.IncrementalTaskInputs#removed[] action that executes for any input file that has been removed since the previous execution.

++++
<sample id="taskDefinition" dir="userguide/tasks/incrementalTask" title="Defining an incremental task action" includeLocation="true">
                <sourcefile file="build.gradle" snippet="incremental-task"/>
            </sample>
++++

If for some reason the task is not run incremental, e.g. by running with --rerun-tasks, only the outOfDate action is executed, even if there where deleted input files. You should consider handling this case at the beginning, as is done in the example above.

For a simple transformer task like this, the task action simply needs to generate output files for any out-of-date inputs, and delete output files for any removed inputs.

A task may only contain a single incremental task action.

[[sec:which_inputs_are_considered_out_of_date]]
==== Which inputs are considered out of date?

When Gradle has history of a previous task execution, and the only changes to the task execution context since that execution are to input files, then Gradle is able to determine which input files need to be reprocessed by the task. In this case, the api:org.gradle.api.tasks.incremental.IncrementalTaskInputs#outOfDate[] action will be executed for any input file that was _added_ or _modified_, and the api:org.gradle.api.tasks.incremental.IncrementalTaskInputs#removed[] action will be executed for any _removed_ input file.

However, there are many cases where Gradle is unable to determine which input files need to be reprocessed. Examples include:

* There is no history available from a previous execution.
* You are building with a different version of Gradle. Currently, Gradle does not use task history from a different version.
* An `upToDateWhen` criteria added to the task returns `false`.
* An input property has changed since the previous execution.
* One or more output files have changed since the previous execution.

In any of these cases, Gradle will consider all of the input files to be `outOfDate`. The api:org.gradle.api.tasks.incremental.IncrementalTaskInputs#outOfDate[] action will be executed for every input file, and the api:org.gradle.api.tasks.incremental.IncrementalTaskInputs#removed[] action will not be executed at all.

You can check if Gradle was able to determine the incremental changes to input files with api:org.gradle.api.tasks.incremental.IncrementalTaskInputs#isIncremental[].

[[sec:an_incremental_task_in_action]]
==== An incremental task in action

Given the incremental task implementation <<taskDefinition,above>>, we can explore the various change scenarios by example. Note that the various mutation tasks ('updateInputs', 'removeInput', etc) are only present for demonstration purposes: these would not normally be part of your build script.

First, consider the `IncrementalReverseTask` executed against a set of inputs for the first time. In this case, all inputs will be considered “out of date”:

++++
<sample id="incrementalTaskFirstRun" dir="userguide/tasks/incrementalTask" title="Running the incremental task for the first time">
                <sourcefile file="build.gradle" snippet="reverse"/>
                <layout after="originalInputs">
                    build.gradle
                    inputs/
                    inputs/1.txt
                    inputs/2.txt
                    inputs/3.txt
                </layout>
                <output args="-q incrementalReverse" ignoreLineOrder="true"/>
            </sample>
++++

Naturally when the task is executed again with no changes, then the entire task is up to date and no files are reported to the task action:

++++
<sample id="incrementalTaskNoChange" dir="userguide/tasks/incrementalTask" title="Running the incremental task with unchanged inputs">
                <test args="-q originalInputs incrementalReverse"/>
                <output args="-q incrementalReverse"/>
            </sample>
++++

When an input file is modified in some way or a new input file is added, then re-executing the task results in those files being reported to api:org.gradle.api.tasks.incremental.IncrementalTaskInputs#outOfDate[]:

++++
<sample id="incrementalTaskUpdatedInputs" dir="userguide/tasks/incrementalTask" title="Running the incremental task with updated input files">
                <sourcefile file="build.gradle" snippet="updated-inputs"/>
                <test args="-q originalInputs incrementalReverse"/>
                <output args="-q updateInputs incrementalReverse" ignoreLineOrder="true"/>
            </sample>
++++

When an existing input file is removed, then re-executing the task results in that file being reported to api:org.gradle.api.tasks.incremental.IncrementalTaskInputs#removed[]:

++++
<sample id="incrementalTaskRemovedInput" dir="userguide/tasks/incrementalTask" title="Running the incremental task with an input file removed">
                <sourcefile file="build.gradle" snippet="removed-input"/>
                <test args="-q originalInputs incrementalReverse"/>
                <output args="-q removeInput incrementalReverse" ignoreLineOrder="true"/>
            </sample>
++++

When an output file is deleted (or modified), then Gradle is unable to determine which input files are out of date. In this case, _all_ input files are reported to the api:org.gradle.api.tasks.incremental.IncrementalTaskInputs#outOfDate[] action, and no input files are reported to the api:org.gradle.api.tasks.incremental.IncrementalTaskInputs#removed[] action:

++++
<sample id="incrementalTaskRemovedOutput" dir="userguide/tasks/incrementalTask" title="Running the incremental task with an output file removed">
                <sourcefile file="build.gradle" snippet="removed-output"/>
                <test args="-q originalInputs incrementalReverse"/>
                <output args="-q removeOutput incrementalReverse" ignoreLineOrder="true"/>
            </sample>
++++

When a task input property is modified, Gradle is unable to determine how this property impacted the task outputs, so all input files are assumed to be out of date. So similar to the changed output file example, _all_ input files are reported to the api:org.gradle.api.tasks.incremental.IncrementalTaskInputs#outOfDate[] action, and no input files are reported to the api:org.gradle.api.tasks.incremental.IncrementalTaskInputs#removed[] action:

++++
<sample id="incrementalTaskChangedProperty" dir="userguide/tasks/incrementalTask" title="Running the incremental task with an input property changed">
                <test args="-q originalInputs incrementalReverse"/>
                <output args="-q -PtaskInputProperty=changed incrementalReverse" ignoreLineOrder="true"/>
            </sample>
++++
