// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[java_library_distribution_plugin]]
= The Java Library Distribution Plugin


[NOTE]
====

The Java library distribution plugin is currently <<feature_lifecycle.adoc#feature_lifecycle,incubating>>. Please be aware that the DSL and other configuration may change in later Gradle versions.

====

The Java library distribution plugin adds support for building a distribution ZIP for a Java library. The distribution contains the JAR file for the library and its dependencies.


[[sec:java_library_distribution_usage]]
== Usage

To use the Java library distribution plugin, include the following in your build script:

=== Example: Using the Java library distribution plugin

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/userguide/javaLibraryDistribution/build.gradle[tag=use-plugin]
----

To define the name for the distribution you have to set the `baseName` property as shown below:

=== Example: Configure the distribution name

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/userguide/javaLibraryDistribution/build.gradle[tag=name-conf]
----

The plugin builds a distribution for your library. The distribution will package up the runtime dependencies of the library. All files stored in `src/main/dist` will be added to the root of the archive distribution. You can run “`gradle distZip`” to create a ZIP file containing the distribution.

[[sec:java_library_distribution_tasks]]
== Tasks

The Java library distribution plugin adds the following tasks to the project.

`distZip` — link:{groovyDslPath}/org.gradle.api.tasks.bundling.Zip.html[Zip]::
_Depends on_: `jar`
+
Creates a full distribution ZIP archive including runtime libraries.


[[java_library_distribution_resources]]
== Including other resources in the distribution

All of the files from the `src/dist` directory are copied. To include any static files in the distribution, simply arrange them in the `src/dist` directory, or add them to the content of the distribution.

=== Example: Include files in the distribution

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/userguide/javaLibraryDistribution/build.gradle[tag=custom-distribution]
----
