// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[maven_plugin]]
= Maven Plugin


[NOTE]
====

This chapter describes deploying artifacts to Maven repositories using the _original_ publishing mechanism available in Gradle 1.0: in Gradle 1.3 a new mechanism for publishing was introduced. This new mechanism introduces some new concepts and features that make Gradle publishing even more powerful and is now the preferred option for publishing artifacts.

You can read about the new publishing plugins in <<publishing_ivy.adoc#publishing_ivy,Publishing Ivy>> and <<publishing_maven.adoc#publishing_maven,Publishing Maven>>.

====

The Maven plugin adds support for deploying artifacts to Maven repositories.


[[sec:maven_usage]]
== Usage

To use the Maven plugin, include the following in your build script:

=== Example: Using the Maven plugin

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/maven/quickstart/build.gradle[tag=use-plugin]
----


[[sec:maven_tasks]]
== Tasks

The Maven plugin defines the following tasks:

`install` — link:{groovyDslPath}/org.gradle.api.tasks.Upload.html[Upload]::
_Depends on_: All tasks that build the associated archives.
+
Installs the associated artifacts to the local Maven cache, including Maven metadata generation. By default the install task is associated with the `archives` configuration. This configuration has by default only the default jar as an element. To learn more about installing to the local repository, see <<#sub:installing_to_the_local_repository,Installing to the local repository>>


[[sec:maven_dependency_management]]
== Dependency management

The Maven plugin does not define any dependency configurations.

[[sec:maven_convention_properties]]
== Convention properties

The Maven plugin defines the following convention properties:

`mavenPomDir` — `File`::
The directory where the generated POMs are written to. _Default value_: `__${project.buildDir}__/poms`

`conf2ScopeMappings` — `link:{javadocPath}/org/gradle/api/artifacts/maven/Conf2ScopeMappingContainer.html[Conf2ScopeMappingContainer]`::
Instructions for mapping Gradle configurations to Maven scopes. See <<#sub:dependency_mapping,Dependency mapping>>.

These properties are provided by a link:{groovyDslPath}/org.gradle.api.plugins.MavenPluginConvention.html[MavenPluginConvention] convention object.

[[sec:maven_convention_methods]]
== Convention methods

The maven plugin provides a factory method for creating a POM. This is useful if you need a POM without the context of uploading to a Maven repo.

=== Example: Creating a standalone pom.

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/maven/pomGeneration/build.gradle[tag=new-pom]
----

Amongst other things, Gradle supports the same builder syntax as polyglot Maven. To learn more about the Gradle Maven POM object, see link:{javadocPath}/org/gradle/api/artifacts/maven/MavenPom.html[MavenPom]. See also: link:{groovyDslPath}/org.gradle.api.plugins.MavenPluginConvention.html[MavenPluginConvention]

[[uploading_to_maven_repositories]]
== Interacting with Maven repositories


[[sec:maven_upload_intro]]
=== Introduction

With Gradle you can deploy to remote Maven repositories or install to your local Maven repository. This includes all Maven metadata manipulation and works also for Maven snapshots. In fact, Gradle's deployment is 100 percent Maven compatible as we use the native Maven Ant tasks under the hood.

Deploying to a Maven repository is only half the fun if you don't have a POM. Fortunately Gradle can generate this POM for you using the dependency information it has.

[[sec:deploying_to_a_maven_repository]]
=== Deploying to a Maven repository

Let's assume your project produces just the default jar file. Now you want to deploy this jar file to a remote Maven repository.

=== Example: Upload of file to remote Maven repository

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/userguide/artifacts/maven/build.gradle[tag=upload-file]
----

That is all. Calling the `uploadArchives` task will generate the POM and deploys the artifact and the POM to the specified repository.

There is more work to do if you need support for protocols other than `file`. In this case the native Maven code we delegate to needs additional libraries. Which libraries are needed depends on what protocol you plan to use. The available protocols and the corresponding libraries are listed in <<#wagonLibs,Protocol JARs for Maven deployment>> (those libraries have transitive dependencies which have transitive dependencies).footnote:[It is planned for a future release to provide out-of-the-box support for this] For example, to use the ssh protocol you can do:

=== Example: Upload of file via SSH

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/userguide/artifacts/maven/build.gradle[tag=upload-with-ssh]
----

There are many configuration options for the Maven deployer. The configuration is done via a Groovy builder. All the elements of this tree are Java beans. To configure the simple attributes you pass a map to the bean elements. To add bean elements to its parent, you use a closure. In the example above _repository_ and _authentication_ are such bean elements. <<#deployerConfig,Configuration elements of Maven deployer>> lists the available bean elements and a link to the Javadoc of the corresponding class. In the Javadoc you can see the possible attributes you can set for a particular element.

In Maven you can define repositories and optionally snapshot repositories. If no snapshot repository is defined, releases and snapshots are both deployed to the `repository` element. Otherwise snapshots are deployed to the `snapshotRepository` element.

[[wagonLibs]]
.Protocol jars for Maven deployment
[%header%autowidth,compact]
|===
| Protocol | Library

| http
| org.apache.maven.wagon:wagon-http:2.2

| ssh
| org.apache.maven.wagon:wagon-ssh:2.2

| ssh-external
| org.apache.maven.wagon:wagon-ssh-external:2.2

| ftp
| org.apache.maven.wagon:wagon-ftp:2.2

| webdav
| org.apache.maven.wagon:wagon-webdav:1.0-beta-2

| file
| -
|===

[[deployerConfig]]
.Configuration elements of the MavenDeployer
[%header%autowidth,compact]
|===
| Element | Javadoc

| root
| link:{javadocPath}/org/gradle/api/artifacts/maven/MavenDeployer.html[MavenDeployer]

| repository
| http://www.docjar.com/docs/api/org/apache/maven/artifact/ant/RemoteRepository.html[org.apache.maven.artifact.ant.RemoteRepository]

| authentication
| http://www.docjar.com/docs/api/org/apache/maven/artifact/ant/Authentication.html[org.apache.maven.artifact.ant.Authentication]

| releases
| http://www.docjar.com/docs/api/org/apache/maven/artifact/ant/RepositoryPolicy.html[org.apache.maven.artifact.ant.RepositoryPolicy]

| snapshots
| http://www.docjar.com/docs/api/org/apache/maven/artifact/ant/RepositoryPolicy.html[org.apache.maven.artifact.ant.RepositoryPolicy]

| proxy
| http://www.docjar.com/docs/api/org/apache/maven/artifact/ant/Proxy.html[org.apache.maven.artifact.ant.Proxy]

| snapshotRepository
| http://www.docjar.com/docs/api/org/apache/maven/artifact/ant/RemoteRepository.html[org.apache.maven.artifact.ant.RemoteRepository]
|===


[[sub:installing_to_the_local_repository]]
=== Installing to the local repository

The Maven plugin adds an `install` task to your project. This task depends on all the archives task of the `archives` configuration. It installs those archives to your local Maven repository. If the default location for the local repository is redefined in a Maven `settings.xml`, this is considered by this task.

[[sec:maven_pom_generation]]
=== Maven POM generation

When deploying an artifact to a Maven repository, Gradle automatically generates a POM for it. The `groupId`, `artifactId`, `version` and `packaging` elements used for the POM default to the values shown in the table below. The `dependency` elements are created from the project's dependency declarations.

.Default Values for Maven POM generation
[%header%autowidth,compact]
|===
| Maven Element | Default Value

| groupId
| project.group

| artifactId
| uploadTask.repositories.mavenDeployer.pom.artifactId (if set) or archiveTask.baseName.

| version
| project.version

| packaging
| archiveTask.extension
|===

Here, `uploadTask` and `archiveTask` refer to the tasks used for uploading and generating the archive, respectively (for example `uploadArchives` and `jar`). `archiveTask.baseName` defaults to `project.archivesBaseName` which in turn defaults to `project.name`.

[NOTE]
====

When you set the “`archiveTask.baseName`” property to a value other than the default, you'll also have to set `uploadTask.repositories.mavenDeployer.pom.artifactId` to the same value. Otherwise, the project at hand may be referenced with the wrong artifact ID from generated POMs for other projects in the same build.

====

Generated POMs can be found in `&lt;buildDir&gt;/poms`. They can be further customized via the link:{javadocPath}/org/gradle/api/artifacts/maven/MavenPom.html[MavenPom] API. For example, you might want the artifact deployed to the Maven repository to have a different version or name than the artifact generated by Gradle. To customize these you can do:

=== Example: Customization of pom

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/userguide/artifacts/maven/build.gradle[tag=customize-pom]
----

To add additional content to the POM, the `pom.project` builder can be used. With this builder, any element listed in the http://maven.apache.org/pom.html[Maven POM reference] can be added.

=== Example: Builder style customization of pom

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/userguide/artifacts/maven/build.gradle[tag=builder]
----

Note: `groupId`, `artifactId`, `version`, and `packaging` should always be set directly on the `pom` object.

=== Example: Modifying auto-generated content

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/maven/pomGeneration/build.gradle[tag=when-configured]
----

If you have more than one artifact to publish, things work a little bit differently. See <<#sub:multiple_artifacts_per_project,Multiple artifacts per project>>.

To customize the settings for the Maven installer (see <<#sub:installing_to_the_local_repository,Installing to the local repository>>), you can do:

=== Example: Customization of Maven installer

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/userguide/artifacts/maven/build.gradle[tag=customize-installer]
----


[[sub:multiple_artifacts_per_project]]
==== Multiple artifacts per project

Maven can only deal with one artifact per project. This is reflected in the structure of the Maven POM. We think there are many situations where it makes sense to have more than one artifact per project. In such a case you need to generate multiple POMs. In such a case you have to explicitly declare each artifact you want to publish to a Maven repository. The link:{javadocPath}/org/gradle/api/artifacts/maven/MavenDeployer.html[MavenDeployer] and the MavenInstaller both provide an API for this:

=== Example: Generation of multiple poms

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/userguide/artifacts/maven/build.gradle[tag=multiple-poms]
----

You need to declare a filter for each artifact you want to publish. This filter defines a boolean expression for which Gradle artifact it accepts. Each filter has a POM associated with it which you can configure. To learn more about this have a look at link:{javadocPath}/org/gradle/api/artifacts/maven/PomFilterContainer.html[PomFilterContainer] and its associated classes.

[[sub:dependency_mapping]]
==== Dependency mapping

The Maven plugin configures the default mapping between the Gradle configurations added by the Java and War plugin and the Maven scopes. Most of the time you don't need to touch this and you can safely skip this section. The mapping works like the following. You can map a configuration to one and only one scope. Different configurations can be mapped to one or different scopes. You can also assign a priority to a particular configuration-to-scope mapping. Have a look at link:{javadocPath}/org/gradle/api/artifacts/maven/Conf2ScopeMappingContainer.html[Conf2ScopeMappingContainer] to learn more. To access the mapping configuration you can say:

=== Example: Accessing a mapping configuration

[source.multi-language-sample,groovy]
.build.gradle
----
include::{samplesPath}/userguide/artifacts/maven/build.gradle[tag=mappings]
----

Gradle exclude rules are converted to Maven excludes if possible. Such a conversion is possible if in the Gradle exclude rule the group as well as the module name is specified (as Maven needs both in contrast to Ivy). Per-configuration excludes are also included in the Maven POM, if they are convertible.
