// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[native_software]]
== Building native software


[NOTE]
====

Support for building native software is currently <<feature_lifecycle,incubating>>. Please be aware that the DSL, APIs and other configuration may change in later Gradle versions.

====

The native software plugins add support for building native software components, such as executables or shared libraries, from code written in C++, C and other languages. While many excellent build tools exist for this space of software development, Gradle offers developers its trademark power and flexibility together with dependency management practices more traditionally found in the JVM development space.

The native software plugins make use of the Gradle <<software_model,software model>>.


[[sec:native_features]]
=== Features

The native software plugins provide:

* Support for building native libraries and applications on Windows, Linux, macOS and other platforms.
* Support for several source languages.
* Support for building different variants of the same software, for different architectures, operating systems, or for any purpose.
* Incremental parallel compilation, precompiled headers.
* Dependency management between native software components.
* Unit test execution.
* Generate Visual studio solution and project files.
* Deep integration with various tool chain, including discovery of installed tool chains.


[[sec:supported_languages]]
=== Supported languages

The following source languages are currently supported:

* C
* C++
* Objective-C
* Objective-C++
* Assembly
* Windows resources


[[native-binaries:tool-chain-support]]
=== Tool chain support

Gradle offers the ability to execute the same build using different tool chains. When you build a native binary, Gradle will attempt to locate a tool chain installed on your machine that can build the binary. You can fine tune exactly how this works, see <<native_binaries:tool_chain>> for details.

The following tool chains are supported:

[cols="a,a,a", options="header"]
|===
| Operating System
| Tool Chain
| Notes

| Linux
| http://gcc.gnu.org/[GCC]
|

| Linux
| http://clang.llvm.org[Clang]
|

| macOS
| XCode
| Uses the Clang tool chain bundled with XCode.

| Windows
| http://www.microsoft.com/visualstudio/en-us[Visual C++]
| Windows XP and later, Visual C++ 2010/2012/2013/2015/2017.

| Windows
| http://gcc.gnu.org/[GCC] with http://cygwin.com[Cygwin 32]
| Windows XP and later.

| Windows
| http://gcc.gnu.org/[GCC] with http://www.mingw.org/[MinGW]
| Windows XP and later. http://mingw-w64.sourceforge.net[Mingw-w64] is currently not supported.
|===

The following tool chains are unofficially supported. They generally work fine, but are not tested continuously:

[cols="a,a,a", options="header"]
|===
| Operating System
| Tool Chain
| Notes

| macOS
| http://gcc.gnu.org/[GCC] from Macports
|

| macOS
| http://clang.llvm.org[Clang] from Macports
|

| Windows
| http://gcc.gnu.org/[GCC] with http://cygwin.com[Cygwin 64]
| Windows XP and later.

| UNIX-like
| http://gcc.gnu.org/[GCC]
|

| UNIX-like
| http://clang.llvm.org[Clang]
|
|===


[[sec:tool_chain_installation]]
=== Tool chain installation


[NOTE]
====

Note that if you are using GCC then you currently need to install support for C+\+, even if you are not building from C++ source. This restriction will be removed in a future Gradle version.

====

To build native software, you will need to have a compatible tool chain installed:


[[sec:windows]]
==== Windows

To build on Windows, install a compatible version of Visual Studio. The native plugins will discover the Visual Studio installations and select the latest version. There is no need to mess around with environment variables or batch scripts. This works fine from a Cygwin shell or the Windows command-line.

Alternatively, you can install Cygwin with GCC or MinGW. Clang is currently not supported.

[[sec:macOS]]
==== macOS

To build on macOS, you should install XCode. The native plugins will discover the XCode installation using the system PATH.

The native plugins also work with GCC and Clang bundled with Macports. To use one of the Macports tool chains, you will need to make the tool chain the default using the `port select` command and add Macports to the system PATH.

[[sec:linux]]
==== Linux

To build on Linux, install a compatible version of GCC or Clang. The native plugins will discover GCC or Clang using the system PATH.

[[sec:native_software_model]]
=== Native software model

The native software model builds on the base Gradle <<software_model_concepts,software model>>.

To build native software using Gradle, your project should define one or more _native components_. Each component represents either an executable or a library that Gradle should build. A project can define any number of components. Gradle does not define any components by default.

For each component, Gradle defines a _source set_ for each language that the component can be built from. A source set is essentially just a set of source directories containing source files. For example, when you apply the `c` plugin and define a library called `helloworld`, Gradle will define, by default, a source set containing the C source files in the `src/helloworld/c` directory. It will use these source files to build the `helloworld` library. This is described in more detail below.

For each component, Gradle defines one or more _binaries_ as output. To build a binary, Gradle will take the source files defined for the component, compile them as appropriate for the source language, and link the result into a binary file. For an executable component, Gradle can produce executable binary files. For a library component, Gradle can produce both static and shared library binary files. For example, when you define a library called `helloworld` and build on Linux, Gradle will, by default, produce `libhelloworld.so` and `libhelloworld.a` binaries.

In many cases, more than one binary can be produced for a component. These binaries may vary based on the tool chain used to build, the compiler/linker flags supplied, the dependencies provided, or additional source files provided. Each native binary produced for a component is referred to as a _variant_. Binary variants are discussed in detail below.

[[sec:parallel_compilation]]
=== Parallel Compilation

Gradle uses the single build worker pool to concurrently compile and link native components, by default. No special configuration is required to enable concurrent building.

By default, the worker pool size is determined by the number of available processors on the build machine (as reported to the build JVM). To explicitly set the number of workers use the `--max-workers` command-line option or `org.gradle.workers.max` system property. There is generally no need to change this setting from its default.

The build worker pool is shared across all build tasks. This means that when using <<sec:parallel_execution,parallel project execution>>, the maximum number of concurrent individual compilation operations does not increase. For example, if the build machine has 4 processing cores and 10 projects are compiling in parallel, Gradle will only use 4 total workers, not 40.

[[sec:building_a_library]]
=== Building a library

To build either a static or shared native library, you define a library component in the `components` container. The following sample defines a library called `hello`:

++++
<sample id="cppLibraries" dir="native-binaries/c" title="Defining a library component">
            <sourcefile file="build.gradle" snippet="libraries"/>
        </sample>
++++

A library component is represented using api:org.gradle.nativeplatform.NativeLibrarySpec[]. Each library component can produce at least one shared library binary (api:org.gradle.nativeplatform.SharedLibraryBinarySpec[]) and at least one static library binary (api:org.gradle.nativeplatform.StaticLibraryBinarySpec[]).

[[sec:building_an_executable]]
=== Building an executable

To build a native executable, you define an executable component in the `components` container. The following sample defines an executable called `main`:

++++
<sample id="cppExecutables" dir="native-binaries/c" title="Defining executable components">
            <sourcefile file="build.gradle" snippet="executables"/>
        </sample>
++++

An executable component is represented using api:org.gradle.nativeplatform.NativeExecutableSpec[]. Each executable component can produce at least one executable binary (api:org.gradle.nativeplatform.NativeExecutableBinarySpec[]).

For each component defined, Gradle adds a api:org.gradle.language.base.FunctionalSourceSet[] with the same name. Each of these functional source sets will contain a language-specific source set for each of the languages supported by the project.

[[sec:dependents]]
=== Assembling or building dependents

Sometimes, you may need to _assemble_ (compile and link) or _build_ (compile, link and test) a component or binary and its _dependents_ (things that depend upon the component or binary). The native software model provides tasks that enable this capability. First, the _dependent components_ report gives insight about the relationships between each component. Second, the _build and assemble dependents_ tasks allow you to assemble or build a component and its dependents in one step.

In the following example, the build file defines `OpenSSL` as a dependency of `libUtil` and `libUtil` as a dependency of `LinuxApp` and `WindowsApp`. Test suites are treated similarly. Dependents can be thought of as reverse dependencies.
++++
<figure>
                <title>Dependent Components Example</title>
                <imageobject>
                    <imagedata fileref="img/nativeDependents.png"/>
                </imageobject>
            </figure>
++++

[NOTE]
====
By following the dependencies backwards, you can see `LinuxApp` and `WindowsApp` are _dependents_ of `libUtil`. When `libUtil` is changed, Gradle will need to recompile or relink `LinuxApp` and `WindowsApp`.
====


When you _assemble_ dependents of a component, the component and all of its dependents are compiled and linked, including any test suite binaries. Gradle's up-to-date checks are used to only compile or link if something has changed. For instance, if you have changed source files in a way that do not affect the headers of your project, Gradle will be able to skip compilation for dependent components and only need to re-link with the new library. Tests are not run when assembling a component.

When you _build_ dependents of a component, the component and all of its dependent binaries are compiled, linked _and checked_. Checking components means running any <<sec:check_tasks,check task>> including executing any test suites, so tests _are_ run when building a component.

In the following sections, we will demonstrate the usage of the `assembleDependents\*`, `buildDependents*` and `dependentComponents` tasks with a sample build that contains a CUnit test suite. The build script for the sample is the following:

++++
<sample id="nativeDependentComponentsSample" dir="native-binaries/cunit" title="Sample build" includeLocation="true">
            <sourcefile file="build.gradle" snippet="terse-example"/>
        </sample>
++++


[[sec:dependents_report]]
==== Dependent components report

Gradle provides a report that you can run from the command-line that shows a graph of components in your project and components that depend upon them. The following is an example of running `gradle dependentComponents` on the sample project:

++++
<sample id="nativeDependentComponentsReport" dir="native-binaries/cunit" title="Dependent components report">
                <output args="dependentComponents"/>
            </sample>
++++

[NOTE]
====
See api:org.gradle.api.reporting.dependents.DependentComponentsReport[] API documentation for more details.
====

By default, non-buildable binaries and test suites are hidden from the report. The `dependentComponents` task provides options that allow you to see all dependents by using the `--all` option:

++++
<sample id="nativeDependentComponentsReportAll" dir="native-binaries/cunit" title="Dependent components report">
                <output args="dependentComponents --all"/>
            </sample>
++++

Here is the corresponding report for the `operators` component, showing dependents of all its binaries:

++++
<sample id="nativeAssembleDependentComponentsReport" dir="native-binaries/cunit" title="Report of components that depends on the operators component">
                <output args="dependentComponents --component operators"/>
            </sample>
++++

Here is the corresponding report for the `operators` component, showing dependents of all its binaries, including test suites:

++++
<sample id="nativeBuildDependentComponentsReport" dir="native-binaries/cunit" title="Report of components that depends on the operators component, including test suites">
                <output args="dependentComponents --test-suites --component operators"/>
            </sample>
++++


[[sec:assemble_dependents]]
==== Assembling dependents

For each api:org.gradle.nativeplatform.NativeBinarySpec[], Gradle will create a task named `assembleDependents__${component.name}${binary.variant}__` that _assembles_ (compile and link) the binary and all of its dependent binaries.

For each api:org.gradle.nativeplatform.NativeComponentSpec[], Gradle will create a task named `assembleDependents__${component.name}__` that _assembles_ all the binaries of the component and all of their dependent binaries.

For example, to assemble the dependents of the "passing" flavor of the "static" library binary of the "operators" component, you would run the `assembleDependentsOperatorsPassingStaticLibrary` task:

++++
<sample id="nativeAssembleDependentComponents" dir="native-binaries/cunit" title="Assemble components that depends on the passing/static binary of the operators component">
    <output args="assembleDependentsOperatorsPassingStaticLibrary --max-workers=1"/>
</sample>
++++

In the output above, the targeted binary gets assembled as well as the test suite binary that depends on it.

You can also assemble _all_ of the dependents of a component (i.e. of all its binaries/variants) using the corresponding component task, e.g. `assembleDependentsOperators`. This is useful if you have many combinations of build types, flavors and platforms and want to assemble all of them.

[[sec:build_dependents]]
==== Building dependents

For each api:org.gradle.nativeplatform.NativeBinarySpec[], Gradle will create a task named `buildDependents__${component.name}${binary.variant}__` that _builds_ (compile, link and check) the binary and all of its dependent binaries.

For each api:org.gradle.nativeplatform.NativeComponentSpec[], Gradle will create a task named `buildDependents__${component.name}__` that _builds_ all the binaries of the component and all of their dependent binaries.

For example, to build the dependents of the "passing" flavor of the "static" library binary of the "operators" component, you would run the `buildDependentsOperatorsPassingStaticLibrary` task:

++++
<sample id="nativeBuildDependentComponents" dir="native-binaries/cunit" title="Build components that depends on the passing/static binary of the operators component">
    <output args="buildDependentsOperatorsPassingStaticLibrary --max-workers=1"/>
</sample>
++++

In the output above, the targeted binary as well as the test suite binary that depends on it are built and the test suite has run.

You can also build _all_ of the dependents of a component (i.e. of all its binaries/variants) using the corresponding component task, e.g. `buildDependentsOperators`.

[[sec:native_tasks]]
=== Tasks

For each api:org.gradle.nativeplatform.NativeBinarySpec[] that can be produced by a build, a single _lifecycle task_ is constructed that can be used to create that binary, together with a set of other tasks that do the actual work of compiling, linking or assembling the binary.

[cols="a,a,a,a", options="header"]
|===
| Component Type
| Native Binary Type
| Lifecycle task
| Location of created binary

| api:org.gradle.nativeplatform.NativeExecutableSpec[]
| api:org.gradle.nativeplatform.NativeExecutableBinarySpec[]
| `__${component.name}__Executable`
| `__${project.buildDir}__/exe/__${component.name}__/__${component.name}__`

| api:org.gradle.nativeplatform.NativeLibrarySpec[]
| api:org.gradle.nativeplatform.SharedLibraryBinarySpec[]
| `__${component.name}__SharedLibrary`
| `__${project.buildDir}__/libs/__${component.name}__/shared/lib__${component.name}__.so`

| api:org.gradle.nativeplatform.NativeLibrarySpec[]
| api:org.gradle.nativeplatform.StaticLibraryBinarySpec[]
| `__${component.name}__StaticLibrary`
| `__${project.buildDir}__/libs/__${component.name}__/static/__${component.name}__.a`
|===


[[sec:check_tasks]]
==== Check tasks

For each api:org.gradle.nativeplatform.NativeBinarySpec[] that can be produced by a build, a single _check task_ is constructed that can be used to assemble and check that binary.

[cols="a,a,a", options="header"]
|===
| Component Type
| Native Binary Type
| Check task

| api:org.gradle.nativeplatform.NativeExecutableSpec[]
| api:org.gradle.nativeplatform.NativeExecutableBinarySpec[]
| `check__${component.name}__Executable`

| api:org.gradle.nativeplatform.NativeLibrarySpec[]
| api:org.gradle.nativeplatform.SharedLibraryBinarySpec[]
| `check__${component.name}__SharedLibrary`

| api:org.gradle.nativeplatform.NativeLibrarySpec[]
| api:org.gradle.nativeplatform.StaticLibraryBinarySpec[]
| `check__${component.name}__StaticLibrary`
|===

The built-in `check` task depends on all the _check tasks_ for binaries in the project. Without either <<native_binaries:cunit,CUnit>> or <<native_binaries:google_test,GoogleTest>> plugins, the binary check task only depends on the _lifecycle task_ that assembles the binary, see <<sec:native_tasks>>.

When the <<native_binaries:cunit,CUnit>> or <<native_binaries:google_test,GoogleTest>> plugins are applied, the task that executes the test suites for a component are automatically wired to the appropriate _check task_.

You can also add custom check tasks as follows:

++++
<sample id="nativeComponentCustomCheck" dir="native-binaries/custom-check" title="Adding a custom check task" includeLocation="true">
                <sourcefile file="build.gradle" snippet="custom-check"/>
            </sample>
++++

Now, running `check` or any of the _check tasks_ for the `hello` binaries will run the custom check task:

++++
<sample id="nativeComponentCustomCheckOutput" dir="native-binaries/custom-check" title="Running checks for a given binary">
                <output args="checkHelloSharedLibrary"/>
            </sample>
++++


[[sec:working_with_shared_libraries]]
==== Working with shared libraries

For each executable binary produced, the `cpp` plugin provides an `install${binary.name}` task, which creates a development install of the executable, along with the shared libraries it requires. This allows you to run the executable without needing to install the shared libraries in their final locations.

[[sec:finding_out_more_about_your_project]]
=== Finding out more about your project

Gradle provides a report that you can run from the command-line that shows some details about the components and binaries that your project produces. To use this report, just run `gradle components`. Below is an example of running this report for one of the sample projects:

++++
<sample id="nativeComponentReport" dir="native-binaries/cpp" title="The components report">
            <output args="components"/>
        </sample>
++++


[[native_binaries:languages]]
=== Language support

Presently, Gradle supports building native software from any combination of source languages listed below. A native binary project will contain one or more named `FunctionalSourceSet` instances (eg 'main', 'test', etc), each of which can contain ``LanguageSourceSet``s containing source files, one for each language.

* C
* C++
* Objective-C
* Objective-C++
* Assembly
* Windows resources


[[sec:cpp_sources]]
==== C++ sources

C++ language support is provided by means of the `'cpp'` plugin.

++++
<sample id="cppPlugin" dir="native-binaries/cpp" title="The 'cpp' plugin">
                <sourcefile file="build.gradle" snippet="apply-plugin"/>
            </sample>
++++

$$C++$$ sources to be included in a native binary are provided via a api:org.gradle.language.cpp.CppSourceSet[], which defines a set of C++ source files and optionally a set of exported header files (for a library). By default, for any named component the api:org.gradle.language.cpp.CppSourceSet[] contains `.cpp` source files in `src/${name}/cpp`, and header files in `src/${name}/headers`.

While the `cpp` plugin defines these default locations for each api:org.gradle.language.cpp.CppSourceSet[], it is possible to extend or override these defaults to allow for a different project layout.

++++
<sample id="cppSourceSet" dir="native-binaries/custom-layout" title="C++ source set">
                <sourcefile file="build.gradle" snippet="cpp-sources"/>
            </sample>
++++

For a library named 'main', header files in `src/main/headers` are considered the "public" or "exported" headers. Header files that should not be exported should be placed inside the `src/main/cpp` directory (though be aware that such header files should always be referenced in a manner relative to the file including them).

[[sec:c_sources]]
==== C sources

C language support is provided by means of the `'c'` plugin.

++++
<sample id="cPlugin" dir="native-binaries/c" title="The 'c' plugin">
                <sourcefile file="build.gradle" snippet="apply-plugin"/>
            </sample>
++++

C sources to be included in a native binary are provided via a api:org.gradle.language.c.CSourceSet[], which defines a set of C source files and optionally a set of exported header files (for a library). By default, for any named component the api:org.gradle.language.c.CSourceSet[] contains `.c` source files in `src/${name}/c`, and header files in `src/${name}/headers`.

While the `c` plugin defines these default locations for each api:org.gradle.language.c.CSourceSet[], it is possible to extend or override these defaults to allow for a different project layout.

++++
<sample id="cSourceSet" dir="native-binaries/custom-layout" title="C source set">
                <sourcefile file="build.gradle" snippet="c-sources"/>
            </sample>
++++

For a library named 'main', header files in `src/main/headers` are considered the "public" or "exported" headers. Header files that should not be exported should be placed inside the `src/main/c` directory (though be aware that such header files should always be referenced in a manner relative to the file including them).

[[sec:assembler_sources]]
==== Assembler sources

Assembly language support is provided by means of the `'assembler'` plugin.

++++
<sample id="assemblerPlugin" dir="native-binaries/assembler" title="The 'assembler' plugin">
                <sourcefile file="build.gradle" snippet="apply-plugin"/>
            </sample>
++++

Assembler sources to be included in a native binary are provided via a api:org.gradle.language.assembler.AssemblerSourceSet[], which defines a set of Assembler source files. By default, for any named component the api:org.gradle.language.assembler.AssemblerSourceSet[] contains `.s` source files under `src/${name}/asm`.

[[sec:objectivec_sources]]
==== Objective-C sources

Objective-C language support is provided by means of the `'objective-c'` plugin.

++++
<sample id="objectiveCPlugin" dir="native-binaries/objective-c" title="The 'objective-c' plugin">
                <sourcefile file="build.gradle" snippet="apply-plugin"/>
            </sample>
++++

Objective-C sources to be included in a native binary are provided via a api:org.gradle.language.objectivec.ObjectiveCSourceSet[], which defines a set of Objective-C source files. By default, for any named component the api:org.gradle.language.objectivec.ObjectiveCSourceSet[] contains `.m` source files under `src/${name}/objectiveC`.

[[sec:objectivecpp_sources]]
==== Objective-C++ sources

Objective-C++ language support is provided by means of the `'objective-cpp'` plugin.

++++
<sample id="objectiveCppPlugin" dir="native-binaries/objective-cpp" title="The 'objective-cpp' plugin">
                <sourcefile file="build.gradle" snippet="apply-plugin"/>
            </sample>
++++

Objective-C$$++$$ sources to be included in a native binary are provided via a api:org.gradle.language.objectivecpp.ObjectiveCppSourceSet[], which defines a set of Objective-C++ source files. By default, for any named component the api:org.gradle.language.objectivecpp.ObjectiveCppSourceSet[] contains `.mm` source files under `src/${name}/objectiveCpp`.

[[sec:configuring_the_compiler_assembler_and_linker]]
=== Configuring the compiler, assembler and linker

Each binary to be produced is associated with a set of compiler and linker settings, which include command-line arguments as well as macro definitions. These settings can be applied to all binaries, an individual binary, or selectively to a group of binaries based on some criteria.

++++
<sample id="allBinarySettings" dir="native-binaries/cpp" title="Settings that apply to all binaries">
            <sourcefile file="build.gradle" snippet="all-binaries"/>
        </sample>
++++

Each binary is associated with a particular api:org.gradle.nativeplatform.toolchain.NativeToolChain[], allowing settings to be targeted based on this value.

It is easy to apply settings to all binaries of a particular type:

++++
<sample id="allSharedLibraryBinarySettings" dir="native-binaries/c" title="Settings that apply to all shared libraries">
            <sourcefile file="build.gradle" snippet="all-shared-libraries"/>
        </sample>
++++

Furthermore, it is possible to specify settings that apply to all binaries produced for a particular `executable` or `library` component:

++++
<sample id="componentBinarySettings" dir="native-binaries/assembler" title="Settings that apply to all binaries produced for the 'main' executable component">
            <sourcefile file="build.gradle" snippet="assembler-args"/>
        </sample>
++++

The example above will apply the supplied configuration to all `executable` binaries built.

Similarly, settings can be specified to target binaries for a component that are of a particular type: eg all shared libraries for the main library component.

++++
<sample id="sharedLibraryArgs" dir="native-binaries/cpp-lib" title="Settings that apply only to shared libraries produced for the 'main' library component">
            <sourcefile file="build.gradle" snippet="args"/>
        </sample>
++++


[[native_binaries:windows-resources]]
=== Windows Resources

When using the api:org.gradle.nativeplatform.toolchain.VisualCpp[] tool chain, Gradle is able to compile Window Resource (`rc`) files and link them into a native binary. This functionality is provided by the `'windows-resources'` plugin.

++++
<sample id="windowsResourcesPlugin" dir="native-binaries/windows-resources" title="The 'windows-resources' plugin">
            <sourcefile file="build.gradle" snippet="apply-plugin"/>
        </sample>
++++

Windows resources to be included in a native binary are provided via a api:org.gradle.language.rc.WindowsResourceSet[], which defines a set of Windows Resource source files. By default, for any named component the api:org.gradle.language.rc.WindowsResourceSet[] contains `.rc` source files under `src/${name}/rc`.

As with other source types, you can configure the location of the windows resources that should be included in the binary.

++++
<sample id="windowsResourceSet" dir="native-binaries/windows-resources" title="Configuring the location of Windows resource sources">
            <sourcefile file="build-resource-only-dll.gradle" snippet="windows-resource-set"/>
        </sample>
++++

You are able to construct a resource-only library by providing Windows Resource sources with no other language sources, and configure the linker as appropriate:

++++
<sample id="resourceOnlyDll" dir="native-binaries/windows-resources" title="Building a resource-only dll">
            <sourcefile file="build-resource-only-dll.gradle" snippet="resource-only-library"/>
        </sample>
++++

The example above also demonstrates the mechanism of passing extra command-line arguments to the resource compiler. The `rcCompiler` extension is of type api:org.gradle.nativeplatform.PreprocessingTool[].

[[sec:library_dependencies]]
=== Library Dependencies

Dependencies for native components are binary libraries that export header files. The header files are used during compilation, with the compiled binary dependency being used during linking and execution. Header files should be organized into subdirectories to prevent clashes of commonly named headers. For instance, if your `mylib` project has a `logging.h` header, it will make it less likely the wrong header is used if you include it as `"mylib/logging.h"` instead of `"logging.h"`.


[[sec:dependencies_within_the_same_project]]
==== Dependencies within the same project

A set of sources may depend on header files provided by another binary component within the same project. A common example is a native executable component that uses functions provided by a separate native library component.

Such a library dependency can be added to a source set associated with the `executable` component:

++++
<sample id="cppSourceLibrary" dir="native-binaries/cpp" title="Providing a library dependency to the source set">
               <sourcefile file="build.gradle" snippet="source-library"/>
           </sample>
++++

Alternatively, a library dependency can be provided directly to the `NativeExecutableBinarySpec` for the `executable`.

++++
<sample id="cppBinaryLibrary" dir="native-binaries/custom-layout" title="Providing a library dependency to the binary">
               <sourcefile file="build.gradle" snippet="binary-library"/>
           </sample>
++++


[[sec:project_dependencies]]
==== Project Dependencies

For a component produced in a different Gradle project, the notation is similar.

++++
<sample id="cppProjectDependencies" dir="native-binaries/multi-project" title="Declaring project dependencies">
                <sourcefile file="build.gradle" snippet="project-dependencies"/>
            </sample>
++++


[[native_binaries:preCompiledHeaders]]
=== Precompiled Headers

Precompiled headers are a performance optimization that reduces the cost of compiling widely used headers multiple times. This feature _precompiles_ a header such that the compiled object file can be reused when compiling each source file rather than recompiling the header each time. This support is available for C, C+\+, Objective-C, and Objective-C++ builds.

To configure a precompiled header, first a header file needs to be defined that includes all of the headers that should be precompiled. It must be specified as the first included header in every source file where the precompiled header should be used. It is assumed that this header file, and any headers it contains, make use of header guards so that they can be included in an idempotent manner. If header guards are not used in a header file, it is possible the header could be compiled more than once and could potentially lead to a broken build.

++++
<sample id="preCompiledHeaderFile" dir="native-binaries/pre-compiled-headers" title="Creating a precompiled header file">
            <sourcefile file="src/hello/headers/pch.h"/>
        </sample>
++++

++++
<sample id="preCompiledHeaderFile" dir="native-binaries/pre-compiled-headers" title="Including a precompiled header file in a source file">
            <sourcefile file="src/hello/cpp/hello.cpp"/>
        </sample>
++++

Precompiled headers are specified on a source set. Only one precompiled header file can be specified on a given source set and will be applied to all source files that declare it as the first include. If a source files does not include this header file as the first header, the file will be compiled in the normal manner (without making use of the precompiled header object file). The string provided should be the same as that which is used in the "#include" directive in the source files.

++++
<sample id="preCompiledHeaderConfig" dir="native-binaries/pre-compiled-headers" title="Configuring a precompiled header">
            <sourcefile file="build.gradle" snippet="libraries"/>
        </sample>
++++

A precompiled header must be included in the same way for all files that use it. Usually, this means the header file should exist in the source set "headers" directory or in a directory included on the compiler include path.

[[native_binaries:variants]]
=== Native Binary Variants

For each executable or library defined, Gradle is able to build a number of different native binary variants. Examples of different variants include debug vs release binaries, 32-bit vs 64-bit binaries, and binaries produced with different custom preprocessor flags.

Binaries produced by Gradle can be differentiated on <<native_binaries:build_type,build type>>, <<native_binaries:platform,platform>>, and <<native_binaries:flavor,flavor>>. For each of these 'variant dimensions', it is possible to specify a set of available values as well as target each component at one, some or all of these. For example, a plugin may define a range of support platforms, but you may choose to only target Windows-x86 for a particular component.


[[native_binaries:build_type]]
==== Build types

A `build type` determines various non-functional aspects of a binary, such as whether debug information is included, or what optimisation level the binary is compiled with. Typical build types are 'debug' and 'release', but a project is free to define any set of build types.

++++
<sample id="buildTypes" dir="native-binaries/variants" title="Defining build types">
                <sourcefile file="build.gradle" snippet="build-types"/>
            </sample>
++++

If no build types are defined in a project, then a single, default build type called 'debug' is added.

For a build type, a Gradle project will typically define a set of compiler/linker flags per tool chain.

++++
<sample id="buildTypeConfig" dir="native-binaries/variants" title="Configuring debug binaries">
                <sourcefile file="build.gradle" snippet="build-type-config"/>
            </sample>
++++

[NOTE]
====
At this stage, it is completely up to the build script to configure the relevant compiler/linker flags for each build type. Future versions of Gradle will automatically include the appropriate debug flags for any 'debug' build type, and may be aware of various levels of optimisation as well.
====


[[native_binaries:platform]]
==== Platform

An executable or library can be built to run on different operating systems and cpu architectures, with a variant being produced for each platform. Gradle defines each OS/architecture combination as a api:org.gradle.nativeplatform.platform.NativePlatform[], and a project may define any number of platforms. If no platforms are defined in a project, then a single, default platform 'current' is added.

[NOTE]
====
Presently, a `Platform` consists of a defined operating system and architecture. As we continue to develop the native binary support in Gradle, the concept of Platform will be extended to include things like C-runtime version, Windows SDK, ABI, etc. Sophisticated builds may use the extensibility of Gradle to apply additional attributes to each platform, which can then be queried to specify particular includes, preprocessor macros or compiler arguments for a native binary.
====

++++
<sample id="platforms" dir="native-binaries/variants" title="Defining platforms">
                <sourcefile file="build.gradle" snippet="platforms"/>
            </sample>
++++

For a given variant, Gradle will attempt to find a api:org.gradle.nativeplatform.toolchain.NativeToolChain[] that is able to build for the target platform. Available tool chains are searched in the order defined. See the <<native_binaries:tool_chain,tool chains>> section below for more details.

[[native_binaries:flavor]]
==== Flavor

Each component can have a set of named `flavors`, and a separate binary variant can be produced for each flavor. While the `build type` and `target platform` variant dimensions have a defined meaning in Gradle, each project is free to define any number of flavors and apply meaning to them in any way.

An example of component flavors might differentiate between 'demo', 'paid' and 'enterprise' editions of the component, where the same set of sources is used to produce binaries with different functions.

++++
<sample id="flavors" dir="native-binaries/flavors" title="Defining flavors">
                <sourcefile file="build.gradle" snippet="flavors"/>
            </sample>
++++

In the example above, a library is defined with a 'english' and 'french' flavor. When compiling the 'french' variant, a separate macro is defined which leads to a different binary being produced.

If no flavor is defined for a component, then a single default flavor named 'default' is used.

[[sec:selecting_the_build_types_platforms_and_flavors_for_a_component]]
==== Selecting the build types, platforms and flavors for a component

For a default component, Gradle will attempt to create a native binary variant for each and every combination of `buildType` and `flavor` defined for the project. It is possible to override this on a per-component basis, by specifying the set of `targetBuildTypes` and/or `targetFlavors`. By default, Gradle will build for the default platform, see <<native_binaries:platform,above>>, unless specified explicitly on a per-component basis by specifying a set of `targetPlatforms`.

++++
<sample id="targets" dir="native-binaries/variants" title="Targeting a component at particular platforms">
                <sourcefile file="build.gradle" snippet="target-platforms"/>
            </sample>
++++

Here you can see that the api:org.gradle.nativeplatform.TargetedNativeComponent#targetPlatform[] method is used to specify a platform that the `NativeExecutableSpec` named `main` should be built for.

A similar mechanism exists for selecting api:org.gradle.nativeplatform.TargetedNativeComponent#targetBuildTypes[] and api:org.gradle.nativeplatform.TargetedNativeComponent#targetFlavors[].

[[sec:building_all_possible_variants]]
==== Building all possible variants

When a set of build types, target platforms, and flavors is defined for a component, a api:org.gradle.nativeplatform.NativeBinarySpec[] model element is created for every possible combination of these. However, in many cases it is not possible to build a particular variant, perhaps because no tool chain is available to build for a particular platform.

If a binary variant cannot be built for any reason, then the api:org.gradle.nativeplatform.NativeBinarySpec[] associated with that variant will not be `buildable`. It is possible to use this property to create a task to generate all possible variants on a particular machine.

++++
<sample id="buildable" dir="native-binaries/tool-chains" title="Building all possible variants">
                <sourcefile file="build.gradle" snippet="buildable"/>
            </sample>
++++


[[native_binaries:tool_chain]]
=== Tool chains

A single build may utilize different tool chains to build variants for different platforms. To this end, the core 'native-binary' plugins will attempt to locate and make available supported tool chains. However, the set of tool chains for a project may also be explicitly defined, allowing additional cross-compilers to be configured as well as allowing the install directories to be specified.


[[sec:defining_tool_chains]]
==== Defining tool chains

The supported tool chain types are:

* api:org.gradle.nativeplatform.toolchain.Gcc[]
* api:org.gradle.nativeplatform.toolchain.Clang[]
* api:org.gradle.nativeplatform.toolchain.VisualCpp[]

++++
<sample id="toolChains" dir="native-binaries/tool-chains" title="Defining tool chains">
                <sourcefile file="build.gradle" snippet="toolChains"/>
            </sample>
++++

Each tool chain implementation allows for a certain degree of configuration (see the API documentation for more details).

[[sec:using_tool_chains]]
==== Using tool chains

It is not necessary or possible to specify the tool chain that should be used to build. For a given variant, Gradle will attempt to locate a api:org.gradle.nativeplatform.toolchain.NativeToolChain[] that is able to build for the target platform. Available tool chains are searched in the order defined.

[NOTE]
====
When a platform does not define an architecture or operating system, the default target of the tool chain is assumed. So if a platform does not define a value for `operatingSystem`, Gradle will find the first available tool chain that can build for the specified `architecture`.
====

The core Gradle tool chains are able to target the following architectures out of the box. In each case, the tool chain will target the current operating system. See the next section for information on cross-compiling for other operating systems.

[cols="a,a", options="header"]
|===
| Tool Chain
| Architectures

| GCC
| x86, x86_64

| Clang
| x86, x86_64

| Visual C++
| x86, x86_64, ia-64
|===

So for GCC running on linux, the supported target platforms are 'linux/x86' and 'linux/x86_64'. For GCC running on Windows via Cygwin, platforms 'windows/x86' and 'windows/x86_64' are supported. (The Cygwin POSIX runtime is not yet modelled as part of the platform, but will be in the future.)

If no target platforms are defined for a project, then all binaries are built to target a default platform named 'current'. This default platform does not specify any `architecture` or `operatingSystem` value, hence using the default values of the first available tool chain.

Gradle provides a _hook_ that allows the build author to control the exact set of arguments passed to a tool chain executable. This enables the build author to work around any limitations in Gradle, or assumptions that Gradle makes. The arguments hook should be seen as a 'last-resort' mechanism, with preference given to truly modelling the underlying domain.

++++
<sample id="withArguments" dir="native-binaries/tool-chains" title="Reconfigure tool arguments">
                <sourcefile file="build.gradle" snippet="withArguments"/>
            </sample>
++++


[[sec:crosscompiling_with_gcc]]
==== Cross-compiling with GCC

Cross-compiling is possible with the api:org.gradle.nativeplatform.toolchain.Gcc[] and api:org.gradle.nativeplatform.toolchain.Clang[] tool chains, by adding support for additional target platforms. This is done by specifying a target platform for a toolchain. For each target platform a custom configuration can be specified.

++++
<sample id="targetPlatforms" dir="native-binaries/target-platforms" title="Defining target platforms">
                <sourcefile file="build.gradle" snippet="targetplatforms"/>
            </sample>
++++


[[native_binaries:visual_studio]]
=== Visual Studio IDE integration

Gradle has the ability to generate Visual Studio project and solution files for the native components defined in your build. This ability is added by the `visual-studio` plugin. For a multi-project build, all projects with native components (and the root project) should have this plugin applied.

When the `visual-studio` plugin is applied to the root project, a task named `visualStudio` is created, which will generate a Visual Studio solution file containing all components in the build. This solution will include a Visual Studio project for each component, as well as configuring each component to build using Gradle.

A task named `openVisualStudio` is also created by the `visual-studio` plugin when the project is the root project. This task generates the Visual Studio solution and then opens the solution in Visual Studio. This means you can simply run `gradlew openVisualStudio` from the root project to generate and open the Visual Studio solution in one convenient step.

The content of the generated visual studio files can be modified via API hooks, provided by the `visualStudio` extension. Take a look at the 'visual-studio' sample, or see api:org.gradle.ide.visualstudio.VisualStudioExtension#getProjects[] and api:org.gradle.ide.visualstudio.VisualStudioRootExtension#getSolution[] in the API documentation for more details.

[[native_binaries:cunit]]
=== CUnit support

The Gradle `cunit` plugin provides support for compiling and executing CUnit tests in your native-binary project. For each api:org.gradle.nativeplatform.NativeExecutableSpec[] and api:org.gradle.nativeplatform.NativeLibrarySpec[] defined in your project, Gradle will create a matching api:org.gradle.nativeplatform.test.cunit.CUnitTestSuiteSpec[] component, named `${component.name}Test`.


[[sec:cunit_sources]]
==== CUnit sources

Gradle will create a api:org.gradle.language.c.CSourceSet[] named 'cunit' for each api:org.gradle.nativeplatform.test.cunit.CUnitTestSuiteSpec[] component in the project. This source set should contain the cunit test files for the component under test. Source files can be located in the conventional location (`src/${component.name}Test/cunit`) or can be configured like any other source set.

Gradle initialises the CUnit test registry and executes the tests, utilising some generated CUnit launcher sources. Gradle will expect and call a function with the signature `void gradle_cunit_register()` that you can use to configure the actual CUnit suites and tests to execute.

++++
<sample id="cunitSources" dir="native-binaries/cunit/src/operatorsTest/c" title="Registering CUnit tests">
                <sourcefile file="suite_operators.c"/>
            </sample>
++++

[NOTE]
====
Due to this mechanism, your CUnit sources may not contain a `main` method since this will clash with the method provided by Gradle.
====


[[sec:building_cunit_executables]]
==== Building CUnit executables

A api:org.gradle.nativeplatform.test.cunit.CUnitTestSuiteSpec[] component has an associated api:org.gradle.nativeplatform.NativeExecutableSpec[] or api:org.gradle.nativeplatform.NativeLibrarySpec[] component. For each api:org.gradle.nativeplatform.NativeBinarySpec[] configured for the main component, a matching api:org.gradle.nativeplatform.test.cunit.CUnitTestSuiteBinarySpec[] will be configured on the test suite component. These test suite binaries can be configured in a similar way to any other binary instance:

++++
<sample id="cunitSources" dir="native-binaries/cunit" title="Configuring CUnit tests">
                <sourcefile file="build.gradle" snippet="configure-test-binary"/>
            </sample>
++++

[NOTE]
====
Both the CUnit sources provided by your project and the generated launcher require the core CUnit headers and libraries. Presently, this library dependency must be provided by your project for each api:org.gradle.nativeplatform.test.cunit.CUnitTestSuiteBinarySpec[].
====


[[sec:running_cunit_tests]]
==== Running CUnit tests

For each api:org.gradle.nativeplatform.test.cunit.CUnitTestSuiteBinarySpec[], Gradle will create a task to execute this binary, which will run all of the registered CUnit tests. Test results will be found in the `__${build.dir}__/test-results` directory.

++++
<sample id="completeCUnitExample" dir="native-binaries/cunit" title="Running CUnit tests" includeLocation="true">
                <sourcefile file="build.gradle" snippet="complete-example"/>
                <output args="-q runOperatorsTestFailingCUnitExe" expectFailure="true"/>
            </sample>
++++

[NOTE]
====

The current support for CUnit is quite rudimentary. Plans for future integration include:

* Allow tests to be declared with Javadoc-style annotations.
* Improved HTML reporting, similar to that available for JUnit.
* Real-time feedback for test execution.
* Support for additional test frameworks.

====


[[native_binaries:google_test]]
=== GoogleTest support

The Gradle `google-test` plugin provides support for compiling and executing GoogleTest tests in your native-binary project. For each api:org.gradle.nativeplatform.NativeExecutableSpec[] and api:org.gradle.nativeplatform.NativeLibrarySpec[] defined in your project, Gradle will create a matching api:org.gradle.nativeplatform.test.googletest.GoogleTestTestSuiteSpec[] component, named `${component.name}Test`.


[[sec:googletest_sources]]
==== GoogleTest sources

Gradle will create a api:org.gradle.language.cpp.CppSourceSet[] named 'cpp' for each api:org.gradle.nativeplatform.test.googletest.GoogleTestTestSuiteSpec[] component in the project. This source set should contain the GoogleTest test files for the component under test. Source files can be located in the conventional location (`src/${component.name}Test/cpp`) or can be configured like any other source set.

[[sec:building_googletest_executables]]
==== Building GoogleTest executables

A api:org.gradle.nativeplatform.test.googletest.GoogleTestTestSuiteSpec[] component has an associated api:org.gradle.nativeplatform.NativeExecutableSpec[] or api:org.gradle.nativeplatform.NativeLibrarySpec[] component. For each api:org.gradle.nativeplatform.NativeBinarySpec[] configured for the main component, a matching api:org.gradle.nativeplatform.test.googletest.GoogleTestTestSuiteBinarySpec[] will be configured on the test suite component. These test suite binaries can be configured in a similar way to any other binary instance:

++++
<sample id="googleTestSources" dir="native-binaries/google-test" title="Registering GoogleTest tests" includeLocation="true">
                <sourcefile file="build.gradle" snippet="configure-test-binary"/>
            </sample>
++++

[NOTE]
====
The GoogleTest sources provided by your project require the core GoogleTest headers and libraries. Presently, this library dependency must be provided by your project for each api:org.gradle.nativeplatform.test.googletest.GoogleTestTestSuiteBinarySpec[].
====


[[sec:running_googletest_tests]]
==== Running GoogleTest tests

For each api:org.gradle.nativeplatform.test.googletest.GoogleTestTestSuiteBinarySpec[], Gradle will create a task to execute this binary, which will run all of the registered GoogleTest tests. Test results will be found in the `__${build.dir}__/test-results` directory.
[NOTE]
====

The current support for GoogleTest is quite rudimentary. Plans for future integration include:

* Improved HTML reporting, similar to that available for JUnit.
* Real-time feedback for test execution.
* Support for additional test frameworks.

====
