// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[scala_plugin]]
== The Scala Plugin

The Scala plugin extends the Java plugin to add support for Scala projects. It can deal with Scala code, mixed Scala and Java code, and even pure Java code (although we don't necessarily recommend to use it for the latter). The plugin supports _joint compilation_, which allows you to freely mix and match Scala and Java code, with dependencies in both directions. For example, a Scala class can extend a Java class that in turn extends a Scala class. This makes it possible to use the best language for the job, and to rewrite any class in the other language if needed.


[[sec:scala_usage]]
=== Usage

To use the Scala plugin, include the following in your build script:

++++
<sample xmlns:xi="http://www.w3.org/2001/XInclude" id="useScalaPlugin" dir="scala/quickstart" title="Using the Scala plugin">
            <sourcefile file="build.gradle" snippet="use-plugin"/>
        </sample>
++++


[[sec:scala_tasks]]
=== Tasks

The Scala plugin adds the following tasks to the project.

.Scala plugin - tasks
[cols="a,a,a,a", options="header"]
|===
| Task name
| Depends on
| Type
| Description

| `compileScala`
| `compileJava`
| api:org.gradle.api.tasks.scala.ScalaCompile[]
| Compiles production Scala source files.

| `compileTestScala`
| `compileTestJava`
| api:org.gradle.api.tasks.scala.ScalaCompile[]
| Compiles test Scala source files.

| `compile__SourceSet__Scala`
| `compile__SourceSet__Java`
| api:org.gradle.api.tasks.scala.ScalaCompile[]
| Compiles the given source set's Scala source files.

| `scaladoc`
| -
| api:org.gradle.api.tasks.scala.ScalaDoc[]
| Generates API documentation for the production Scala source files.
|===

The Scala plugin adds the following dependencies to tasks added by the Java plugin.

.Scala plugin - additional task dependencies
[cols="a,a", options="header"]
|===
| Task name
| Depends on
|  `classes`
|  `compileScala`

|  `testClasses`
|  `compileTestScala`

|  `__sourceSet__Classes`
|  `compile__SourceSet__Scala`
|===

++++
<figure xmlns:xi="http://www.w3.org/2001/XInclude">
            <title>Scala plugin - tasks</title>
            <imageobject>
                <imagedata fileref="img/scalaPluginTasks.png"/>
            </imageobject>
        </figure>
++++


[[sec:scala_project_layout]]
=== Project layout

The Scala plugin assumes the project layout shown below. All the Scala source directories can contain Scala _and_ Java code. The Java source directories may only contain Java source code. None of these directories need to exist or have anything in them; the Scala plugin will simply compile whatever it finds.

[[scalalayout]]
include::javaProjectMainLayout.adoc[]

`src/main/scala`::
Production Scala source. May also contain Java source files for joint compilation.

include::javaProjectTestLayout.adoc[]

`src/test/scala`::
Test Scala source. May also contain Java source files for joint compilation.

include::javaProjectGenericLayout.adoc[]

`src/__sourceSet__/scala`::
Scala source files for the given source set. May also contain Java source files for joint compilation.


[[sec:changing_scala_project_layout]]
==== Changing the project layout

Just like the Java plugin, the Scala plugin allows you to configure custom locations for Scala production and test source files.

++++
<sample xmlns:xi="http://www.w3.org/2001/XInclude" id="customScalaSourceLayout" dir="scala/customizedLayout" title="Custom Scala source layout">
                <sourcefile file="build.gradle" snippet="custom-source-locations"/>
            </sample>
++++


[[sec:scala_dependency_management]]
=== Dependency management

Scala projects need to declare a `scala-library` dependency. This dependency will then be used on compile and runtime class paths. It will also be used to get hold of the Scala compiler and Scaladoc tool, respectively.footnote:[See <<sec:configure_scala_classpath>>.]

If Scala is used for production code, the `scala-library` dependency should be added to the `compile` configuration:

++++
<sample xmlns:xi="http://www.w3.org/2001/XInclude" id="declareScalaDependency" dir="scala/quickstart" title="Declaring a Scala dependency for production code">
            <sourcefile file="build.gradle" snippet="scala-dependency"/>
        </sample>
++++

If Scala is only used for test code, the `scala-library` dependency should be added to the `testCompile` configuration:

++++
<sample xmlns:xi="http://www.w3.org/2001/XInclude" id="declareScalaTestDependency" dir="userguide/scala/scalaDependency" title="Declaring a Scala dependency for test code">
            <sourcefile file="build.gradle" snippet="scala-test-dependency"/>
        </sample>
++++


[[sec:configure_scala_classpath]]
=== Automatic configuration of scalaClasspath

The `ScalaCompile` and `ScalaDoc` tasks consume Scala code in two ways: on their `classpath`, and on their `scalaClasspath`. The former is used to locate classes referenced by the source code, and will typically contain `scala-library` along with other libraries. The latter is used to load and execute the Scala compiler and Scaladoc tool, respectively, and should only contain the `scala-compiler` library and its dependencies.

Unless a task's `scalaClasspath` is configured explicitly, the Scala (base) plugin will try to infer it from the task's `classpath`. This is done as follows:

* If a `scala-library` jar is found on `classpath`, and the project has at least one repository declared, a corresponding `scala-compiler` repository dependency will be added to `scalaClasspath`.
* Otherwise, execution of the task will fail with a message saying that `scalaClasspath` could not be inferred.


[[sec:configure_zinc_compiler]]
=== Configuring the Zinc compiler

The Scala plugin uses a configuration named `zinc` to resolve the https://github.com/typesafehub/zinc[Zinc compiler] and its dependencies. Gradle will provide a default version of Zinc, but if you need to use a particular Zinc version, you can add an explicit dependency like `“com.typesafe.zinc:zinc:0.3.6”` to the `zinc` configuration. Gradle supports version 0.3.0 of Zinc and above; however, due to a regression in the Zinc compiler, versions 0.3.2 through 0.3.5.2 cannot be used.

++++
<sample xmlns:xi="http://www.w3.org/2001/XInclude" id="declareZincDependency" dir="userguide/scala/zincDependency" title="Declaring a version of the Zinc compiler to use">
            <sourcefile file="build.gradle" snippet="zinc-dependency"/>
        </sample>
++++

[NOTE]
====

It is important to take care when declaring your `scala-library` dependency. The Zinc compiler itself needs a compatible version of `scala-library` that may be different from the version required by your application. Gradle takes care of adding a compatible version of `scala-library` for you, but over-broad dependency resolution rules could force an incompatible version to be used instead.

For example, using `configurations.all` to force a particular version of `scala-library` would also override the version used by the Zinc compiler:

++++
<sample xmlns:xi="http://www.w3.org/2001/XInclude" id="allScalaLibraryDependency" dir="userguide/scala/zincOverride" title="Forcing a scala-library dependency for all configurations">
                <sourcefile file="build.gradle" snippet="all-dependency"/>
            </sample>
++++

The best way to avoid this problem is to be more selective when configuring the `scala-library` dependency (such as not using a `configuration.all` rule or using a conditional to prevent the rule from being applied to the `zinc` configuration). Sometimes this rule may come from a plugin or other code that you do not have control over. In such a case, you can force a correct version of the library on the `zinc` configuration only:

++++
<sample xmlns:xi="http://www.w3.org/2001/XInclude" id="zincScalaLibraryDependency" dir="userguide/scala/zincOverride" title="Forcing a scala-library dependency for the zinc configuration">
                <sourcefile file="build.gradle" snippet="zinc-dependency"/>
            </sample>
++++

You can diagnose problems with the version of the Zinc compiler selected by running <<sec:dependency_insight,dependencyInsight>> for the `zinc` configuration.

====


[[sec:scala_convention_properties]]
=== Convention properties

The Scala plugin does not add any convention properties to the project.

[[sec:scala_source_set_properties]]
=== Source set properties

The Scala plugin adds the following convention properties to each source set in the project. You can use these properties in your build script as though they were properties of the source set object.

.Scala plugin - source set properties
[cols="a,a,a,a", options="header"]
|===
| Property name
| Type
| Default value
| Description

|  `scala`
|  api:org.gradle.api.file.SourceDirectorySet[] (read-only)
| Not null
| The Scala source files of this source set. Contains all `.scala` and `.java` files found in the Scala source directories, and excludes all other types of files.

|  `scala.srcDirs`
|  `Set&lt;File&gt;`. Can set using anything described in <<sec:specifying_multiple_files>>.
|  `[__projectDir__/src/__name__/scala]`
| The source directories containing the Scala source files of this source set. May also contain Java source files for joint compilation.

|  `allScala`
|  api:org.gradle.api.file.FileTree[] (read-only)
| Not null
| All Scala source files of this source set. Contains only the `.scala` files found in the Scala source directories.
|===

These convention properties are provided by a convention object of type api:org.gradle.api.tasks.ScalaSourceSet[].

The Scala plugin also modifies some source set properties:

.Scala plugin - source set properties
[cols="a,a", options="header"]
|===
| Property name
| Change

|  `allJava`
| Adds all `.java` files found in the Scala source directories.

|  `allSource`
| Adds all source files found in the Scala source directories.
|===


[[sec:scala_compiling_in_external_process]]
=== Compiling in external process

Scala compilation takes place in an external process.

Memory settings for the external process default to the defaults of the JVM. To adjust memory settings, configure the `scalaCompileOptions.forkOptions` property as needed:
++++
<sample xmlns:xi="http://www.w3.org/2001/XInclude" id="zinc" dir="scala/zinc" title="Adjusting memory settings">
                <sourcefile file="build.gradle" snippet="adjust-memory"/>
            </sample>
++++


[[sec:scala_incremental_compilation]]
=== Incremental compilation

By compiling only classes whose source code has changed since the previous compilation, and classes affected by these changes, incremental compilation can significantly reduce Scala compilation time. It is particularly effective when frequently compiling small code increments, as is often done at development time.

The Scala plugin defaults to incremental compilation by integrating with https://github.com/typesafehub/zinc[Zinc], a standalone version of https://github.com/harrah/xsbt[sbt]'s incremental Scala compiler. If you want to disable the incremental compilation, set `force = true` in your build file:

++++
<sample xmlns:xi="http://www.w3.org/2001/XInclude" id="zinc" dir="scala/force" title="Forcing all code to be compiled">
            <sourcefile file="build.gradle" snippet="force-compilation"/>
        </sample>
++++

_Note:_ This will only cause all classes to be recompiled if at least one input source file has changed. If there are no changes to the source files, the `compileScala` task will still be considered `UP-TO-DATE` as usual.

The Zinc-based Scala Compiler supports joint compilation of Java and Scala code. By default, all Java and Scala code under `src/main/scala` will participate in joint compilation. Even Java code will be compiled incrementally.

Incremental compilation requires dependency analysis of the source code. The results of this analysis are stored in the file designated by `scalaCompileOptions.incrementalOptions.analysisFile` (which has a sensible default). In a multi-project build, analysis files are passed on to downstream `ScalaCompile` tasks to enable incremental compilation across project boundaries. For `ScalaCompile` tasks added by the Scala plugin, no configuration is necessary to make this work. For other `ScalaCompile` tasks that you might add, the property `scalaCompileOptions.incrementalOptions.publishedCode` needs to be configured to point to the classes folder or Jar archive by which the code is passed on to compile class paths of downstream `ScalaCompile` tasks. Note that if `publishedCode` is not set correctly, downstream tasks may not recompile code affected by upstream changes, leading to incorrect compilation results.

Note that Zinc's Nailgun based daemon mode is not supported. Instead, we plan to enhance Gradle's own compiler daemon to stay alive across Gradle invocations, reusing the same Scala compiler. This is expected to yield another significant speedup for Scala compilation.

[[sec:scala_cross_compilation]]
=== Compiling and testing for Java 6 or Java 7

The Scala compiler ignores Gradle's `targetCompatibility` and `sourceCompatibility` settings. In Scala 2.11, the Scala compiler always compiles to Java 6 compatible bytecode. In Scala 2.12, the Scala compiler always compiles to Java 8 compatible bytecode. If you also have Java source, you can follow the same steps as for the <<sec:java_cross_compilation,Java plugin>> to ensure the correct Java compiler is used.
++++
<sample xmlns:xi="http://www.w3.org/2001/XInclude" id="scalaCrossCompilation" dir="scala/crossCompilation" title="Configure Java 6 build for Scala">
                <sourcefile file="gradle.properties"/>
                <sourcefile file="build.gradle" snippet="scala-cross-compilation"/>
            </sample>
++++


[[sec:eclipse_integration]]
=== Eclipse Integration

When the Eclipse plugin encounters a Scala project, it adds additional configuration to make the project work with Scala IDE out of the box. Specifically, the plugin adds a Scala nature and dependency container.

[[sec:intellij_idea_integration]]
=== IntelliJ IDEA Integration

When the IDEA plugin encounters a Scala project, it adds additional configuration to make the project work with IDEA out of the box. Specifically, the plugin adds a Scala SDK (IntelliJ IDEA 14+) and a Scala compiler library that matches the Scala version on the project's class path. The Scala plugin is backwards compatible with earlier versions of IntelliJ IDEA and it is possible to add a Scala facet instead of the default Scala SDK by configuring `targetVersion` on api:org.gradle.plugins.ide.idea.model.IdeaModel[].
++++
<sample xmlns:xi="http://www.w3.org/2001/XInclude" id="ideaTargetVersion" dir="userguide/scala/ideaTargetVersion" title="Explicitly specify a target IntelliJ IDEA version">
                <sourcefile file="build.gradle" snippet="scala-idea-target-version"/>
            </sample>
++++

