// Copyright 2018 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[upgrade_version_4]]
= Upgrade your build from Gradle 4.x to 5.0

This chapter provides the information you need to migrate your older Gradle 4.x builds to Gradle 5.0. In most cases, you will need to apply the changes from all versions that come after the one you're upgrading from. For example, if you're upgrading from Gradle 4.3, you will also need to apply the changes from 4.4, 4.5, etc.

A few pointers about upgrading:

 * Run `gradle --warn --warning-mode=all build` — or whatever task performs a full build — with the version of Gradle you're upgrading to in order to see any deprecations that apply to your build.
 * Make sure you update the versions of plugins you use in your build when upgrading the Gradle version. Some plugins will break with newer versions of Gradle, for example because they use internal APIs that have been removed or changed.

Here are some significant new and improved features to try:

 * <<#rel4.8:switch_to_publishing_plugins,Maven Publish and Ivy Publish Plugins>> that now support digital signatures with the <<signing_plugin#signing_plugin,Signing Plugin>>.
 * <<#changes_4.6,New and improved POM support>> for your builds.
 * The <<custom_tasks.adoc#worker_api,Worker API>> for enabling units of work to run in parallel.
 * A new, <<feature_lifecycle#sec:incubating_state,incubating>> API for <<#rel4.9:lazy_task_creation,creating and configuring tasks lazily>> that can significantly improve your build's configuration time.

Significant other changes to watch out for as they may break your build include:

 * A change that means you should <<#rel4.8:configure_internal_tasks,configure existing `wrapper` and `init` tasks>> rather than defining your own.
 * The <<#rel4.8:pom_wildcard_exclusions,honoring of implicit wildcards in Maven POM exclusions>>, which may result in dependencies being excluded that weren't before.
 * A <<#rel4.6:annotation_processor_configuration,change to the way you add Java annotation processors to a project>>.

Read the sections relevant to your particular upgrade to get a comprehensive overview of the changes you might need to account for in your build.

[[changes_5.0]]
== Changes in 5.0

 * `<<` for task definitions no longer works, i.e. `task myTask << { ... }`

[[changes_4.10]]
== Changes in 4.10

=== Deprecated classes, methods and properties

Follow the API links to learn how to deal with these deprecations (if no extra information is provided here):

 * `TaskContainer.add()` and `TaskContainer.addAll()` — use link:{javadocPath}/org/gradle/api/tasks/TaskContainer.html#create-java.lang.String-java.lang.Class-org.gradle.api.Action-[TaskContainer.create()] or link:{javadocPath}/org/gradle/api/tasks/TaskContainer.html#register-java.lang.String-java.lang.Class-org.gradle.api.Action-[TaskContainer.register()] instead

=== Potential breaking changes

 * There have been several potentially breaking changes in Kotlin DSL — see the _Breaking changes_ section of https://github.com/gradle/kotlin-dsl/releases/tag/v1.0-RC3[that project's release notes].
 * You can no longer create your own instances of link:{javadocPath}/org/gradle/api/plugins/JavaPluginConvention.html[JavaPluginConvention], link:{javadocPath}/org/gradle/api/plugins/ApplicationPluginConvention.html[ApplicationPluginConvention], link:{javadocPath}/org/gradle/api/plugins/WarPluginConvention.html[WarPluginConvention], link:{javadocPath}/org/gradle/plugins/ear/EarPluginConvention.html[EarPluginConvention], link:{javadocPath}/org/gradle/api/plugins/BasePluginConvention.html[BasePluginConvention], and link:{javadocPath}/org/gradle/api/plugins/ProjectReportsPluginConvention.html[ProjectReportsPluginConvention].
 * You can no longer use any of the link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:beforeEvaluate(org.gradle.api.Action)[Project.beforeEvaluate()] or link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:afterEvaluate(org.gradle.api.Action)[Project.afterEvaluate()] methods with lazy task configuration, for example inside a link:{javadocPath}/org/gradle/api/tasks/TaskContainer.html#register-java.lang.String-java.lang.Class-org.gradle.api.Action-[TaskContainer.register()] block.
 * <<#rel4.10:aws_s3_permissions,Publishing to AWS S3 requires new permissions>>.
 * Both link:{javadocPath}/org/gradle/plugin/devel/tasks/PluginUnderTestMetadata.html[PluginUnderTestMetadata] and link:{javadocPath}/org/gradle/plugin/devel/tasks/GeneratePluginDescriptors.html[GeneratePluginDescriptors] — classes used by the <<java_gradle_plugin#,Java Gradle Plugin Development Plugin>> — have been updated to use the Provider API.
+
Use the link:{javadocPath}/org/gradle/api/provider/Property.html#set-T-[Property.set()] method to modify their values rather than using standard property assignment syntax, unless you are doing so in a Groovy build script. Standard property assignment still works in that one case.

[[changes_4.9]]
== Changes in 4.9

 * <<#rel4.9:lazy_task_creation,Consider trying the lazy API for task creation and configuration>>

=== Potential breaking changes

 * You can no longer use GPath syntax with link:{javadocPath}/org/gradle/api/tasks/TaskCollection.html#withType-java.lang.Class-[tasks.withType()].
+
Use http://docs.groovy-lang.org/latest/html/documentation/#_spread_operator[Groovy's spread operator] instead. For example, you would replace `tasks.withType(JavaCompile).name` with `tasks.withType(JavaCompile)*.name`.

[[changes_4.8]]
== Changes in 4.8

 * <<#rel4.8:switch_to_publishing_plugins,Switch to the Maven Publish and Ivy Publish plugins>>
 * <<#rel4.8:deferred_configuration,Use deferred configuration with the publishing plugins>>
 * <<#rel4.8:configure_internal_tasks,Configure existing `wrapper` and `init` tasks>> rather than defining your own
 * Use <<java_testing.adoc#test_filtering,test filtering>> rather than the <<java_testing.adoc#sec:single_test_execution_via_system_properties,old system properties>> like `-Dtest.single`
 * Consider migrating to the built-in <<dependency_locking#dependency_locking,dependency locking mechanism>> if you are currently using a plugin or custom solution for this
 * Use the `--debug-jvm` command-line option rather than `-Dtest.debug`

=== Deprecated classes, methods and properties

Follow the API links to learn how to deal with these deprecations (if no extra information is provided here):

 * `SimpleFileCollection` — use link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:files(java.lang.Object++[]++)[Project.files(Object...)] instead
 * link:{javadocPath}/org/gradle/api/file/FileCollection.html#add-org.gradle.api.file.FileCollection-[FileCollection.add(FileCollection)]
 * link:{javadocPath}/org/gradle/api/file/FileCollection.html#stopExecutionIfEmpty--[FileCollection.stopExecutionIfEmpty()]
 * link:{javadocPath}/org/gradle/plugins/signing/Signature.html#getToSignArtifact--[Signature.toSignArtifact]

=== Potential breaking changes

 * Build will now fail if a specified init script is not found.
 * `TaskContainer.remove()` now actually removes the given task — some plugins may have accidentally relied on the old behavior.
 * link:{javadocPath}/org/gradle/plugins/signing/Signature.html#setFile-java.io.File-[Signature.setFile(File)] no longer does anything and is deprecated.
 * <<#rel4.8:pom_wildcard_exclusions,Gradle now honors implicit wildcards in Maven POM exclusions>>.
 * The Kotlin DSL now respects JSR-305 package annotations.
+
This will lead to some types annotated according to JSR-305 being treated as nullable where they were treated as non-nullable before. This may lead to compilation errors in the build script. See https://github.com/gradle/kotlin-dsl/releases/tag/v0.17.4[the relevant Kotlin DSL release notes] for details.
 * Error messages will be directed to standard error rather than standard output now, unless a console is attached to both standard output and standard error. This may affect tools that scrape a build's plain console output. Ignore this change if you're upgrading from an earlier version of Gradle.

[[changes_4.7]]
== Changes in 4.7

=== Deprecated classes, methods and properties

Follow the API links to learn how to deal with these deprecations (if no extra information is provided here):

 * link:{javadocPath}/org/gradle/api/file/FileCollection.html#asType-java.lang.Class-[FileCollection.asType(Class)] for file types, such as `File` and `FileTree`. This method is used by Groovy's `as` keyword, e.g. `someFileCollection as File[]`
 * link:{groovyDslPath}/org.gradle.api.Task.html#org.gradle.api.Task:deleteAllActions()[Task.deleteAllActions()] — this has no replacement

=== Other deprecations

 * The new location by convention of Checkstyle configuration files is in the root project's _config/checkstyle_ directory, not that of the subprojects.
+
For now, by-convention config files in subprojects will override any in the root project in order to maintain backwards compatibility.

=== Potential breaking changes

 * The structure of Gradle's <<#rel4.7:plain_console_output,plain console output>> has changed, which may break tools that scrape that output.
 * The APIs of many native tasks related to compilation, linking and installation <<rel:4.6:native_task_api_changes,have changed in breaking ways>>.
 * [Kotlin DSL] Delegated properties used to access Gradle's build properties — defined in _gradle.properties_ for example — must now be explicitly typed.
 * [Kotlin DSL] Declaring a `plugins {}` block inside a nested scope now throws an exception.
 * [Kotlin DSL] Only one `pluginManagement {}` block is allowed now.
 * The cache control DSL provided by the `org.gradle.api.artifacts.cache.*` interfaces are no longer available.
 * `getEnabledDirectoryReportDestinations()`, `getEnabledFileReportDestinations()` and `getEnabledReportNames()` have all been removed from `org.gradle.api.reporting.ReportContainer`.
 * link:{javadocPath}/org/gradle/StartParameter.html#getProjectProperties--[StartParameter.projectProperties] and link:{javadocPath}/org/gradle/StartParameter.html#getSystemPropertiesArgs--[StartParameter.systemPropertiesArgs] now return immutable maps.

[[changes_4.6]]
== Changes in 4.6

There is now improved POM support in Gradle that will be enabled by default in Gradle 5.0. Add the line

    enableFeaturePreview('IMPROVED_POM_SUPPORT')

to your _settings.gradle_ file to get the following:

 * <<#rel4.6:bom_import,BOM import>>
 * <<#rel4.6:pom_optional_dependencies,Support for optional dependencies when consuming POMs>>
 * <<#rel4.6:pom_compile_runtime_separation,Separation of compile and runtime dependencies when consuming POMs>>

Note that some of these features may break your build.

=== Deprecated classes, methods and properties

Follow the API links to learn how to deal with these deprecations (if no extra information is provided here):

 * link:{javadocPath}/org/gradle/api/file/FileCollection.html#asType-java.lang.Class-[FileCollection.asType(Class)] for file types, such as `File` and `FileTree`. This method is used by Groovy's `as` keyword, e.g. `someFileCollection as File[]`
 * link:{groovyDslPath}/org.gradle.api.Task.html#org.gradle.api.Task:deleteAllActions()[Task.deleteAllActions()] — this has no replacement
 * link:{javadocPath}/org/gradle/caching/local/DirectoryBuildCache.html#setTargetSizeInMB-long-[DirectoryBuildCache.setTargetSizeInMB(long)], i.e. the `targetSizeInMB` configuration property for local build caches

=== Other deprecations

[[rel4.6:annotation_processor_configuration]]
 * You should not put annotation processors on the compile classpath or declare them with the `-processorpath` compiler argument.
+
They should be added to the `annotationProcessor` configuration instead. If you don't want any processing, but your compile classpath contains a processor unintentionally (e.g. as part of a library you depend on), use the `-proc:none` compiler argument to ignore it.
 * Upgrade from Play 2.2 to a newer version.
 * Use link:{javadocPath}/org/gradle/process/CommandLineArgumentProvider.html[CommandLineArgumentProvider] in place of link:{javadocPath}/org/gradle/api/tasks/compile/CompilerArgumentProvider.html[CompilerArgumentProvider].

=== Potential breaking changes

 * The Java plugins now add a `__sourceSet__AnnotationProcessor` configuration for each source set, which might break if any of them match existing configurations you have. We recommend you remove your conflicting configuration declarations.
 * The `StartParameter.taskOutputCacheEnabled` property has been replaced by link:{javadocPath}/org/gradle/StartParameter.html#setBuildCacheEnabled-boolean-[StartParameter.setBuildCacheEnabled(boolean)].
 * The Visual Studio integration now only <<#rel4.6:visual_studio_single_solution,configures a single solution for all components in a build>>.
 * Gradle has replaced HttpClient 4.4.1 with version 4.5.5.
 * Gradle now bundles the `kotlin-stdlib-jdk8` artifact instead of `kotlin-stdlib-jre8`. This may affect your build. Please see the http://kotlinlang.org/docs/reference/whatsnew12.html#kotlin-standard-library-artifacts-and-split-packages[Kotlin documentation] for more details.

[[changes_4.5]]
== Changes in 4.5

 * Make sure you have a _settings.gradle_ file: it avoids a performance penalty and allows you to set the root project's name. Also, the `-u`/`--no-search-upward` command line option that allowed you to bypass the performance penalty is now deprecated.
 * Gradle now ignores the build cache configuration of included builds (<<composite_builds.adoc#composite_builds,composite builds>>) and instead uses the root build's configuration for all the builds.

=== Potential breaking changes

 * Two overloaded `ValidateTaskProperties.setOutputFile()` methods were removed. They are replaced with auto-generated setters when the task is accessed from a build script, but that won't be the case from plugins and other code outside of the build script.
 * The Maven Publish Plugin now produces more complete maven-metadata.xml files, including maintaining a list of `<snapshotVersion>` elements. Some older versions of Maven may not be able to consume this metadata.
 * <<#rel4.5:http_build_cache_no_follow_redirects,`HttpBuildCache` no longer follows redirects>>.
 * The `Depend` task type has been removed.
 * link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:file(java.lang.Object)[Project.file(Object)] no longer normalizes case for file paths on case-insensitive file systems. It now ignores case in such circumstances and does not touch the file system.
 * link:{javadocPath}/org/gradle/api/provider/ListProperty.html[ListProperty] no longer extends link:{javadocPath}/org/gradle/api/provider/Property.html[Property].

[[changes_4.4]]
== Changes in 4.4

 * Don't use the `-a`/`--no-rebuild` command-line option: it will be removed in Gradle 5.0.

=== Potential breaking changes

 * link:{groovyDslPath}/org.gradle.api.tasks.testing.AbstractTestTask.html[AbstractTestTask] is now extended by non-JVM test tasks as well as link:{groovyDslPath}/org.gradle.api.tasks.testing.Test.html[Test]. Plugins should beware configuring all tasks of type `AbstractTestTask` because of this.
 * The default output location for link:{groovyDslPath}/org.gradle.plugins.ide.eclipse.model.EclipseClasspath.html#org.gradle.plugins.ide.eclipse.model.EclipseClasspath:defaultOutputDir[EclipseClasspath.defaultOutputDir] has changed from __``$projectDir``/bin__ to __``$projectDir``/bin/default__.
 * The deprecated `InstallExecutable.setDestinationDir(Provider)` was removed — use link:{groovyDslPath}/org.gradle.nativeplatform.tasks.InstallExecutable.html#org.gradle.nativeplatform.tasks.InstallExecutable:installDirectory[InstallExecutable.installDirectory] instead.
 * The deprecated `InstallExecutable.setExecutable(Provider)` was removed — use link:{groovyDslPath}/org.gradle.nativeplatform.tasks.InstallExecutable.html#org.gradle.nativeplatform.tasks.InstallExecutable:executableFile[InstallExecutable.executableFile] instead.
 * Gradle will no longer prefer a version of Visual Studio found on the path over other locations. It is now a last resort.
+
You can bypass the toolchain discovery by specifying the installation directory of the version of Visual Studio you want via link:{groovyDslPath}/org.gradle.nativeplatform.toolchain.VisualCpp.html#org.gradle.nativeplatform.toolchain.VisualCpp:installDir[VisualCpp.setInstallDir(Object)].
 * `pluginManagement.repositories` is now of type link:{groovyDslPath}/org.gradle.api.artifacts.dsl.RepositoryHandler.html[RepositoryHandler] rather than `PluginRepositoriesSpec`, which has been removed.
 * 5xx HTTP errors during dependency resolution will now trigger exceptions in the build.
 * The embedded Apache Ant has been upgraded from 1.9.6 to 1.9.9.
 * <<#rel4.4:security_library_upgrades,Several third-party libraries used by Gradle have been upgraded>> to fix security issues.

[[changes_4.3]]
== Changes in 4.3

 * The `plugins {}` block can now be <<plugins.adoc#sec:subprojects_plugins_dsl,used in subprojects>> and for <<plugins.adoc#sec:buildsrc_plugins_dsl,plugins in the _buildSrc_ directory>>.

=== Deprecated classes, methods and properties

Follow the API links to learn how to deal with these deprecations (if no extra information is provided here):

 * `TaskInternal.execute()` — this was sometimes used to invoke a task directly from plugins or other tasks in a mistaken attempt to reuse code. Do not execute tasks directly. Consider using task dependencies, task rules, reusable utility methods, or the <<custom_tasks.adoc#worker_api,Worker API>> instead.
 * link:{javadocPath}/org/gradle/api/tasks/TaskDestroyables.html#file-java.lang.Object-[TaskDestroyables.file(Object)]
 * link:{javadocPath}/org/gradle/api/tasks/TaskDestroyables.html#files-java.lang.Object++...++-[TaskDestroyables.files(Object...)]
 * link:{javadocPath}/org/gradle/api/provider/PropertyState.html[PropertyState]
 * link:{javadocPath}/org/gradle/api/file/DirectoryVar.html[DirectoryVar]
 * link:{javadocPath}/org/gradle/api/file/RegularFileVar.html[RegularFileVar]
 * link:{javadocPath}/org/gradle/api/file/ProjectLayout.html#newDirectoryVar--[ProjectLayout.newDirectoryVar()]
 * link:{javadocPath}/org/gradle/api/file/ProjectLayout.html#newFileVar--[ProjectLayout.newFileVar()]
 * link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:property(java.lang.Class)[Project.property(Class)]
 * link:{javadocPath}/org/gradle/api/Script.html#property-java.lang.Class-[Script.property(Class)]
 * link:{javadocPath}/org/gradle/api/provider/ProviderFactory.html#property-java.lang.Class-[ProviderFactory.property(Class)]
 * link:{groovyDslPath}/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:bootClasspath[CompileOptions.bootClasspath]

=== Other deprecations

 * You should no longer run Gradle versions older than 2.6 via the Tooling API.
 * You should no longer run any version of Gradle via an older version of the Tooling API than 3.0.
 * You should no longer chain link:{javadocPath}/org/gradle/api/tasks/TaskInputs.html#property-java.lang.String-java.lang.Object-[TaskInputs.property(String,Object)] and link:{javadocPath}/org/gradle/api/tasks/TaskInputs.html#properties-java.util.Map-[TaskInputs.properties(Map)] methods.
 * You should not call link:{javadocPath}/org/gradle/api/tasks/TaskInputs.html#file-java.lang.Object-[TaskInputs.file(Object)] with an argument that resolves to anything other than a single regular file.
 * You should not call link:{javadocPath}/org/gradle/api/tasks/TaskInputs.html#dir-java.lang.Object-[TaskInputs.dir(Object)] with an argument that resolves to anything other than a single directory.
 * You should no longer use the `--recompile-scripts` command-line option.

=== Potential breaking changes

 * link:{javadocPath}/org/gradle/api/DefaultTask.html#newOutputDirectory--[DefaultTask.newOutputDirectory()] now returns a `DirectoryProperty` instead of a `DirectoryVar`.
 * link:{javadocPath}/org/gradle/api/DefaultTask.html#newOutputFile--[DefaultTask.newOutputFile()] now returns a `RegularFileProperty` instead of a `RegularFileVar`.
 * link:{javadocPath}/org/gradle/api/DefaultTask.html#newInputFile--[DefaultTask.newInputFile()] now returns a `RegularFileProperty` instead of a `RegularFileVar`.
 * link:{javadocPath}/org/gradle/api/file/ProjectLayout.html#getBuildDirectory--[ProjectLayout.buildDirectory] now returns a `DirectoryProperty` instead of a `DirectoryVar`.
 * link:{groovyDslPath}/org.gradle.language.nativeplatform.tasks.AbstractNativeCompileTask.html#org.gradle.language.nativeplatform.tasks.AbstractNativeCompileTask:compilerArgs[AbstractNativeCompileTask.compilerArgs] is now of type `ListProperty<String>` instead of `List<String>`.
 * link:{groovyDslPath}/org.gradle.language.nativeplatform.tasks.AbstractNativeCompileTask.html#org.gradle.language.nativeplatform.tasks.AbstractNativeCompileTask:objectFileDir[AbstractNativeCompileTask.objectFileDir] is now of type `DirectoryProperty` instead of `File`.
 * link:{groovyDslPath}/org.gradle.nativeplatform.tasks.AbstractLinkTask.html#org.gradle.nativeplatform.tasks.AbstractLinkTask:linkerArgs[AbstractLinkTask.linkerArgs] is now of type `ListProperty<String>` instead of `List<String>`.
 * `TaskDestroyables.getFiles()` is no longer part of the public API.
 * Overlapping version ranges for a dependency now result in Gradle picking a version that satisfies all declared ranges.
+
For example, if a dependency on `some-module` is found with a version range of `[3,6]` and also transitively with a range of `[4,8]`, Gradle now selects version 6 instead of 8. The prior behavior was to select 8.
 * The order of elements in `Iterable` properties marked with either `@OutputFiles` or `@OutputDirectories` now matters. If the order changes, the property is no longer considered up to date.
+
Prefer using separate properties with `@OutputFile`/`@OutputDirectory` annotations or use `Map` properties with `@OutputFiles`/`@OutputDirectories` instead.
 * Gradle will no longer ignore dependency resolution errors from a repository when there is another repository it can check. Dependency resolution will fail instead. This results in more deterministic behavior with respect to resolution results.

[[changes_4.2]]
== Changes in 4.2

=== Deprecations

 * You should no longer use any of the following characters in domain object names, such as project and task names: <space> `/ \ : < > " ? * |`. You should also not use `.` as a leading or trailing character.

=== Potential breaking changes

 * The `withPathSensitivity()` methods on link:{javadocPath}/org/gradle/api/tasks/TaskFilePropertyBuilder.html[TaskFilePropertyBuilder] and link:{javadocPath}/org/gradle/api/tasks/TaskOutputFilePropertyBuilder.html[TaskOutputFilePropertyBuilder] have been removed.
 * The bundled `bndlib` has been upgraded from 3.2.0 to 3.4.0.
 * The FindBugs Plugin no longer renders progress information from its analysis. If you rely on that output in any way, you can enable it with link:{groovyDslPath}/org.gradle.api.plugins.quality.FindBugs.html#org.gradle.api.plugins.quality.FindBugs:showProgress[FindBugs.showProgress].

[[changes_4.1]]
== Changes in 4.1

 * Consider using the new <<custom_tasks.adoc#worker_api,Worker API>> to enable units of work within your build to run in parallel.

=== Deprecated classes, methods and properties

Follow the API links to learn how to deal with these deprecations (if no extra information is provided here):

 * link:{javadocPath}/org/gradle/api/tasks/scala/ScalaDocOptions.html#getStyleSheet--[ScalaDocOptions.styleSheet] — the Scaladoc Ant task in Scala 2.11.8 and later no longer support this property.
 * link:{javadocPath}/org/gradle/api/Nullable.html[Nullable]
 * link:{javadocPath}/org/gradle/api/Task.html#dependsOnTaskDidWork--[Task.dependsOnTaskDidWork()]

=== Potential breaking changes

 * Non-Java projects that have a <<dependency_types.adoc#sub:project_dependencies,project dependency>> on a Java project now consume the `runtimeElements` configuration by default instead of the `default` configuration.
+
To override this behavior, you can explicitly declare the configuration to use in the project dependency. For example: `project(path: ':myJavaProject', configuration: 'default')`.
 * Default Zinc compiler upgraded from 0.3.13 to 0.3.15.
 * [Kotlin DSL] Base package renamed from `org.gradle.script.lang.kotlin` to `org.gradle.kotlin.dsl`.


== Changes in detail

[[rel4.10:aws_s3_permissions]]
=== [4.10] Publishing to AWS S3 requires new permissions

The S3 repository transport protocol allows Gradle to publish artifacts to AWS S3 buckets. Starting with this release, every artifact uploaded to an S3 bucket will be equipped with the `bucket-owner-full-control` canned ACL. Make sure that the AWS account used to publish artifacts has the `s3:PutObjectAcl` and `s3:PutObjectVersionAcl` permissions, otherwise the upload will fail.

[source,json]
----
{
    "Version":"2012-10-17",
    "Statement":[
        // ...
        {
            "Effect":"Allow",
            "Action":[
                "s3:PutObject", // necessary for uploading objects
                "s3:PutObjectAcl", // required starting with this release
                "s3:PutObjectVersionAcl" // if S3 bucket versioning is enabled
            ],
            "Resource":"arn:aws:s3:::myCompanyBucket/*"
        }
    ]
}
----

See <<repository_types#sub:s3_cross_account,AWS S3 Cross Account Access>> for more information.

[[rel4.9:lazy_task_creation]]
=== [4.9] Consider trying the lazy API for task creation and configuration

Gradle 4.9 introduced a new way to create and configure tasks that works lazily. When you use this approach for tasks that are expensive to configure, or when you have many, many tasks, your build configuration time can drop significantly when those tasks don't run.

You can learn more about lazily creating tasks in the <<task_configuration_avoidance#task_configuration_avoidance,Task Configuration Avoidance>> chapter. You can also read about the background to this new feature in https://blog.gradle.org/preview-avoiding-task-configuration-time[this blog post].

[[rel4.8:switch_to_publishing_plugins]]
=== [4.8] Switch to the Maven Publish and Ivy Publish Plugins

Now that the publishing plugins are stable, we recommend that you migrate from the <<artifact_management.adoc#artifact_management,legacy publishing>> mechanism for standard Java projects, i.e. those based on the <<java_plugin#java_plugin,Java Plugin>>. That includes projects that use any one of: <<java_library_plugin#java_library_plugin,Java Library Plugin>>, <<application_plugin#application_plugin,Application Plugin>> or <<war_plugin#war_plugin,War Plugin>>.

To use the new approach, simply replace any `upload<Conf>` configuration with a `publishing {}` block. See the <<publishing_overview.adoc#publishing_overview,publishing overview chapter>> for more information.

[[rel4.8:deferred_configuration]]
=== [4.8] Use deferred configuration for publishing plugins

Prior to Gradle 4.8, the `publishing {}` block was implicitly treated as if all the logic inside it was executed after the project was evaluated.
This was confusing, because it was the only block that behaved that way.
As part of the stabilization effort in Gradle 4.8, we are deprecating this behavior and asking all users to migrate their build.

The new, stable behavior can be switched on by adding the following to your settings file:

    enableFeaturePreview('STABLE_PUBLISHING')

We recommend doing a test run with a local repository to see whether all artifacts still have the expected coordinates. In most cases everything should work as before and you are done. However, your publishing block may rely on the implicit deferred configuration, particularly if it relies on values that may change during the configuration phase of the build.

For example, under the new behavior, the following logic assumes that `jar.baseName` doesn't change after `artifactId` is set:

[source,groovy]
----
subprojects {
    publishing {
        publications {
            mavenJava {
                from components.java
                artifactId = jar.baseName
            }
        }
    }
}
----

If that assumption is incorrect or might possibly be incorrect in the future, the `artifactId` must be set within an `afterEvaluate {}` block, like so:


[source,groovy]
----
subprojects {
    publishing {
        publications {
            mavenJava {
                from components.java
                afterEvaluate {
                    artifactId = jar.baseName
                }
            }
        }
    }
}
----

[[rel4.8:configure_internal_tasks]]
=== [4.8] Configure existing `wrapper` and `init` tasks

You should no longer define your own `wrapper` and `init` tasks. Configure the existing tasks instead, for example by converting this:

----
task wrapper(type: Wrapper) {
    ...
}
----

to this:

----
wrapper {
    ...
}
----

[[rel4.8:pom_wildcard_exclusions]]
=== [4.8] Gradle now honors implicit wildcards in Maven POM exclusions

If an exclusion in a Maven POM was missing either a `groupId` or `artifactId`, Gradle used to ignore the exclusion. Now the missing elements are treated as implicit wildcards — e.g. `<groupId>*</groupId>` — which means that some of your dependencies may now be excluded where they weren't before.

You will need to explicitly declare any missing dependencies that you need.

[[rel4.7:plain_console_output]]
=== [4.7] Changes to the structure of Gradle's plain console output

The plain console mode now formats output consistently with the rich console, which means that the output format has changed. For example:

 * The output produced by a given task is now grouped together, even when other tasks execute in parallel with it.
 * Task execution headers are printed with a "> Task" prefix.
 * All output produced during build execution is written to the standard output file handle. This includes messages written to System.err unless you are redirecting standard error to a file or any other non-console destination.

This may break tools that scrape details from the plain console output.

[[rel:4.6:native_task_api_changes]]
=== [4.6] Changes to the APIs of native tasks related to compilation, linking and installation

Many tasks related to compiling, linking and installing native libraries and applications have been converted to the Provider API so that they support <<lazy_configuration.adoc#lazy_configuration,lazy configuration>>. This conversion has introduced some breaking changes to the APIs of the tasks so that they match the conventions of the Provider API.

The following tasks have been changed:

link:{groovyDslPath}/org.gradle.nativeplatform.tasks.AbstractLinkTask.html[AbstractLinkTask] and its subclasses::
 * `getDestinationDir()` was replaced by `getDestinationDirectory()`.
 * `getBinaryFile()`, `getOutputFile()` was replaced by `getLinkedFile()`.
 * `setOutputFile(File)` was removed. Use `Property.set()` instead.
 * `setOutputFile(Provider)` was removed. Use `Property.set()` instead.
 * `getTargetPlatform()` was changed to return a `Property`.
 * `setTargetPlatform(NativePlatform)` was removed. Use `Property.set()` instead.
 * `getToolChain()` was changed to return a `Property`.
 * `setToolChain(NativeToolChain)` was removed. Use `Property.set()` instead.

link:{groovyDslPath}/org.gradle.nativeplatform.tasks.CreateStaticLibrary.html[CreateStaticLibrary]::
 * `getOutputFile()` was changed to return a `Property`.
 * `setOutputFile(File)` was removed. Use `Property.set()` instead.
 * `setOutputFile(Provider)` was removed. Use `Property.set()` instead.
 * `getTargetPlatform()` was changed to return a `Property`.
 * `setTargetPlatform(NativePlatform)` was removed. Use `Property.set()` instead.
 * `getToolChain()` was changed to return a `Property`.
 * `setToolChain(NativeToolChain)` was removed. Use `Property.set()` instead.
 * `getStaticLibArgs()` was changed to return a `ListProperty`.
 * `setStaticLibArgs(List)` was removed. Use `ListProperty.set()` instead.

link:{groovyDslPath}/org.gradle.nativeplatform.tasks.InstallExecutable.html[InstallExecutable]::
 * `getSourceFile()` was replaced by `getExecutableFile()`.
 * `getPlatform()` was replaced by `getTargetPlatform()`.
 * `setTargetPlatform(NativePlatform)` was removed. Use `Property.set()` instead.
 * `getToolChain()` was changed to return a `Property`.
 * `setToolChain(NativeToolChain)` was removed. Use `Property.set()` instead.

The following have also seen similar changes:

 * link:{groovyDslPath}/org.gradle.language.assembler.tasks.Assemble.html[Assemble]
 * link:{groovyDslPath}/org.gradle.language.rc.tasks.WindowsResourceCompile.html[WindowsResourceCompile]
 * link:{javadocPath}/org/gradle/nativeplatform/tasks/StripSymbols.html[StripSymbols]
 * link:{javadocPath}/org/gradle/nativeplatform/tasks/ExtractSymbols.html[ExtractSymbols]
 * link:{javadocPath}/org/gradle/language/swift/tasks/SwiftCompile.html[SwiftCompile]
 * link:{javadocPath}/org/gradle/nativeplatform/tasks/LinkMachOBundle.html[LinkMachOBundle]

[[rel4.6:bom_import]]
=== [4.6] BOM import

Gradle now provides support for importing bill of materials (BOM) files, which are effectively POM files that use `<dependencyManagement>` sections to control the versions of direct and transitive dependencies. All you need to do is declare the POM as just another dependency.

The following example picks the versions of the `gson` and `dom4j` dependencies from the declared Spring Boot BOM:

----
dependencies {
    // import a BOM
    implementation 'org.springframework.boot:spring-boot-dependencies:1.5.8.RELEASE'

    // define dependencies without versions
    implementation 'com.google.code.gson:gson'
    implementation 'dom4j:dom4j'
}
----


[[rel4.6:pom_optional_dependencies]]
=== [4.6] Support for optional dependencies when consuming POMs

Gradle now creates a <<managing_transitive_dependencies.adoc#sec:dependency_constraints,dependency constraint>> for each dependency declaration in a POM file with an `<optional>true</optional>` element. This results in the expected behavior:

 * The dependency module is ignored if it is only ever declared as optional.
 * If the dependency module is also declared elsewhere as not optional, then the constraint derived from the optional dependency declaration is considered when picking the version.

In other words, if an optional dependency has a declared version higher than another, non-optional one, the optional dependency's version is used by default. However, Gradle does add solely optional dependencies to the dependency graph, which means you won't see them in the associated configuration's set of files.

[[rel4.6:pom_compile_runtime_separation]]
=== [4.6] Separation of compile and runtime dependencies when consuming POMs

Since Gradle 1.0, runtime-scoped dependencies have been included in the Java compilation classpath, which has some drawbacks:

 * The compilation classpath is much larger than it needs to be, slowing down compilation.
 * The compilation classpath includes runtime-scoped files that do not impact compilation, resulting in unnecessary re-compilation when those files change.

With this new behavior, the Java and Java Library plugins both honor the <<java_library_plugin.adoc#sec:java_library_separation,separation of compile and runtime scopes>>. This means that the compilation classpath only includes compile-scoped dependencies, while the runtime classpath adds the runtime-scoped dependencies as well. This is particularly useful if you develop and publish Java libraries with Gradle where the separation between `api` and `implementation` dependencies is reflected in the published scopes.

[[rel4.6:visual_studio_single_solution]]
=== [4.6] Visual Studio integration only supports a single solution file for all components of a build

link:{groovyDslPath}/org.gradle.ide.visualstudio.VisualStudioExtension.html[VisualStudioExtension] no longer has a `solutions` property. Instead, you configure a single solution via link:{groovyDslPath}/org.gradle.ide.visualstudio.VisualStudioRootExtension.html[VisualStudioRootExtension] in the root project, like so:

----
model {
    visualStudio {
        solution {
            solutionFile.location = "vs/${name}.sln"
        }
    }
}
----

In addition, there are no longer individual tasks to generate the solution files for each component, but rather a single `visualStudio` task that generates a solution file that encompasses all components in the build.

[[rel4.5:http_build_cache_no_follow_redirects]]
=== [4.5] `HttpBuildCache` no longer follows redirects

When connecting to an HTTP build cache backend via `HttpBuildCache`, Gradle does not follow redirects any more, treating them as errors instead. Getting a redirect from the build cache backend is mostly a configuration error — using an "http" URL instead of "https" for example — and has negative effects on performance.

[[rel4.4:security_library_upgrades]]
=== [4.4] Third-party dependency upgrades

This version includes several upgrades of third-party dependencies:

 * jackson: 2.6.6 -> 2.8.9
 * plexus-utils: 2.0.6 -> 2.1
 * xercesImpl: 2.9.1 -> 2.11.0
 * bsh: 2.0b4 -> 2.0b6
 * bouncycastle: 1.57 -> 1.58

This fix the following security issues:

 * http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-7525[CVE-2017-7525] (critical)
 * SONATYPE-2017-0359 (critical)
 * SONATYPE-2017-0355 (critical)
 * SONATYPE-2017-0398 (critical)
 * https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4002[CVE-2013-4002] (critical)
 * https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-2510[CVE-2016-2510] (severe)
 * SONATYPE-2016-0397 (severe)
 * https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-2625[CVE-2009-2625] (severe)
 * SONATYPE-2017-0348 (severe)

Gradle does not expose public APIs for these 3rd-party dependencies, but those who customize Gradle will want to be aware.

