// Copyright 2018 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= Gradle Documentation Home

Welcome to Gradle, an open-source build automation tool that focuses on flexibility and performance. We have a wealth of documentation here to help you learn and master it.

== Getting started

If you're new to Gradle, start with the <<getting_started#getting_started,Getting Started page>>, which will explain what Gradle is and introduce you to other documentation that will guide you through the first steps of learning to use the tool.

== Tutorials

We provide HOWTO-style tutorials at our link:{guidesUrl}/[Gradle Guides] site. They are designed to teach you aspects of Gradle by getting you to work through various scenarios and actively use Gradle. They are also designed not to take up much of your time.

Note that you can filter the guides by various categories — such as link:{guidesUrl}/?q=Fundamentals[Fundamentals] — and also search by guide title.

== User manual

The user manual describes all the significant features of Gradle and explains how to use them. The left navigation bar provides the links to the manual's various chapters under the sections _Running Gradle Builds_, _Authoring Gradle Builds_, and _Extending Gradle_.

The manual contains a huge amount of content, so don't expect to read it from cover to cover (as it were). However, we do recommend investing some time in reading whole chapters or large sections as a whole to get a better grounding in Gradle. You can pick out just the paragraphs and small sections relevant to a particular problem, but doing so exclusively will leave you with a less useful and broad understanding of how Gradle works and how to make best use of its features.

== Migrations and upgrades

Many of you will be migrating from another build tool and so we have some dedicated guides to help you do that. It's also very common for users to upgrade their version of Gradle to take advantage of new features and bug fixes, so we also have help on that front.

Here are the current migration and upgrade guides:

 * link:{guidesUrl}/migrating-from-maven/[Migrating from Maven]
 * link:{guidesUrl}/migrating-build-logic-from-groovy-to-kotlin/[Migrating build logic from Groovy to Kotlin]
 * <<upgrading_version_4#upgrading_version_4,Upgrading your builds from Gradle 4.x to 5.0>>

== Reference documentation

Gradle has an extensive API and lots of prepackaged functionality that you can use. Although much of it is covered in the user manual, you will often want to look up specific information about a type or plugin. That's where the reference documentation comes in:

 * link:{groovyDslPath}/[Groovy DSL reference] — covers the most common and important parts of Gradle's public API, with a focus on Groovy-based build scripts
 * link:{javadocPath}/[Javadoc API reference] — provides comprehensive coverage of Gradle's public API in the standard Javadoc HTML format
 * https://gradle.github.io/kotlin-dsl-docs/api/[Kotlin DSL reference] — provides comprehensive coverage of Gradle's public API, including additional Kotlin-specific types, in standard Dokka format
 * <<plugin_reference#plugin_reference,Plugin reference>> — lists all the core plugins packaged with Gradle and links to their documentation
 * <<third_party_integration#third_party_integration,Third-party integrations>> — lists various tools that integrate with Gradle, such as IDEs and continous integration systems

== Other sources of help

 * **Forum** — The fastest way to get help is through the link:https://discuss.gradle.org[Gradle Forum, title="Gradle help and discussion forums"]. Community members and core contributors answer your questions.
 * **Training** — Free, web-based Gradle training from Gradle developers happens every month. Head over to the link:{website}/training/[training page, title="Gradle training schedule"] to sign up.
 * **Enterprise Services** — Support and training can be purchased alongside a link:https://gradle.com/enterprise[Gradle Enterprise] subscription.

== Licenses

[.legalnotice]
Gradle build tool source code is open and licensed under the link:https://github.com/gradle/gradle/blob/master/LICENSE[Apache License 2.0].
Gradle user manual and DSL references are licensed under link:http://creativecommons.org/licenses/by-nc-sa/4.0/[Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License].
