// Copyright 2018 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[gradle_overview]]
[[what_is_gradle]]
= What is Gradle?

== Gradle Build Tool

Gradle Build Tool is a fast, dependable, and adaptable open-source https://en.wikipedia.org/wiki/Build_automation[build automation] tool with an elegant and extensible declarative build language.

In this User Manual, Gradle Build Tool is called **Gradle**.

== Why Gradle?

Gradle is a widely used and mature built tool with an active community and a strong developer ecosystem. So why Gradle?

* Gradle is the most popular build system for JVM and the default in Android and Kotlin Multi-Platform with a rich community plugin ecosystem.
* Gradle can automate a wide range of software build automation scenarios, either through built-in functionality, plugins, or custom build logic.
* Gradle provides a high-level, declarative, and expressive build language that makes it easy to both read and write build logic.
* Gradle is fast, scalable, and can build projects of any size and complexity.
* Gradle produces dependable results, even with optimizations such as incremental builds, build caching, or parallel execution.

Several major IDEs support Gradle, including Android Studio, IntelliJ IDEA, Visual Studio Code, Eclipse, and NetBeans.

Gradle provides a free service called https://scans.gradle.com/[Build Scan®] which provides extensive information about a build that you can use to identify problems or share for debugging help.
