// Copyright (C) 2024 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[part4_unit_test]]
= Part 4: Writing a Unit Test

Learn the basics of unit testing your plugin.

****
**In this section, you will:**

- Write a Unit Test for your plugin
- Run a Unit Test to test your plugin
****

[[part4_begin]]
== Step 0. Before you Begin

1. You initialized your plugin in <<part1_gradle_init_plugin.adoc#part1_begin,part 1>>.
2. You added an extension to your plugin in <<part2_add_extension.adoc#part2_begin,part 2>>.
3. You created a custom task in <<part3_create_custom_task.adoc#part3_begin, part3>>.

== Step 1. About Unit Tests

Grade init provides a sample unit test that we can reuse.
[.multi-language-text.lang-kotlin]
----
It is available in `src/test/kotlin/org/example/PluginTutorialPluginTest.kt`.
----
[.multi-language-text.lang-groovy]
----
It is available in `src/test/groovy/org/example/PluginTutorialPluginTest.groovy`.
----
Let's take a look:

====
include::sample[dir="snippets/plugins/plugin-tutorial/kotlin",files="plugin/src/test/kotlin/org/example/PluginTutorialPluginTest.kt[tags=init-test]"]
include::sample[dir="snippets/plugins/plugin-tutorial/groovy",files="plugin/src/test/groovy/org/example/PluginTutorialPluginTest.groovy[tags=init-test]"]
====

It is quite simple, it applies the `org.example.greeting` plugin and verifies that the `greeting` task is available.

== Step 2. Update the Test

[.multi-language-text.lang-kotlin]
----
First, update the name of the file from `PluginTutorialPluginTest.kt` to `SlackPluginTest.kt`.
----
[.multi-language-text.lang-groovy]
----
First, update the name of the file from `PluginTutorialPluginTest.groovy` to `SlackPluginTest.groovy`.
----

Second, update your test so it looks as follows:

====
include::sample[dir="snippets/plugins/plugin-tutorial/kotlin",files="plugin/src/test/kotlin/org/example/SlackPluginTest.kt[]"]
include::sample[dir="snippets/plugins/plugin-tutorial/groovy",files="plugin/src/test/groovy/org/example/SlackPluginTest.groovy[]"]
====

We are essentially re-using the unit test from Gradle init as-is.

This test creates a fake Gradle project in memory, applies the plugin, and checks that it registered the `sendTestSlackMessage` task.

1. **`ProjectBuilder.builder().build()`** - makes a test project (no files, no real build).
2. **`project.plugins.apply(...)`** - applies your plugin to it.
3. **`assertNotNull(...)`** - confirms the task exists after the plugin is applied.

== Step 3. Run the Test

Then, you can run the `test` task and ensure it passes.

[source,text]
----
$ ./gradlew test

> Task :plugin:checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :plugin:processTestResources NO-SOURCE
> Task :plugin:pluginDescriptors UP-TO-DATE
> Task :plugin:processResources UP-TO-DATE
> Task :plugin:compileKotlin UP-TO-DATE
> Task :plugin:compileJava NO-SOURCE
> Task :plugin:classes UP-TO-DATE
> Task :plugin:pluginUnderTestMetadata UP-TO-DATE
> Task :plugin:jar UP-TO-DATE
> Task :plugin:compileTestKotlin
> Task :plugin:compileTestJava NO-SOURCE
> Task :plugin:testClasses UP-TO-DATE
> Task :plugin:test

BUILD SUCCESSFUL in 1s
7 actionable tasks: 2 executed, 5 up-to-date
----

You can optionally add another test or change the existing test to get it to fail.

[.text-right]
**Next Step:** <<part5_add_dataflow_action#part5_add_dataflow_action,Add a DataFlow Action>> >>
