// Copyright (C) 2024 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[part7_use_consumer_project]]
= Part 7: Use a Consumer Project

Learn how to set up a dummy `consumer` project to test your plugin.

****
**In this section, you will:**

- Create a `consumer` Project
- Test the Plugin
****

[[part7_begin]]
== Step 0. Before you Begin

1. You initialized your plugin in <<part1_gradle_init_plugin.adoc#part1_begin,part 1>>.
2. You added an extension to your plugin in <<part2_add_extension.adoc#part2_begin,part 2>>.
3. You created a custom task in <<part3_create_custom_task.adoc#part3_begin, part3>>.
4. You wrote a unit test in <<part4_unit_test.adoc#part4_begin,part 4>>.
5. You added a dataflow action to your plugin in <<part5_add_dataflow_action.adoc#part5_begin,part 2>>.
6. You wrote a functional test in <<part6_functional_test.adoc#part6_begin,part 6>>.

== Step 1. Create `consumer` Project

Create a sibling `consumer` build to try the plugin without publishing anything.
Update your directory structure so it looks as follows:

[.multi-language-sample]
=====
[source, kotlin]
----
.
├── gradlew
├── settings.gradle.kts
├── plugin/
└── consumer/   //<1>
    ├── settings.gradle.kts
    └── build.gradle.kts
----
<1> Create a `consumer` project
=====
[.multi-language-sample]
=====
[source, groovy]
----
.
├── gradlew
├── settings.gradle
├── plugin/
└── consumer/   //<1>
    ├── settings.gradle
    └── build.gradle
----
<1> Create a `consumer` project
=====

You also need to update the root `settings.gradle(.kts)` file so the `consumer` project is a Composite Build and we no longer include the `plugin` as a build:

====
include::sample[dir="snippets/plugins/plugin-tutorial/kotlin",files="settings.gradle.kts[]"]
include::sample[dir="snippets/plugins/plugin-tutorial/groovy",files="settings.gradle[]"]
====

And your `plugin` no longer has access to the version catalog in the root since it is now an included build so you need to update any references:

====
include::sample[dir="snippets/plugins/plugin-tutorial/kotlin",files="plugin/build.gradle.kts[tags=plugins]"]
include::sample[dir="snippets/plugins/plugin-tutorial/groovy",files="plugin/build.gradle[tags=dependencies]"]
====

NOTE: There are workarounds for this, but it is outside the scope of this tutorial.

== Step 2. Wire the `consumer` to include the `plugin`

Add a settings.gradle(.kts) file to the `consumer` project and wire it to the plugin via `pluginManagement {}`:

====
include::sample[dir="snippets/plugins/plugin-tutorial/kotlin",files="consumer/settings.gradle.kts[]"]
include::sample[dir="snippets/plugins/plugin-tutorial/kotlin",files="consumer/settings.gradle.kts[]"]
====

`includeBuild("../plugin")` makes the plugin from the plugin directory available by its ID without publishing.

== Step 3. Apply and configure the plugin in the `consumer`

====
include::sample[dir="snippets/plugins/plugin-tutorial/kotlin",files="consumer/build.gradle.kts[]"]
include::sample[dir="snippets/plugins/plugin-tutorial/groovy",files="consumer/build.gradle[]"]
====


No version is needed, the plugin is resolved from the included build.

== Step 4. Run the `consumer`

From the `consumer` directory:

[source,text]
----
./gradlew sendSlackMessage
----

Or from the `root` directory:

[source,text]
----
./gradlew :consumer:sendSlackMessage
----

You can also run:

[source,text]
----
./gradlew build                 // from consumer dir
./gradlew :consumer:build       // from root dir
----

And see the Slack message appear.

That’s it!
You can now iterate on the plugin in `plugin/`, and immediately test it in `consumer/` with zero publishing friction.

Congratulations, you have completed the tutorial!
