// Copyright (C) 2025 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[part2_add_extension]]
= Part 2: Add an Extension

Learn about extensions and how to add them to your plugin.

****
**In this section, you will:**

- Understand Plugin Extensions
- Add an Extension to the Slack Plugin
****

[[part2_begin]]
== Step 0. Before you Begin

1. You initialized your plugin in <<part1_gradle_init_plugin.adoc#part1_begin,part 1>>.

== Step 1. Understanding Plugin Extensions

A plugin extension is a block users can configure in their `build.gradle(.kts)` file to customize how the plugin behaves.
It lets you expose settings like:

[source,text]
----
greeting {
    message.set("Hi")
    recipient.set("CI Server")
}
----

Behind the scenes, this block maps to a Kotlin/Java class with properties.
Gradle injects values set by the user into the plugin logic.

== Step 2. Rename the Plugin Class

First, let's rename the Plugin class of our 'Hello World' example from the Gradle init default.

[.multi-language-text.lang-kotlin]
----
Rename the file `plugin/src/main/kotlin/org/example/PluginTutorialPlugin.kt` to `plugin/src/main/kotlin/org/example/SlackPlugin.kt`.
----
[.multi-language-text.lang-groovy]
----
Rename the file `plugin/src/main/groovy/org/example/PluginTutorialPlugin.groovy` to `plugin/src/main/groovy/org/example/SlackPlugin.groovy`.
----

TIP: In an IDE, renaming the file should update the plugin class automatically.

[.multi-language-text.lang-kotlin]
----
Then, take the class name, `class PluginTutorialPlugin: Plugin<Project> {}`, and update it to `abstract class SlackPlugin: Plugin<Project> {}` so it looks like this:
----
[.multi-language-text.lang-groovy]
----
Then, take the class name, `class PluginTutorialPlugin implements Plugin<Project> {}`, and update it to `abstract class SlackPlugin implements Plugin<Project> {}` so it looks like this:
----

====
include::sample[dir="snippets/plugins/plugin-tutorial/kotlin",files="plugin/src/main/kotlin/org/example/SlackPlugin.kt[tags=slack-plugin]"]
include::sample[dir="snippets/plugins/plugin-tutorial/groovy",files="plugin/src/main/groovy/org/example/SlackPlugin.groovy[tags=slack-plugin]"]
====

WARNING: Make sure the class is abstract.

You also need to update the build file to reflect the name changes:

====
include::sample[dir="snippets/plugins/plugin-tutorial/kotlin",files="plugin/build.gradle.kts[tags=gradle-plugin]"]
include::sample[dir="snippets/plugins/plugin-tutorial/groovy",files="plugin/build.gradle.kts[tags=gradle-plugin]"]
====

== Step 3. Define the Extension Class

We will create a class that holds user-configurable properties.
For this we're using Gradle’s `Property<T>` type for laziness and compatibility with the Configuration Cache.

Create a file called `plugin/src/main/kotlin/org/example/SlackExtension.kt` and add the following code:

====
include::sample[dir="snippets/plugins/plugin-tutorial/kotlin",files="plugin/src/main/kotlin/org/example/SlackExtension.kt[]"]
include::sample[dir="snippets/plugins/plugin-tutorial/groovy",files="plugin/src/main/groovy/org/example/SlackExtension.groovy[]"]
====

This code provides configuration for the plugin with a DSL block:

[source,text]
----
slack {
    token.set(System.getenv("SLACK_TOKEN"))
    channel.set("#build-notifications")
    message.set("Hello from Gradle!")
}
----

== Step 3. Register the Extension in the Plugin

In order for the plugin to use the extension and provide the DSL block to users, it must *register* the extension.

Add the following code and update your plugin class so it looks like this:

====
include::sample[dir="snippets/plugins/plugin-tutorial/kotlin",files="plugin/src/main/kotlin/org/example/SlackPlugin.kt[tags=slack-extension]"]
include::sample[dir="snippets/plugins/plugin-tutorial/groovy",files="plugin/src/main/groovy/org/example/SlackPlugin.groovy[tags=slack-extension]"]
====

We've also updated the dummy `greeting` task so it is called `sendTestSlackMessage` and it prints out some of the variable values in the extension.

== Step 4. Benefits of Using Extensions

* Keeps plugin configuration clean and declarative
* Integrates seamlessly into the build script DSL
* Encourages reuse and convention-based configuration
* Supports Gradle's lazy configuration and Configuration Cache

[.text-right]
**Next Step:** <<part3_create_custom_task#part3_create_custom_task,Create a Custom Task>> >>
