package Gradle_Promotion.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with uuid = 'e4bc6ac6-ab3f-4459-b4c4-7d6ba6e2cbf6' (id = 'Gradle_Promotion_GradlePromotionBranches')
accordingly, and delete the patch script.
*/
changeVcsRoot(uuid("e4bc6ac6-ab3f-4459-b4c4-7d6ba6e2cbf6")) {
    val expected = GitVcsRoot({
        uuid = "e4bc6ac6-ab3f-4459-b4c4-7d6ba6e2cbf6"
        id("Gradle_Promotion_GradlePromotionBranches")
        name = "Gradle Promotion Branches"
        url = "https://github.com/gradle/gradle-promote.git"
        branchSpec = "+:refs/heads/*"
        agentGitPath = "%env.TEAMCITY_GIT_PATH%"
        useMirrors = false
        authMethod = password {
            userName = "gradlewaregitbot"
            password = "credentialsJSON:5306bfc7-041e-46e8-8d61-1d49424e7b04"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "bot-teamcity"
            password = "credentialsJSON:5fe7c16b-cef8-4e22-a305-52f6ae768b72"
        }
    }

}
