plugins {
    id("gradlebuild.distribution.api-java")
}

description = "Implementation for interacting with S3 repositories"

dependencies {
    api(projects.serviceProvider)
    api(projects.credentials)
    api(projects.credentialsApi)
    api(projects.resources)
    api(projects.resourcesHttp)

    api(libs.awsS3S3)
    api(libs.awsS3Kms) {
        because("Loaded by the AWS libraries with reflection when present")
    }
    api(libs.awsSdkCore)
    api(libs.awsSdkRegions)
    api(libs.guava)
    api(libs.jspecify)

    implementation(projects.baseServices)
    implementation(projects.hashing)

    implementation(libs.awsApacheHttpClient)
    implementation(libs.awsSdkAuth)
    implementation(libs.awsSdkAwsCore)
    implementation(libs.awsSdkHttpClientSpi)
    implementation(libs.awsSdkRetries)
    implementation(libs.awsSdkRetriesSpi)
    implementation(libs.awsSdkUtils)
    implementation(libs.commonsLang)
    implementation(libs.slf4jApi)

    runtimeOnly(projects.core)
    runtimeOnly(projects.coreApi)

    runtimeOnly(libs.awsS3Sts) {
        because("Loaded by the AWS libraries with reflection when present: https://github.com/gradle/gradle/issues/15332")
    }

    testImplementation(testFixtures(projects.core))
    testImplementation(testFixtures(projects.dependencyManagement))
    testImplementation(testFixtures(projects.ivy))
    testImplementation(testFixtures(projects.maven))
    testImplementation(libs.awsS3Control)

    integTestImplementation(projects.logging)
    integTestImplementation(libs.commonsIo)
    integTestImplementation(libs.groovyXml)
    integTestImplementation(testLibs.littleproxy)

    integTestDistributionRuntimeOnly(projects.distributionsBasics)
}

gradleModule {
    requiredRuntimes {
        daemon = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
    }
}

dependencyAnalysis {
    issues {
        onUnusedDependencies() {
            // This need to exist to be loaded reflectively
            exclude(libs.awsS3Kms)
            exclude(libs.awsS3Sts)
        }
    }
}

