// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tooling.proto

package org.gradle.tooling.internal.grpc.proto;

public interface BuildResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gradle.tooling.grpc.BuildResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * SUCCESS / FAILED / ... - distinguishes cancellation from failure
   * </pre>
   *
   * <code>.gradle.tooling.grpc.Outcome outcome = 3;</code>
   * @return The enum numeric value on the wire for outcome.
   */
  int getOutcomeValue();
  /**
   * <pre>
   * SUCCESS / FAILED / ... - distinguishes cancellation from failure
   * </pre>
   *
   * <code>.gradle.tooling.grpc.Outcome outcome = 3;</code>
   * @return The outcome.
   */
  org.gradle.tooling.internal.grpc.proto.Outcome getOutcome();

  /**
   * <pre>
   * structured failure tree (causes), not just a message
   * </pre>
   *
   * <code>repeated .gradle.tooling.grpc.Failure failures = 4;</code>
   */
  java.util.List<org.gradle.tooling.internal.grpc.proto.Failure> 
      getFailuresList();
  /**
   * <pre>
   * structured failure tree (causes), not just a message
   * </pre>
   *
   * <code>repeated .gradle.tooling.grpc.Failure failures = 4;</code>
   */
  org.gradle.tooling.internal.grpc.proto.Failure getFailures(int index);
  /**
   * <pre>
   * structured failure tree (causes), not just a message
   * </pre>
   *
   * <code>repeated .gradle.tooling.grpc.Failure failures = 4;</code>
   */
  int getFailuresCount();
  /**
   * <pre>
   * structured failure tree (causes), not just a message
   * </pre>
   *
   * <code>repeated .gradle.tooling.grpc.Failure failures = 4;</code>
   */
  java.util.List<? extends org.gradle.tooling.internal.grpc.proto.FailureOrBuilder> 
      getFailuresOrBuilderList();
  /**
   * <pre>
   * structured failure tree (causes), not just a message
   * </pre>
   *
   * <code>repeated .gradle.tooling.grpc.Failure failures = 4;</code>
   */
  org.gradle.tooling.internal.grpc.proto.FailureOrBuilder getFailuresOrBuilder(
      int index);
}
