// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tooling.proto

package org.gradle.tooling.internal.grpc.proto;

public interface OperationResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gradle.tooling.grpc.OperationResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gradle.tooling.grpc.Outcome outcome = 1;</code>
   * @return The enum numeric value on the wire for outcome.
   */
  int getOutcomeValue();
  /**
   * <code>.gradle.tooling.grpc.Outcome outcome = 1;</code>
   * @return The outcome.
   */
  org.gradle.tooling.internal.grpc.proto.Outcome getOutcome();

  /**
   * <pre>
   * set when outcome is FAILED
   * </pre>
   *
   * <code>string failure_message = 2;</code>
   * @return The failureMessage.
   */
  java.lang.String getFailureMessage();
  /**
   * <pre>
   * set when outcome is FAILED
   * </pre>
   *
   * <code>string failure_message = 2;</code>
   * @return The bytes for failureMessage.
   */
  com.google.protobuf.ByteString
      getFailureMessageBytes();
}
