// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tooling.proto

package org.gradle.tooling.internal.grpc.proto;

/**
 * Protobuf type {@code gradle.tooling.grpc.StyledOutput}
 */
public final class StyledOutput extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gradle.tooling.grpc.StyledOutput)
    StyledOutputOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StyledOutput.newBuilder() to construct.
  private StyledOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StyledOutput() {
    spans_ = java.util.Collections.emptyList();
    level_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StyledOutput();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_StyledOutput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_StyledOutput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.gradle.tooling.internal.grpc.proto.StyledOutput.class, org.gradle.tooling.internal.grpc.proto.StyledOutput.Builder.class);
  }

  public static final int SPANS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.gradle.tooling.internal.grpc.proto.Span> spans_;
  /**
   * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.gradle.tooling.internal.grpc.proto.Span> getSpansList() {
    return spans_;
  }
  /**
   * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.gradle.tooling.internal.grpc.proto.SpanOrBuilder> 
      getSpansOrBuilderList() {
    return spans_;
  }
  /**
   * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
   */
  @java.lang.Override
  public int getSpansCount() {
    return spans_.size();
  }
  /**
   * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
   */
  @java.lang.Override
  public org.gradle.tooling.internal.grpc.proto.Span getSpans(int index) {
    return spans_.get(index);
  }
  /**
   * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
   */
  @java.lang.Override
  public org.gradle.tooling.internal.grpc.proto.SpanOrBuilder getSpansOrBuilder(
      int index) {
    return spans_.get(index);
  }

  public static final int LEVEL_FIELD_NUMBER = 2;
  private int level_ = 0;
  /**
   * <code>.gradle.tooling.grpc.LogLevel level = 2;</code>
   * @return The enum numeric value on the wire for level.
   */
  @java.lang.Override public int getLevelValue() {
    return level_;
  }
  /**
   * <code>.gradle.tooling.grpc.LogLevel level = 2;</code>
   * @return The level.
   */
  @java.lang.Override public org.gradle.tooling.internal.grpc.proto.LogLevel getLevel() {
    org.gradle.tooling.internal.grpc.proto.LogLevel result = org.gradle.tooling.internal.grpc.proto.LogLevel.forNumber(level_);
    return result == null ? org.gradle.tooling.internal.grpc.proto.LogLevel.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < spans_.size(); i++) {
      output.writeMessage(1, spans_.get(i));
    }
    if (level_ != org.gradle.tooling.internal.grpc.proto.LogLevel.LOG_LEVEL_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, level_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < spans_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, spans_.get(i));
    }
    if (level_ != org.gradle.tooling.internal.grpc.proto.LogLevel.LOG_LEVEL_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, level_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.gradle.tooling.internal.grpc.proto.StyledOutput)) {
      return super.equals(obj);
    }
    org.gradle.tooling.internal.grpc.proto.StyledOutput other = (org.gradle.tooling.internal.grpc.proto.StyledOutput) obj;

    if (!getSpansList()
        .equals(other.getSpansList())) return false;
    if (level_ != other.level_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSpansCount() > 0) {
      hash = (37 * hash) + SPANS_FIELD_NUMBER;
      hash = (53 * hash) + getSpansList().hashCode();
    }
    hash = (37 * hash) + LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + level_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.gradle.tooling.internal.grpc.proto.StyledOutput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gradle.tooling.internal.grpc.proto.StyledOutput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.StyledOutput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gradle.tooling.internal.grpc.proto.StyledOutput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.StyledOutput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gradle.tooling.internal.grpc.proto.StyledOutput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.StyledOutput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gradle.tooling.internal.grpc.proto.StyledOutput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.StyledOutput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.gradle.tooling.internal.grpc.proto.StyledOutput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.StyledOutput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gradle.tooling.internal.grpc.proto.StyledOutput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.gradle.tooling.internal.grpc.proto.StyledOutput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gradle.tooling.grpc.StyledOutput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gradle.tooling.grpc.StyledOutput)
      org.gradle.tooling.internal.grpc.proto.StyledOutputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_StyledOutput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_StyledOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gradle.tooling.internal.grpc.proto.StyledOutput.class, org.gradle.tooling.internal.grpc.proto.StyledOutput.Builder.class);
    }

    // Construct using org.gradle.tooling.internal.grpc.proto.StyledOutput.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
      } else {
        spans_ = null;
        spansBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      level_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_StyledOutput_descriptor;
    }

    @java.lang.Override
    public org.gradle.tooling.internal.grpc.proto.StyledOutput getDefaultInstanceForType() {
      return org.gradle.tooling.internal.grpc.proto.StyledOutput.getDefaultInstance();
    }

    @java.lang.Override
    public org.gradle.tooling.internal.grpc.proto.StyledOutput build() {
      org.gradle.tooling.internal.grpc.proto.StyledOutput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.gradle.tooling.internal.grpc.proto.StyledOutput buildPartial() {
      org.gradle.tooling.internal.grpc.proto.StyledOutput result = new org.gradle.tooling.internal.grpc.proto.StyledOutput(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.gradle.tooling.internal.grpc.proto.StyledOutput result) {
      if (spansBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          spans_ = java.util.Collections.unmodifiableList(spans_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.spans_ = spans_;
      } else {
        result.spans_ = spansBuilder_.build();
      }
    }

    private void buildPartial0(org.gradle.tooling.internal.grpc.proto.StyledOutput result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.level_ = level_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.gradle.tooling.internal.grpc.proto.StyledOutput) {
        return mergeFrom((org.gradle.tooling.internal.grpc.proto.StyledOutput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.gradle.tooling.internal.grpc.proto.StyledOutput other) {
      if (other == org.gradle.tooling.internal.grpc.proto.StyledOutput.getDefaultInstance()) return this;
      if (spansBuilder_ == null) {
        if (!other.spans_.isEmpty()) {
          if (spans_.isEmpty()) {
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSpansIsMutable();
            spans_.addAll(other.spans_);
          }
          onChanged();
        }
      } else {
        if (!other.spans_.isEmpty()) {
          if (spansBuilder_.isEmpty()) {
            spansBuilder_.dispose();
            spansBuilder_ = null;
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000001);
            spansBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSpansFieldBuilder() : null;
          } else {
            spansBuilder_.addAllMessages(other.spans_);
          }
        }
      }
      if (other.level_ != 0) {
        setLevelValue(other.getLevelValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.gradle.tooling.internal.grpc.proto.Span m =
                  input.readMessage(
                      org.gradle.tooling.internal.grpc.proto.Span.parser(),
                      extensionRegistry);
              if (spansBuilder_ == null) {
                ensureSpansIsMutable();
                spans_.add(m);
              } else {
                spansBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              level_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.gradle.tooling.internal.grpc.proto.Span> spans_ =
      java.util.Collections.emptyList();
    private void ensureSpansIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        spans_ = new java.util.ArrayList<org.gradle.tooling.internal.grpc.proto.Span>(spans_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.gradle.tooling.internal.grpc.proto.Span, org.gradle.tooling.internal.grpc.proto.Span.Builder, org.gradle.tooling.internal.grpc.proto.SpanOrBuilder> spansBuilder_;

    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public java.util.List<org.gradle.tooling.internal.grpc.proto.Span> getSpansList() {
      if (spansBuilder_ == null) {
        return java.util.Collections.unmodifiableList(spans_);
      } else {
        return spansBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public int getSpansCount() {
      if (spansBuilder_ == null) {
        return spans_.size();
      } else {
        return spansBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public org.gradle.tooling.internal.grpc.proto.Span getSpans(int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);
      } else {
        return spansBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public Builder setSpans(
        int index, org.gradle.tooling.internal.grpc.proto.Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.set(index, value);
        onChanged();
      } else {
        spansBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public Builder setSpans(
        int index, org.gradle.tooling.internal.grpc.proto.Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.set(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public Builder addSpans(org.gradle.tooling.internal.grpc.proto.Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(value);
        onChanged();
      } else {
        spansBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public Builder addSpans(
        int index, org.gradle.tooling.internal.grpc.proto.Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(index, value);
        onChanged();
      } else {
        spansBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public Builder addSpans(
        org.gradle.tooling.internal.grpc.proto.Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public Builder addSpans(
        int index, org.gradle.tooling.internal.grpc.proto.Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public Builder addAllSpans(
        java.lang.Iterable<? extends org.gradle.tooling.internal.grpc.proto.Span> values) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, spans_);
        onChanged();
      } else {
        spansBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public Builder clearSpans() {
      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        spansBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public Builder removeSpans(int index) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.remove(index);
        onChanged();
      } else {
        spansBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public org.gradle.tooling.internal.grpc.proto.Span.Builder getSpansBuilder(
        int index) {
      return getSpansFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public org.gradle.tooling.internal.grpc.proto.SpanOrBuilder getSpansOrBuilder(
        int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);  } else {
        return spansBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public java.util.List<? extends org.gradle.tooling.internal.grpc.proto.SpanOrBuilder> 
         getSpansOrBuilderList() {
      if (spansBuilder_ != null) {
        return spansBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(spans_);
      }
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public org.gradle.tooling.internal.grpc.proto.Span.Builder addSpansBuilder() {
      return getSpansFieldBuilder().addBuilder(
          org.gradle.tooling.internal.grpc.proto.Span.getDefaultInstance());
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public org.gradle.tooling.internal.grpc.proto.Span.Builder addSpansBuilder(
        int index) {
      return getSpansFieldBuilder().addBuilder(
          index, org.gradle.tooling.internal.grpc.proto.Span.getDefaultInstance());
    }
    /**
     * <code>repeated .gradle.tooling.grpc.Span spans = 1;</code>
     */
    public java.util.List<org.gradle.tooling.internal.grpc.proto.Span.Builder> 
         getSpansBuilderList() {
      return getSpansFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.gradle.tooling.internal.grpc.proto.Span, org.gradle.tooling.internal.grpc.proto.Span.Builder, org.gradle.tooling.internal.grpc.proto.SpanOrBuilder> 
        getSpansFieldBuilder() {
      if (spansBuilder_ == null) {
        spansBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.gradle.tooling.internal.grpc.proto.Span, org.gradle.tooling.internal.grpc.proto.Span.Builder, org.gradle.tooling.internal.grpc.proto.SpanOrBuilder>(
                spans_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        spans_ = null;
      }
      return spansBuilder_;
    }

    private int level_ = 0;
    /**
     * <code>.gradle.tooling.grpc.LogLevel level = 2;</code>
     * @return The enum numeric value on the wire for level.
     */
    @java.lang.Override public int getLevelValue() {
      return level_;
    }
    /**
     * <code>.gradle.tooling.grpc.LogLevel level = 2;</code>
     * @param value The enum numeric value on the wire for level to set.
     * @return This builder for chaining.
     */
    public Builder setLevelValue(int value) {
      level_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.gradle.tooling.grpc.LogLevel level = 2;</code>
     * @return The level.
     */
    @java.lang.Override
    public org.gradle.tooling.internal.grpc.proto.LogLevel getLevel() {
      org.gradle.tooling.internal.grpc.proto.LogLevel result = org.gradle.tooling.internal.grpc.proto.LogLevel.forNumber(level_);
      return result == null ? org.gradle.tooling.internal.grpc.proto.LogLevel.UNRECOGNIZED : result;
    }
    /**
     * <code>.gradle.tooling.grpc.LogLevel level = 2;</code>
     * @param value The level to set.
     * @return This builder for chaining.
     */
    public Builder setLevel(org.gradle.tooling.internal.grpc.proto.LogLevel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      level_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.gradle.tooling.grpc.LogLevel level = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLevel() {
      bitField0_ = (bitField0_ & ~0x00000002);
      level_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gradle.tooling.grpc.StyledOutput)
  }

  // @@protoc_insertion_point(class_scope:gradle.tooling.grpc.StyledOutput)
  private static final org.gradle.tooling.internal.grpc.proto.StyledOutput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.gradle.tooling.internal.grpc.proto.StyledOutput();
  }

  public static org.gradle.tooling.internal.grpc.proto.StyledOutput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StyledOutput>
      PARSER = new com.google.protobuf.AbstractParser<StyledOutput>() {
    @java.lang.Override
    public StyledOutput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StyledOutput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StyledOutput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.gradle.tooling.internal.grpc.proto.StyledOutput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

