// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tooling.proto

package org.gradle.tooling.internal.grpc.proto;

public final class ToolingProto {
  private ToolingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_BuildRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_BuildRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_CancelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_CancelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_CancelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_CancelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_BuildEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_BuildEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_ProgressEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_ProgressEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_OutputLine_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_OutputLine_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_StyledOutput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_StyledOutput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_Span_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_Span_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_BuildResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_BuildResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_ModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_ModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_ModelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_ModelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_BuildEnvironment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_BuildEnvironment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_TaskList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_TaskList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_TaskInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_TaskInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rtooling.proto\022\023gradle.tooling.grpc\032\031go" +
      "ogle/protobuf/any.proto\"C\n\014BuildRequest\022" +
      "\014\n\004args\030\001 \003(\t\022\023\n\013project_dir\030\002 \001(\t\022\020\n\010bu" +
      "ild_id\030\003 \001(\t\"!\n\rCancelRequest\022\020\n\010build_i" +
      "d\030\001 \001(\t\"4\n\016CancelResponse\022\021\n\tcancelled\030\001" +
      " \001(\010\022\017\n\007message\030\002 \001(\t\"\350\001\n\nBuildEvent\0221\n\006" +
      "output\030\001 \001(\0132\037.gradle.tooling.grpc.Outpu" +
      "tLineH\000\0222\n\006result\030\002 \001(\0132 .gradle.tooling" +
      ".grpc.BuildResultH\000\0223\n\006styled\030\003 \001(\0132!.gr" +
      "adle.tooling.grpc.StyledOutputH\000\0226\n\010prog" +
      "ress\030\004 \001(\0132\".gradle.tooling.grpc.Progres" +
      "sEventH\000B\006\n\004kind\"e\n\rProgressEvent\022/\n\004typ" +
      "e\030\001 \001(\0162!.gradle.tooling.grpc.ProgressTy" +
      "pe\022\023\n\013description\030\002 \001(\t\022\016\n\006status\030\003 \001(\t\"" +
      "H\n\nOutputLine\022\014\n\004text\030\001 \001(\t\022,\n\005level\030\002 \001" +
      "(\0162\035.gradle.tooling.grpc.LogLevel\"f\n\014Sty" +
      "ledOutput\022(\n\005spans\030\001 \003(\0132\031.gradle.toolin" +
      "g.grpc.Span\022,\n\005level\030\002 \001(\0162\035.gradle.tool" +
      "ing.grpc.LogLevel\"?\n\004Span\022\014\n\004text\030\001 \001(\t\022" +
      ")\n\005style\030\002 \001(\0162\032.gradle.tooling.grpc.Sty" +
      "le\"/\n\013BuildResult\022\017\n\007success\030\001 \001(\010\022\017\n\007me" +
      "ssage\030\002 \001(\t\"\244\001\n\014ModelRequest\022\023\n\013project_" +
      "dir\030\001 \001(\t\022,\n\004type\030\002 \001(\0162\036.gradle.tooling" +
      ".grpc.ModelType\022\022\n\nmodel_name\030\003 \001(\t\022\024\n\014p" +
      "roject_path\030\004 \001(\t\022\'\n\tparameter\030\005 \001(\0132\024.g" +
      "oogle.protobuf.Any\"\327\001\n\rModelResponse\022\017\n\007" +
      "success\030\001 \001(\010\022\r\n\005error\030\002 \001(\t\022B\n\021build_en" +
      "vironment\030\003 \001(\0132%.gradle.tooling.grpc.Bu" +
      "ildEnvironmentH\000\022.\n\005tasks\030\004 \001(\0132\035.gradle" +
      ".tooling.grpc.TaskListH\000\022)\n\tmodel_any\030\005 " +
      "\001(\0132\024.google.protobuf.AnyH\000B\007\n\005model\"S\n\020" +
      "BuildEnvironment\022\026\n\016gradle_version\030\001 \001(\t" +
      "\022\021\n\tjava_home\030\002 \001(\t\022\024\n\014java_version\030\003 \001(" +
      "\005\"N\n\010TaskList\022\024\n\014project_path\030\001 \001(\t\022,\n\005t" +
      "asks\030\002 \003(\0132\035.gradle.tooling.grpc.TaskInf" +
      "o\"J\n\010TaskInfo\022\014\n\004name\030\001 \001(\t\022\014\n\004path\030\002 \001(" +
      "\t\022\r\n\005group\030\003 \001(\t\022\023\n\013description\030\004 \001(\t*N\n" +
      "\014ProgressType\022\022\n\016PROGRESS_START\020\000\022\023\n\017PRO" +
      "GRESS_STATUS\020\001\022\025\n\021PROGRESS_COMPLETE\020\002*i\n" +
      "\010LogLevel\022\031\n\025LOG_LEVEL_UNSPECIFIED\020\000\022\t\n\005" +
      "QUIET\020\001\022\010\n\004WARN\020\002\022\r\n\tLIFECYCLE\020\003\022\010\n\004INFO" +
      "\020\004\022\t\n\005DEBUG\020\005\022\t\n\005ERROR\020\006*\204\002\n\005Style\022\020\n\014ST" +
      "YLE_NORMAL\020\000\022\020\n\014STYLE_HEADER\020\001\022\024\n\020STYLE_" +
      "USER_INPUT\020\002\022\024\n\020STYLE_IDENTIFIER\020\003\022\025\n\021ST" +
      "YLE_DESCRIPTION\020\004\022\031\n\025STYLE_PROGRESS_STAT" +
      "US\020\005\022\021\n\rSTYLE_SUCCESS\020\006\022\030\n\024STYLE_SUCCESS" +
      "_HEADER\020\007\022\021\n\rSTYLE_FAILURE\020\010\022\030\n\024STYLE_FA" +
      "ILURE_HEADER\020\t\022\016\n\nSTYLE_INFO\020\n\022\017\n\013STYLE_" +
      "ERROR\020\013*9\n\tModelType\022\033\n\027MODEL_BUILD_ENVI" +
      "RONMENT\020\000\022\017\n\013MODEL_TASKS\020\0012\203\002\n\007Tooling\022P" +
      "\n\010RunBuild\022!.gradle.tooling.grpc.BuildRe" +
      "quest\032\037.gradle.tooling.grpc.BuildEvent0\001" +
      "\022S\n\nQueryModel\022!.gradle.tooling.grpc.Mod" +
      "elRequest\032\".gradle.tooling.grpc.ModelRes" +
      "ponse\022Q\n\006Cancel\022\".gradle.tooling.grpc.Ca" +
      "ncelRequest\032#.gradle.tooling.grpc.Cancel" +
      "ResponseB8\n&org.gradle.tooling.internal." +
      "grpc.protoB\014ToolingProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_gradle_tooling_grpc_BuildRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gradle_tooling_grpc_BuildRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_BuildRequest_descriptor,
        new java.lang.String[] { "Args", "ProjectDir", "BuildId", });
    internal_static_gradle_tooling_grpc_CancelRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gradle_tooling_grpc_CancelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_CancelRequest_descriptor,
        new java.lang.String[] { "BuildId", });
    internal_static_gradle_tooling_grpc_CancelResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gradle_tooling_grpc_CancelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_CancelResponse_descriptor,
        new java.lang.String[] { "Cancelled", "Message", });
    internal_static_gradle_tooling_grpc_BuildEvent_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gradle_tooling_grpc_BuildEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_BuildEvent_descriptor,
        new java.lang.String[] { "Output", "Result", "Styled", "Progress", "Kind", });
    internal_static_gradle_tooling_grpc_ProgressEvent_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_gradle_tooling_grpc_ProgressEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_ProgressEvent_descriptor,
        new java.lang.String[] { "Type", "Description", "Status", });
    internal_static_gradle_tooling_grpc_OutputLine_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_gradle_tooling_grpc_OutputLine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_OutputLine_descriptor,
        new java.lang.String[] { "Text", "Level", });
    internal_static_gradle_tooling_grpc_StyledOutput_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_gradle_tooling_grpc_StyledOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_StyledOutput_descriptor,
        new java.lang.String[] { "Spans", "Level", });
    internal_static_gradle_tooling_grpc_Span_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_gradle_tooling_grpc_Span_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_Span_descriptor,
        new java.lang.String[] { "Text", "Style", });
    internal_static_gradle_tooling_grpc_BuildResult_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_gradle_tooling_grpc_BuildResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_BuildResult_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_gradle_tooling_grpc_ModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_gradle_tooling_grpc_ModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_ModelRequest_descriptor,
        new java.lang.String[] { "ProjectDir", "Type", "ModelName", "ProjectPath", "Parameter", });
    internal_static_gradle_tooling_grpc_ModelResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_gradle_tooling_grpc_ModelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_ModelResponse_descriptor,
        new java.lang.String[] { "Success", "Error", "BuildEnvironment", "Tasks", "ModelAny", "Model", });
    internal_static_gradle_tooling_grpc_BuildEnvironment_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_gradle_tooling_grpc_BuildEnvironment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_BuildEnvironment_descriptor,
        new java.lang.String[] { "GradleVersion", "JavaHome", "JavaVersion", });
    internal_static_gradle_tooling_grpc_TaskList_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_gradle_tooling_grpc_TaskList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_TaskList_descriptor,
        new java.lang.String[] { "ProjectPath", "Tasks", });
    internal_static_gradle_tooling_grpc_TaskInfo_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_gradle_tooling_grpc_TaskInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_TaskInfo_descriptor,
        new java.lang.String[] { "Name", "Path", "Group", "Description", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
