// Copyright (C) 2025 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[best_practices_general]]
= General Gradle Best Practices

[[use_kotlin_dsl]]
== Use Kotlin DSL

Prefer the Kotlin DSL (`build.gradle.kts`) over the Groovy DSL (`build.gradle`) when authoring new builds or creating new subprojects in existing builds.

=== Explanation

The Kotlin DSL offers several advantages over the Groovy DSL:

* *Strict typing*: IDEs provide better auto-completion and navigation with the Kotlin DSL.
* *Improved readability*: Code written in Kotlin is often easier to follow and understand.
* *Single-language stack*: Projects that already use Kotlin for production and test code don’t need to introduce Groovy just for the build.

Since Gradle 8.0, link:https://blog.gradle.org/kotlin-dsl-is-now-the-default-for-new-gradle-builds[Kotlin DSL is the default] for new builds created with `gradle init`.
Android Studio also link:https://developer.android.com/build/migrate-to-kotlin-dsl#timeline[defaults to Kotlin DSL].

=== References

- <<kotlin_dsl.adoc#kotdsl:kotlin_dsl,Kotlin DSL Primer>>

=== Tags

<<tags_reference.adoc#tag:kotlin-dsl,`#kotlin-dsl`>>

[[use_latest_minor_versions]]
== Use the Latest Minor Version of Gradle

Stay on the latest minor version of the major Gradle release you're using, and regularly update your plugins to the latest compatible versions.

=== Explanation

Gradle follows a fairly predictable, time-based release cadence.
Only the latest minor version of the current and previous major release is actively supported.

We recommend the following strategy:

* Try upgrading directly to the latest minor version of your current major Gradle release.
* If that fails, upgrade one minor version at a time to isolate regressions or compatibility issues.

Each new minor version includes:

* Performance and stability improvements.
* Deprecation warnings that help you prepare for the next major release.
* Fixes for known bugs and security vulnerabilities.

Use the `wrapper` task to update your project:

[source, bash]
----
./gradlew wrapper --gradle-version <version>
----

You can also install the latest Gradle versions easily using tools like link:https://sdkman.io/[SDKMAN!] or link:https://brew.sh/[Homebrew], depending on your platform.

=== Plugin Compatibility

Always use the latest compatible version of each plugin:

* Upgrade Gradle before plugins.
* Test plugin compatibility using link:https://slack.engineering/shadow-jobs/[shadow jobs].
* Consult changelogs when updating.

Subscribe to the Gradle link:https://newsletter.gradle.org/[newsletter] to stay informed about new Gradle releases, features, and plugins.

=== References

- <<upgrading_version_8.adoc#upgrading_version_8,Upgrade Guide>>

=== Tags

<<tags_reference.adoc#tag:plugins,`#plugins`>>

[[use_the_plugins_block]]
== Apply Plugins Using the `plugins` Block
:keywords: plugins,structuring-builds

You should always use the `plugins` block to <<plugin_basics.adoc#applying_plugins,apply plugins>> in your build scripts.

=== Explanation

The `plugins` block is the preferred way to apply plugins in Gradle.
The plugins API allows Gradle to better manage the loading of plugins and it is both more concise and less error-prone than adding dependencies to the buildscript's classpath explicitly in order to use the `apply` method.

It allows Gradle to optimize the loading and reuse of plugin classes and helps inform tools about the potential properties and values in extensions the plugins will add to the build script.
It is constrained to be idempotent (produce the same result every time) and side effect-free (safe for Gradle to execute at any time).

=== Example

==== Don't Do This

====
include::sample[dir="snippets/bestPractices/usePluginsBlock-avoid/kotlin",files="build.gradle.kts[tags=avoid-this]"]
include::sample[dir="snippets/bestPractices/usePluginsBlock-avoid/groovy",files="build.gradle[tags=avoid-this]"]
====

<1> *Declare a Repository*: To use the legacy plugin application syntax, you need to explicitly tell Gradle where to find a plugin.
<2> *Declare a Plugin Dependency*: To use the legacy plugin application syntax with third-party plugins, you need to explicitly tell Gradle the full coordinates of the plugin.
<3> *Apply a Core Plugin*: This is very similar using either method.
<4> *Apply a Third-Party Plugin*: The syntax is the same as for core Gradle plugins, but the version is not present at the point of application in your buildscript.

==== Do This Instead

====
include::sample[dir="snippets/bestPractices/usePluginsBlock-do/kotlin",files="build.gradle.kts[tags=do-this]"]
include::sample[dir="snippets/bestPractices/usePluginsBlock-do/groovy",files="build.gradle[tags=do-this]"]
====

<1> *Apply a Core Plugin*: This is very similar using either method.
<2> *Apply a Third-Party Plugin*: You specify the version using method chaining in the `plugins` block itself.

=== References

- <<plugins.adoc#sec:using_plugins,Using Plugins>>

=== Tags

`<<tags_reference.adoc#tag:structuring-builds,#structuring-builds>>`

[[do_not_use_internal_apis]]
== Do Not Use Internal APIs
:keywords: upgrades

Do not use APIs from a package where any segment of the package is `internal`, or types that have `Internal` or `Impl` as a suffix in the name.

=== Explanation

Using internal APIs is inherently risky and can cause significant problems during upgrades.
Gradle and many plugins (such as Android Gradle Plugin and Kotlin Gradle Plugin) treat these internal APIs as subject to unannounced breaking changes during any new Gradle release, even during minor releases.
There have been numerous cases where even highly experienced plugin developers have been bitten by their usage of such APIs leading to unexpected breakages for their users.

If you require specific functionality that is missing, it’s best to submit a feature request.
As a temporary workaround consider copying the necessary code into your own codebase and extending a Gradle public type with your own custom implementation using the copied code.

=== Example

==== Don't Do This

====
include::sample[dir="snippets/bestPractices/avoidInternal/kotlin",files="build.gradle.kts[tags=avoid-this]"]
include::sample[dir="snippets/bestPractices/avoidInternal/groovy",files="build.gradle[tags=avoid-this]"]
====

<1> Casting to `AttributeContainerInternal` and using `toMap()` should be avoided as it relies on an internal API.

==== Do This Instead

====
include::sample[dir="snippets/bestPractices/avoidInternal/kotlin",files="build.gradle.kts[tags=do-this]"]
include::sample[dir="snippets/bestPractices/avoidInternal/groovy",files="build.gradle[tags=do-this]"]
====

<1> Implementing your own version of `toMap()` that only uses public APIs is a lot more robust.

=== References

- link:https://docs.gradle.org/current/javadoc/[Gradle API]

=== Tags

<<tags_reference.adoc#tag:upgrades,`#upgrades`>>

[[no_source_in_root]]
== Do Not Put Source Files in the Root Project
:keywords: structuring-builds

Do not put source files in your root project; instead, put them in a separate project.

=== Explanation

The root project is a special project in Gradle that serves as the entry point for your build.

It is the place to configure settings that apply globally to the entire build.
For example, you can _declare_ (but not apply) plugins here to ensure the same plugin version is consistently available across all projects and define other configurations shared by all projects within the build.

NOTE: Be careful not to apply plugins unnecessarily in the root project - many plugins only affect source code and should only be applied to the projects that contain source code.

The root project should not be used for source files, instead they should be located in a separate Gradle project.

Setting up your build like this from the start will also make it easier to add new projects as your build grows in the future.

=== Example

==== Don't Do This

[.multi-language-sample]
=====
.A common way to structure new builds
[source, kotlin]
----
├── build.gradle.kts // Applies the `java-library` plugin to the root project
├── settings.gradle.kts
└── src // This directory shouldn't exist
    └── main
        └── java
            └── org
                └── example
                    └── MyClass1.java
----
=====
[.multi-language-sample]
=====
.A common way to structure new builds
[source, groovy]
----
├── build.gradle // Applies the `java-library` plugin to the root project
├── settings.gradle
└── src // This directory shouldn't exist
    └── main
        └── java
            └── org
                └── example
                    └── MyClass1.java
----
=====

====
include::sample[dir="snippets/bestPractices/noSourceInRoot-avoid/kotlin",files="build.gradle.kts[tags=avoid-this]"]
include::sample[dir="snippets/bestPractices/noSourceInRoot-avoid/groovy",files="build.gradle[tags=avoid-this]"]
====

<1> The `java-library` plugin is applied to the root project, as there are Java source files are in the root project.

==== Do This Instead


[.multi-language-sample]
=====
.A better way to structure new builds
[source, kotlin]
----
├── core
│    ├── build.gradle.kts // Applies the `java-library` plugin to only the `core` project
│    └── src // Source lives in a "core" (sub)project
│        └── main
│            └── java
│                └── org
│                    └── example
│                        └── MyClass1.java
└── settings.gradle.kts

----
=====
[.multi-language-sample]
=====
.A better way to structure new builds
[source, groovy]
----
├── core
│    ├── build.gradle // Applies the `java-library` plugin to only the `core` project
│    └── src // Source lives in a "core" (sub)project
│        └── main
│            └── java
│                └── org
│                    └── example
│                        └── MyClass1.java
└── settings.gradle
----
=====

====
include::sample[dir="snippets/bestPractices/noSourceInRoot-do/kotlin",files="settings.gradle.kts[tags=do-this]"]
include::sample[dir="snippets/bestPractices/noSourceInRoot-do/groovy",files="settings.gradle[tags=do-this]"]
====
====
include::sample[dir="snippets/bestPractices/noSourceInRoot-do/kotlin/core",files="build.gradle.kts[tags=do-this]"]
include::sample[dir="snippets/bestPractices/noSourceInRoot-do/groovy/core",files="build.gradle[tags=do-this]"]
====

<1> The root project exists only to configure the build, informing Gradle of a (sub)project named `core`.
<2> The `java-library` plugin is only applied to the `core` project, which contains the Java source files.

=== References

- <<multi_project_builds.adoc#multi_project_builds,Structuring Projects with Gradle>>
- <<organizing_gradle_projects.adoc#sec:settings_file,Organizing Gradle Projects>>

=== Tags

`<<tags_reference.adoc#tag:structuring-builds,#structuring-builds>>`
