// Copyright (C) 2025 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[best_practices_for_performance]]
= Best Practices for Performance

[[use_utf8_encoding]]
== Use UTF-8 File Encoding

Set `UTF-8` as the default file encoding to ensure consistent behavior across platforms.

=== Explanation

Use `UTF-8` as the default file encoding to ensure consistent behavior across environments and avoid caching issues caused by platform-dependent default encodings.

This is especially important when working with build caching, since differences in file encoding between environments can cause unexpected cache misses.

To enforce `UTF-8` encoding, add the following to your `gradle.properties` file:

[source,properties]
----
org.gradle.jvmargs=-Dfile.encoding=UTF-8
----

NOTE: Do not rely on the default encoding of the underlying JVM or operating system, as this may differ between environments and lead to inconsistent behavior.

=== References

- <<common_caching_problems.adoc#system_file_encoding,File encoding and Caching>>.

=== Tags

`<<tags_reference.adoc#tag:properties,#properties>>`, `<<tags_reference.adoc#tag:caching,#caching>>`

[[use_build_cache]]
== Use the Build Cache

Use the build cache to save time by reusing outputs produced by other builds.

=== Explanation

The build cache avoids executing a task to recompute its outputs if Gradle can instead reuse those outputs from an earlier build, resulting in faster builds.

This avoids unnecessary work when a task's inputs haven't changed - since the work of producing output has already been done during a previous run - and the result will be the same.

=== Example

==== Don't Do This

Build caching is disabled by default if not set:

====
include::sample[dir="snippets/bestPractices/useBuildCache-avoid/kotlin",files="gradle.properties[tags=avoid-this]"]
====

==== Do This Instead

To enable the build cache, add the following to your `gradle.properties` file:

====
include::sample[dir="snippets/bestPractices/useBuildCache-do/kotlin",files="gradle.properties[tags=do-this]"]
====
When building your project for the first time, the cache will be populated with the output of the compilation.

You can even issue a `gradle clean` command to remove the outputs from the build directory.

----
> gradle clean
:clean

BUILD SUCCESSFUL
----

On subsequent builds, instead of executing the ``:compileJava` task again, the outputs of the task will be loaded from the build cache:

----
> gradle compileJava

include::{snippetsPath}/bestPractices/useBuildCache-do/tests/useBuildCache-do.secondRun.out[]
----

=== References

- <<build_cache.adoc#sec:build_cache_intro,Build Cache Overview>>

=== Tags

`<<tags_reference.adoc#tag:properties,#properties>>`, `<<tags_reference.adoc#tag:caching,#caching>>`
