// Copyright (C) 2025 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[best_practices_for_dependencies]]
= Best Practices for Dependencies

[[name_version_catalog_entries]]
== Name Version Catalog Entries Appropriately

Consistent and descriptive names in your version catalog enhance readability and maintainability across your build scripts.

=== Explanation

Version catalogs provide a centralized way to manage dependencies.
Adopting clear naming conventions for catalog entries ensures that developers can easily identify and use dependencies throughout the project.

The following guidelines help in naming catalog entries effectively:

1. **Use dashes to separate segments**: Prefer dashes (`-`) over underscores (`_`) to separate different parts of the entry name.
+
*Example*: For `org.apache.logging.log4j:log4j-api`, use `log4j-api`

2. **Derive the first segment from the project group**: Use a unique identifier from the project's group ID as the first segment.
+
*Example*: For `com.fasterxml.jackson.core:jackson-databind`, use `jackson-databind`

3. **Omit redundant segments**: If the group and artifact IDs are the same, avoid repeating them.
+
*Example*: For `io.ktor:ktor-client-core`, use `ktor-client-core`, not `ktor-ktor-client-core`

4. **Convert internal dashes to camelCase**: If the artifact ID contains dashes, convert them to camelCase for better readability in code.
+
*Example*: `spring-boot-starter-web` becomes `springBootStarterWeb`

5. **Avoid implicit terms**: Exclude terms that are obvious or implied in the context of your project.
+
*Example*: For `com.amazonaws:aws-java-sdk-core`, use `aws-core`, not `aws-javaSdkCore`

6. **Suffix plugin libraries with `-plugin`**: When referencing a plugin as a library (not in the `[plugins]` section), append `-plugin` to the name.
+
*Example*: For `org.owasp:dependency-check-gradle`, use `dependency-check-plugin`

=== Examples

====
include::sample[dir="snippets/bestPractices/versionCatalogNaming/kotlin",files="gradle/libs.versions.toml[]"]
====

====
include::sample[dir="snippets/bestPractices/versionCatalogNaming/kotlin",files="build.gradle.kts[tags=do-this]"]
include::sample[dir="snippets/bestPractices/versionCatalogNaming/groovy",files="build.gradle[tags=do-this]"]
====

=== References

- link:https://blog.gradle.org/best-practices-naming-version-catalog-entries[Best Practices for Naming Gradle Version Catalog Entries]

=== Tags

`<<tags_reference.adoc#tag:version-catalog,#version-catalog>>`

[[set_up_repositories_in_settings]]
== Set up your dependency repositories in `settings.gradle.kts`

Declare your repositories for your plugins and dependencies in `settings.gradle.kts`.

=== Explanation

Using `settings.gradle.kts` file to declare repositories has several benefits:

 - Avoids repetition: Centralizing repository declarations eliminates the need to repeat them in each project's `build.gradle.kts`.
 - Improves debuggability: Ensures all projects resolve dependencies during resolution from the same repositories, in a consistent order.
 - Matches the build model: Repositories are not part of the project definition; they are part of global build logic, so settings is a more appropriate place for them.

Note: While https://github.com/gradle/gradle/issues/32443[`dependencyResolutionManagement.repositories` is an incubating API], it is the preferred way of declaring repositories.

=== Example

==== Don't Do This

You could set up repositories in individual `build.gradle.kts` files with:

====
include::sample[dir="snippets/bestPractices/settingsRepositoriesDont/kotlin",files="build.gradle.kts[tags=avoid-this]"]
include::sample[dir="snippets/bestPractices/settingsRepositoriesDont/groovy",files="build.gradle[tags=avoid-this]"]
====

==== Do This Instead

Instead, you should set them up in `settings.gradle.kts` like this:

====
include::sample[dir="snippets/bestPractices/settingsRepositoriesDo/kotlin",files="settings.gradle.kts[tags=do-this]"]
include::sample[dir="snippets/bestPractices/settingsRepositoriesDo/groovy",files="settings.gradle[tags=do-this]"]
====

=== Tags
`<<tags_reference.adoc#tag:structuring-builds,#structuring-builds>>`
