// Copyright (C) 2025 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[best_practices_general]]
= General Gradle Best Practices

[[use_latest_minor_versions]]
== Use the Latest Minor Version of Gradle and Plugins

Stay on the latest minor version of the major Gradle release you're using, and regularly update your plugins to the latest compatible versions.

=== Explanation

Each new Gradle minor release includes important bug fixes, performance improvements, and deprecation warnings that help you prepare for future breaking changes.

Staying current with minor versions helps you:

* Benefit from performance and stability improvements.
* Catch deprecations early, while fixes are still simple.
* Avoid large, painful upgrades caused by skipping too many versions.

Similarly, use the latest _compatible_ version for each plugin in your build:

* Prefer the latest minor version: Stay on the latest `.Y` release of the major Gradle version you're using.
* Test compatibility proactively: Run link:https://slack.engineering/shadow-jobs/[shadow jobs] or CI jobs to detect regressions early.
* Upgrade Gradle first: Many plugin upgrades require features or fixes in newer Gradle versions.

=== Example

==== Don't Do This

====
include::sample[dir="snippets/bestPractices/useLatestVersion/kotlin/avoid-this",files="build.gradle.kts[tags=avoid-this]"]
include::sample[dir="snippets/bestPractices/useLatestVersion/groovy/avoid-this",files="build.gradle[tags=avoid-this]"]
====

<1> Old and potentially buggy version of plugin.

==== Do This Instead

====
include::sample[dir="snippets/bestPractices/useLatestVersion/kotlin/do-this",files="build.gradle.kts[tags=do-this]"]
include::sample[dir="snippets/bestPractices/useLatestVersion/groovy/do-this",files="build.gradle[tags=do-this]"]
====

<1> Latest known stable minor version of plugin.

=== References
<<upgrading_version_8.adoc#upgrading_version_8,Upgrade Guide>>

=== Tags
`#plugins`

[[use_the_plugins_block]]
== Apply Plugins Using the `plugins` Block

You should always use the `plugins` block to <<plugin_basics.adoc#applying_plugins,apply plugins>> in your build scripts.

=== Explanation

The `plugins` block is the preferred way to apply plugins in Gradle.
The plugins API allows Gradle to better manage the loading of plugins and it is both more concise and less error-prone than adding dependencies to the buildscript's classpath explicitly in order to use the `apply` method.

It allows Gradle to optimize the loading and reuse of plugin classes and helps inform tools about the potential properties and values in extensions the plugins will add to the build script.
It is constrained to be idempotent (produce the same result every time) and side effect-free (safe for Gradle to execute at any time).

=== Example

==== Don't Do This

====
include::sample[dir="snippets/bestPractices/usePluginsBlock/kotlin/avoid-this",files="build.gradle.kts[tags=avoid-this]"]
include::sample[dir="snippets/bestPractices/usePluginsBlock/groovy/avoid-this",files="build.gradle[tags=avoid-this]"]
====

<1> *Declare a Repository*: To use the legacy plugin application syntax, you need to explicitly tell Gradle where to find a plugin.
<2> *Declare a Plugin Dependency*: To use the legacy plugin application syntax with third-party plugins, you need to explicitly tell Gradle the full coordinates of the plugin.
<3> *Apply a Core Plugin*: This is very similar using either method.
<4> *Apply a Third-Party Plugin*: The syntax is the same as for core Gradle plugins, but the version is not present at the point of application in your buildscript.

==== Do This Instead

====
include::sample[dir="snippets/bestPractices/usePluginsBlock/kotlin/do-this",files="build.gradle.kts[tags=do-this]"]
include::sample[dir="snippets/bestPractices/usePluginsBlock/groovy/do-this",files="build.gradle[tags=do-this]"]
====

<1> *Apply a Core Plugin*: This is very similar using either method.
<2> *Apply a Third-Party Plugin*: You specify the version using method chaining in the `plugins` block itself.

=== References
<<plugins.adoc#sec:using_plugins,Using Plugins>>

=== Tags
`#structuring-builds`
