// Copyright (C) 2025 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[best_practices_general]]
= General Gradle Best Practices

[[use_the_plugins_block]]
== Apply Plugins Using the `plugins` Block

You should always use the `plugins` block to <<plugin_basics.adoc#applying_plugins,apply plugins>> in your build scripts.

=== Explanation

The `plugins` block is the preferred way to apply plugins in Gradle.
The plugins API allows Gradle to better manage the loading of plugins and it is both more concise and less error-prone than adding dependencies to the buildscript's classpath explicitly in order to use the `apply` method.

It allows Gradle to optimize the loading and reuse of plugin classes and helps inform tools about the potential properties and values in extensions the plugins will add to the build script.
It is constrained to be idempotent (produce the same result every time) and side effect-free (safe for Gradle to execute at any time).

=== Example

==== Don't Do This

====
include::sample[dir="snippets/bestPractices/usePluginsBlock/kotlin/avoid-this",files="build.gradle.kts[tags=avoid-this]"]
include::sample[dir="snippets/bestPractices/usePluginsBlock/groovy/avoid-this",files="build.gradle[tags=avoid-this]"]
====

<1> *Declare a Repository*: To use the legacy plugin application syntax, you need to explicitly tell Gradle where to find a plugin.
<2> *Declare a Plugin Dependency*: To use the legacy plugin application syntax with third-party plugins, you need to explicitly tell Gradle the full coordinates of the plugin.
<3> *Apply a Core Plugin*: This is very similar using either method.
<4> *Apply a Third-Party Plugin*: The syntax is the same as for core Gradle plugins, but the version is not present at the point of application in your buildscript.

==== Do This Instead

====
include::sample[dir="snippets/bestPractices/usePluginsBlock/kotlin/do-this",files="build.gradle.kts[tags=do-this]"]
include::sample[dir="snippets/bestPractices/usePluginsBlock/groovy/do-this",files="build.gradle[tags=do-this]"]
====

<1> *Apply a Core Plugin*: This is very similar using either method.
<2> *Apply a Third-Party Plugin*: You specify the version using method chaining in the `plugins` block itself.

=== References
<<plugins.adoc#sec:using_plugins,Using Plugins>>

=== Tags
`#structuring-builds`

== Do Not Use Internal APIs

Do not use APIs from a package where any segment of the package is `internal`, or types that have `Internal` or `Impl` as a suffix in the name.

=== Explanation

Using internal APIs is inherently risky and can cause significant problems during upgrades.
Gradle and many plugins (such as Android Gradle Plugin and Kotlin Gradle Plugin) treat these internal APIs as subject to unannounced breaking changes during any new Gradle release, even during minor releases.
There have been numerous cases where even highly experienced plugin developers have been bitten by their usage of such APIs leading to unexpected breakages for their users.

If you require specific functionality that is missing, it’s best to submit a feature request.
As a temporary workaround consider copying the necessary code into your own codebase and extending a Gradle public type with your own custom implementation using the copied code.

=== Example

==== Don't Do This

====
include::sample[dir="snippets/bestPractices/avoidInternal/kotlin",files="build.gradle.kts[tags=avoid-this]"]
include::sample[dir="snippets/bestPractices/avoidInternal/groovy",files="build.gradle[tags=avoid-this]"]
====

<1> Casting to `AttributeContainerInternal` and using `toMap()` should be avoided as it relies on an internal API.

==== Do This Instead

====
include::sample[dir="snippets/bestPractices/avoidInternal/kotlin",files="build.gradle.kts[tags=do-this]"]
include::sample[dir="snippets/bestPractices/avoidInternal/groovy",files="build.gradle[tags=do-this]"]
====

<2> Implementing your own version of `toMap()` that only uses public APIs is a lot more robust.

=== Tags
`#upgrades`

[[favor_composite_builds]]
== Favor Composite Builds over `buildSrc`

You should setup a <<composite_builds.adoc#defining_composite_builds,Composite Build>> (commonly called an "included build") to hold your _build logic_ (such as any plugins - including convention plugins - and other customizations that are specific to your build).

=== Explanation

The preferred location for build logic is an included build named `build-logic`, **not** in `buildSrc`.

The automatically available `buildSrc` is great for rapid prototyping, but suffers from some subtle disadvantages:
- There are classloader differences in how these 2 approaches behave that can be surprising; included builds are treated just like external dependencies, which is a simpler mental model.  Dependency resolution behaves subtly differently in buildSrc.
- There can potentially be fewer task invalidations in a build when files in an included build are modified, leading to faster builds.
- Included builds are complete Gradle builds and can be opened, worked on, and built independently as standalone projects.

Ideally, there shouldn’t be any differences between these 2 approaches, and `buildSrc` should behave like an implicitly available included build if present.
However, due to historical reasons, these differences currently exist.
It is likely that in the future this recommendation will be weakened or removed entirely, as Gradle continues to work to converge the behavior of these two approaches.
At present, however, the differences can be a potential stumbling block.

As there is only minor additional configuration necessary to setup a composite build, we recommend using these instead of `buildSrc`.

=== Example

==== Don't Do This

====
include::sample[dir="snippets/bestPractices/favorCompositeBuilds/kotlin/avoid-this/buildSrc",files="build.gradle.kts[tags=avoid-this]"]
include::sample[dir="snippets/bestPractices/favorCompositeBuilds/groovy/avoid-this/buildSrc",files="build.gradle[tags=avoid-this]"]
====

*Setup a Plugin Build*: This is the same using either method.

====
include::sample[dir="snippets/bestPractices/favorCompositeBuilds/kotlin/avoid-this",files="settings.gradle.kts[tags=avoid-this]"]
include::sample[dir="snippets/bestPractices/favorCompositeBuilds/groovy/avoid-this",files="settings.gradle[tags=avoid-this]"]
====

*BuildSrc products are automatically usable*: There is no additional configuration with this method.

==== Do This Instead

====
include::sample[dir="snippets/bestPractices/favorCompositeBuilds/kotlin/do-this/build-logic",files="build.gradle.kts[tags=do-this]"]
include::sample[dir="snippets/bestPractices/favorCompositeBuilds/groovy/do-this/build-logic",files="build.gradle[tags=do-this]"]
====

*Setup a Plugin Build*: This is the same using either method.

====
include::sample[dir="snippets/bestPractices/favorCompositeBuilds/kotlin/do-this",files="settings.gradle.kts[tags=do-this]"]
include::sample[dir="snippets/bestPractices/favorCompositeBuilds/groovy/do-this",files="settings.gradle[tags=do-this]"]
====

<1> *Composite builds must be declared*: Use the `includeBuild` method to locate and include a build in order to use its products.

=== References
<<part3_multi_project_builds.adoc#step_3_understand_composite_builds,Composite Builds in the Multi-Project Builds Tutorial>>
<<composite_builds.adoc#composite_builds,Composite Builds reference documentation>>

=== Tags
`#structuring-builds`
