package Gradle_Check.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.GradleBuildStep
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = 'Gradle_Check_Quick_Java7_Oracle_Windows_iT' (id = 'Gradle_Check_Quick_Java7_Oracle_Windows_iT')
accordingly and delete the patch script.
*/
changeBuildType("Gradle_Check_Quick_Java7_Oracle_Windows_iT") {
    expectSteps {
        gradle {
            name = "CLEAN_BUILD_SRC"
            tasks = "clean"
            buildFile = "build.gradle.kts"
            workingDir = "buildSrc"
            gradleParams = """-PmaxParallelForks=%maxParallelForks% -s --daemon --continue -I "%teamcity.build.checkoutDir%/gradle/init-scripts/build-scan.init.gradle.kts" "-Djava7Home=%windows.java7.oracle.64bit%""""
            useGradleWrapper = true
            gradleWrapperPath = ".."
        }
        gradle {
            name = "GRADLE_RUNNER"
            tasks = "clean internalTesting:quickTest"
            buildFile = ""
            gradleParams = """-PmaxParallelForks=%maxParallelForks% -s --daemon --continue -I "%teamcity.build.checkoutDir%/gradle/init-scripts/build-scan.init.gradle.kts" "-Djava7Home=%windows.java7.oracle.64bit%" --build-cache "-Dgradle.cache.remote.url=%gradle.cache.remote.url%" "-Dgradle.cache.remote.username=%gradle.cache.remote.username%" "-Dgradle.cache.remote.password=%gradle.cache.remote.password%" "-PtestJavaHome=%windows.java7.oracle.64bit%" "-Dscan.tag.FunctionalTest" "-Dscan.value.coverageOs=windows" "-Dscan.value.coverageJvmVendor=oracle" "-Dscan.value.coverageJvmVersion=java7" "-Dscan.tag.Check" "-Dscan.tag.QuickFeedback""""
            useGradleWrapper = true
        }
        script {
            name = "CHECK_CLEAN_M2"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            scriptContent = """
                IF exist %teamcity.agent.jvm.user.home%\.m2\repository (
                    TREE %teamcity.agent.jvm.user.home%\.m2\repository
                    RMDIR /S /Q %teamcity.agent.jvm.user.home%\.m2\repository
                    EXIT 1
                )
            """.trimIndent()
        }
        gradle {
            name = "VERIFY_TEST_FILES_CLEANUP"
            tasks = "verifyTestFilesCleanup"
            buildFile = ""
            gradleParams = """-PmaxParallelForks=%maxParallelForks% -s --daemon --continue -I "%teamcity.build.checkoutDir%/gradle/init-scripts/build-scan.init.gradle.kts" "-Djava7Home=%windows.java7.oracle.64bit%""""
            useGradleWrapper = true
        }
        gradle {
            name = "KILL_PROCESSES_STARTED_BY_GRADLE"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            tasks = "killExistingProcessesStartedByGradle"
            buildFile = ""
            gradleParams = """-PmaxParallelForks=%maxParallelForks% -s --daemon --continue -I "%teamcity.build.checkoutDir%/gradle/init-scripts/build-scan.init.gradle.kts" "-Djava7Home=%windows.java7.oracle.64bit%""""
            useGradleWrapper = true
        }
        gradle {
            name = "TAG_BUILD"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            tasks = "tagBuild"
            buildFile = "gradle/buildTagging.gradle"
            gradleParams = """-PmaxParallelForks=%maxParallelForks% -s --daemon --continue -I "%teamcity.build.checkoutDir%/gradle/init-scripts/build-scan.init.gradle.kts" "-Djava7Home=%windows.java7.oracle.64bit%" -PteamCityUsername=%teamcity.username.restbot% -PteamCityPassword=%teamcity.password.restbot% -PteamCityBuildId=%teamcity.build.id% -PgithubToken=%github.ci.oauth.token%"""
            useGradleWrapper = true
        }
    }
    steps {
        update<GradleBuildStep>(1) {
            gradleParams = """-PmaxParallelForks=%maxParallelForks% -s --daemon --continue -I "%teamcity.build.checkoutDir%/gradle/init-scripts/build-scan.init.gradle.kts" "-Djava7Home=%windows.java7.oracle.64bit%" --build-cache "-Dgradle.cache.remote.url=%gradle.cache.remote.url%" "-Dgradle.cache.remote.username=%gradle.cache.remote.username%" -Dgradle.cache.remote.password="%gradle.cache.remote.password%" "-PtestJavaHome=%windows.java7.oracle.64bit%" "-Dscan.tag.FunctionalTest" "-Dscan.value.coverageOs=windows" "-Dscan.value.coverageJvmVendor=oracle" "-Dscan.value.coverageJvmVersion=java7" "-Dscan.tag.Check" "-Dscan.tag.QuickFeedback""""
            param("org.jfrog.artifactory.selectedDeployableServer.defaultModuleVersionConfiguration", "GLOBAL")
        }
    }
}
