/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id("gradlebuild.distribution.api-java")
}

description = "The client-side connection to a Gradle daemon: connector, connection and protocol dispatchers. " +
    "Shared by the daemon build client and the daemon management API."

dependencies {
    api(projects.core)
    api(projects.daemonMessaging)
    api(projects.daemonProtocol)
    api(projects.enterpriseLogging)
    api(projects.messaging)
    api(projects.serialization)
    api(projects.stdlibJavaExtensions)
    api(libs.jspecify)

    implementation(projects.concurrent)
    implementation(projects.daemonLogging)
    implementation(projects.loggingApi)
    implementation(projects.time)

    implementation(libs.guava)

    runtimeOnly(projects.logging)

    testImplementation(testFixtures(projects.daemonProtocol))
}

gradleModule {
    requiredRuntimes {
        client = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
    }
}
