// Copyright (C) 2024 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[license]]
= License Information

[[sec:gradle_documentation]]
== Gradle Documentation

Copyright © 2024 Gradle, Inc. All rights reserved.
Gradle is a trademark of Gradle, Inc.

Gradle's Build Tool source code is open-source and licensed under the link:https://github.com/gradle/gradle/blob/master/LICENSE[Apache License 2.0].

Gradle's User Manual and DSL Reference Manual are licensed under link:http://creativecommons.org/licenses/by-nc-sa/4.0/[Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License].

[[licenses:build_scan_plugin]]
== Gradle Build Scan Plugin

Use of the link:https://scans.gradle.com/plugin/[Build Scan plugin] is subject to link:https://gradle.com/legal/terms-of-service/[Gradle's Terms of Service].
