// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tooling.proto

package org.gradle.tooling.internal.grpc.proto;

/**
 * Protobuf type {@code gradle.tooling.grpc.BuildRequest}
 */
public final class BuildRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gradle.tooling.grpc.BuildRequest)
    BuildRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BuildRequest.newBuilder() to construct.
  private BuildRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BuildRequest() {
    args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    projectDir_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BuildRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_BuildRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_BuildRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.gradle.tooling.internal.grpc.proto.BuildRequest.class, org.gradle.tooling.internal.grpc.proto.BuildRequest.Builder.class);
  }

  public static final int ARGS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList args_;
  /**
   * <pre>
   * CLI-equivalent args: tasks + flags (-P/-D/--x)
   * </pre>
   *
   * <code>repeated string args = 1;</code>
   * @return A list containing the args.
   */
  public com.google.protobuf.ProtocolStringList
      getArgsList() {
    return args_;
  }
  /**
   * <pre>
   * CLI-equivalent args: tasks + flags (-P/-D/--x)
   * </pre>
   *
   * <code>repeated string args = 1;</code>
   * @return The count of args.
   */
  public int getArgsCount() {
    return args_.size();
  }
  /**
   * <pre>
   * CLI-equivalent args: tasks + flags (-P/-D/--x)
   * </pre>
   *
   * <code>repeated string args = 1;</code>
   * @param index The index of the element to return.
   * @return The args at the given index.
   */
  public java.lang.String getArgs(int index) {
    return args_.get(index);
  }
  /**
   * <pre>
   * CLI-equivalent args: tasks + flags (-P/-D/--x)
   * </pre>
   *
   * <code>repeated string args = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the args at the given index.
   */
  public com.google.protobuf.ByteString
      getArgsBytes(int index) {
    return args_.getByteString(index);
  }

  public static final int PROJECT_DIR_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object projectDir_ = "";
  /**
   * <pre>
   * build root; drives build layout
   * </pre>
   *
   * <code>string project_dir = 2;</code>
   * @return The projectDir.
   */
  @java.lang.Override
  public java.lang.String getProjectDir() {
    java.lang.Object ref = projectDir_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      projectDir_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * build root; drives build layout
   * </pre>
   *
   * <code>string project_dir = 2;</code>
   * @return The bytes for projectDir.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProjectDirBytes() {
    java.lang.Object ref = projectDir_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projectDir_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < args_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, args_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(projectDir_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, projectDir_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < args_.size(); i++) {
        dataSize += computeStringSizeNoTag(args_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getArgsList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(projectDir_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, projectDir_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.gradle.tooling.internal.grpc.proto.BuildRequest)) {
      return super.equals(obj);
    }
    org.gradle.tooling.internal.grpc.proto.BuildRequest other = (org.gradle.tooling.internal.grpc.proto.BuildRequest) obj;

    if (!getArgsList()
        .equals(other.getArgsList())) return false;
    if (!getProjectDir()
        .equals(other.getProjectDir())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getArgsCount() > 0) {
      hash = (37 * hash) + ARGS_FIELD_NUMBER;
      hash = (53 * hash) + getArgsList().hashCode();
    }
    hash = (37 * hash) + PROJECT_DIR_FIELD_NUMBER;
    hash = (53 * hash) + getProjectDir().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.gradle.tooling.internal.grpc.proto.BuildRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gradle.tooling.internal.grpc.proto.BuildRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.BuildRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gradle.tooling.internal.grpc.proto.BuildRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.BuildRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gradle.tooling.internal.grpc.proto.BuildRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.BuildRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gradle.tooling.internal.grpc.proto.BuildRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.BuildRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.gradle.tooling.internal.grpc.proto.BuildRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.BuildRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gradle.tooling.internal.grpc.proto.BuildRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.gradle.tooling.internal.grpc.proto.BuildRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gradle.tooling.grpc.BuildRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gradle.tooling.grpc.BuildRequest)
      org.gradle.tooling.internal.grpc.proto.BuildRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_BuildRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_BuildRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gradle.tooling.internal.grpc.proto.BuildRequest.class, org.gradle.tooling.internal.grpc.proto.BuildRequest.Builder.class);
    }

    // Construct using org.gradle.tooling.internal.grpc.proto.BuildRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      projectDir_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_BuildRequest_descriptor;
    }

    @java.lang.Override
    public org.gradle.tooling.internal.grpc.proto.BuildRequest getDefaultInstanceForType() {
      return org.gradle.tooling.internal.grpc.proto.BuildRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.gradle.tooling.internal.grpc.proto.BuildRequest build() {
      org.gradle.tooling.internal.grpc.proto.BuildRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.gradle.tooling.internal.grpc.proto.BuildRequest buildPartial() {
      org.gradle.tooling.internal.grpc.proto.BuildRequest result = new org.gradle.tooling.internal.grpc.proto.BuildRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.gradle.tooling.internal.grpc.proto.BuildRequest result) {
      if (((bitField0_ & 0x00000001) != 0)) {
        args_ = args_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.args_ = args_;
    }

    private void buildPartial0(org.gradle.tooling.internal.grpc.proto.BuildRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.projectDir_ = projectDir_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.gradle.tooling.internal.grpc.proto.BuildRequest) {
        return mergeFrom((org.gradle.tooling.internal.grpc.proto.BuildRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.gradle.tooling.internal.grpc.proto.BuildRequest other) {
      if (other == org.gradle.tooling.internal.grpc.proto.BuildRequest.getDefaultInstance()) return this;
      if (!other.args_.isEmpty()) {
        if (args_.isEmpty()) {
          args_ = other.args_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureArgsIsMutable();
          args_.addAll(other.args_);
        }
        onChanged();
      }
      if (!other.getProjectDir().isEmpty()) {
        projectDir_ = other.projectDir_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureArgsIsMutable();
              args_.add(s);
              break;
            } // case 10
            case 18: {
              projectDir_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureArgsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        args_ = new com.google.protobuf.LazyStringArrayList(args_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * CLI-equivalent args: tasks + flags (-P/-D/--x)
     * </pre>
     *
     * <code>repeated string args = 1;</code>
     * @return A list containing the args.
     */
    public com.google.protobuf.ProtocolStringList
        getArgsList() {
      return args_.getUnmodifiableView();
    }
    /**
     * <pre>
     * CLI-equivalent args: tasks + flags (-P/-D/--x)
     * </pre>
     *
     * <code>repeated string args = 1;</code>
     * @return The count of args.
     */
    public int getArgsCount() {
      return args_.size();
    }
    /**
     * <pre>
     * CLI-equivalent args: tasks + flags (-P/-D/--x)
     * </pre>
     *
     * <code>repeated string args = 1;</code>
     * @param index The index of the element to return.
     * @return The args at the given index.
     */
    public java.lang.String getArgs(int index) {
      return args_.get(index);
    }
    /**
     * <pre>
     * CLI-equivalent args: tasks + flags (-P/-D/--x)
     * </pre>
     *
     * <code>repeated string args = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the args at the given index.
     */
    public com.google.protobuf.ByteString
        getArgsBytes(int index) {
      return args_.getByteString(index);
    }
    /**
     * <pre>
     * CLI-equivalent args: tasks + flags (-P/-D/--x)
     * </pre>
     *
     * <code>repeated string args = 1;</code>
     * @param index The index to set the value at.
     * @param value The args to set.
     * @return This builder for chaining.
     */
    public Builder setArgs(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureArgsIsMutable();
      args_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * CLI-equivalent args: tasks + flags (-P/-D/--x)
     * </pre>
     *
     * <code>repeated string args = 1;</code>
     * @param value The args to add.
     * @return This builder for chaining.
     */
    public Builder addArgs(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureArgsIsMutable();
      args_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * CLI-equivalent args: tasks + flags (-P/-D/--x)
     * </pre>
     *
     * <code>repeated string args = 1;</code>
     * @param values The args to add.
     * @return This builder for chaining.
     */
    public Builder addAllArgs(
        java.lang.Iterable<java.lang.String> values) {
      ensureArgsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, args_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * CLI-equivalent args: tasks + flags (-P/-D/--x)
     * </pre>
     *
     * <code>repeated string args = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearArgs() {
      args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * CLI-equivalent args: tasks + flags (-P/-D/--x)
     * </pre>
     *
     * <code>repeated string args = 1;</code>
     * @param value The bytes of the args to add.
     * @return This builder for chaining.
     */
    public Builder addArgsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureArgsIsMutable();
      args_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object projectDir_ = "";
    /**
     * <pre>
     * build root; drives build layout
     * </pre>
     *
     * <code>string project_dir = 2;</code>
     * @return The projectDir.
     */
    public java.lang.String getProjectDir() {
      java.lang.Object ref = projectDir_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectDir_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * build root; drives build layout
     * </pre>
     *
     * <code>string project_dir = 2;</code>
     * @return The bytes for projectDir.
     */
    public com.google.protobuf.ByteString
        getProjectDirBytes() {
      java.lang.Object ref = projectDir_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * build root; drives build layout
     * </pre>
     *
     * <code>string project_dir = 2;</code>
     * @param value The projectDir to set.
     * @return This builder for chaining.
     */
    public Builder setProjectDir(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      projectDir_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * build root; drives build layout
     * </pre>
     *
     * <code>string project_dir = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProjectDir() {
      projectDir_ = getDefaultInstance().getProjectDir();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * build root; drives build layout
     * </pre>
     *
     * <code>string project_dir = 2;</code>
     * @param value The bytes for projectDir to set.
     * @return This builder for chaining.
     */
    public Builder setProjectDirBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      projectDir_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gradle.tooling.grpc.BuildRequest)
  }

  // @@protoc_insertion_point(class_scope:gradle.tooling.grpc.BuildRequest)
  private static final org.gradle.tooling.internal.grpc.proto.BuildRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.gradle.tooling.internal.grpc.proto.BuildRequest();
  }

  public static org.gradle.tooling.internal.grpc.proto.BuildRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BuildRequest>
      PARSER = new com.google.protobuf.AbstractParser<BuildRequest>() {
    @java.lang.Override
    public BuildRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BuildRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BuildRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.gradle.tooling.internal.grpc.proto.BuildRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

