// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tooling.proto

package org.gradle.tooling.internal.grpc.proto;

public interface InputChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gradle.tooling.grpc.InputChunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the running build to feed
   * </pre>
   *
   * <code>string build_id = 1;</code>
   * @return The buildId.
   */
  java.lang.String getBuildId();
  /**
   * <pre>
   * the running build to feed
   * </pre>
   *
   * <code>string build_id = 1;</code>
   * @return The bytes for buildId.
   */
  com.google.protobuf.ByteString
      getBuildIdBytes();

  /**
   * <pre>
   * standard-input bytes
   * </pre>
   *
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <pre>
   * signals end of input (closes the build's standard input)
   * </pre>
   *
   * <code>bool close = 3;</code>
   * @return The close.
   */
  boolean getClose();
}
