// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tooling.proto

package org.gradle.tooling.internal.grpc.proto;

/**
 * Protobuf type {@code gradle.tooling.grpc.OperationDescriptor}
 */
public final class OperationDescriptor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gradle.tooling.grpc.OperationDescriptor)
    OperationDescriptorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OperationDescriptor.newBuilder() to construct.
  private OperationDescriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OperationDescriptor() {
    id_ = "";
    parentId_ = "";
    displayName_ = "";
    type_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OperationDescriptor();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_OperationDescriptor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_OperationDescriptor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.gradle.tooling.internal.grpc.proto.OperationDescriptor.class, org.gradle.tooling.internal.grpc.proto.OperationDescriptor.Builder.class);
  }

  private int detailsCase_ = 0;
  private java.lang.Object details_;
  public enum DetailsCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TASK(10),
    DETAILS_NOT_SET(0);
    private final int value;
    private DetailsCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DetailsCase valueOf(int value) {
      return forNumber(value);
    }

    public static DetailsCase forNumber(int value) {
      switch (value) {
        case 10: return TASK;
        case 0: return DETAILS_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DetailsCase
  getDetailsCase() {
    return DetailsCase.forNumber(
        detailsCase_);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parentId_ = "";
  /**
   * <pre>
   * builds the operation tree
   * </pre>
   *
   * <code>string parent_id = 2;</code>
   * @return The parentId.
   */
  @java.lang.Override
  public java.lang.String getParentId() {
    java.lang.Object ref = parentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * builds the operation tree
   * </pre>
   *
   * <code>string parent_id = 2;</code>
   * @return The bytes for parentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentIdBytes() {
    java.lang.Object ref = parentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAY_NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object displayName_ = "";
  /**
   * <code>string display_name = 3;</code>
   * @return The displayName.
   */
  @java.lang.Override
  public java.lang.String getDisplayName() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayName_ = s;
      return s;
    }
  }
  /**
   * <code>string display_name = 3;</code>
   * @return The bytes for displayName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisplayNameBytes() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private int type_ = 0;
  /**
   * <code>.gradle.tooling.grpc.OperationType type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.gradle.tooling.grpc.OperationType type = 4;</code>
   * @return The type.
   */
  @java.lang.Override public org.gradle.tooling.internal.grpc.proto.OperationType getType() {
    org.gradle.tooling.internal.grpc.proto.OperationType result = org.gradle.tooling.internal.grpc.proto.OperationType.forNumber(type_);
    return result == null ? org.gradle.tooling.internal.grpc.proto.OperationType.UNRECOGNIZED : result;
  }

  public static final int TASK_FIELD_NUMBER = 10;
  /**
   * <code>.gradle.tooling.grpc.TaskOperationDetails task = 10;</code>
   * @return Whether the task field is set.
   */
  @java.lang.Override
  public boolean hasTask() {
    return detailsCase_ == 10;
  }
  /**
   * <code>.gradle.tooling.grpc.TaskOperationDetails task = 10;</code>
   * @return The task.
   */
  @java.lang.Override
  public org.gradle.tooling.internal.grpc.proto.TaskOperationDetails getTask() {
    if (detailsCase_ == 10) {
       return (org.gradle.tooling.internal.grpc.proto.TaskOperationDetails) details_;
    }
    return org.gradle.tooling.internal.grpc.proto.TaskOperationDetails.getDefaultInstance();
  }
  /**
   * <code>.gradle.tooling.grpc.TaskOperationDetails task = 10;</code>
   */
  @java.lang.Override
  public org.gradle.tooling.internal.grpc.proto.TaskOperationDetailsOrBuilder getTaskOrBuilder() {
    if (detailsCase_ == 10) {
       return (org.gradle.tooling.internal.grpc.proto.TaskOperationDetails) details_;
    }
    return org.gradle.tooling.internal.grpc.proto.TaskOperationDetails.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, parentId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(displayName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, displayName_);
    }
    if (type_ != org.gradle.tooling.internal.grpc.proto.OperationType.OPERATION_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, type_);
    }
    if (detailsCase_ == 10) {
      output.writeMessage(10, (org.gradle.tooling.internal.grpc.proto.TaskOperationDetails) details_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, parentId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(displayName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, displayName_);
    }
    if (type_ != org.gradle.tooling.internal.grpc.proto.OperationType.OPERATION_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, type_);
    }
    if (detailsCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (org.gradle.tooling.internal.grpc.proto.TaskOperationDetails) details_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.gradle.tooling.internal.grpc.proto.OperationDescriptor)) {
      return super.equals(obj);
    }
    org.gradle.tooling.internal.grpc.proto.OperationDescriptor other = (org.gradle.tooling.internal.grpc.proto.OperationDescriptor) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getParentId()
        .equals(other.getParentId())) return false;
    if (!getDisplayName()
        .equals(other.getDisplayName())) return false;
    if (type_ != other.type_) return false;
    if (!getDetailsCase().equals(other.getDetailsCase())) return false;
    switch (detailsCase_) {
      case 10:
        if (!getTask()
            .equals(other.getTask())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + PARENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getParentId().hashCode();
    hash = (37 * hash) + DISPLAY_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    switch (detailsCase_) {
      case 10:
        hash = (37 * hash) + TASK_FIELD_NUMBER;
        hash = (53 * hash) + getTask().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.gradle.tooling.internal.grpc.proto.OperationDescriptor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gradle.tooling.internal.grpc.proto.OperationDescriptor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.OperationDescriptor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gradle.tooling.internal.grpc.proto.OperationDescriptor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.OperationDescriptor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gradle.tooling.internal.grpc.proto.OperationDescriptor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.OperationDescriptor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gradle.tooling.internal.grpc.proto.OperationDescriptor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.OperationDescriptor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.gradle.tooling.internal.grpc.proto.OperationDescriptor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gradle.tooling.internal.grpc.proto.OperationDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gradle.tooling.internal.grpc.proto.OperationDescriptor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.gradle.tooling.internal.grpc.proto.OperationDescriptor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gradle.tooling.grpc.OperationDescriptor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gradle.tooling.grpc.OperationDescriptor)
      org.gradle.tooling.internal.grpc.proto.OperationDescriptorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_OperationDescriptor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_OperationDescriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gradle.tooling.internal.grpc.proto.OperationDescriptor.class, org.gradle.tooling.internal.grpc.proto.OperationDescriptor.Builder.class);
    }

    // Construct using org.gradle.tooling.internal.grpc.proto.OperationDescriptor.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      parentId_ = "";
      displayName_ = "";
      type_ = 0;
      if (taskBuilder_ != null) {
        taskBuilder_.clear();
      }
      detailsCase_ = 0;
      details_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.gradle.tooling.internal.grpc.proto.ToolingProto.internal_static_gradle_tooling_grpc_OperationDescriptor_descriptor;
    }

    @java.lang.Override
    public org.gradle.tooling.internal.grpc.proto.OperationDescriptor getDefaultInstanceForType() {
      return org.gradle.tooling.internal.grpc.proto.OperationDescriptor.getDefaultInstance();
    }

    @java.lang.Override
    public org.gradle.tooling.internal.grpc.proto.OperationDescriptor build() {
      org.gradle.tooling.internal.grpc.proto.OperationDescriptor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.gradle.tooling.internal.grpc.proto.OperationDescriptor buildPartial() {
      org.gradle.tooling.internal.grpc.proto.OperationDescriptor result = new org.gradle.tooling.internal.grpc.proto.OperationDescriptor(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(org.gradle.tooling.internal.grpc.proto.OperationDescriptor result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.parentId_ = parentId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.displayName_ = displayName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.type_ = type_;
      }
    }

    private void buildPartialOneofs(org.gradle.tooling.internal.grpc.proto.OperationDescriptor result) {
      result.detailsCase_ = detailsCase_;
      result.details_ = this.details_;
      if (detailsCase_ == 10 &&
          taskBuilder_ != null) {
        result.details_ = taskBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.gradle.tooling.internal.grpc.proto.OperationDescriptor) {
        return mergeFrom((org.gradle.tooling.internal.grpc.proto.OperationDescriptor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.gradle.tooling.internal.grpc.proto.OperationDescriptor other) {
      if (other == org.gradle.tooling.internal.grpc.proto.OperationDescriptor.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getParentId().isEmpty()) {
        parentId_ = other.parentId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getDisplayName().isEmpty()) {
        displayName_ = other.displayName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      switch (other.getDetailsCase()) {
        case TASK: {
          mergeTask(other.getTask());
          break;
        }
        case DETAILS_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              parentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              displayName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 82: {
              input.readMessage(
                  getTaskFieldBuilder().getBuilder(),
                  extensionRegistry);
              detailsCase_ = 10;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int detailsCase_ = 0;
    private java.lang.Object details_;
    public DetailsCase
        getDetailsCase() {
      return DetailsCase.forNumber(
          detailsCase_);
    }

    public Builder clearDetails() {
      detailsCase_ = 0;
      details_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object parentId_ = "";
    /**
     * <pre>
     * builds the operation tree
     * </pre>
     *
     * <code>string parent_id = 2;</code>
     * @return The parentId.
     */
    public java.lang.String getParentId() {
      java.lang.Object ref = parentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * builds the operation tree
     * </pre>
     *
     * <code>string parent_id = 2;</code>
     * @return The bytes for parentId.
     */
    public com.google.protobuf.ByteString
        getParentIdBytes() {
      java.lang.Object ref = parentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * builds the operation tree
     * </pre>
     *
     * <code>string parent_id = 2;</code>
     * @param value The parentId to set.
     * @return This builder for chaining.
     */
    public Builder setParentId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parentId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * builds the operation tree
     * </pre>
     *
     * <code>string parent_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentId() {
      parentId_ = getDefaultInstance().getParentId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * builds the operation tree
     * </pre>
     *
     * <code>string parent_id = 2;</code>
     * @param value The bytes for parentId to set.
     * @return This builder for chaining.
     */
    public Builder setParentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parentId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object displayName_ = "";
    /**
     * <code>string display_name = 3;</code>
     * @return The displayName.
     */
    public java.lang.String getDisplayName() {
      java.lang.Object ref = displayName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string display_name = 3;</code>
     * @return The bytes for displayName.
     */
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      java.lang.Object ref = displayName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string display_name = 3;</code>
     * @param value The displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      displayName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string display_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayName() {
      displayName_ = getDefaultInstance().getDisplayName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string display_name = 3;</code>
     * @param value The bytes for displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      displayName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.gradle.tooling.grpc.OperationType type = 4;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.gradle.tooling.grpc.OperationType type = 4;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.gradle.tooling.grpc.OperationType type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public org.gradle.tooling.internal.grpc.proto.OperationType getType() {
      org.gradle.tooling.internal.grpc.proto.OperationType result = org.gradle.tooling.internal.grpc.proto.OperationType.forNumber(type_);
      return result == null ? org.gradle.tooling.internal.grpc.proto.OperationType.UNRECOGNIZED : result;
    }
    /**
     * <code>.gradle.tooling.grpc.OperationType type = 4;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(org.gradle.tooling.internal.grpc.proto.OperationType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.gradle.tooling.grpc.OperationType type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.gradle.tooling.internal.grpc.proto.TaskOperationDetails, org.gradle.tooling.internal.grpc.proto.TaskOperationDetails.Builder, org.gradle.tooling.internal.grpc.proto.TaskOperationDetailsOrBuilder> taskBuilder_;
    /**
     * <code>.gradle.tooling.grpc.TaskOperationDetails task = 10;</code>
     * @return Whether the task field is set.
     */
    @java.lang.Override
    public boolean hasTask() {
      return detailsCase_ == 10;
    }
    /**
     * <code>.gradle.tooling.grpc.TaskOperationDetails task = 10;</code>
     * @return The task.
     */
    @java.lang.Override
    public org.gradle.tooling.internal.grpc.proto.TaskOperationDetails getTask() {
      if (taskBuilder_ == null) {
        if (detailsCase_ == 10) {
          return (org.gradle.tooling.internal.grpc.proto.TaskOperationDetails) details_;
        }
        return org.gradle.tooling.internal.grpc.proto.TaskOperationDetails.getDefaultInstance();
      } else {
        if (detailsCase_ == 10) {
          return taskBuilder_.getMessage();
        }
        return org.gradle.tooling.internal.grpc.proto.TaskOperationDetails.getDefaultInstance();
      }
    }
    /**
     * <code>.gradle.tooling.grpc.TaskOperationDetails task = 10;</code>
     */
    public Builder setTask(org.gradle.tooling.internal.grpc.proto.TaskOperationDetails value) {
      if (taskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        details_ = value;
        onChanged();
      } else {
        taskBuilder_.setMessage(value);
      }
      detailsCase_ = 10;
      return this;
    }
    /**
     * <code>.gradle.tooling.grpc.TaskOperationDetails task = 10;</code>
     */
    public Builder setTask(
        org.gradle.tooling.internal.grpc.proto.TaskOperationDetails.Builder builderForValue) {
      if (taskBuilder_ == null) {
        details_ = builderForValue.build();
        onChanged();
      } else {
        taskBuilder_.setMessage(builderForValue.build());
      }
      detailsCase_ = 10;
      return this;
    }
    /**
     * <code>.gradle.tooling.grpc.TaskOperationDetails task = 10;</code>
     */
    public Builder mergeTask(org.gradle.tooling.internal.grpc.proto.TaskOperationDetails value) {
      if (taskBuilder_ == null) {
        if (detailsCase_ == 10 &&
            details_ != org.gradle.tooling.internal.grpc.proto.TaskOperationDetails.getDefaultInstance()) {
          details_ = org.gradle.tooling.internal.grpc.proto.TaskOperationDetails.newBuilder((org.gradle.tooling.internal.grpc.proto.TaskOperationDetails) details_)
              .mergeFrom(value).buildPartial();
        } else {
          details_ = value;
        }
        onChanged();
      } else {
        if (detailsCase_ == 10) {
          taskBuilder_.mergeFrom(value);
        } else {
          taskBuilder_.setMessage(value);
        }
      }
      detailsCase_ = 10;
      return this;
    }
    /**
     * <code>.gradle.tooling.grpc.TaskOperationDetails task = 10;</code>
     */
    public Builder clearTask() {
      if (taskBuilder_ == null) {
        if (detailsCase_ == 10) {
          detailsCase_ = 0;
          details_ = null;
          onChanged();
        }
      } else {
        if (detailsCase_ == 10) {
          detailsCase_ = 0;
          details_ = null;
        }
        taskBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gradle.tooling.grpc.TaskOperationDetails task = 10;</code>
     */
    public org.gradle.tooling.internal.grpc.proto.TaskOperationDetails.Builder getTaskBuilder() {
      return getTaskFieldBuilder().getBuilder();
    }
    /**
     * <code>.gradle.tooling.grpc.TaskOperationDetails task = 10;</code>
     */
    @java.lang.Override
    public org.gradle.tooling.internal.grpc.proto.TaskOperationDetailsOrBuilder getTaskOrBuilder() {
      if ((detailsCase_ == 10) && (taskBuilder_ != null)) {
        return taskBuilder_.getMessageOrBuilder();
      } else {
        if (detailsCase_ == 10) {
          return (org.gradle.tooling.internal.grpc.proto.TaskOperationDetails) details_;
        }
        return org.gradle.tooling.internal.grpc.proto.TaskOperationDetails.getDefaultInstance();
      }
    }
    /**
     * <code>.gradle.tooling.grpc.TaskOperationDetails task = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.gradle.tooling.internal.grpc.proto.TaskOperationDetails, org.gradle.tooling.internal.grpc.proto.TaskOperationDetails.Builder, org.gradle.tooling.internal.grpc.proto.TaskOperationDetailsOrBuilder> 
        getTaskFieldBuilder() {
      if (taskBuilder_ == null) {
        if (!(detailsCase_ == 10)) {
          details_ = org.gradle.tooling.internal.grpc.proto.TaskOperationDetails.getDefaultInstance();
        }
        taskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.gradle.tooling.internal.grpc.proto.TaskOperationDetails, org.gradle.tooling.internal.grpc.proto.TaskOperationDetails.Builder, org.gradle.tooling.internal.grpc.proto.TaskOperationDetailsOrBuilder>(
                (org.gradle.tooling.internal.grpc.proto.TaskOperationDetails) details_,
                getParentForChildren(),
                isClean());
        details_ = null;
      }
      detailsCase_ = 10;
      onChanged();
      return taskBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gradle.tooling.grpc.OperationDescriptor)
  }

  // @@protoc_insertion_point(class_scope:gradle.tooling.grpc.OperationDescriptor)
  private static final org.gradle.tooling.internal.grpc.proto.OperationDescriptor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.gradle.tooling.internal.grpc.proto.OperationDescriptor();
  }

  public static org.gradle.tooling.internal.grpc.proto.OperationDescriptor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OperationDescriptor>
      PARSER = new com.google.protobuf.AbstractParser<OperationDescriptor>() {
    @java.lang.Override
    public OperationDescriptor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OperationDescriptor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OperationDescriptor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.gradle.tooling.internal.grpc.proto.OperationDescriptor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

