// Copyright 2023 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[about_manual]]
= The User Manual

Explore our guides and examples to use Gradle.

[[releases]]
== Releases

Information on Gradle releases and how to install Gradle is found in the <<installation.adoc#installation,Releases section>>.

[[content]]
== Content

The Gradle User Manual is broken down into the following sections:

<<command_line_interface.adoc#command_line_interface,Running Gradle Builds>> :: Learn Gradle basics and how to use Gradle to build your project.
<<build_lifecycle.adoc#build_lifecycle,Authoring Gradle Builds>> :: Develop tasks and plugins to customize your build.
<<building_java_projects.adoc#building_java_projects,Authoring JVM Builds>> :: Use Gradle with your Java project.
<<dependency_management_terminology.adoc#dependency_management_terminology,Working with Dependencies>> :: Add dependencies to your build.
<<performance.adoc#performance_gradle,Optimizing Builds>> :: Use caches to optimize your build and understand the Gradle daemon, incremental builds and file system watching.
<<jenkins.adoc#build_jenkins,Gradle on CI>> :: Gradle integration with popular continuous integration (CI) servers.

[[reference]]
== Reference

. Gradle's API link:{javadocPath}/index.html[Javadocs^]
. Gradle's link:{groovyDslPath}/index.html[Groovy DSL^]
. Gradle's link:{kotlinDslPath}/index.html[Kotlin DSL^]
. Gradle's <<plugin_reference#plugin_reference,Core Plugins>>
