/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id("gradlebuild.distribution.implementation-java")
    id("gradlebuild.xdcl-ecosystem-library")
}

description = "Built-in XDCL JVM ecosystem: schema + generated facades, published for plugin authors and shipped in the distribution (prototype)"

// The consumable ecosystem library: its `.xdsl` schema (packed under META-INF/xdcl/ by
// xdcl-gradle-plugin) and the Java facades generated from it. A downstream XDCL plugin depends on
// THIS to `import` the schema and reference the facades; the plugin that activates the ecosystem
// (applied by id) lives in the sibling :xdcl-jvm-ecosystem-plugin. Publishable because it carries
// no internal-Gradle dependency — only the external org.xdcl facade API.
dependencies {
    // The shared schema java.xdsl `import`s (org.gradle.xdcl.ecosystem.common.dsl): the dependency
    // scopes and the HasDependencies capability trait the JavaLibrary template composes. `api` so
    // consumers importing the JVM schema also see the common facades, and so xdclCodegen resolves
    // the import from this dependency's packed schema (importedSchemaDirectories).
    api(projects.xdclCommonEcosystem)
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
    }
}
