/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id("gradlebuild.distribution.implementation-java")
    id("gradlebuild.xdcl-builtin-ecosystem")
}

description = "The built-in XDCL plugin-development ecosystem plugin (plugin-development-ecosystem): a carrier generated from plugin-development-ecosystem.xdcl that binds XdclGradlePluginReaction. Unlike the java ecosystem it registers no model of its own — the reaction applies the REAL plugin-development machinery (java-library, java-gradle-plugin, and the bundled xdcl codegen plugin) by id. Shipped in the distribution and applied by id; the schema + facades it consumes live in the published :xdcl-plugin-development library."

dependencies {
    api(projects.coreApi)
    api(projects.xdclPluginDevelopment)

    implementation(projects.xdclCommonEcosystem)

    // Shared imperative helpers (Repositories) for the common HasRepositories capability trait.
    // DependencyScopes is NOT used here: the reaction applies the real java-library plugin, which
    // owns the api/implementation/... configurations, so declared dependencies are added to those
    // real configurations directly instead of creating ecosystem dependency scopes.
    implementation(projects.xdclEcosystemSupport)
}

gradleModule {
    requiredRuntimes {
        daemon = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
    }
}
