#!/bin/bash
# Copyright 2024 The Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -euo pipefail

BOOTSTRAP_CLI_VERSION="0.10.0"
GRADLE_USER_HOME="/mnt/tcagent1/.gradle"
CACHE_METRICS_FILE="artifact-cache-metrics/store.json"
REPORTING_DIR="artifact-cache-report/store"

function downloadDvBootstrapCliTool() {
  local start_time=$(date +%s)000

  echo "Starting to download develocity-artifact-cache-cli ${BOOTSTRAP_CLI_VERSION}..."

  set -x
  curl -fsSL -u "$GBT_REPO_GRDEV_NET_READONLY_USERNAME:$GBT_REPO_GRDEV_NET_READONLY_PASSWORD" \
    "https://repo.grdev.net:443/artifactory/develocity-artifact-cache-cli-libs-releases/com/gradle/develocity-artifact-cache-cli/${BOOTSTRAP_CLI_VERSION}/develocity-artifact-cache-cli-${BOOTSTRAP_CLI_VERSION}.jar" \
    -o ${TMPDIR}/develocity-artifact-cache-cli.jar

  DOWNLOAD_EXIT_CODE=$?
  set +x

  local end_time=$(date +%s)000
  local duration=$((end_time - start_time))
  echo "Downloading develocity-artifact-cache-cli ${BOOTSTRAP_CLI_VERSION} finished in ${duration} ms with exit code ${DOWNLOAD_EXIT_CODE}."

  if [ "${DOWNLOAD_EXIT_CODE}" -eq 0 ]; then
    ls -hal "${TMPDIR}"
  fi
}

function storeArtifactCache() {
  local start_time=$(date +%s)000

  echo "Starting to store artifact cache..."

  set -x
  "/opt/jdk/open-jdk-21/bin/java" -jar "${TMPDIR}/develocity-artifact-cache-cli.jar" \
    store \
    --http1-preferred \
    --dv-server=https://ge.gradle.org \
    --reporting-directory=${REPORTING_DIR} \
    --operation-timeout=PT10M \
    --gradle-home=${GRADLE_USER_HOME} \
    --cache-metrics-file="${CACHE_METRICS_FILE}" \
    --verbose

  local restoreExitCode=$?
  set +x

  local end_time=$(date +%s)000
  local duration=$((end_time - start_time))
  echo "Storing bootstrap image finished in ${duration} ms with exit code ${restoreExitCode}."
}

export DEVELOCITY_ARTIFACT_CACHE_BASE_BRANCH_NAME="master"

downloadDvBootstrapCliTool
storeArtifactCache