NOTE: You can open the samples inside an IDE using the https://www.jetbrains.com/help/idea/gradle.html#gradle_import_project_start[IntelliJ native importer] or https://projects.eclipse.org/projects/tools.buildship[Eclipse Buildship].

This sample shows how to add additional test types to JVM projects in Gradle.
Test types are also known as unit test, integration test, functional test, etc.
In this sample, we are testing Java projects with JUnit 4, however, adding additional test types is consistent across JVM languages.

Applications can be configured as follow:

====
include::sample[dir="samples/jvm-components-with-additional-test-types/groovy",files="application/build.gradle[]"]
include::sample[dir="samples/jvm-components-with-additional-test-types/kotlin",files="application/build.gradle.kts[]"]
====

Libraries can be configured as follow:

====
include::sample[dir="samples/jvm-components-with-additional-test-types/groovy",files="list/build.gradle[]"]
include::sample[dir="samples/jvm-components-with-additional-test-types/kotlin",files="list/build.gradle.kts[]"]
====

The additional tests for the projects can be executed via the `integrationTest` task or as part of lifecycle `check` task as demonstrated:

====
[.testable-sample,dir="groovy"]
=====
[.sample-command]
----
$ ./gradlew check

BUILD SUCCESSFUL in 2s
11 actionable tasks: 11 executed
----
=====
====

For more information, see link:{userManualPath}/java_testing.html#sec:configuring_java_integration_tests[section Configuring integration tests in the Testing in Java project chapter].
