// Copyright 2020 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[toolchains]]
= Toolchains for JVM projects

Choosing the right Java version and Java Virtual machine for a project is an essential choice.
This chapter is dedicated to explaining how to instruct Gradle which JVM/JDK to use for a particular build, how to set up your environment to make use of it and what other features can help you and your team to work using the same setup.

A Java Toolchain (from now on referred to simply as toolchain) is a set of tools, usually taken from a local JRE/JDK installation that are used to configure different aspects of a build.
Compile tasks may use `javac` as their compiler, test and exec tasks may use the `java` command while `javadoc` will be used to generate documentation.

== Consuming Toolchains

A build can globally define what toolchain it targets by stating the Java Language version it needs:

====
include::sample[dir="samples/java/jvm-multi-project-with-toolchains/groovy/",files="buildSrc/src/main/groovy/myproject.java-conventions.gradle[tags=toolchain]"]
include::sample[dir="samples/java/jvm-multi-project-with-toolchains/kotlin/",files="buildSrc/src/main/kotlin/myproject.java-conventions.gradle.kts[tags=toolchain]"]
====

Executing the build (e.g. using `gradle check`) will now handle several things for you and others running your build


1. Setup all compile and test tasks with the corresponding Java installation
2. Gradle detects <<sec:auto_detection,locally installed JVMs>>
3. Gradle chooses a JRE/JDK matching the requirements of the build (in this case a JVM supporting Java 14)
4. If no matching JVM is found, it will automatically download a matching JDK from https://adoptopenjdk.net/[AdoptOpenJDK]

By default, defining a toolchain automatically applies matching defaults for `sourceCompatibility`/`targetCompatibility`
and the usage of the `-release` flag.
You may still want to override those values if you need more control over the exact compatibility level.

=== Specify custom toolchains for individual tasks

In case you want to tweak which toolchain is used for a specific task, you can specify the exact tool a task is using.
For example, a `Test` task exposes a `JavaLauncher` property that defines which java executable to use to launch the tests.

In the example below, we configure the default toolchain to use JDK8 for compiling and testing.
Additionally, we introduce a new Test task that is going to run our unit tests but using a JRE or JDK 14 (whatever is available).
Depending on the task, a JRE might be enough while for other tasks (e.g. compilation), a JDK is required.
By default, Gradle prefers installed JDKs over JREs.

====
include::sample[dir="samples/java/jvm-multi-project-with-toolchains/groovy/",files="list/build.gradle[tags=customToolchain]"]
include::sample[dir="samples/java/jvm-multi-project-with-toolchains/kotlin",files="list/build.gradle.kts[tags=customToolchain]"]
====

Toolchains tool providers can be obtained from the `javaToolchains` extension.
(TODO: link) Three tools are available:

* A `JavaCompiler` which is the tool used by the `JavaCompile` task
* A `JavaLauncher` which is the tool used by the `JavaExec` or `Test` tasks
* A `JavadocTool` which is the tool used by the `Javadoc` task

For plugin authors, custom tasks that require a tool should expose a `Property<>` with the desired tool as generic type.
By injecting the `JavaToolchainService` in the plugin, it is also possible to wire a convention in those properties by obtaining the `JavaToolchainSpec` from the `java` extension on the project.

[[sec:auto_detection]]
=== Auto detection of installed toolchains

By default, Gradle automatically detects local JRE/JDK installations so no further configuration is required by the user.
The following is a list of common package managers and locations that are supported by the JVM auto detection.

Operation-system specific locations:

* Linux
* MacOs
* Windows

Supported Package Managers:

* https://asdf-vm.com/#/[Asdf-vm]
* https://github.com/shyiko/jabba[Jabba]
* https://sdkman.io/[SDKMAN!]

==== How to disable auto-detection

In order to disable auto-detection, you can use the `org.gradle.java.installations.auto-detect` gradle property.
Either start gradle using `-Porg.gradle.java.installations.auto-detect=false` or put
`org.gradle.java.installations.auto-detect=false` into your `gradle.properties` file.

[[sec:provisioning]]
=== Auto Provisioning

If no toolchain is found matching the requirements of the build, Gradle will automatically download a matching JDK from AdoptOpenJDK. By default, it will request a HotSpot JDK matching the current operating system and architecture.
Provisioning JDKs are installed in the <<directory_layout.adoc#dir:gradle_user_home,Gradle User Home directory>>.

By default, the public https://api.adoptopenjdk.net/[AdoptOpenJDK APIs] are used to determine and download a matching JDK.
In case you want to use another server that is compatible with v3 of the AdoptOpenJDK API, you can point Gradle to use a different host.

```
org.gradle.jvm.toolchain.install.adoptopenjdk.baseUri=https://api.company.net/
```

