/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.util.internal;

import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * Extensions to {@link Arbitraries} that are used in Gradle's tests.
 */
@NullMarked
public class MoreArbitraries {
    /**
     * Provides extra edge cases to an existing arbitrary.
     * Primarily used when a specific test requires edge cases that are not generally applicable to all tests
     * using the base arbitrary.
     *
     * @param base the base arbitrary to which the extra edge cases should be added
     * @param extraEdgeCases the extra edge cases to include in the resulting arbitrary
     * @return a new arbitrary that includes the extra edge cases in addition to the values generated by the base arbitrary
     */
    public static <T extends @Nullable Object> Arbitrary<T> includeExtraEdgeCases(
        Arbitrary<T> base, final T... extraEdgeCases
    ) {
        return Arbitraries.oneOf(base, Arbitraries.of(extraEdgeCases))
            .edgeCases(c -> c.add(extraEdgeCases));
    }

    private MoreArbitraries() {
        throw new AssertionError("Utility class");
    }
}
