// Copyright (C) 2025 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[plugin_introduction]]
= Getting Started

Plugin authors that are ready to write their own plugins and publish it should start here.

To get started developing Gradle plugins:

1. Read the <<gradle_author_intro,Deep Dive chapters>>.
2. Follow the <<author_tutorial,Advanced Tutorial>> for a hands-on approach.

[[gradle_plugin_intro]]
== 1. Gradle Deep Dive

The deep dive section goes through developing tasks, understanding services, writing and publishing plugins.

[sidebar]
_Training level_: **Advanced** +
_Reading time_: **35 minutes**

This section covers:

<<gradle_directories.adoc#gradle_directories,Part 1.>> Anatomy of a Gradle Build +
<<into_multi_project_builds.adoc#intro_multi_project_builds,Part 2.>> Structuring Multi-Project Builds +
<<build_lifecycle.adoc#build_lifecycle,Part 3.>> Gradle Build Lifecycle +
<<writing_build_scripts.adoc#writing_build_scripts,Part 4.>> Writing Build Scripts +
<<gradle_managed_types.adoc#gradle_types_intro,Part 5.>> Gradle Managed Types +
<<dependencies.adoc#dependencies_intro,Part 6.>> Managing Dependencies +
<<writing_tasks.adoc#writing_tasks,Part 7.>> Creating and Registering Tasks +
<<plugins.adoc#using_plugins,Part 8.>> Working With Plugins +

[[plugin_tutorial]]
== 2. Intermediate Gradle Tutorial

Coming Soon!
