// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[structure_large_projects]]
= Tasks Sample

This sample shows how to create a plugin with tasks that have dependency resolution results as inputs.

The plugin is packaged via an included build and is demonstrated on a multi-project build for a Java application.

== Download the sample

The software product built in this sample is an application that does X

The application does X
++++
<div class="button-9-sect">
    <a href="../samples/zips/sample_tasks_with_dependency_resolution_result_inputs-groovy-dsl.zip">
        <button class="button-9" role="button"><span class="icon"><i class="fa fa-download"></i></span> Groovy DSL</button>
    </a>
    <a href="../samples/zips/sample_tasks_with_dependency_resolution_result_inputs-kotlin-dsl.zip">
        <button class="button-9" role="button"><span class="icon"><i class="fa fa-download"></i></span> Kotlin DSL</button>
    </a>
</div>
++++

NOTE: You can open this sample inside an IDE.

== The sample explained

====
include::sample[dir="kotlin",files="settings.gradle.kts[tag=includes];list/build.gradle.kts[];utilities/build.gradle.kts[];build.gradle.kts[]"]
include::sample[dir="groovy",files="settings.gradle[tag=includes];list/build.gradle[];utilities/build.gradle[];build.gradle[]"]
====

To execute the sample tasks:

====
[.testable-sample,dir="groovy"]
=====
[.sample-command]
----
> ./gradlew -q listResolvedArtifacts
include::{samplesPath}/writing-tasks/tasks-with-dependency-resolution-result-inputs/tests/listResolvedArtifacts.out[]

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----
=====
=====
[.sample-command]
----
> ./gradlew -q graphResolvedComponents
include::{samplesPath}/writing-tasks/tasks-with-dependency-resolution-result-inputs/tests/graphResolvedComponents.out[]

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----
=====
=====
[.sample-command]
----
> ./gradlew -q graphResolvedComponentsAndFiles
include::{samplesPath}/writing-tasks/tasks-with-dependency-resolution-result-inputs/tests/graphResolvedComponentsAndFiles.out[]

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----
=====
====
