// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[structure_large_projects]]
= Tasks Sample

This sample shows how to create a plugin with tasks that have dependency resolution results as inputs.

The plugin is packaged via an included build and is demonstrated on a multi-project build for a Java application.

== Download the sample

The software product built in this sample is a plugin that lists dependencies used in the build (both internal and external).

++++
<div class="button-9-sect">
    <a href="../samples/zips/sample_tasks_with_dependency_resolution_result_inputs-groovy-dsl.zip">
        <button class="button-9" role="button"><span class="icon"><i class="fa fa-download"></i></span> Groovy DSL</button>
    </a>
    <a href="../samples/zips/sample_tasks_with_dependency_resolution_result_inputs-kotlin-dsl.zip">
        <button class="button-9" role="button"><span class="icon"><i class="fa fa-download"></i></span> Kotlin DSL</button>
    </a>
</div>
++++

NOTE: You can open this sample inside an IDE.

== The sample explained

The sample is a multi-project build with an included build and two subprojects:

1. dependency-report - separate build where the custom tasks and plugin are coded
2. list - subproject that produces a jar file
3. utilities - subproject that produces a jar file

====
include::sample[dir="samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/kotlin",files="settings.gradle.kts"]
include::sample[dir="samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/groovy",files="settings.gradle"]
====

The build creates the plugin in `dependency-report`:

====
include::sample[dir="samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/kotlin",files="build.gradle.kts"]
include::sample[dir="samples/writing-tasks/tasks-with-dependency-resolution-result-inputs/groovy",files="build.gradle"]
====

The `dependency-report` plugin exposes three custom tasks:

1. listResolvedArtifacts in `dependency-reports/src/main/java/com.example/ListResolvedArtifacts.java`
2. graphResolvedComponents in `dependency-reports/src/main/java/com.example/GraphResolvedComponents.java`
3. graphResolvedComponentsAndFiles in `dependency-reports/src/main/java/com.example/GraphResolvedComponentsAndFiles.java`

To execute the sample tasks:

====
[.testable-sample,dir="groovy"]
=====
[.sample-command]
----
> ./gradlew -q listResolvedArtifacts
include::{samplesPath}/writing-tasks/tasks-with-dependency-resolution-result-inputs/tests/listResolvedArtifacts.out[]

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----
=====
=====
[.sample-command]
----
> ./gradlew -q graphResolvedComponents
include::{samplesPath}/writing-tasks/tasks-with-dependency-resolution-result-inputs/tests/graphResolvedComponents.out[]

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----
=====
=====
[.sample-command]
----
> ./gradlew -q graphResolvedComponentsAndFiles
include::{samplesPath}/writing-tasks/tasks-with-dependency-resolution-result-inputs/tests/graphResolvedComponentsAndFiles.out[]

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
----
=====
====
