CREATE SCHEMA IF NOT EXISTS filestore;

CREATE TABLE IF NOT EXISTS filestore.catalog
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_key     VARCHAR(32)         NOT NULL,
    entry_size    BIGINT              NOT NULL,
    entry_content BINARY LARGE OBJECT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_catalog_entry_key ON filestore.catalog (entry_key);
