// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= Execution Engine

The role of the **execution engine** is to take some work with well-defined inputs and outputs, and using the inputs manifest the outputs as efficiently as possible.

The engine is implemented as a network of steps.
During execution the engine passes a _context_ object along that accumulates information about the work as it gets passed deeper in the hierarchy of steps.
When the outputs have been manifested, a _result_ object gets passed back along the same path, accumulating metadata about the manifested outputs along the way.

== Semantic structure of pipeline

[mermaid]
....
flowchart TD
  Identify[Identify work]
  IdentityCache{{In identity cache?}}
  ChoosePipeline{{Work type?}}

  Identify -->|identity| IdentityCache
  IdentityCache -->|hit| Done
  IdentityCache -->|miss| ChoosePipeline
  Done[Done]

  ChoosePipeline -->|"non-incremental work\n(excluding tasks)"| ImmutablePipeline
  subgraph ImmutablePipeline[Immutable pipeline]
    LoadImmutableHistory["Load history\n(check if workspace exists)"]

    LoadImmutableHistory -->|hit| CheckImmutableWorkspace[Check workspace]
    LoadImmutableHistory -->|miss| AllocateTemporaryWorkspace[Allocate temporary workspace]
    AllocateTemporaryWorkspace --> CheckIfImmutableEmpty{{Empty sources?}}
    CheckIfImmutableEmpty -->|no| ExecuteNonIncrementalWork["Execute work\n(or load from cache)"]
    ExecuteNonIncrementalWork -->|success| StoreImmutableHistory
    CheckIfImmutableEmpty -->|yes| StoreImmutableHistory
    StoreImmutableHistory["Store history"] --> MoveWorkspaceToImmutableArea[Move workspace\nto immutable area]
  end
  CheckImmutableWorkspace --> Done
  ExecuteNonIncrementalWork -->|failure| Done
  MoveWorkspaceToImmutableArea --> Done

  ChoosePipeline --->|"tasks and incremental work"| MutablePipeline
  subgraph MutablePipeline["Mutable pipeline"]
    AllocateMutableWorkspace[Allocate mutable workspace\nunder lock]

    AllocateMutableWorkspace --> LoadMutableHistory[Load history]
    LoadMutableHistory --> CleanStaleOutputs[Clean stale outputs]
    CleanStaleOutputs --> SkipIfSourcesEmpty{{Empty sources?}}
    SkipIfSourcesEmpty -->|no| SkipUpToDate{{Is up-to-date?}}
    SkipIfSourcesEmpty -->|yes| DeletePreviousOutputs[Delete previous outputs]
    SkipUpToDate -->|no| ExecuteIncrementalWork["Execute work\n(or load from cache)"]
    DeletePreviousOutputs ----> StoreMutableHistory[Store history]
    ExecuteIncrementalWork --> RecordOutputs["Record outputs\n(for stale output cleanup later)"]
    RecordOutputs --> StoreMutableHistory
  end
  StoreMutableHistory --> Done
  SkipUpToDate -->|yes| Done
....
