// Copyright (C) 2023 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

== Steps

[mermaid]
....
flowchart BT
    subgraph Ingress[Ingress]
        ExecutionEngine

        ExecutionEngine -->|ExecutionRequestContext| IdentityStep
        IdentityStep -->|Result| ExecutionEngine

        IdentityStep
        IdentityCacheStep
        ChoosePipelineStep

        IdentityStep -->|IdentityContext| IdentityCacheStep
        IdentityCacheStep -->|Result| IdentityStep

        IdentityCacheStep -->|IdentityContext| ChoosePipelineStep
        ChoosePipelineStep -->|Result| IdentityCacheStep

        ChoosePipelineStep -->|IdentityContext| AssignWorkspaceStep
        AssignWorkspaceStep -->|Result| ChoosePipelineStep

    end

    subgraph MutablePipeline[Mutable pipeline]
        AssignWorkspaceStep
        HandleStaleOutputsStep
        LoadPreviousExecutionStateStep
        SkipEmptyIncrementalWorkStep
        CaptureStateBeforeExecutionStep
        ValidateStep
        ResolveCachingStateStep
        ResolveChangesStep
        SkipUpToDateStep
        StoreExecutionStateStep
        BuildCacheStep
        ResolveInputChangesStep
        CaptureStateAfterExecutionStep
        BroadcastChangingOutputsStep
        RemovePreviousOutputsStep

        AssignWorkspaceStep ==>|WorkspaceContext| HandleStaleOutputsStep
        HandleStaleOutputsStep -->|AfterExecutionResult| AssignWorkspaceStep

        HandleStaleOutputsStep -->|WorkspaceContext| LoadPreviousExecutionStateStep
        LoadPreviousExecutionStateStep -->|AfterExecutionResult| HandleStaleOutputsStep

        LoadPreviousExecutionStateStep ==>|PreviousExecutionContext| SkipEmptyIncrementalWorkStep
        SkipEmptyIncrementalWorkStep -->|AfterExecutionResult| LoadPreviousExecutionStateStep

        SkipEmptyIncrementalWorkStep -->|PreviousExecutionContext| CaptureStateBeforeExecutionStep
        CaptureStateBeforeExecutionStep -->|CachingResult| SkipEmptyIncrementalWorkStep

        CaptureStateBeforeExecutionStep ==>|BeforeExecutionState| ValidateStep
        ValidateStep -->|CachingResult| CaptureStateBeforeExecutionStep

        ValidateStep ==>|ValidationFinishedContext| ResolveCachingStateStep
        ResolveCachingStateStep ==>|CachingResult| ValidateStep

        ResolveCachingStateStep ==>|CachingContext| ResolveChangesStep
        ResolveChangesStep -.->|Result| ResolveCachingStateStep

        ResolveChangesStep ==>|IncrementalChangesContext| SkipUpToDateStep
        SkipUpToDateStep ==>|UpToDateResult| ResolveChangesStep

        SkipUpToDateStep -->|IncrementalChangesContext| StoreExecutionStateStep
        StoreExecutionStateStep -->|AfterExecutionResult| SkipUpToDateStep

        StoreExecutionStateStep -->|PreviousExecutionContext| BuildCacheStep
        BuildCacheStep -->|AfterExecutionResult| StoreExecutionStateStep

        BuildCacheStep -->|IncrementalChangesContext| ResolveInputChangesStep
        ResolveInputChangesStep -->|Result| BuildCacheStep

        ResolveInputChangesStep ==>|InputChangesContext| CaptureStateAfterExecutionStep
        CaptureStateAfterExecutionStep ==>|AfterExecutionResult| ResolveInputChangesStep

        CaptureStateAfterExecutionStep -->|BeforeExecutionState| BroadcastChangingOutputsStep
        BroadcastChangingOutputsStep -->|Result| CaptureStateAfterExecutionStep

        BroadcastChangingOutputsStep ==>|ChangingOutputsContext| RemovePreviousOutputsStep
        RemovePreviousOutputsStep -->|Result| BroadcastChangingOutputsStep

        RemovePreviousOutputsStep -->|ChangingOutputsContext| PreCreateOutputParentsStep
        PreCreateOutputParentsStep -->|Result| RemovePreviousOutputsStep
    end

    PreCreateOutputParentsStep -->|ChangingOutputsContext| TimeoutStep
    TimeoutStep -->|Result| PreCreateOutputParentsStep

    subgraph SharedPipeline[Shared pipeline]
        PreCreateOutputParentsStep
        TimeoutStep
        CancelExecutionStep
        ExecuteStep

        TimeoutStep -->|ChangingOutputsContext| CancelExecutionStep
        CancelExecutionStep -->|Result| TimeoutStep

        CancelExecutionStep -->|ChangingOutputsContext| ExecuteStep
        ExecuteStep -->|Result| CancelExecutionStep
    end

....
