// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ide_model.proto

package com.example.ide.proto;

public final class IdeModelProto {
  private IdeModelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_ide_IdeProjectModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_ide_IdeProjectModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ide_model.proto\022\017com.example.ide\"d\n\017Id" +
      "eProjectModel\022\024\n\014project_path\030\001 \001(\t\022\024\n\014p" +
      "roject_name\030\002 \001(\t\022\021\n\tbuild_dir\030\003 \001(\t\022\022\n\n" +
      "plugin_ids\030\004 \003(\tB(\n\025com.example.ide.prot" +
      "oB\rIdeModelProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_ide_IdeProjectModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_ide_IdeProjectModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_ide_IdeProjectModel_descriptor,
        new java.lang.String[] { "ProjectPath", "ProjectName", "BuildDir", "PluginIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
