plugins {
    id("gradlebuild.distribution.api-java")
}

description = "Process execution abstractions."

dependencies {
    api(projects.concurrent)
    api(projects.baseServices)
    api(projects.buildOperations)
    api(projects.coreApi)

    api(libs.inject)
    api(libs.jspecify)
    api(libs.nativePlatform)

    implementation(projects.loggingApi)
    implementation(projects.messaging)
    implementation(projects.native)
    implementation(projects.serviceLookup)

    implementation(libs.commonsIo)
    implementation(libs.guava)
    implementation(libs.jnrConstants)
    implementation(libs.slf4jApi)

    runtimeOnly(projects.logging)

    testImplementation(testFixtures(projects.core))

    integTestDistributionRuntimeOnly(projects.distributionsCore)
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

packageCycles {
    excludePatterns.add("org/gradle/process/internal/**")
}
