// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tooling.proto

package org.gradle.tooling.grpc.proto;

public interface OutputLineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gradle.tooling.grpc.OutputLine)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>.gradle.tooling.grpc.LogLevel level = 2;</code>
   * @return The enum numeric value on the wire for level.
   */
  int getLevelValue();
  /**
   * <code>.gradle.tooling.grpc.LogLevel level = 2;</code>
   * @return The level.
   */
  org.gradle.tooling.grpc.proto.LogLevel getLevel();
}
