// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tooling.proto

package org.gradle.tooling.grpc.proto;

public final class ToolingProto {
  private ToolingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_BuildRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_BuildRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_BuildEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_BuildEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_ProgressEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_ProgressEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_OutputLine_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_OutputLine_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_StyledOutput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_StyledOutput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_Span_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_Span_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_BuildResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_BuildResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_ModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_ModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_ModelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_ModelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_BuildEnvironment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_BuildEnvironment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_TaskList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_TaskList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gradle_tooling_grpc_TaskInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gradle_tooling_grpc_TaskInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rtooling.proto\022\023gradle.tooling.grpc\"1\n\014" +
      "BuildRequest\022\014\n\004args\030\001 \003(\t\022\023\n\013project_di" +
      "r\030\002 \001(\t\"\350\001\n\nBuildEvent\0221\n\006output\030\001 \001(\0132\037" +
      ".gradle.tooling.grpc.OutputLineH\000\0222\n\006res" +
      "ult\030\002 \001(\0132 .gradle.tooling.grpc.BuildRes" +
      "ultH\000\0223\n\006styled\030\003 \001(\0132!.gradle.tooling.g" +
      "rpc.StyledOutputH\000\0226\n\010progress\030\004 \001(\0132\".g" +
      "radle.tooling.grpc.ProgressEventH\000B\006\n\004ki" +
      "nd\"e\n\rProgressEvent\022/\n\004type\030\001 \001(\0162!.grad" +
      "le.tooling.grpc.ProgressType\022\023\n\013descript" +
      "ion\030\002 \001(\t\022\016\n\006status\030\003 \001(\t\"H\n\nOutputLine\022" +
      "\014\n\004text\030\001 \001(\t\022,\n\005level\030\002 \001(\0162\035.gradle.to" +
      "oling.grpc.LogLevel\"f\n\014StyledOutput\022(\n\005s" +
      "pans\030\001 \003(\0132\031.gradle.tooling.grpc.Span\022,\n" +
      "\005level\030\002 \001(\0162\035.gradle.tooling.grpc.LogLe" +
      "vel\"?\n\004Span\022\014\n\004text\030\001 \001(\t\022)\n\005style\030\002 \001(\016" +
      "2\032.gradle.tooling.grpc.Style\"/\n\013BuildRes" +
      "ult\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"Q\n" +
      "\014ModelRequest\022\023\n\013project_dir\030\001 \001(\t\022,\n\004ty" +
      "pe\030\002 \001(\0162\036.gradle.tooling.grpc.ModelType" +
      "\"\254\001\n\rModelResponse\022\017\n\007success\030\001 \001(\010\022\r\n\005e" +
      "rror\030\002 \001(\t\022B\n\021build_environment\030\003 \001(\0132%." +
      "gradle.tooling.grpc.BuildEnvironmentH\000\022." +
      "\n\005tasks\030\004 \001(\0132\035.gradle.tooling.grpc.Task" +
      "ListH\000B\007\n\005model\"S\n\020BuildEnvironment\022\026\n\016g" +
      "radle_version\030\001 \001(\t\022\021\n\tjava_home\030\002 \001(\t\022\024" +
      "\n\014java_version\030\003 \001(\005\"N\n\010TaskList\022\024\n\014proj" +
      "ect_path\030\001 \001(\t\022,\n\005tasks\030\002 \003(\0132\035.gradle.t" +
      "ooling.grpc.TaskInfo\"J\n\010TaskInfo\022\014\n\004name" +
      "\030\001 \001(\t\022\014\n\004path\030\002 \001(\t\022\r\n\005group\030\003 \001(\t\022\023\n\013d" +
      "escription\030\004 \001(\t*N\n\014ProgressType\022\022\n\016PROG" +
      "RESS_START\020\000\022\023\n\017PROGRESS_STATUS\020\001\022\025\n\021PRO" +
      "GRESS_COMPLETE\020\002*i\n\010LogLevel\022\031\n\025LOG_LEVE" +
      "L_UNSPECIFIED\020\000\022\t\n\005QUIET\020\001\022\010\n\004WARN\020\002\022\r\n\t" +
      "LIFECYCLE\020\003\022\010\n\004INFO\020\004\022\t\n\005DEBUG\020\005\022\t\n\005ERRO" +
      "R\020\006*\204\002\n\005Style\022\020\n\014STYLE_NORMAL\020\000\022\020\n\014STYLE" +
      "_HEADER\020\001\022\024\n\020STYLE_USER_INPUT\020\002\022\024\n\020STYLE" +
      "_IDENTIFIER\020\003\022\025\n\021STYLE_DESCRIPTION\020\004\022\031\n\025" +
      "STYLE_PROGRESS_STATUS\020\005\022\021\n\rSTYLE_SUCCESS" +
      "\020\006\022\030\n\024STYLE_SUCCESS_HEADER\020\007\022\021\n\rSTYLE_FA" +
      "ILURE\020\010\022\030\n\024STYLE_FAILURE_HEADER\020\t\022\016\n\nSTY" +
      "LE_INFO\020\n\022\017\n\013STYLE_ERROR\020\013*9\n\tModelType\022" +
      "\033\n\027MODEL_BUILD_ENVIRONMENT\020\000\022\017\n\013MODEL_TA" +
      "SKS\020\0012\260\001\n\007Tooling\022P\n\010RunBuild\022!.gradle.t" +
      "ooling.grpc.BuildRequest\032\037.gradle.toolin" +
      "g.grpc.BuildEvent0\001\022S\n\nQueryModel\022!.grad" +
      "le.tooling.grpc.ModelRequest\032\".gradle.to" +
      "oling.grpc.ModelResponseB/\n\035org.gradle.t" +
      "ooling.grpc.protoB\014ToolingProtoP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gradle_tooling_grpc_BuildRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gradle_tooling_grpc_BuildRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_BuildRequest_descriptor,
        new java.lang.String[] { "Args", "ProjectDir", });
    internal_static_gradle_tooling_grpc_BuildEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gradle_tooling_grpc_BuildEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_BuildEvent_descriptor,
        new java.lang.String[] { "Output", "Result", "Styled", "Progress", "Kind", });
    internal_static_gradle_tooling_grpc_ProgressEvent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gradle_tooling_grpc_ProgressEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_ProgressEvent_descriptor,
        new java.lang.String[] { "Type", "Description", "Status", });
    internal_static_gradle_tooling_grpc_OutputLine_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gradle_tooling_grpc_OutputLine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_OutputLine_descriptor,
        new java.lang.String[] { "Text", "Level", });
    internal_static_gradle_tooling_grpc_StyledOutput_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_gradle_tooling_grpc_StyledOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_StyledOutput_descriptor,
        new java.lang.String[] { "Spans", "Level", });
    internal_static_gradle_tooling_grpc_Span_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_gradle_tooling_grpc_Span_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_Span_descriptor,
        new java.lang.String[] { "Text", "Style", });
    internal_static_gradle_tooling_grpc_BuildResult_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_gradle_tooling_grpc_BuildResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_BuildResult_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_gradle_tooling_grpc_ModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_gradle_tooling_grpc_ModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_ModelRequest_descriptor,
        new java.lang.String[] { "ProjectDir", "Type", });
    internal_static_gradle_tooling_grpc_ModelResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_gradle_tooling_grpc_ModelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_ModelResponse_descriptor,
        new java.lang.String[] { "Success", "Error", "BuildEnvironment", "Tasks", "Model", });
    internal_static_gradle_tooling_grpc_BuildEnvironment_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_gradle_tooling_grpc_BuildEnvironment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_BuildEnvironment_descriptor,
        new java.lang.String[] { "GradleVersion", "JavaHome", "JavaVersion", });
    internal_static_gradle_tooling_grpc_TaskList_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_gradle_tooling_grpc_TaskList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_TaskList_descriptor,
        new java.lang.String[] { "ProjectPath", "Tasks", });
    internal_static_gradle_tooling_grpc_TaskInfo_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_gradle_tooling_grpc_TaskInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gradle_tooling_grpc_TaskInfo_descriptor,
        new java.lang.String[] { "Name", "Path", "Group", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
