// Copyright (C) 2024 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[eclipse_plugin]]
= The Eclipse Plugins

The Eclipse plugins allow customizing how the http://eclipse.org[Eclipse IDE] understands your project. When Eclipse imports a Gradle build via https://projects.eclipse.org/projects/tools.buildship[Buildship], it takes the `eclipse { ... }` configuration into account.

The `eclipse-wtp` is automatically applied whenever the `eclipse` plugin is applied to a <<war_plugin.adoc#war_plugin,War>> or <<ear_plugin.adoc#ear_plugin,Ear>> project. For utility projects (i.e. <<java_plugin.adoc#java_plugin,Java>> projects used by other web projects), you need to apply the `eclipse-wtp` plugin explicitly.

What exactly the `eclipse` plugin configures depends on which other plugins are used:

.Eclipse plugin behavior
[%header%autowidth,compact]
|===
| Plugin | Description

| None
| Configures minimal project information.

| <<java_plugin.adoc#java_plugin,Java>>
| Adds Java configuration: the classpath and JDT settings.

| <<groovy_plugin.adoc#groovy_plugin,Groovy>>
| Adds Groovy configuration.

| <<scala_plugin.adoc#scala_plugin,Scala>>
| Adds Scala support.

| <<war_plugin.adoc#war_plugin,War>>
| Adds web application support.

| <<ear_plugin.adoc#ear_plugin,Ear>>
| Adds ear application support.
|===

The `eclipse-wtp` plugin configures the WTP component model. If a <<java_plugin.adoc#java_plugin,Java>> or <<war_plugin.adoc#war_plugin,War>> is applied, the classpath will be extended to get a proper packaging structure for this utility library or web application project.

Both Eclipse plugins are open to customization.


[[sec:eclipse_usage]]
== Usage

To use either the Eclipse or the Eclipse WTP plugin, include one of the lines in your build script.

Using the Eclipse plugin:

====
include::sample[dir="snippets/reference/core-plugins/eclipse/kotlin",files="build.gradle.kts[tags=use-eclipse-plugin]"]
include::sample[dir="snippets/reference/core-plugins/eclipse/groovy",files="build.gradle[tags=use-eclipse-plugin]"]
====

Using the Eclipse WTP plugin:

====
include::sample[dir="snippets/reference/core-plugins/eclipse/kotlin",files="build.gradle.kts[tags=use-eclipse-wtp-plugin]"]
include::sample[dir="snippets/reference/core-plugins/eclipse/groovy",files="build.gradle[tags=use-eclipse-wtp-plugin]"]
====

_Note:_ Internally, the `eclipse-wtp` plugin also applies the `eclipse` plugin so you don't need to apply both.

NOTE: The IDE file generation tasks that these plugins used to contribute (`eclipse`, `eclipseProject`, `eclipseClasspath`, `eclipseJdt`, `eclipseWtp`, `eclipseWtpComponent`, `eclipseWtpFacet` and the associated `clean*` tasks) were deprecated in Gradle 9 and have been removed. Use Eclipse's https://projects.eclipse.org/projects/tools.buildship[Buildship] integration to import the project instead. See the <<upgrading_major_version_10.adoc#ide_task_removal,upgrade guide>> for details.

[[sec:eclipse_configuration]]
== Configuration


[[eclipse-configuration]]
.Configuration of the Eclipse plugins
[%header%autowidth,compact]
|===
| Model | Reference name | Description

| link:{groovyDslPath}/org.gradle.plugins.ide.eclipse.model.EclipseModel.html[EclipseModel]
| `eclipse`
| Top level element that enables configuration of the Eclipse plugin in a DSL-friendly fashion.

| link:{groovyDslPath}/org.gradle.plugins.ide.eclipse.model.EclipseProject.html[EclipseProject]
| `eclipse.project`
| Allows configuring project information

| link:{groovyDslPath}/org.gradle.plugins.ide.eclipse.model.EclipseClasspath.html[EclipseClasspath]
| `eclipse.classpath`
| Allows configuring classpath information.

| link:{groovyDslPath}/org.gradle.plugins.ide.eclipse.model.EclipseJdt.html[EclipseJdt]
| `eclipse.jdt`
| Allows configuring jdt information (source/target Java compatibility).

| link:{groovyDslPath}/org.gradle.plugins.ide.eclipse.model.EclipseWtpComponent.html[EclipseWtpComponent]
| `eclipse.wtp.component`
| Allows configuring wtp component information only if `eclipse-wtp` plugin was applied.

|===

[[sec:eclipse_customizing_the_generated_files]]
== Customizing the Eclipse model

The Eclipse plugins provide a DSL for configuring model objects that model the Eclipse view of the project. Buildship consumes this model through the Tooling API when it imports or synchronizes the project. The model objects provide lower level hooks for working with the domain objects before and after they are populated from the Gradle build, for fine tuning that the Eclipse and Eclipse WTP plugins do not model.

[[sec:hooking_into_the_eclipse_generation_lifecycle]]
=== Hooking into the model assembly lifecycle

The Eclipse plugins provide objects modeling the sections of the Eclipse model that are assembled by Gradle. The assembly lifecycle is as follows:

. A domain object with empty content is created
. The `beforeMerged` hook is executed with the empty domain object
. The configuration inferred from the Gradle build or defined explicitly in the eclipse DSL is merged into the domain object
. The `whenMerged` hook is executed with the fully populated domain object

[[eclipse-plugin-hooks]]
==== Advanced configuration hooks

The following list covers the domain object used for each of the Eclipse model types:

link:{groovyDslPath}/org.gradle.plugins.ide.eclipse.model.EclipseProject.html[EclipseProject]::
  * `beforeMerged { link:{javadocPath}/org/gradle/plugins/ide/eclipse/model/Project.html[Project] arg -&gt; ... }`
  * `whenMerged { link:{javadocPath}/org/gradle/plugins/ide/eclipse/model/Project.html[Project] arg -&gt; ... }`

link:{groovyDslPath}/org.gradle.plugins.ide.eclipse.model.EclipseClasspath.html[EclipseClasspath]::
  * `beforeMerged { link:{javadocPath}/org/gradle/plugins/ide/eclipse/model/Classpath.html[Classpath] arg -&gt; ... }`
  * `whenMerged { link:{javadocPath}/org/gradle/plugins/ide/eclipse/model/Classpath.html[Classpath] arg -&gt; ... }`

[[sec:eclipse_modify_domain_objects]]
==== Modifying the fully populated domain objects

The `whenMerged` hook allows to manipulate the fully populated domain objects. Here is how you would export all the dependencies of an Eclipse project:

====
include::sample[dir="snippets/reference/core-plugins/eclipse/kotlin",files="build.gradle.kts[tags=module-when-merged]"]
include::sample[dir="snippets/reference/core-plugins/eclipse/groovy",files="build.gradle[tags=module-when-merged]"]
====

[[sec:test-sources]]
== Separation of test classpath entries

Eclipse defines only one classpath per project which implies limitations on how Gradle projects can be mapped.
Eclipse 4.8 introduced the concept of link:https://www.eclipse.org/eclipse/news/4.8/jdt.php#jdt-test-sources[test sources].
This feature allows the Eclipse plugin to define better separation between test and non-test sources.

The Eclipse classpath consists of classpath entries: source directories, jar files, project dependencies, etc.
Each classpath entry can have a list of classpath attributes, where the attributes are string key-value pairs.
There are two classpath attribute relevant for test sources: `test` and `without_test_code`, both of which can have `true` or `false` as values.

If a source directory has the `test=true` classpath attribute then the contents are considered test sources.
Test sources have access to non-test sources, but non-test sources don't have access to test sources.
Similarly, test sources can only reference classes from a jar file if the jar file has the `test=true` classpath attribute.
For project dependencies if the `test=true` attribute is present the classes in the target project are visible to test sources.
If the `without_test_code=false` attribute is present then the test sources of the target project are also accessible.  By default, test code is not available (which can be thought of as implicitly having `without_test_code=true`).

The following rules apply for the test attribute declaration when generating the Eclipse classpath:

- Source sets and dependency configurations are categorized as test if their name contain the 'test' substring, irrespective of case.
- All source sets and dependency configurations defined by the JVM test suite plugin are categorized as test.
- Source directories have the `test=true` classpath attribute if the container source set is a test source set.
- Jar files and project dependencies have the `test=true` attribute if they are present only in test dependency configurations.
- Project dependencies have the `without_test_sources=false` attribute if the target project applies the java-test-fixtures plugin.

You can customize the test source sets and configurations:

====
include::sample[dir="snippets/reference/core-plugins/eclipse/kotlin",files="build.gradle.kts[tags=test-sources]"]
include::sample[dir="snippets/reference/core-plugins/eclipse/groovy",files="build.gradle[tags=test-sources]"]
====

TIP: Consider migrating away from manual definition of additional test source sets and towards the use of the <<jvm_test_suite_plugin#jvm_test_suite_plugin,JVM Test Suite Plugin>> in scenarios like this.

You can also customize if a project should expose test sources to upstream project dependencies via the `containsTestFixtures` property.

====
include::sample[dir="snippets/reference/core-plugins/eclipse/kotlin",files="build.gradle.kts[tags=test-fixtures]"]
include::sample[dir="snippets/reference/core-plugins/eclipse/groovy",files="build.gradle[tags=test-fixtures]"]
====

Note, that this configuration also applies to the classpath of Buildship projects.
