// Copyright (C) 2024 Gradle, Inc.
//
// Licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 4.0 International License.;
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://creativecommons.org/licenses/by-nc-sa/4.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[idea_plugin]]
= The IDEA Plugin

The IDEA plugin allows customizing how http://www.jetbrains.com/idea/[IntelliJ IDEA] understands your project. When IDEA imports a Gradle build via its https://www.jetbrains.com/help/idea/gradle.html#gradle_import[built-in Gradle integration], it takes the `idea { ... }` configuration into account. Both external dependencies (including associated source and Javadoc files) and project dependencies are considered.

[NOTE]
====
You do not need to apply this plugin to import your project into IDEA. Apply it only if you want to customize the IDEA representation of your project beyond what the import derives from the build itself — see the <<#sec:idea_configuration,Configuration>> section for more details.
====

[[sec:idea_usage]]
== Usage

To use the IDEA plugin, include this in your build script:

.Using the IDEA plugin
====
include::sample[dir="snippets/reference/core-plugins/idea/kotlin",files="build.gradle.kts[tags=use-plugin]"]
include::sample[dir="snippets/reference/core-plugins/idea/groovy",files="build.gradle[tags=use-plugin]"]
====

NOTE: The IDE file generation tasks that this plugin used to contribute (`idea`, `ideaProject`, `ideaModule`, `ideaWorkspace`, `openIdea` and the associated `clean*` tasks) were deprecated in Gradle 9 and have been removed. Use IDEA's built-in Gradle integration to import the project instead. See the <<upgrading_version_9.adoc#ide_task_deprecation,upgrade guide>> for details.

[[sec:idea_configuration]]
== Configuration

The plugin adds some configuration options that allow to customize how IDEA understands the project. For example, you can add source and resource directories. This configuration is honored by IDEA's import facility.

Here are the configuration properties you can use:

[[idea-configuration]]

`idea` — link:{groovyDslPath}/org.gradle.plugins.ide.idea.model.IdeaModel.html[IdeaModel]::
Top level element that enables configuration of the idea plugin in a DSL-friendly fashion

`idea.project` link:{groovyDslPath}/org.gradle.plugins.ide.idea.model.IdeaProject.html[IdeaProject]::
Allows configuring project information

`idea.module` link:{groovyDslPath}/org.gradle.plugins.ide.idea.model.IdeaModule.html[IdeaModule]::
Allows configuring module information

Follow the links to the types for examples of using these configuration properties.

[[sec:idea_identify_additional_source_sets]]
== Identifying additional test directories

When using this plugin together with the <<java_plugin.adoc#java_plugin,Java plugin>>, after adding additional source sets you may wish to inform IDEA when they contain test source rather than production source, so that the IDE can treat the directories appropriately.  This can be accomplished by using this plugin's `Module` block.

====
include::sample[dir="snippets/reference/core-plugins/ideaAdditionalTestSources/kotlin",files="build.gradle.kts[tags=mark-additional-sourcesets-as-test]"]
include::sample[dir="snippets/reference/core-plugins/ideaAdditionalTestSources/groovy",files="build.gradle[tags=mark-additional-sourcesets-as-test]"]
====

NOTE: When working with the <<jvm_test_suite_plugin#jvm_test_suite_plugin,JVM Test Suite Plugin>>, test sources will automatically identified correctly.
